import type { Fact } from './group1';

/** Canadian history and civics; scales from symbols and basics to Confederation, rights, and modern policy. */
export const canadianHistory: Record<number, Fact[]> = {
  1: [
    ['What is the capital city of Canada?', 'Ottawa', 'Toronto', 'Montreal', 'Vancouver'],
    ['What leaf is on the Canadian flag?', 'Maple leaf', 'Oak leaf', 'Pine leaf', 'Palm leaf'],
    ['What colours are on Canada\'s flag?', 'Red and white', 'Blue and white', 'Green and gold', 'Black and yellow'],
    ['What animal is on the Canadian nickel (5 cents)?', 'Beaver', 'Moose', 'Polar bear', 'Loon'],
    ['What bird is on the Canadian one-dollar coin?', 'Common loon', 'Eagle', 'Owl', 'Penguin'],
    ['What is Canada\'s birthday called?', 'Canada Day', 'Maple Day', 'Confederation Day only', 'Winter Day'],
    ['On what date do we celebrate Canada Day?', 'July 1', 'June 24', 'May 24', 'August 1'],
    ['What is the name of Canada\'s national winter sport?', 'Ice hockey', 'Lacrosse', 'Curling', 'Skiing'],
    ['What is the name of Canada\'s official summer sport?', 'Lacrosse', 'Ice hockey', 'Soccer', 'Baseball'],
    ['What ocean is on Canada\'s east coast?', 'Atlantic Ocean', 'Pacific Ocean', 'Indian Ocean', 'Arctic only'],
    ['What ocean is on Canada\'s west coast?', 'Pacific Ocean', 'Atlantic Ocean', 'Southern Ocean', 'Black Sea'],
    ['Which province is famous for the Rocky Mountains?', 'British Columbia (and Alberta)', 'Prince Edward Island', 'Nova Scotia', 'Newfoundland only'],
    ['Which province is the smallest by land area?', 'Prince Edward Island', 'Nova Scotia', 'New Brunswick', 'Ontario'],
    ['What is the largest province by area?', 'Quebec', 'Ontario', 'British Columbia', 'Alberta'],
    ['What is the name of the French-speaking province?', 'Quebec', 'Ontario', 'Manitoba', 'Saskatchewan'],
    ['What tower is a famous symbol of Toronto?', 'CN Tower', 'Space Needle', 'Eiffel Tower', 'Big Ben'],
    ['What are Canada\'s Indigenous peoples called in a respectful general term?', 'First Nations, Inuit, and Métis', 'Pilgrims', 'Settlers only', 'Explorers only'],
    ['What is the name of Canada\'s national anthem?', 'O Canada', 'God Save the King', 'The Maple Song', 'True North'],
    ['In English, how does "O Canada" often start?', 'O Canada! Our home and native land!', 'O maple! Our syrup', 'O hockey! Our rink', 'O winter! Our snow'],
    ['What is a toque?', 'A warm knit hat', 'A boot', 'A sled', 'A boat'],
    ['What sweet treat is poured on snow to make taffy in winter?', 'Maple taffy on snow', 'Chocolate snow', 'Salt taffy', 'Pepper candy'],
    ['What is the Royal Canadian Mounted Police nickname?', 'Mounties', 'Troopers', 'Rangers', 'Sheriffs'],
    ['What is "eh" often associated with?', 'Canadian casual speech', 'French only', 'Inuit only', 'Atlantic only'],
    ['Which animal is a symbol of Canada on coins and stamps?', 'Beaver', 'Kangaroo', 'Lion', 'Tiger'],
    ['What is the northern territory known for polar bears and auroras?', 'Nunavut', 'Yukon only', 'PEI', 'Ontario'],
    ['What city hosted the 2010 Winter Olympics in Canada?', 'Vancouver (and Whistler)', 'Calgary', 'Toronto', 'Montreal'],
    ['What is a "double-double" at Tim Hortons?', 'Coffee with two creams and two sugars', 'Four donuts', 'Two bagels', 'Two soups'],
    ['What is poutine?', 'Fries with cheese curds and gravy', 'A pancake', 'A pie', 'A salad'],
    ['Which province has oil sands famous worldwide?', 'Alberta', 'Quebec', 'PEI', 'Nova Scotia'],
    ['What is the name of Canada\'s central prairie province known for wheat?', 'Saskatchewan', 'Quebec', 'PEI', 'Yukon'],
    ['What bay is huge and partly frozen in northern Canada?', 'Hudson Bay', 'Chesapeake Bay', 'San Francisco Bay', 'Bay of Bengal'],
    ['What is the name of the narrow strait east of northern Quebec?', 'Hudson Strait', 'English Channel', 'Strait of Gibraltar', 'Bering Strait'],
    ['What is the capital of Ontario?', 'Toronto', 'Ottawa', 'Kingston', 'Hamilton'],
    ['What is the capital of British Columbia?', 'Victoria', 'Vancouver', 'Kelowna', 'Prince George'],
    ['What is the capital of Alberta?', 'Edmonton', 'Calgary', 'Red Deer', 'Banff'],
    ['What is the capital of Quebec?', 'Quebec City', 'Montreal', 'Sherbrooke', 'Trois-Rivières'],
    ['What is the capital of Nova Scotia?', 'Halifax', 'Sydney', 'Dartmouth only', 'Truro'],
    ['What is the capital of New Brunswick?', 'Fredericton', 'Saint John', 'Moncton', 'Dieppe'],
    ['What is the capital of Manitoba?', 'Winnipeg', 'Brandon', 'Churchill', 'Steinbach'],
    ['What is the capital of Saskatchewan?', 'Regina', 'Saskatoon', 'Moose Jaw', 'Prince Albert'],
    ['What is the capital of Newfoundland and Labrador?', "St. John's", 'Corner Brook', 'Gander', 'Labrador City'],
    ['What is the capital of Prince Edward Island?', 'Charlottetown', 'Summerside', 'Montague', 'Souris'],
    ['What territory has capital Whitehorse?', 'Yukon', 'NWT', 'Nunavut', 'Alaska'],
    ['What territory has capital Yellowknife?', 'Northwest Territories', 'Yukon', 'Nunavut', 'Nunavik'],
    ['What territory has capital Iqaluit?', 'Nunavut', 'Yukon', 'NWT', 'Greenland'],
    ['What is the longest river in Canada?', 'Mackenzie River', 'St. Lawrence', 'Fraser', 'Yukon River'],
    ['What waterfall is famous on the Canada–US border?', 'Niagara Falls', 'Angel Falls', 'Victoria Falls', 'Iguazu Falls'],
    ['Who is on the Canadian $5 bill (polymer era portrait)?', 'Sir Wilfrid Laurier (historical series)', 'Queen only', 'Trudeau only', 'Macdonald'],
    ['What is Remembrance Day in Canada?', 'November 11 to honour veterans', 'July 1', 'May long weekend', 'Thanksgiving'],
    ['What flower is worn for Remembrance Day?', 'Poppy', 'Rose', 'Daisy', 'Tulip'],
  ],
  2: [
    ['Who was Canada\'s first Prime Minister?', 'John A. Macdonald', 'Wilfrid Laurier', 'Pierre Trudeau', 'Robert Borden'],
    ['In what year did Confederation create Canada (first four provinces)?', '1867', '1776', '1812', '1905'],
    ['What was the name of the act of Parliament that created Canada?', 'British North America Act', 'Canada Act only (1982)', 'Magna Carta', 'Constitution Act 1982 only'],
    ['Which four provinces were the original Dominion in 1867?', 'Ontario, Quebec, Nova Scotia, New Brunswick', 'All 10 provinces', 'BC and Alberta', 'Manitoba only'],
    ['What was the name of the Indigenous confederacy in the Great Lakes region historically?', 'Haudenosaunee (Iroquois Confederacy)', 'Aztec', 'Inca', 'Zulu'],
    ['What is the name of the trade route for fur across Canada?', 'Fur trade routes (e.g. voyageur routes)', 'Silk Road', 'Spice Route', 'Salt Road'],
    ['Who were voyageurs?', 'French-Canadian canoe paddlers in the fur trade', 'British soldiers only', 'Gold miners', 'Rail workers'],
    ['What company was powerful in early fur trade?', 'Hudson\'s Bay Company', 'Google', 'CN Rail', 'Air Canada'],
    ['What war in 1812 involved British North America vs US invasion?', 'War of 1812', 'Seven Years\' War', 'World War I', 'Fenian Raids only'],
    ['Who defended Canada in 1812 alongside British regulars?', 'Militia, Indigenous allies, and local forces', 'Only France', 'Only Spain', 'No one'],
    ['What Laura Secord is famous for?', 'Warning British forces of American attack in War of 1812', 'Prime Minister', 'Inventor', 'Painter'],
    ['What is the Underground Railroad?', 'Network helping freedom seekers reach Canada', 'Subway in Toronto', 'Train to Vancouver', 'Gold rush'],
    ['What is the Klondike Gold Rush region?', 'Yukon', 'Ontario', 'Quebec', 'PEI'],
    ['When did Alberta and Saskatchewan become provinces?', '1905', '1867', '1871', '1949'],
    ['When did Newfoundland join Canada?', '1949', '1867', '1982', '2000'],
    ['What is the Last Spike in Canadian history?', 'Ceremony completing the transcontinental railway', 'First hockey goal', 'First maple syrup', 'First vote'],
    ['Who is often associated with promoting the Pacific railway (controversial legacy)?', 'John A. Macdonald government era', 'Laurier only', 'Trudeau', 'Queen Victoria alone'],
    ['What head tax targeted Chinese immigrants?', 'Chinese Head Tax', 'Irish tax', 'French tax', 'German tax'],
    ['What is Komagata Maru incident about?', 'South Asian passengers denied entry in Vancouver 1914', 'Japanese fishing boat', 'Arctic expedition', 'Navy battle'],
    ['What is residential school system (truth and reconciliation context)?', 'Government/church schools that harmed Indigenous children', 'Boarding schools for elites', 'Military academies', 'French immersion'],
    ['What is the Truth and Reconciliation Commission?', 'Inquiry documenting residential school harms', 'Olympic committee', 'Trade commission', 'Tax office'],
    ['How many Calls to Action did the TRC report include?', '94', '10', '50', '200'],
    ['What is National Indigenous Peoples Day?', 'June 21', 'July 1', 'September 30', 'November 11'],
    ['What is Orange Shirt Day / National Day for Truth and Reconciliation?', 'September 30', 'July 1', 'June 21', 'May 24'],
    ['What is the Métis Nation symbol often seen?', 'Infinity flag / sash culture', 'Maple leaf only', 'Union Jack only', 'Star only'],
    ['What is the Constitution Act, 1982 famous for?', 'Patriation and Charter of Rights and Freedoms', 'Creating provinces', 'End of WWI', 'Gold standard'],
    ['Who was Prime Minister during patriation?', 'Pierre Trudeau', 'John Diefenbaker', 'Brian Mulroney', 'Jean Chrétien'],
    ['What document protects rights in Canada since 1982?', 'Canadian Charter of Rights and Freedoms', 'Bill of Rights 1689', 'US Constitution', 'Magna Carta'],
    ['What is Section 35 of Constitution Act, 1982?', 'Recognizes and affirms Aboriginal and treaty rights', 'Tax section', 'Language section', 'Education only'],
    ['What are the two official languages at the federal level?', 'English and French', 'English and Spanish', 'French and Inuktitut', 'English only'],
    ['What is Official Languages Act about?', 'Federal bilingual services', 'Provincial hockey rules', 'Immigration caps', 'Currency'],
    ['What is multiculturalism policy era?', '1971 official multiculturalism (Pierre Trudeau era)', '1982 only', '2000 only', '1867'],
    ['What is the Quiet Revolution?', '1960s Quebec social and secular modernization', 'American Revolution', 'Russian Revolution', 'Industrial England'],
    ['What is FLQ October Crisis (1970)?', 'Quebec terrorism crisis and War Measures Act', 'Hockey riot', 'Expo 67', 'Referendum 1995'],
    ['What were the Quebec sovereignty referendums years?', '1980 and 1995', '1867 and 1905', '2000 and 2010', '1970 only'],
    ['What is Meech Lake Accord (failed)?', 'Constitutional reform attempt 1987–1990', 'Trade deal', 'NHL merger', 'Rail deal'],
    ['What is Charlottetown Accord?', '1992 failed constitutional referendum package', 'City founding', 'Island name', 'Treaty only'],
    ['What is NAFTA (historical)?', 'North American trade agreement including Canada', 'NATO', 'UN', 'Commonwealth'],
    ['What replaced NAFTA for Canada/US/Mexico?', 'CUSMA / USMCA', 'EU deal', 'TPP only', 'Brexit'],
    ['What is the CBC?', 'Canadian Broadcasting Corporation', 'Central Bank of Canada', 'Canadian Baseball Club', 'Border Control'],
    ['What is the CRTC?', 'Regulates broadcasting and telecom', 'Railways', 'Banks', 'Hospitals'],
    ['What is the RCMP federal role?', 'National police / rural policing in provinces', 'Only municipal Toronto', 'Only military', 'Only courts'],
    ['What is CSIS?', 'Canadian Security Intelligence Service', 'Space agency', 'Tax agency', 'Health agency'],
    ['What is Elections Canada?', 'Non-partisan agency running federal elections', 'Political party', 'Court', 'Bank'],
    ['How many years is a maximum federal Parliament term?', '5 years', '4', '6', '10'],
    ['What is first-past-the-post?', 'Electoral system: most votes in riding wins seat', 'Proportional only', 'Ranked ballot only', 'Senate election'],
    ['What is a riding?', 'Electoral district', 'Horse event', 'Ski trail', 'Ferry route'],
    ['What is the House of Commons?', 'Elected lower house of Parliament', 'Senate', 'Supreme Court', 'Cabinet only'],
    ['What is the Senate?', 'Upper chamber of Parliament (appointed)', 'Elected house', 'City council', 'School board'],
    ['Who represents the Crown in Canada federally?', 'Governor General', 'Premier', 'Mayor', 'Chief Justice'],
  ],
  3: [
    ['What battle in 1759 shaped British control of Quebec?', 'Battle of the Plains of Abraham', 'Battle of Waterloo', 'Battle of Hastings', 'Battle of Yorktown'],
    ['What treaty in 1763 ended the Seven Years\' War in North America?', 'Treaty of Paris 1763', 'Treaty of Versailles 1919', 'Treaty of Ghent', 'Jay Treaty'],
    ['What is the Quebec Act of 1774?', 'Recognized French civil law and Catholic rights in Quebec', 'Independence declaration', 'Railway act', 'Conscription'],
    ['What is Upper Canada and Lower Canada?', 'Early names for southern Ontario and southern Quebec', 'Northwest only', 'Atlantic only', 'Arctic'],
    ['What rebellion(s) sought reform in 1837?', 'Rebellions of 1837 in Upper and Lower Canada', 'Riel Rebellion only', 'October Crisis', 'FLQ only'],
    ['Who were the Reformers led by in Upper Canada?', 'William Lyon Mackenzie', 'John A. Macdonald', 'Louis Riel', 'Robert Baldwin'],
    ['Who led Patriotes in Lower Canada?', 'Louis-Joseph Papineau', 'Laurier', 'Cartier', 'Champlain'],
    ['What is responsible government achieved in Province of Canada era?', 'Cabinet must hold confidence of elected assembly', 'Monarchy ends', 'US annexation', 'No parties'],
    ['Who were Fathers of Confederation?', 'Leaders who framed 1867 union', 'All PMs ever', 'All premiers', 'Generals only'],
    ['What is Charlottetown Conference 1864?', 'Key meeting leading to Confederation', 'PEI only festival', 'Treaty with US', 'Railway opening'],
    ['What is Quebec Conference 1864?', 'Drafted framework for Confederation', 'Hockey founding', 'Expo planning', 'NATO'],
    ['What is London Conference 1866?', 'Refined BNA Act wording', 'Olympics', 'Coronation', 'Treaty of Paris'],
    ['What is Rupert\'s Land?', 'Hudson\'s Bay Company territory transferred to Canada 1870', 'Gold fields only', 'Arctic islands only', 'US purchase'],
    ['What is Red River Resistance / provisional government 1869–70?', 'Métis led by Louis Riel over rights during transfer', 'Gold rush', 'Rail strike', 'Fenian raid'],
    ['What province was created from Rupert\'s Land entry 1870?', 'Manitoba', 'Alberta', 'BC', 'Saskatchewan'],
    ['What is North-West Rebellion 1885?', 'Métis and Indigenous–settler conflict on prairies', 'War of 1812', 'October Crisis', 'Klondike'],
    ['What is hanging of Riel outcome?', '1885 treason conviction — controversial national divide', 'Exile only', 'Acquittal', 'PM appointment'],
    ['What is National Policy of Macdonald?', 'Tariffs to build Canadian industry and railway', 'Free trade only', 'Income tax', 'Conscription'],
    ['What is Chinese Immigration Act 1923 (Chinese Exclusion Act)?', 'Banned most Chinese immigration until 1947', 'Welcomed all', 'French only ban', 'Irish ban'],
    ['What is Komagata Maru?', '1914 ship denied landing reflecting racist immigration laws', 'Navy flagship', 'Ferry to Victoria', 'Hudson Bay ship'],
    ['What is Winnipeg General Strike 1919?', 'Massive labour strike', 'Hockey strike', 'Student strike', 'Farmer picnic'],
    ['What is Statute of Westminster 1931?', 'Gave Dominion legislative independence from UK', 'Created Canada 1867', 'Charter 1982', 'NAFTA'],
    ['What is Canada\'s role in WWII overview?', 'Large military contribution; Dieppe; D-Day; home front', 'Stayed neutral', 'Joined Axis', 'No navy'],
    ['What is conscription crisis WWII?', 'Deep divide especially in Quebec over mandatory service', 'Tax crisis', 'Rail crisis', 'Oil crisis'],
    ['What is VE-Day?', 'Victory in Europe May 1945', 'D-Day', 'VJ-Day only', 'Armistice 1918'],
    ['What is citizenship Act 1947?', 'First Canadian citizenship law separate from British subject', 'Charter', 'BNA Act', 'Québec Act'],
    ['What is Newfoundland National Convention?', 'Led to referendum to join Canada 1949', 'Québec referendum', 'NWT division', 'Yukon act'],
    ['What is Bill 101 (Quebec)?', 'French language charter strengthening French in Quebec', 'Highway bill', 'Tax bill', 'Healthcare'],
    ['What is October Crisis outcome legacy?', 'War Measures Act debate; civil liberties questions', 'Nothing happened', 'Quebec independence', 'NHL merger'],
    ['What is patriation?', 'Bringing constitution home to amend in Canada', 'Selling railways', 'Joining US', 'Abolishing monarchy'],
    ['What is notwithstanding clause (Section 33)?', 'Parliament/legislatures can override some Charter rights temporarily', 'PM appointment', 'Senate powers', 'Tax override'],
    ['What is Section 15 Charter?', 'Equality rights', 'Mobility', 'Language', 'Vote age'],
    ['What is Section 2 Charter?', 'Fundamental freedoms (expression, religion, etc.)', 'Property', 'Healthcare', 'Education'],
    ['What is Oakes test?', 'Legal test for reasonable limits under Section 1 Charter', 'Boat safety', 'Tax audit', 'Election recount'],
    ['What is Meech Lake failure issue?', 'Did not pass ratification deadlines — distinct society debate', 'Trade only', 'NHL', 'Rail'],
    ['What is Charlottetown Accord vote result?', 'Failed in 1992 referendum', 'Passed unanimously', 'Never voted', 'Provinces only'],
    ['What is Nisga\'a Treaty (1999)?', 'First modern treaty in BC — landmark self-governance', 'US treaty', 'French treaty', 'Hudson Bay sale'],
    ['What is Nunavut creation 1999?', 'Eastern Arctic split from NWT as Inuit-majority territory', 'Yukon split', 'Quebec split', 'Labrador split'],
    ['What is Clarity Act?', 'Federal law on secession referendum clarity after 1995 Quebec vote', 'Language act', 'Tax act', 'Fishing act'],
    ['What is Kelowna Accord (not implemented)?', '2005 First Nations funding/education deal fell with government change', 'NAFTA', 'Meech', 'Charlottetown'],
    ['What is Truth and Reconciliation Commission mandate?', 'Residential schools truth telling', 'Economic forecasts', 'Military strategy', 'Olympic bid'],
    ['What is United Nations Declaration on the Rights of Indigenous Peoples (UNDRIP) Canadian context?', 'BC first to implement law; federal UNDRIP legislation debates', 'Ignored always', 'US law', 'EU law'],
    ['What is missing and murdered Indigenous women and girls inquiry?', 'National Inquiry MMIWG 2016–', 'Hockey inquiry', 'Rail inquiry', 'Bank inquiry'],
    ['What is Phoenix Pay System scandal?', 'Federal payroll system failures harming public servants', 'Bird study', 'Water pay', 'Provincial health'],
    ['What is SNC-Lavalin affair (2019 politics)?', 'Ethics controversy over prosecution and remediation agreement', 'Hockey trade', 'Quebec secession', 'NAFTA'],
    ['What is Emergencies Act convoy 2022?', 'Federal emergency powers used during Ottawa protests — debated legacy', 'War Measures 1970', 'Rail act', 'Quarantine Act only'],
    ['What is carbon pricing federal backstop?', 'National climate policy tool with provincial variations', 'Gas tax holiday', 'Income tax', 'Sales tax only'],
    ['What is legalization of cannabis (2018)?', 'Federal Cannabis Act regulated recreational use', 'Alcohol ban', 'Tobacco ban', 'Gambling ban'],
    ['What is medically assisted dying law evolution?', 'MAID statutes debated and expanded carefully over years', 'Abortion law 1867', 'Vaccine law', 'Euthanasia banned always'],
    ['What is Official Development Assistance context?', 'Canada\'s international aid spending debates', 'NATO only', 'NHL salary cap', 'CPP'],
  ],
  4: [
    ['What is Durham Report 1839?', 'Recommended responsible government — union of Canadas', 'Created RCMP', 'Created Senate', 'Annexed Alaska'],
    ['What is Act of Union 1840?', 'United Upper and Lower Canada into one legislature', 'Created Manitoba', 'Joined Newfoundland', 'US Civil War'],
    ['What is Baldwin–LaFontaine ministry significance?', 'Responsible government milestone 1848–49', 'Confederation 1867', 'Riel trial', 'NAFTA'],
    ['What is Reciprocity Treaty 1854?', 'Free trade with US (later cancelled)', 'Railway treaty', 'NATO', 'Fenian'],
    ['What is Grand Trunk Railway context?', 'Major early railway company pre-Confederation', 'Air Canada', 'CPR only post-1881', 'Hudson Bay'],
    ['What is Charlottetown and Quebec Conferences outcome document?', '72 Resolutions basis for BNA Act', 'Charter', 'Meech', 'White Paper'],
    ['What is anti-confederation sentiment in Nova Scotia?', 'Joseph Howe initially opposed; later reconciled', 'Quebec only', 'BC only', 'None'],
    ['What is Red River Expedition 1870?', 'Wolseley expedition related to Riel aftermath tensions', 'Gold rush police', 'Alaska purchase', 'Fenian raid'],
    ['What is Numbered Treaties?', 'Series of post-1870 Crown–First Nations treaties on prairies', 'US treaties', 'French treaties', 'Nunavut'],
    ['What is Indian Act (1876) legacy?', 'Colonial law controlling Indigenous lives — amended many times', 'Charter', 'Québec Act', 'Immigration Act'],
    ['What is Pacific Scandal?', '1873 railway bribery scandal brought down Macdonald government', 'Watergate Canada', 'Sponsorship', 'SNC'],
    ['What is National Policy tariffs purpose?', 'Protect infant industries and fund railway', 'Free trade', 'Income redistribution', 'Abolish provinces'],
    ['What is North-West Mounted Police precursor?', 'Later becomes RCMP — established 1873', 'OPP 1867', 'CSIS 1984', 'Coast Guard'],
    ['What is Head-Smashed-In Buffalo Jump?', 'UNESCO Indigenous hunting site Alberta', 'Gold mine', 'Fort York', 'CN Tower'],
    ['What is Klondike rush capital feel?', 'Dawson City boom', 'Vancouver 2010', 'Montreal 1976', 'Toronto 1850'],
    ['What is Alaska Boundary Dispute outcome?', '1903 arbitration favoured US — Canadian anger', 'Canada got Alaska', 'No border', '1812'],
    ['What is South African War (Boer War) Canadian participation?', 'Contingents sent under British imperialism debates', 'WWI', 'WWII', 'Korea'],
    ['What is Naval Service Act 1910?', 'Created Canadian Navy', 'RCAF', 'RCMP', 'Coast Guard'],
    ['What is Laurier–Sifton immigration policy context?', 'Preferential European immigration — discriminatory era', 'Open door', 'Points system 1967', 'None'],
    ['What is Manitoba Schools Question?', 'Late 1800s Catholic vs Protestant schools funding crisis', 'Bill 101', 'Charter', 'Residential'],
    ['What is Alaska Highway WWII?', 'Built as military supply route through BC/Yukon', 'Trans-Canada', 'CPR', 'Rideau Canal'],
    ['What is Japanese Canadian internment?', 'WWII forced removal inland from BC coast', 'WWI only', '1812', 'Never'],
    ['What is High Arctic relocation 1950s?', 'Inuit moved to harsh settlements — government apology later', 'Klondike', 'Nunavut 1999 plan', 'DEW line only'],
    ['What is DEW Line?', 'Cold War radar line across Canadian North', 'Dew drinking', 'Farming line', 'Rail line'],
    ['What is Newfoundland Commission of Government?', '1934–1949 UK appointed rule between dominion and joining Canada', 'Québec', 'NWT', 'Yukon'],
    ['What is St. Lawrence Seaway completion era?', '1959 opening with US partnership', '1867', '1812', '1982'],
    ['What is Avro Arrow cancellation 1959?', 'CF-105 jet fighter program scrapped — brain drain debates', 'NASA founding', 'NATO', 'Canadarm'],
    ['What is Quiet Revolution programs?', 'State secularization; hydro; education reforms', 'Revolutionary war', 'October Crisis only', 'Meech'],
    ['What is FLQ manifesto theme?', 'Quebec independence and radical left nationalism', 'Energy policy', 'Bilingualism', 'NATO'],
    ['What is War Measures Act 1970 scope?', 'Military/police powers suspending some civil liberties briefly', 'Normal law', 'Charter', 'Emergencies Act same'],
    ['What is James Bay and Northern Quebec Agreement 1975?', 'Major modern treaty with Cree and Inuit', 'NAFTA', 'Nunavut split', 'Meech'],
    ['What is Constitution Act 1867 division of powers?', 'Sections 91 federal / 92 provincial responsibilities', 'Charter', 'Senate appointments', 'Supreme Court 1982'],
    ['What is living tree doctrine?', 'Constitution interpreted flexibly over time', 'Arbor day', 'Forestry act', 'Carbon tax'],
    ['What is Patriation reference Supreme Court?', '1981 split decision on unilateral federal patriation', '1995 referendum', 'Meech reference', 'Oakes'],
    ['What is Quebec Veto understanding post patriation?', 'Political convention debates; not absolute legal veto in all cases', 'Charter Section 33', 'US filibuster', 'Senate veto'],
    ['What is Charlottetown Accord content areas?', 'Senate reform, Indigenous self-government, distinct society', 'Only tax', 'Only flag', 'Only anthem'],
    ['What is Calgary Accord?', '1996 Alberta–Quebec framework attempt post-Charlottetown', 'NHL', 'NAFTA', 'Nisga\'a'],
    ['What is Social Union Framework Agreement 1999?', 'Federal–provincial social program principles', 'NAFTA', 'Meech', 'Clarity'],
    ['What is Sponsorship scandal?', '2000s federal advertising program corruption in Quebec', 'SNC', 'Phoenix', 'Rail'],
    ['What is Kelowna Accord funding focus?', 'Education, health, housing for Indigenous peoples', 'Military', 'Senate', 'Olympics'],
    ['What is Apology for residential schools 2008?', 'PM Stephen Harper delivered apology in House', '1996 only', 'TRC only same day', 'Never'],
    ['What is TRC 94 Calls to Action categories?', 'Child welfare, education, language, health, justice…', 'Tax', 'Defence', 'Olympics'],
    ['What is Jordan\'s Principle?', 'First Nations children get needed services without jurisdictional disputes', 'Basketball rule', 'Charter Section 15', 'Senate rule'],
    ['What is United Nations Declaration implementation Act debates?', 'Aligning Canadian law with UNDRIP — consent and resource questions', 'NATO', 'NAFTA', 'FIFA'],
    ['What is carbon tax Supreme Court reference 2021?', 'Federal Greenhouse Gas Pollution Pricing Act constitutional', 'Emergencies Act', 'Clarity', 'Oakes'],
    ['What is medically assisted dying Carter v. Canada?', '2015 SCC struck down prior Criminal Code limits — Parliament responded', 'Same-sex marriage', 'Abortion Morgentaler', 'Insite safe injection'],
    ['What is R v. Morgentaler 1988?', 'Abortion law struck as violating Charter security of person', 'MAID', 'Insite', 'Charter language'],
    ['What is Reference re Secession of Quebec 1998?', 'Clarity on unilateral secession under international and constitutional law', 'Meech', 'Charlottetown', 'Nisga\'a'],
    ['What is duty to consult Indigenous peoples?', 'Crown must consult (and sometimes accommodate) on decisions affecting rights', 'Vote', 'Tax', 'Senate'],
    ['What is modern treaties Nunavut land claims?', 'Nunavut Land Claims Agreement led to territory', 'James Bay only', 'Treaty 6 only', 'US treaty'],
  ],
  5: [
    ['What is Treaty of Utrecht 1713 effect on Canada?', 'France ceded Acadia, Newfoundland, Hudson Bay to Britain', 'Canada formed', 'US independence', 'Quebec Act'],
    ['What is Acadian Expulsion (Grand Dérangement)?', '1755 removal of Acadians by British forces', '1812', '1837', '1867'],
    ['What is Siege of Québec 1759 commanders?', 'Wolfe vs Montcalm (both died in battle aftermath)', 'Brock vs Tecumseh', 'Riel vs Middleton', 'Currie vs Ludendorff'],
    ['What is Royal Proclamation 1763 significance for Indigenous law?', 'Foundation for Aboriginal title and treaty process in Canadian law', 'Created provinces', 'Ended War of 1812', 'Created RCMP'],
    ['What is Quebec Act 1774 American reaction?', 'Listed among Intolerable Acts by some American revolutionaries', 'Celebrated', 'Ignored', 'Funded'],
    ['What is Constitutional Act 1791?', 'Divided Province of Quebec into Upper and Lower Canada', 'Created Canada', 'Charter', 'Manitoba Act'],
    ['What is War of 1812 Tecumseh alliance?', 'Shawnee leader allied with British in Great Lakes', 'Riel', 'Pontiac', 'Joseph Brant only'],
    ['What is Treaty of Ghent 1814?', 'Ended War of 1812 — status quo ante bellum', 'Paris 1763', 'Versailles 1919', 'CUSMA'],
    ['What is Durham Report responsible government recommendation?', 'Union of Canadas and responsible assembly', 'Confederation immediate', 'Annex US', 'Abolish French'],
    ['What is Baldwin–LaFontaine reform achievement?', 'Responsible government working model', 'Confederation', 'Rail complete', 'Manitoba'],
    ['What is Reciprocity cancellation 1866 context?', 'US Civil War protectionism ended treaty — pushed colonial trade thoughts', 'NAFTA', 'Auto Pact', 'CUSMA'],
    ['What is Confederation railway promise to NS and NB?', 'Intercolonial Railway commitment helped bring them in', 'Transcontinental done 1867', 'None', 'Subway'],
    ['What is anti-confederation movement resolution?', 'Howe led repeal effort then joined federal cabinet', 'War', 'Annexation to US done', 'Nothing'],
    ['What is Rupert\'s Land purchase price 1869?', '£300,000 paid to HBC (historical accounts)', 'Free', '$1', 'Gold'],
    ['What is Manitoba Act 1870?', 'Created province; promised land to Métis; language rights', 'Charter', 'BNA', 'Québec Act'],
    ['What is scrip system criticism?', 'Land scrip to Métis often unfairly converted or lost', 'Treaty annuities perfect', 'Residential schools good', 'None'],
    ['What is Numbered Treaties annuities?', 'Annual payments promised; many disputes over fulfillment', 'No payments', 'US payments', 'Private only'],
    ['What is North-West Rebellion Battle of Batoche?', '1885 decisive battle — Riel forces defeated', '1812', '1837', '1970'],
    ['What is hanging of Riel political divide?', 'Ontario/English vs Quebec/French interpretations', 'No divide', 'US civil war', 'NHL'],
    ['What is National Policy and western alienation seeds?', 'Tariffs hurt farmers selling to US; trust in Ottawa tested', 'Nothing', 'Free trade', 'NAFTA'],
    ['What is Wilfrid Laurier compromise era?', 'Boer War volunteers, naval compromise, immigration growth', 'Conscription WWI happy all', 'October Crisis', 'Meech'],
    ['What is Naval Aid Bill Laurier defeat 1911?', 'Election lost partly over naval policy vs imperial preference', 'Reciprocity election', 'Conscription', 'Meech'],
    ['What is Reciprocity election 1911?', 'Laurier lost partly on freer trade with US fears', 'Naval bill', 'Conscription', 'Quebec'],
    ['What is War Measures Act WWI?', 'Internment of Ukrainian Canadians and others deemed enemy aliens', 'Japanese WWII only', 'None', 'FLQ'],
    ['What is Military Service Act 1917?', 'Conscription crisis — deep opposition especially Quebec', 'Volunteer only', 'WWII end', 'Korea'],
    ['What is Winnipeg General Strike leaders?', 'Western labour radicalism; government fears of revolution', 'Students', 'Farmers only', 'Doctors'],
    ['What is Group of Seven art context?', '1920s Canadian landscape nationalism in art', 'Confederation painters', 'Digital art', 'War artists only'],
    ['What is Statute of Westminster effect on BNA Act?', 'Amendment required UK consent until patriation', 'Immediate patriation', 'Charter', 'Clarity'],
    ['What is Rowell–Sirois Commission?', 'Depression-era report recommending unemployment insurance federal role', 'Rail', 'NHL', 'Senate'],
    ['What is WWII Italian Canadian internment?', 'Civil liberties violation alongside Japanese internment', 'None', 'German only myth', 'Never'],
    ['What is VE/VJ demobilization issues?', 'Repatriation, jobs, veterans benefits', 'Nothing', 'Cold War start only', 'Korea only'],
    ['What is Citizenship Act 1947 symbolic break?', 'Canadian citizen legal category', 'Ends monarchy', 'Creates provinces', 'Charter'],
    ['What is Newfoundland referendums sequence?', '1948 votes — narrow join Canada', 'One vote', 'US state vote', 'Québec'],
    ['What is Quiet Revolution nationalization?', 'Hydro-Québec takeover of private electricity', 'CN privatization', 'Air Canada founding', 'NHL'],
    ['What is October Crisis War Measures legacy rights?', 'Civil liberties movement; later Emergencies Act refined', 'Nothing learned', 'Charter ignored', 'Clarity'],
    ['What is Official Languages Act 1969?', 'Federal bilingualism institutions', 'Bill 101', 'Charter', 'Meech'],
    ['What is October Crisis FLQ demands?', 'Release of "political prisoners" and manifesto broadcast', 'Independence immediate', 'Tax cuts', 'Hockey'],
    ['What is patriation night / constitutional compromise?', 'November 1981 federal–provincial deal excluding Quebec initially', 'Meech signing', 'Charlottetown', 'Clarity'],
    ['What is Quebec not signing 1982 Constitution political wound?', 'Constitution patriated without Quebec National Assembly accord', 'All signed happily', 'Meech fixed all', 'Never'],
    ['What is Meech Lake "distinct society"?', 'Recognized Quebec distinct society clause proposed', 'Senate reform done', 'Veto Quebec only', 'Charter repeal'],
    ['What is Charlottetown triple defeat?', 'Federal, Quebec, and other provincial failures', 'Unanimous pass', 'Only PEI voted', 'Senate only'],
    ['What is Calgary Declaration 1997?', 'Federalism principles after 1995 referendum', 'NHL', 'NAFTA', 'Nisga\'a'],
    ['What is Social Union Framework Agreement principles?', 'Portability, accessibility, comprehensiveness, universality, public administration', 'NAFTA', 'Fiscal stabilization only', 'Senate'],
    ['What is Nisga\'a Treaty self-government?', 'First modern BC treaty — land and governance', 'James Bay', 'Nunavut', 'US'],
    ['What is Nunavut land claims percentage?', 'Inuit received title to large fraction of territory; public government', '0%', '100% private', 'US state'],
    ['What is Clarity Act question clarity?', 'Clear question; clear majority; role of other provinces in negotiation', 'Unilateral', 'No rules', 'US law'],
    ['What is Secession Reference clarity on international law?', 'Unilateral secession not a right under Canadian constitution alone', 'Always allowed', 'UN bans Quebec', 'NATO decides'],
    ['What is Kelowna Accord collapse impact?', 'Lost momentum on closing gaps — later attempts', 'Implemented fully', 'Caused NAFTA', 'Ended CPP'],
    ['What is Truth and Reconciliation 94 Calls implementation debate?', 'Ongoing provincial/federal action gaps', 'Completed 2015', 'Ignored', 'Private only'],
    ['What is Murdered and Missing Indigenous Women and Girls Calls for Justice?', '231 Calls for Justice from Inquiry', '94 only', 'None', 'Senate'],
    ['What is Jordan\'s Principle legal victories?', 'Human Rights Tribunal orders on child welfare funding discrimination', 'Sports', 'Tax', 'Senate'],
  ],
  6: [
    ['What is Royal Proclamation 1763 fiduciary duty jurisprudence?', 'Calder, Delgamuukw, Tsilhqot\'in line on Aboriginal title', 'Charter s.15', 'Oakes', 'Reference secession'],
    ['What is Duty to Consult Haida Nation / Taku?', '2004 SCC established consultation spectrum by strength of claim', 'Delgamuukw facts only', 'Marshall fishing', 'Clyde River'],
    ['What is Tsilhqot\'in Nation v. British Columbia 2014?', 'First declaration of Aboriginal title to specific lands', 'Marshall', 'Van der Peet', 'Sparrow'],
    ['What is R v. Sparrow 1990?', 'Section 35 rights are not absolute — justified infringement test', 'Duty to consult', 'Oakes', 'Carter'],
    ['What is R v. Marshall on treaty fishing?', '1999 Mi\'kmaq treaty rights to fish commercially — implementation clashes', 'Sparrow', 'Delgamuukw', 'Tsilhqot\'in'],
    ['What is Delgamuukw v. British Columbia?', '1997 oral history evidence and Aboriginal title legal test', 'Tsilhqot\'in', 'Calder', 'Marshall'],
    ['What is Calder v. Attorney General (BC)?', '1973 split decision recognizing Aboriginal title possibility', 'Delgamuukw', 'Tsilhqot\'in', 'Oakes'],
    ['What is Van der Peet test?', 'Integral to distinctive culture test for Aboriginal rights', 'Sparrow justification', 'Oakes', 'Nexus'],
    ['What is Clyde River Supreme Court 2017?', 'NU regulatory board environmental assessment inadequate — duty to consult', 'Reference', 'Haida', 'Nadar'],
    ['What is Mikisew Cree 2018 SCC?', 'Legislative process and duty to consult limits debated', 'Haida', 'Tsilhqot\'in', 'Marshall'],
    ['What is Indigenous child welfare CHRT compensation orders?', 'Canadian Human Rights Tribunal on discrimination funding', 'Jordan only soft', 'TRC cash', 'MMIWG'],
    ['What is UNDRIP BC DRIPA vs federal UNDRIP Act differences?', 'BC law earlier; consent and harmonization debates continue', 'Identical', 'Opposite', 'EU law'],
    ['What is free, prior and informed consent (FPIC) debate?', 'Resource projects on Indigenous lands — legal vs political meanings', 'UN only', 'Never Canada', 'Charter s.2'],
    ['What is modern treaty implementation gaps?', 'Implementation plans underfunded vs promises', 'Perfect compliance', 'No treaties', 'US only'],
    ['What is Section 35 fiduciary Crown obligation?', 'Honour of Crown in taking up title lands', 'Tax', 'Charter s.1', 'Senate'],
    ['What is justificatory framework Sparrow?', 'Valid legislative objective; honourable priority; minimal impairment', 'Oakes identical', 'No test', 'US strict scrutiny'],
    ['What is Quebec Secession Reference clarity on democracy?', 'Democratic vote carries political weight but not unilateral legality alone', 'Unilateral OK', 'Illegal always', 'UN runs vote'],
    ['What is Patriation Reference convention breach debate?', 'Whether federal actions breached constitutional convention', 'No issue', 'Criminal', 'Contract'],
    ['What is living tree Edwards v. Canada (AG)?', 'Persons case — Privy Council interprets BNA Act progressively', 'Oakes', 'Secession', 'Nadar'],
    ['What is Nadaraja / administrative law overlap with Indigenous?', 'Procedural fairness in tribunal decisions affecting rights', 'Sparrow', 'Haida', 'Charter'],
    ['What is Reference re Senate Reform 2014?', 'Limits on unilateral provincial Senate elections etc.', 'Abolish easy', 'Appoint provinces', 'Elect all'],
    ['What is Reference re Supreme Court Act?', 'Eligibility of SCC judges from Quebec — federalism nuances', 'Senate', 'Charter', 'Clarity'],
    ['What is Carter v. Canada assisted dying follow-up Truchon?', 'Quebec disability criteria challenges — evolving legislation', 'Morgentaler', 'Insite', 'Hunter v Southam'],
    ['What is Canada (AG) v. Bedford 2013?', 'Prostitution laws struck; Parliament responded with PCEPA model', 'Morgentaler', 'Little Sisters', 'Sharpe'],
    ['What is Little Sisters Book and Art Emporium v. Canada?', 'Customs censorship and Charter freedom of expression', 'Bedford', 'Irwin Toy', 'Ford v Quebec'],
    ['What is Irwin Toy Ltd. v. Quebec?', 'Commercial speech and Charter section 1 limits', 'Ford language', 'Bedford', 'Oakes'],
    ['What is Ford v. Quebec?', 'Strike down parts of Bill 101 sign law — not withstanding use later', 'Bill 101 all void', 'Charter language rights s.23', 'Meech'],
    ['What is R v. Big M Drug Mart Sunday closing?', 'Freedom of religion Charter early case', 'Oakes', 'Morgentaler', 'Sparrow'],
    ['What is Oakes proportionality test parts?', 'Pressing objective; rational connection; minimal impairment; balance', 'Sparrow same', 'One step', 'US only'],
    ['What is Doré/Loyola framework?', 'Administrative decision makers balancing Charter values', 'Oakes only courts', 'Sparrow', 'Haida'],
    ['What is Vriend v. Alberta?', 'Reading in sexual orientation to provincial human rights law', 'Charter s.15', 'Morgentaler', 'Bedford'],
    ['What is Same-sex marriage reference 2004?', 'Federal authority to define marriage including same-sex', 'Provincial only', 'US Supreme Court', 'Charter s.2'],
    ['What is Trinity Western law school cases arc?', 'Religious freedom vs LGBTQ equality in accreditation — split outcomes over time', 'Ford', 'Big M', 'Bedford'],
    ['What is carbon pricing constitutional division?', 'GGPPA upheld as national concern peace order good government', 'Provincial only', 'Criminal law only', 'Tax only'],
    ['What is cooperative federalism vs watertight compartments?', 'Modern spending power and shared cost programs debates', '1867 only', 'No federal spending', 'US tenth'],
    ['What is spending power reference?', 'Federal strings on transfers — conditional grants constitutionality debates', 'Carbon', 'Clarity', 'Senate'],
    ['What is fiscal stabilization program constitutional?', 'Equalization and stabilization formulas political sensitivity', 'Charter', 'Clarity', 'Senate'],
    ['What is Quebec distinct society clause Meech failure impact?', 'Later Calgary/Social Union attempts; no entrenched clause', 'Entrenched 1990', 'Repealed Charter', 'US tenth'],
    ['What is Charlottetown Senate Triple-E proposal?', 'Elected, equal, effective — failed with accord', 'Implemented', 'Senate gone', 'US Senate copy'],
    ['What is Indigenous self-government Charlottetown proposal?', 'Recognized inherent right — accord failed', 'Implemented fully', 'Never proposed', 'US tribes'],
    ['What is Peace, order and good government (POGG) national concern branch evolution?', 'Carbon, marine pollution, etc. modern cases', 'Only 1867', 'Never used', 'Criminal only'],
    ['What is provincial inability branch POGG?', 'When provincial laws cannot address extra-provincial harms', 'Carbon', 'Senate', 'Clarity'],
    ['What is emergency branch POGG?', 'War and urgent national crises historically', 'Carbon', 'Senate', 'Municipal'],
    ['What is Emergencies Act 1988 vs War Measures Act?', 'Parliamentary oversight and proportionality requirements', 'Identical', 'Stricter never', 'Weaker'],
    ['What is Rouleau Commission?', 'Public inquiry into Emergencies Act 2022 invocation', 'Gomery', 'Krever', 'MMIWG'],
    ['What is sponsorship inquiry Gomery?', 'Public inquiry into sponsorship scandal', 'Rouleau', 'Krever', 'Air India'],
    ['What is Krever Inquiry?', 'Contaminated blood scandal public inquiry', 'Gomery', 'MMIWG', 'Phoenix'],
    ['What is Air India bombing 1985 legacy inquiries?', 'Failures in intelligence and prosecution — security reforms', 'CSIS birth', 'RCMP only', 'None'],
    ['What is Maher Arar inquiry recommendations?', 'Rendition and torture mistakes — RCMP and border reforms', 'MMIWG', 'Gomery', 'Krever'],
    ['What is Phoenix pay class actions?', 'Workers compensation litigation and settlements', 'SNC', 'Sponsorship', 'Residential'],
    ['What is SNC-Lavalin remediation agreement legal model?', 'Deferred prosecution agreements for corporate corruption — ethics debates', 'Phoenix', 'Sponsorship', 'Gomery'],
  ],
};
