import type { Fact } from './group1';

/** Professional financial technology and modern payments — suitable for corporate events. */
export const fintech: Record<number, Fact[]> = {
  1: [
    ['What is a mobile banking app used for?', 'Managing accounts and payments on a phone', 'Only playing games', 'Only social media', 'Only email'],
    ['What is a debit card?', 'Pays directly from your bank account', 'A loan from the bank', 'A gift card', 'A paper check'],
    ['What is a credit card?', 'Lets you borrow funds up to a limit to pay later', 'Same as debit always', 'Only for cash withdrawals', 'A store loyalty card'],
    ['What is contactless payment?', 'Tap card or phone near a reader without inserting', 'Mailing a check', 'Phone call to bank', 'Cash only'],
    ['What is a digital wallet?', 'App that stores payment methods securely', 'A physical wallet photo', 'A spreadsheet', 'A paper ledger'],
    ['What is an ATM mainly for?', 'Withdrawing cash and basic account services', 'Applying for mortgages', 'Stock trading', 'Tax filing'],
    ['What is a bank statement?', 'A record of account transactions over a period', 'A job reference', 'A loan contract', 'A credit score'],
    ['What is a transaction fee?', 'A charge for processing a payment or service', 'Free always', 'Only government tax', 'Interest earned'],
    ['What is peer-to-peer payment (e.g. app to app)?', 'Sending money directly between people digitally', 'Only bank wires', 'Only checks', 'Only payroll'],
    ['What is two-factor authentication?', 'A second verification step beyond a password', 'Two passwords only', 'Two bank accounts', 'Two signatures'],
    ['What is encryption in banking apps?', 'Scrambling data so only authorized parties can read it', 'Deleting all data', 'Printing receipts', 'Slowing the app'],
    ['What is a routing number (US) used for?', 'Identifying your bank in transfers', 'Your password', 'Your credit score', 'Your branch hours'],
    ['What is a savings account primarily for?', 'Storing money to earn interest over time', 'Daily spending only', 'Stock trading', 'Payroll only'],
    ['What is a checking account primarily for?', 'Everyday deposits and withdrawals', 'Long-term investing only', 'Retirement only', 'Foreign exchange only'],
    ['What is a loan principal?', 'The original amount borrowed before interest', 'The interest only', 'The monthly fee', 'The credit limit'],
    ['What is interest on a loan?', 'Cost of borrowing over time', 'Free money from bank', 'One-time application fee', 'Insurance premium'],
    ['What is a budget (simple definition)?', 'A plan for income and spending', 'A bank account type', 'A tax audit', 'A stock ticker'],
    ['What is payroll direct deposit?', 'Paycheck sent electronically to your bank account', 'Cash envelope', 'Paper check mailed to employer', 'Wire to vendor'],
    ['What is a receipt?', 'Proof of a purchase', 'A loan document', 'A stock certificate', 'A password reset'],
    ['What is expense reimbursement?', 'Employer paying you back for approved work costs', 'A bank loan', 'A tax refund', 'A dividend'],
    ['What is a corporate card?', 'Card issued by employer for authorized business spend', 'Personal debit card', 'Gift card', 'ATM-only card'],
    ['What is invoicing?', 'Requesting payment for goods or services delivered', 'Paying a supplier', 'Filing taxes', 'Opening an account'],
    ['What is accounts payable?', 'Money a company owes suppliers', 'Money customers owe the company', 'Employee salaries paid', 'Shareholder equity'],
    ['What is accounts receivable?', 'Money customers owe the company', 'Money owed to suppliers', 'Cash in vault', 'Bond principal'],
    ['What is a point-of-sale (POS) terminal?', 'Device that processes in-store card payments', 'An HR system', 'A stock exchange', 'A website only'],
    ['What is chip-and-PIN?', 'Card security using embedded chip and PIN entry', 'Signature-only cards', 'Online-only checkout', 'Cash discount'],
    ['What is fraud monitoring?', 'Watching transactions for suspicious patterns', 'Marketing emails', 'Credit score marketing', 'Branch staffing'],
    ['What is a beneficiary on a wire transfer?', 'The intended recipient of funds', 'The bank CEO', 'The wire fee', 'The exchange rate'],
    ['What is foreign exchange (FX) rate?', 'Price of one currency in terms of another', 'Stock price', 'Bond coupon', 'Inflation index'],
    ['What is a neobank (simple)?', 'Digital-first bank without traditional branch network', 'Only investment bank', 'Only central bank', 'Only credit union'],
    ['What is Buy Now Pay Later (BNPL)?', 'Short-term installment financing at checkout', 'A 30-year mortgage', 'Stock options', '401(k) loan'],
    ['What is a subscription billing model?', 'Recurring charges for ongoing access to a product/service', 'One-time invoice', 'Cash only', 'Payroll deduction only'],
    ['What is tokenization in card security?', 'Replacing sensitive card data with a surrogate value', 'Printing tokens at branch', 'Reward points only', 'PIN change'],
    ['What is PCI DSS about (one line)?', 'Security standards for organizations that handle card data', 'Payroll compliance', 'Public company annual report', 'Patent classification'],
    ['What is KYC in banking (simple)?', 'Know Your Customer — verifying customer identity', 'Keep Your Card', 'Key Yield Curve', 'Know Your Competitor'],
    ['What is AML about (simple)?', 'Anti–money laundering controls and monitoring', 'Automated loan marketing', 'Asset liability model', 'Annual minimum loan'],
    ['What is open banking (simple)?', 'Sharing financial data via APIs with customer consent', 'Banks open 24/7', 'No passwords', 'Public stock tickers'],
    ['What is a core banking system?', 'Central software processing accounts, loans, and transactions', 'Gym membership software', 'CRM only', 'Email server'],
    ['What is real-time gross settlement (concept)?', 'Settling payments individually in near real time', 'Monthly batch only', 'Cash deposits only', 'Stock settlement T+5'],
    ['What is ACH (US) in one line?', 'Network for bank-to-bank electronic transfers', 'Credit card brand', 'International wire only', 'Cryptocurrency network'],
    ['What is a wire transfer?', 'Electronic movement of funds between institutions, often same-day', 'ACH always free', 'Cash deposit', 'Payroll batch'],
    ['What is liquidity (corporate finance simple)?', 'Ability to meet short-term obligations with available cash-like assets', 'Profitability', 'Revenue growth', 'Headcount'],
    ['What is a stablecoin (general)?', 'Digital asset designed to hold stable value vs a reference', 'Central bank only', 'Always unregulated', 'Same as stock'],
    ['What is regtech?', 'Technology helping firms comply with regulations efficiently', 'Registered trademarks', 'Regional telecom', 'Retail technology'],
    ['What is insurtech?', 'Technology innovation in insurance products and distribution', 'Internal audit tech', 'Installment tech only', 'Internet speed'],
    ['What is embedded finance?', 'Financial services offered inside non-bank customer journeys', 'ATMs in malls only', 'Bank vault design', 'Payroll only'],
    ['What is a payment gateway?', 'Service authorizing card/e-wallet payments for merchants', 'Bank vault door', 'HR gateway', 'VPN gateway'],
    ['What is ISO 8583 related to?', 'Financial transaction card originated messages standard', 'ISO country codes', 'ISO image format', 'ISO 9001 quality'],
    ['What is a ledger in accounting?', 'Record of financial transactions', 'Office notebook', 'Shipping ledger dock', 'Patent ledger'],
    ['What is reconciliation in finance ops?', 'Matching two sets of records to ensure they agree', 'Firing an employee', 'Merging banks', 'IPO pricing'],
  ],
  2: [
    ['What is interchange in card payments?', 'Fee between merchant and card networks/issuers for processing', 'Currency exchange desk', 'Stock interchange', 'Wire interchange'],
    ['What is a merchant acquirer?', 'Bank or processor that enables merchants to accept cards', 'Customer who acquires goods', 'Company buyer of startups', 'Tax collector'],
    ['What is PSD2 in Europe about (high level)?', 'Payment services regulation including SCA and open banking', 'Privacy only', 'Securities trading', 'Pension deposits'],
    ['What is Strong Customer Authentication (SCA)?', 'Multi-factor customer verification for electronic payments', 'Single password only', 'CEO approval', 'Branch visit only'],
    ['What is RTP / instant payments (general)?', 'Near real-time retail payment systems (country-specific)', 'Batch ACH only', '30-day invoice', 'Stock T+0'],
    ['What is a CBDC?', 'Central bank digital currency liability', 'Commercial bank token', 'Bitcoin', 'Stablecoin always'],
    ['What is a custodian in asset servicing?', 'Entity that holds securities for safekeeping on behalf of clients', 'Retail teller', 'Loan officer', 'Tax preparer'],
    ['What is clearing vs settlement (simple)?', 'Clearing: confirming obligations; Settlement: actual transfer of assets/funds', 'Same step', 'Only for stocks', 'Only for cash'],
    ['What is T+2 settlement (classic equities)?', 'Trade date plus two business days for standard settlement', 'Two seconds', 'Two months', 'Two years'],
    ['What is SWIFT used for?', 'Secure messaging network for international payment instructions', 'Domestic ACH', 'Cryptocurrency mining', 'Credit scoring'],
    ['What is an IBAN?', 'International Bank Account Number format for cross-border payments', 'Internal budget account number', 'Internet bandwidth allocation', 'Invoice batch account'],
    ['What is FX hedging (simple)?', 'Using instruments to reduce currency fluctuation risk', 'Hiding foreign accounts', 'Eliminating FX entirely', 'Tax avoidance'],
    ['What is a letter of credit in trade finance?', 'Bank guarantee that seller will be paid if documents comply', 'Personal credit report', 'Credit card limit letter', 'Loan denial letter'],
    ['What is supply chain finance?', 'Financing solutions linked to supplier-buyer trade flows', 'Retail supply closet', 'HR supply planning', 'IT supply tickets'],
    ['What is dynamic discounting?', 'Supplier offered early payment for a discount that varies by timing', 'Random discounts', 'Employee discounts', 'Loyalty points'],
    ['What is invoice factoring?', 'Selling receivables to a third party for immediate cash less a fee', 'Factoring polynomials', 'Tax factoring', 'HR factoring'],
    ['What is a virtual account?', 'Sub-account structure for tracking collections/payments without many physical accounts', 'VR bank branch', 'Fake account', 'Demo account only'],
    ['What is treasury management system (TMS)?', 'Software for cash, liquidity, investments, and risk operations', 'Retail mobile app', 'HR payroll system', 'CRM'],
    ['What is cash pooling (treasury)?', 'Centralizing subsidiary balances to optimize interest and liquidity', 'ATM cash loading', 'Retail cash drawers', 'Payroll pooling'],
    ['What is notional pooling?', 'Offsetting balances for interest calculation without physical transfer', 'Swimming pool financing', 'Stock pool', 'Insurance pool'],
    ['What is a payment service provider (PSP)?', 'Company processing payments for merchants', 'Federal Reserve', 'Stockbroker', 'Insurance broker'],
    ['What is a sponsor bank in fintech?', 'Licensed bank partnering with fintech for regulated activities', 'Event sponsor', 'Sports sponsor', 'Charity sponsor'],
    ['What is BIN (bank identification number)?', 'First digits of card identifying issuing institution', 'Binary file', 'Shopping basket ID', 'Blockchain index'],
    ['What is 3-D Secure for cards?', 'Extra authentication step for online card transactions', 'Three-day settlement', 'Triple interchange', 'Three PINs'],
    ['What is a chargeback?', 'Reversal of a card transaction after dispute', 'Extra charge', 'Wire fee', 'ATM fee'],
    ['What is a payment orchestration layer?', 'Routes transactions across multiple PSPs/acquirers for resilience/cost', 'Orchestra tickets', 'DNS orchestration', 'HR scheduling'],
    ['What is a ledger in blockchain (simple)?', 'Append-only record of transactions across a network', 'SQL database always', 'Bank vault paper', 'Excel only'],
    ['What is a smart contract (simple)?', 'Self-executing code on a blockchain when conditions are met', 'Paper contract with QR', 'Employment contract PDF', 'SLA template'],
    ['What is DeFi (high level)?', 'Decentralized financial protocols on blockchains', 'Department of Finance', 'Defined finance KPIs', 'Delaware incorporation'],
    ['What is a robo-advisor?', 'Automated portfolio management using algorithms', 'Robot factory advisor', 'Physical branch robot', 'ATM robot'],
    ['What is reg reporting automation?', 'Systems producing regulatory submissions from data pipelines', 'Automated marketing', 'Automated hiring', 'Automated payroll jokes'],
    ['What is SOX control testing?', 'Testing internal controls over financial reporting (US)', 'Socks inventory audit', 'Software license audit', 'Sales training'],
    ['What is Basel III about (very high level)?', 'International banking standards for capital, liquidity, and leverage', 'Basel world watch fair', 'Base salary law', 'Basketball rules'],
    ['What is liquidity coverage ratio about?', 'Short-term liquidity buffer vs stressed outflows', 'Loan approval speed', 'Credit score', 'Branch count'],
    ['What is IFRS 9 impairment model about?', 'Expected credit loss recognition for financial instruments', 'Nine IFRS reports', 'Nine-year leases', 'Nine-day payments'],
    ['What is a payment initiation service (PIS) under PSD2?', 'Third party initiates payment from user bank with consent', 'Bank prints checks', 'Cash delivery', 'ATM refill'],
    ['What is account information service (AIS) under PSD2?', 'Aggregating account data with consent via APIs', 'Opening new accounts', 'Closing accounts', 'Printing statements only'],
    ['What is tokenized card data in mobile wallets?', 'Device-specific surrogate, not actual PAN, used for tap', 'Photo of card', 'Barcode of loyalty', 'QR of invoice'],
    ['What is faster payments / FedNow (US concept)?', 'Infrastructure for near real-time bank payments', 'Same as checks', 'Credit card network', 'Stock exchange'],
    ['What is RTP in US payments (The Clearing House)?', 'Real-time payments rail for instant bank transfers', 'Return to payer', 'Real-time pricing', 'Retail tax portal'],
    ['What is ISO 20022 migration about?', 'Richer structured data in payment messages globally', '20022 ISO certificates', 'Binary upgrade', 'QR code size'],
    ['What is a digital asset custody solution?', 'Secure storage and policy controls for institutional crypto assets', 'USB stick backup', 'Cloud photo storage', 'Email archive'],
    ['What is travel rule in crypto compliance?', 'Sharing sender/beneficiary info for transfers above thresholds', 'Airline ticket rules', 'Vacation policy', 'Sales travel budget'],
    ['What is blockchain analytics used for?', 'Tracing flows and risk flags on-chain for compliance', 'Mining bitcoin', 'Designing logos', 'Writing smart contracts only'],
    ['What is embedded lending?', 'Credit offered at point of need inside a merchant journey', 'Bank branch lending', 'Only mortgages', 'Only car loans at dealer'],
    ['What is BNPL credit risk concern?', 'Higher delinquency vs traditional underwriting in some cohorts', 'BNPL has no risk', 'BNPL is illegal', 'BNPL is only B2B'],
    ['What is a banking-as-a-service (BaaS) platform?', 'APIs letting brands embed regulated banking products', 'Bank building architects', 'ATM maintenance', 'Vault cooling'],
    ['What is KYB?', 'Know Your Business — verifying corporate customers', 'Keep Your Budget', 'Key Yearly Bonus', 'Know Your Brand'],
    ['What is adverse media screening?', 'Checking news/legal sources for negative information on clients', 'Social media ads', 'Press releases only', 'Stock media'],
  ],
  3: [
    ['What is AML transaction monitoring tuned to detect?', 'Structuring, unusual velocity, sanctions hits, typologies', 'Marketing clicks', 'Website latency', 'Employee birthdays'],
    ['What is a SAR in financial crime compliance?', 'Suspicious activity report to authorities (jurisdiction-specific)', 'Sales activity report', 'System availability report', 'Stock analyst rating'],
    ['What is beneficial ownership threshold commonly about?', 'Identifying individuals who own or control above a set %', 'Minimum credit score', 'Minimum deposit', 'Minimum invoice'],
    ['What is sanctions list screening?', 'Matching names/entities against OFAC/EU/UN etc. lists', 'Screening job applicants', 'Screening vendors for diversity', 'Screening ads'],
    ['What is PEP in KYC context?', 'Politically exposed person — higher risk monitoring', 'Personal expense policy', 'Preferred equity partner', 'Payment escrow platform'],
    ['What is EDD in KYC?', 'Enhanced due diligence for higher-risk relationships', 'Estimated delivery date', 'End of day deposit', 'Electronic debit draft'],
    ['What is CDD vs EDD?', 'Customer due diligence baseline vs enhanced for higher risk', 'Credit debit difference', 'Cash deposit difference', 'Corporate division department'],
    ['What is a correspondent bank?', 'Bank providing services on behalf of another bank in cross-border flows', 'Bank CEO correspondent', 'Customer bank', 'Retail branch'],
    ['What is nostro vs vostro accounts?', 'Our account at your bank vs your account at our bank', 'North vs south accounts', 'New vs old accounts', 'Net vs gross'],
    ['What is SWIFT gpi about?', 'Tracking and faster transparency for cross-border payments', 'Government PI', 'Gaming payment interface', 'General payment index'],
    ['What is a payment vs settlement finality difference?', 'Payment instruction vs irrevocable transfer of funds/securities', 'No difference', 'Only domestic', 'Only crypto'],
    ['What is CLS Bank role (high level)?', 'Mitigating FX settlement risk via payment-versus-payment', 'Clearing stock loans', 'Customer loan servicing', 'Credit limit setting'],
    ['What is intraday liquidity risk?', 'Running out of cash during the business day despite end-day surplus', 'Year-end risk', 'FX translation risk', 'Cyber risk'],
    ['What is a liquidity stress test?', 'Modeling cash needs under adverse scenarios', 'Stress testing employees', 'Marketing stress test', 'Server load test'],
    ['What is IRRBB?', 'Interest rate risk in the banking book', 'Internal rate of return buyback', 'Invoice receipt routing batch base', 'Investor relations risk'],
    ['What is FRTB in market risk (Basel)?', 'Fundamental review of the trading book standards', 'Fast real-time banking', 'Federal retail tax base', 'Foreign remittance tax bureau'],
    ['What is CVA desk function (simple)?', 'Managing counterparty credit valuation adjustments on derivatives', 'Customer value analytics', 'Cash vault administration', 'Card verification API'],
    ['What is initial margin for cleared derivatives?', 'Collateral required upfront to cover potential future exposure', 'First invoice margin', 'IPO margin', 'Interest margin'],
    ['What is variation margin?', 'Daily collateral transfers based on mark-to-market moves', 'Variable interest rate', 'Variance report', 'Vendor margin'],
    ['What is EMIR in EU about (one line)?', 'OTC derivatives reporting and clearing obligations', 'Emergency interest rates', 'Employee immigration records', 'Electronic money issuance rules'],
    ['What is MiFID II mainly about?', 'EU markets in financial instruments transparency and conduct', 'Military finance', 'Minimum deposit II', 'Mutual fund insurance directive'],
    ['What is SFDR about?', 'EU sustainable finance disclosure rules for products/advisers', 'Single factor default risk', 'Securities fraud detection report', 'Swift financial data relay'],
    ['What is DORA in EU (2024 era)?', 'Digital operational resilience for financial entities', 'Data ownership rights act', 'Deposit oversight risk assessment', 'Dividend operational reporting audit'],
    ['What is NIS2 related to?', 'EU cybersecurity directive expanding obligations', 'Network interchange standard 2', 'National insurance schedule', 'Non-interest spread'],
    ['What is PCI token service provider?', 'Entity issuing tokens replacing PAN per PCI rules', 'Personal credit index', 'Public capital investment', 'Prime custody intermediary'],
    ['What is network tokenization (Visa/MC context)?', 'Domain- or device-scoped tokens replacing primary PAN', 'Tokenizing employees', 'Tokenizing real estate', 'Tokenizing emails'],
    ['What is 3DS2 improvement over 3DS1?', 'Richer data and smoother mobile/challenge flows', 'Three domains instead of two', 'Triple fees', 'Three signatures'],
    ['What is account-to-account (A2A) payment growth driver?', 'Open banking rails and lower merchant costs vs cards', 'Cash comeback', 'Check revival', 'Wire-only regulation'],
    ['What is embedded insurance?', 'Coverage offered within purchase flows (travel, device, etc.)', 'HR benefits portal', 'Bank vault insurance', 'CEO insurance'],
    ['What is parametric insurance (fintech angle)?', 'Payouts triggered by objective parameters (weather, flight delay)', 'Parameter tuning in SQL', 'Parliamentary insurance', 'Parent insurance'],
    ['What is usage-based billing?', 'Charges tied to measured consumption of a service', 'Flat fee only', 'Annual license only', 'Cash only'],
    ['What is revenue recognition ASC 606 / IFRS 15 about?', 'When and how to recognize revenue from contracts with customers', 'Tax recognition', 'Payroll recognition', 'Dividend recognition'],
    ['What is ASC 326 / IFRS 9 expected credit losses?', 'Forward-looking impairment for financial instruments', 'Expected customer logins', 'Expected server cost', 'Expected churn rate marketing'],
    ['What is lease accounting ASC 842 / IFRS 16 change?', 'Most leases on balance sheet as ROU asset and liability', 'Leases off balance sheet always', 'Only car leases', 'Only real estate lessors'],
    ['What is SOX ITGC?', 'IT general controls supporting financial reporting reliability', 'Socks inventory control', 'Sales order XML gateway control', 'Software open exchange'],
    ['What is BCBS 239 about?', 'Risk data aggregation and risk reporting principles for banks', '239 Basel committee members', 'Branch cash balance standard', 'Buy-side compliance benchmark'],
    ['What is operational resilience in UK/EU financial regs?', 'Impact tolerances and self-assessment for disruption', 'Office Wi-Fi speed', 'HR resilience training', 'Marketing bounce rate'],
    ['What is consumer duty (UK FCA concept)?', 'Delivering good outcomes for retail customers', 'Duty on imports', 'Duty-free shopping', 'Director fiduciary duty only'],
    ['What is GDPR lawful basis for processing (examples)?', 'Consent, contract, legal obligation, legitimate interests, etc.', 'Always consent only', 'No basis needed', 'CEO approval'],
    ['What is right to erasure ("right to be forgotten")?', 'Request deletion of personal data under conditions', 'Delete bank accounts always', 'Delete credit history always', 'Delete invoices'],
    ['What is Schrems II relevance?', 'EU-US data transfers need safeguards after court decision', 'Schema design', 'Streams II protocol', 'Screening II rules'],
    ['What is DORA ICT third-party risk?', 'Managing concentration and resilience for critical ICT vendors', 'Dora the explorer', 'Door access', 'Deposit origination risk'],
    ['What is eIDAS about?', 'EU trust services for electronic identification and signatures', 'Electronic IRS', 'Employee ID as service', 'Equity identification and settlement'],
    ['What is PSD3 / PSR EU package (high level, 2023+)?', 'Updated payment services rules and supervision (in evolution)', 'Private securities directive', 'Public sector directive', 'Payment standard draft 3 only'],
    ['What is instant payments obligation trend in EU?', 'Requiring reachability of instant credit transfers in euro', 'Banning cards', 'Mandating cash', 'Eliminating FX'],
    ['What is CBDC privacy design tension?', 'Traceability for illicit finance vs user privacy expectations', 'No tension', 'Privacy always maximal', 'Traceability impossible'],
    ['What is algorithmic trading control requirement?', 'Kill switches, throttles, and testing to prevent market disruption', 'Banning algorithms', 'No controls needed', 'Only retail'],
    ['What is MAR inside information rule?', 'EU market abuse regulation on unlawful disclosure/use of inside info', 'Marketing annual review', 'Margin at risk', 'Mutual assistance rule'],
    ['What is SFTR about?', 'Securities financing transactions reporting', 'Single factor testing rule', 'Swift financial transaction relay', 'Sustainable finance taxonomy reporting'],
  ],
  4: [
    ['What is liquidity risk LCR vs NSFR (Basel III)?', 'Short-term 30-day stress vs stable funding structural match', 'Same ratio', 'Only capital', 'Only leverage'],
    ['What is NSFR available stable funding (ASF) vs required stable funding (RSF)?', 'Stable funding sources vs illiquid asset needs', 'Assets vs sales', 'Revenue vs expenses', 'Deposits vs loans'],
    ['What is TLAC for G-SIBs?', 'Total loss-absorbing capacity for resolution', 'Total loans and credit', 'Tax loss carryforward', 'Technical liquidity adjustment charge'],
    ['What is resolution planning ("living will")?', 'Plan for orderly failure without systemic harm', 'CEO will', 'Product roadmap', 'HR succession'],
    ['What is IRRBB standard about?', 'Measuring and controlling interest rate risk on banking book positions', 'Internet risk', 'Insurance risk', 'Invoice routing risk'],
    ['What is capital floor output floor in Basel output floor?', 'Limits RWA reduction from internal models vs standardized', 'Floor of bank lobby', 'Minimum output VAT', 'Floating rate floor'],
    ['What is SA-CCR?', 'Standardized approach for counterparty credit risk exposures', 'Sales and customer credit review', 'System access customer control record', 'Securities analysis CCR'],
    ['What is IMM for CCR?', 'Internal model method for counterparty credit risk', 'Immediate payment method', 'Integrated margin management', 'International money market'],
    ['What is UTI under EMIR REFIT?', 'Unique Trade Identifier for derivatives reporting', 'Universal tax identifier', 'User transaction index', 'Unified transfer instruction'],
    ['What is ISO 20022 pain.001 / pain.002?', 'Customer credit transfer initiation and status messages', 'Pain points in UX', 'Payment audit index', 'Private AI network'],
    ['What is Request to Pay (RTP messaging concept)?', 'Messaging framework requesting payment from payer (varies by scheme)', 'Same as FedNow', 'Wire SWIFT MT103', 'Card authorization'],
    ['What is four-party card model?', 'Cardholder, issuer, merchant, acquirer (+ networks)', 'Two parties only', 'Six parties always', 'Government only'],
    ['What is scheme fees vs interchange?', 'Network brand fees vs issuer/acquirer interchange component', 'Same fee', 'Only tax', 'Only FX'],
    ['What is least cost routing (debit)?', 'Merchants route transactions to lower-cost network when dual-badged', 'Customer picks network', 'Random routing', 'Government routing'],
    ['What is PINless debit fraud controls?', 'Risk limits and velocity checks for card-not-present debit', 'No controls', 'PIN always required online', 'Debit banned online'],
    ['What is account funding transaction (AFT) / original credit transaction (OCT)?', 'Pull/push models for wallet loads and disbursements in card rails', 'Wire only', 'ACH only', 'Cash only'],
    ['What is merchant category code (MCC) used for?', 'Classifying merchant business for pricing and risk', 'Customer credit score', 'Currency conversion', 'Card expiry'],
    ['What is dynamic currency conversion?', 'Cardholder offered conversion at POS by merchant/acquirer', 'Central bank conversion', 'Free conversion always', 'Illegal in EU'],
    ['What is FX markup on cross-border card?', 'Spread over benchmark FX embedded in card conversion', 'Regulated zero always', 'Interchange only', 'Government tax'],
    ['What is supply chain finance reverse factoring?', 'Buyer-approved invoice financing early to supplier', 'Reverse merger', 'Reverse stock split', 'Reverse wire'],
    ['What is inventory financing?', 'Lending secured by or tied to inventory collateral', 'Office supply financing', 'Cloud inventory', 'HR inventory'],
    ['What is receivables securitization?', 'Packaging receivables into tradable securities', 'Deleting receivables', 'Factoring without investors', 'Payroll securitization'],
    ['What is credit default swap (CDS) (simple)?', 'Contract transferring credit exposure on a reference entity', 'Default on credit card', 'Swap bank accounts', 'Deposit insurance'],
    ['What is central clearing mandate for OTC derivatives?', 'Standardized swaps cleared through CCPs', 'All trades on blockchain', 'No clearing allowed', 'Only exchange traded'],
    ['What is CCP default waterfall?', 'Layers of margin and default fund contributions absorbing losses', 'Waterfall chart in Excel', 'CEO pay waterfall', 'Customer waterfall'],
    ['What is variation margin segregation rule (post-crisis)?', 'Protecting cleared client margin at CCP', 'No segregation', 'Segregate stocks only', 'Segregate HR files'],
    ['What is SFTR reuse disclosure about?', 'Transparency of reuse of collateral in SFTs', 'Software reuse', 'Server reuse', 'Staff reuse'],
    ['What is Basel leverage ratio?', 'Tier 1 capital measure vs total exposures (non-risk-weighted backstop)', 'Same as Tier 2', 'Same as LCR', 'Same as RWA'],
    ['What is output floor issue for banks?', 'Modeled RWA cannot fall too far below standardized percentage', 'Output VAT floor', 'Floor trading', 'Data output floor'],
    ['What is RWA?', 'Risk-weighted assets for capital adequacy', 'Risk-weighted accounts payable', 'Random weighted averages', 'Real-world assets only crypto'],
    ['What is CET1 capital?', 'Common Equity Tier 1 — highest quality regulatory capital', 'Customer electronic tier 1', 'Corporate expense tier 1', 'Cash electronic transfer 1'],
    ['What is AT1 / CoCo bonds?', 'Additional Tier 1 contingent convertible capital instruments', 'Automated teller 1', 'Annual tax 1', 'Asset transfer 1'],
    ['What is liquidity transfer pricing (FTP)?', 'Internal bank pricing of funding liquidity to business lines', 'File transfer protocol', 'Federal tax price', 'Foreign trade premium'],
    ['What is behavioral modeling in ALM?', 'Modeling deposit stickiness and optionality for interest risk', 'HR behavior', 'Customer marketing models', 'Fraud behavior only'],
    ['What is funds transfer pricing (FTP) curve?', 'Curve assigning internal funding rates to products', 'Fed funds curve only', 'FX curve only', 'Stock price curve'],
    ['What is NII sensitivity?', 'How net interest income moves with rates', 'Non-interest income', 'Net internal index', 'Nominal inflation index'],
    ['What is EVE in IRRBB?', 'Economic value of equity sensitivity to rate shocks', 'Enterprise value to equity', 'Expected value error', 'Earnings volatility estimate'],
    ['What is parallel vs steepener shock in IRRBB?', 'Rates move parallel vs curve shape changes', 'Same thing', 'Stock shocks', 'Credit shocks'],
    ['What is blockchain trilemma (informal)?', 'Decentralization, security, scalability tradeoffs', 'No tradeoffs', 'Regulatory trilemma', 'Banking trilemma'],
    ['What is layer-2 scaling on Ethereum (concept)?', 'Offload execution with security anchored to L1', 'Second bank account', 'Two-factor ledger', 'Layered KYC'],
    ['What is proof-of-stake vs proof-of-work (high level)?', 'Validators stake vs miners compute hashes to secure network', 'Same mechanism', 'Only Bitcoin uses PoS', 'Only banks use PoW'],
    ['What is oracle problem in DeFi?', 'Getting trustworthy off-chain data on-chain', 'Database oracle only', 'HR oracle', 'SQL problem'],
    ['What is MEV in crypto (simple)?', 'Value extractable by reordering/timing transactions in blocks', 'Minimum expected value', 'Monthly escrow value', 'Merchant escrow verification'],
    ['What is stablecoin reserve attestation?', 'Third-party checks of backing assets vs liabilities', 'Attestation of employees', 'Tax attestation', 'SOX attestation only'],
    ['What is Travel Rule FATF Recommendation 16?', 'VASP sharing originator/beneficiary info for transfers', 'Travel expense policy', 'Flight booking rule', 'Tourism tax'],
    ['What is VASP?', 'Virtual asset service provider under FATF-style frameworks', 'Vendor approved service partner', 'Volume adjusted sale price', 'Virtual account service portal'],
    ['What is chainalysis-type tooling used for?', 'Investigation and compliance monitoring on-chain', 'Mining optimization', 'Wallet UI design', 'NFT art curation'],
    ['What is bank-run risk on stablecoins?', 'If reserves doubted, rapid redemptions strain liquidity', 'Impossible for stablecoins', 'Only for cash', 'Only for CBDC'],
    ['What is narrow banking proposal idea?', '100% safe asset backing for transaction accounts', 'Very small branches', 'Narrow AI in banking', 'Narrow credit scores'],
  ],
  5: [
    ['What is FRTB standardized vs internal models approach?', 'Sensitivities-based vs full internal sim vs desk constraints', 'Same', 'Only VaR', 'Only credit'],
    ['What is default risk charge in FRTB?', 'Charge for jump-to-default risk', 'Charge for late payments', 'Charge for wire defaults', 'Charge for API defaults'],
    ['What is NMRF in FRTB?', 'Non-modellable risk factors requiring capital add-on', 'Non-marketable retail funds', 'New market risk framework', 'Net margin reserve factor'],
    ['What is PLAT vs DRC vs residual in FRTB?', 'Risk factor capital components alongside default risk and residual', 'Platinum tier', 'Platform risk', 'Profit loss attribution test'],
    ['What is SA-CVA vs BA-CVA?', 'Standardized vs basic approach for CVA capital', 'Same', 'Only for retail', 'Only for insurance'],
    ['What is IMM exposure calculation?', 'Effective expected positive exposure profile under netting/collateral', 'Immediate exposure', 'Internal money movement', 'Integrated margin model'],
    ['What is margin period of risk for OTC?', 'Assumed liquidation period for margin calculations', '1 day always', '30 days always', 'Zero for cleared'],
    ['What is SA-CCR hedging recognition sets?', 'Sets of trades recognized for offset within asset class', 'Hedging flowers', 'SQL sets', 'HR hedging'],
    ['What is CEM vs SM vs IMM for exposure?', 'Current exposure method vs standardized vs internal model', 'Same', 'Only for repos', 'Only for cards'],
    ['What is UMR phases for uncleared margin?', 'Phased IM requirements for bilateral OTC', 'Universal margin reset', 'Uncleared merchant receivables', 'Underwriting margin rule'],
    ['What is SIMM for uncleared margin?', 'Standard Initial Margin Model (ISDA) for bilateral IM', 'Simple interest margin model', 'Securities internal market maker', 'Single index margin method'],
    ['What is BCBS intraday liquidity monitoring tools?', 'Metrics for intraday flows and stress', 'ATM tools', 'Intraday stock trading', 'Internal chat tools'],
    ['What is RRP operational tool (Fed)?', 'Reverse repo facility absorbing reserves overnight', 'Retail reward program', 'Risk review panel', 'Real-time payments'],
    ['What is standing repo facility (concept)?', 'Backstop liquidity for Treasury repo markets', 'Employee repo', 'Retail repo', 'Reporting repo'],
    ['What is SLR (supplementary leverage ratio) tweak context?', 'Temporary exclusions affecting Treasury reserves during stress (historical)', 'Student loan ratio', 'Senior leverage review', 'Service level ratio'],
    ['What is LCR numerator high-quality liquid assets categories?', 'Level 1 and 2 assets per rules with haircuts', 'All loans', 'All equities', 'All crypto'],
    ['What is ASF vs RSF in NSFR detail?', 'Stable funding sources vs required stable funding weights by asset type', 'Assets vs sales', 'Cash vs credit', 'Loans vs deposits'],
    ['What is structural FX position recognition?', 'Accounting-driven long positions in equity of foreign subs', 'Structural engineering FX', 'FX hedging ban', 'FX tax'],
    ['What is IRRBB policy rate vs market rate shocks?', 'Shocks to risk-free curve vs credit spreads in banking book', 'Same shock', 'Only credit', 'Only operational'],
    ['What is behavioral optionality in deposits?', 'Early withdrawals and repricing tied to customer behavior', 'CEO options', 'Employee stock options', 'Call options on bonds only'],
    ['What is core vs non-core deposit modeling?', 'Stable vs volatile portions for liquidity risk', 'Checking vs savings names', 'Retail vs corporate names', 'USD vs EUR'],
    ['What is FTP behavioral beta?', 'Sensitivity of product rate to market rate changes', 'HR beta', 'Stock beta only', 'Software beta version'],
    ['What is funds transfer pricing liquidity premium?', 'Charge for term liquidity consumed by long-term assets', 'Premium cable', 'Insurance premium', 'Loan premium tax'],
    ['What is economic capital vs regulatory capital?', 'Internal risk-based capital vs rules-based requirements', 'Same always', 'Only regulatory matters', 'Only economic matters'],
    ['What is RAROC?', 'Risk-adjusted return on capital', 'Return after retirement on capital', 'Retail annual rate of change', 'Regulatory annual review of compliance'],
    ['What is KVA (valuation adjustment)?', 'Capital cost embedded into derivatives valuation', 'Kind value added', 'Key vendor agreement', 'Known variance adjustment'],
    ['What is MVA (margin valuation adjustment)?', 'Cost of funding initial margin in derivatives pricing', 'Market value added', 'Monthly variance analysis', 'Minimum viable API'],
    ['What is FVA (funding valuation adjustment)?', 'Cost of funding uncollateralized derivatives exposures', 'Fair value adjustment', 'Foreign valuation adjustment', 'Forward variance adjustment'],
    ['What is XVA desk?', 'Manages CVA/DVA/FVA/KVA/MVA adjustments', 'Foreign exchange desk', 'XML validation API', 'X-border vendor approvals'],
    ['What is OIS discounting for derivatives?', 'Discounting using overnight index swap curves', 'Office information systems', 'Order initiation system', 'Open insurance standard'],
    ['What is CSA credit support annex?', 'Legal doc specifying margin terms for derivatives', 'Customer service agreement', 'Central securities association', 'Compliance scope audit'],
    ['What is GMRA for repos?', 'Global Master Repurchase Agreement standard', 'General market risk analysis', 'Gross margin return adjustment', 'Global merchant risk assessment'],
    ['What is ICMA standard for repo?', 'Market standards for repo trading documentation', 'Internal control maturity assessment', 'International card merchant agreement', 'Integrated cash management account'],
    ['What is liability-driven investment (LDI) for pensions?', 'Hedging liabilities with matched-duration assets', 'Liability insurance', 'Loan default index', 'Liquidity demand indicator'],
    ['What is pension risk transfer?', 'Shifting pension obligations to insurer via buy-in/out', 'Transferring 401k to checking', 'Payroll transfer', 'Stock transfer'],
    ['What is longevity risk reinsurance?', 'Hedging pensioners living longer than expected', 'CEO longevity', 'Product longevity', 'Server uptime'],
    ['What is cat bond?', 'Insurance-linked security transferring catastrophe risk to capital markets', 'Category bond', 'Catalog bond', 'CAT scanner bond'],
    ['What is ILS market?', 'Insurance-linked securities market', 'International loan syndication', 'Integrated ledger system', 'Inline security'],
    ['What is side pocket in hedge funds?', 'Illiquid assets segregated with separate redemption rules', 'Pocket money', 'Side channel payments', 'Sidebar in app'],
    ['What is gates and lockups in private funds?', 'Limits on redemption timing to manage illiquidity', 'Security gates', 'Encryption lockups', 'Payroll lock'],
    ['What is NAV calculation independence?', 'Pricing and NAV calc segregated from portfolio management conflicts', 'NAV always public', 'NAV never changes', 'NAV is tax'],
    ['What is Form PF (US private funds)?', 'Confidential reporting of private fund systemic risk data to SEC', 'Public form', 'Payroll form', 'Tax form 1040'],
    ['What is AIFMD in EU?', 'Alternative investment fund managers directive', 'Automated invoice fraud management directive', 'Annual internal finance monitoring document', 'Asset integrity file management directive'],
    ['What is UCITS liquidity rules gist?', 'Retail fund liquidity management and redemption terms', 'US credit IT systems', 'Uniform corporate income tax standard', 'Unclaimed items tracking system'],
    ['What is MMF reform post-crisis theme?', 'Fees, gates, and floating NAV ideas for stable value funds', 'Money merge functions', 'Mutual marketing funds', 'Monthly management fees'],
    ['What is swing pricing in mutual funds?', 'Adjusting NAV to pass transaction costs to subscribing/redeeming investors', 'Golf swing', 'FX swing', 'Swing trading'],
    ['What is anti-dilution in venture (concept)?', 'Protects investor from down-round share price dilution', 'Dilutes employees', 'Dilutes customers', 'Dilutes regulators'],
    ['What is liquidation preference stack?', 'Order in which proceeds pay preferred vs common in exit', 'Stack of invoices', 'Stack in programming', 'Stack of ATMs'],
    ['What is PIK toggle in leveraged finance?', 'Payment-in-kind interest option vs cash interest', 'Personal identification key', 'Public investment kiosk', 'Purchase inventory kit'],
    ['What is covenant-lite loan?', 'Loans with fewer maintenance covenants, more incurrence-based', 'No covenants ever', 'Only for mortgages', 'Government loans'],
    ['What is OID original issue discount for bonds?', 'Discount treated partly as interest income over life', 'Order ID', 'Official issuer domain', 'Open interest derivative'],
  ],
  6: [
    ['What is Basel endgame proposal theme (US 2023+ debate)?', 'Capital rule changes affecting large banks\' RWA and output floor', 'Ending Basel', 'Crypto endgame', 'Retail endgame'],
    ['What is GSIB surcharge?', 'Extra capital requirement for global systemically important banks', 'General sales import bank', 'Global stablecoin interest benchmark', 'Government securities insurance bond'],
    ['What is TLAC MREL interaction EU?', 'Resolution capital requirements for banks / resolution entities', 'MREL is unrelated', 'Only US', 'Only insurance'],
    ['What is SR 11-7 model risk guidance (US)?', 'Federal Reserve supervisory expectations for model validation', 'Software release 11-7', 'Securities rule', 'Swap rule'],
    ['What is OCC 2011-12 (US) model risk?', 'OCC bulletin on model risk management for banks', 'Tax bulletin', 'Insurance bulletin', 'SEC marketing rule'],
    ['What is PRA SS3/18 UK?', 'Stress testing expectations for banks', 'Privacy standard', 'Payment standard', 'Pension standard'],
    ['What is ECB TRIM stress test?', 'Targeted review of internal models affecting capital', 'Trimming staff', 'TRIM SQL function', 'Trade reporting internal model'],
    ['What is EBA stress test methodology public element?', 'Adverse macro scenarios applied to bank balance sheets', 'Employee benefit analysis', 'Executive bonus analysis', 'Energy benchmark analysis'],
    ['What is IRRBB Pillar 2 requirement gist?', 'Supervisory outlier tests beyond standardized Pillar 1', 'Only Pillar 1', 'Only leverage', 'Only liquidity'],
    ['What is SA output floor binding issue?', 'Standardized capital becomes binding vs modeled RWA', 'Floor never binds', 'Only for insurers', 'Only for brokers'],
    ['What is countercyclical capital buffer?', 'Macroprudential buffer raised in good times to absorb losses', 'Always zero', 'Always 10%', 'Only for fintech'],
    ['What is G-SII in insurance?', 'Global systemically important insurer designation', 'Government social insurance identifier', 'General securities internal index', 'Global swap interest index'],
    ['What is ICS for IAIS?', 'International capital standard for insurance groups', 'Internal control system', 'Integrated cash system', 'International compliance statement'],
    ['What is FMI Principles CPSS-IOSCO?', 'Principles for financial market infrastructures (CSDs, CCPs, payment systems)', 'Fraud management interface', 'Foreign market index', 'Federal mortgage insurance'],
    ['What is CPMI-IOSCO PFMI implementation monitoring?', 'Oversight of payment, clearing, settlement systems', 'Portfolio management interface', 'Private finance market index', 'Public fund marketing initiative'],
    ['What is PFMI key consideration for CCP recovery?', 'Tools like variation margin gains haircutting, partial tear-up', 'No recovery tools', 'Only bankruptcy', 'Only insurance'],
    ['What is skin-in-the-game for securitization?', 'Sponsor retains risk slice to align incentives', 'Sports sponsorship', 'Skin care marketing', 'Security in game purchases'],
    ['What is STS securitization label in EU?', 'Simple, transparent, and standardized criteria for favorable capital', 'Science technology society', 'Short-term swap', 'Sales tax standard'],
    ['What is synthetic securitization vs traditional?', 'Credit protection via derivatives vs true sale of assets', 'Same', 'Only crypto', 'Only mortgages'],
    ['What is significant risk transfer (SRT) test?', 'Whether securitization truly transfers credit risk for capital relief', 'Single risk transfer', 'Software regression testing', 'Securities registration threshold'],
    ['What is look-through approach for investment funds in capital rules?', 'Risk weight underlying exposures not just fund label', 'Look through walls', 'Look through earnings', 'Look through customers'],
    ['What is step-in risk guidance?', 'Risk banks implicitly support off-balance-sheet vehicles in stress', 'Step-in interviews', 'Step functions in pricing', 'Staircase risk'],
    ['What is contingent liquidity risk from guarantees?', 'Draws on committed lines when markets freeze', 'ATM guarantees', 'Deposit guarantees only', 'HR guarantees'],
    ['What is intragroup liquidity transfer restrictions in resolution?', 'Ring-fencing limits liquidity sharing in resolution', 'Unlimited transfers', 'Only domestic', 'Only retail'],
    ['What is MREL for resolution entities EU?', 'Minimum requirement for own funds and eligible liabilities', 'Minimum reserve escrow line', 'Market risk exposure limit', 'Mutual repo eligibility list'],
    ['What is bail-in debt?', 'Debt written down or converted to equity in resolution', 'Bailout debt', 'Bridge loan', 'Bankruptcy loan'],
    ['What is single point of entry resolution strategy?', 'Parent holds TLAC and resolves subsidiarily', 'Multiple POEs', 'Only for insurers', 'Only for brokers'],
    ['What is contractual recognition of stays under ISDA?', 'Close-out stays recognized for resolution stays', 'Contract stays forever', 'No stays', 'Only equities'],
    ['What is NSFR ASF stable funding recognition for deposits?', 'Stable vs less stable deposit ASF factors', 'All deposits 100%', 'No deposits', 'Only wholesale'],
    ['What is LCR operational requirement?', 'Unencumbered HQLA operational capability to monetize', 'Hiring liquidity analysts', 'Liquidity committee charter', 'Loan credit review'],
    ['What is intraday credit lines monitoring?', 'Tracking daylight overdrafts and intraday limits', 'Credit card monitoring', 'Retail credit monitoring', 'Marketing credit'],
    ['What is wholesale vs retail funding stability?', 'Wholesale more flighty; retail often stickier behaviorally', 'Same stability', 'Wholesale safer always', 'Retail always unstable'],
    ['What is encumbrance of assets?', 'Pledged or restricted assets not freely available for liquidity', 'Encryption', 'Encouragement', 'Encapsulation'],
    ['What is matched book repo desk?', 'Repo borrowing and lending balanced', 'Matched customer names', 'Matched currencies only', 'Matched spreadsheets'],
    ['What is sponsored repo access for MMFs?', 'Access to cleared repo via dealer sponsorship', 'Sponsored Instagram', 'Sponsored visas', 'Sponsored audits'],
    ['What is FICC market structure SEC rules theme?', 'Transparency and competition in US Treasury/corporate markets', 'FICC is a bank name only', 'Fixed income only crypto', 'Foreign investor compliance code'],
    ['What is TRACE reporting for corporates?', 'Trade reporting and compliance engine transparency', 'Traceability matrix', 'Traceroute', 'Track receivables'],
    ['What is CAT consolidated audit trail (US equities)?', 'Centralized order event reporting across venues', 'CAT scan', 'Customer account transfer', 'Credit audit trail'],
    ['What is Reg NMS order protection?', 'Best execution across linked markets for protected quotes', 'NMS never applies', 'Only options', 'Only crypto'],
    ['What is MiFID II systematic internalizer?', 'Venue classification for internalizing client orders', 'Internal IT system', 'Systematic risk', 'Internal audit'],
    ['What is double volume cap for dark pools EU?', 'Limits on dark trading when lit volume insufficient', 'Two volume caps stacked', 'Dark pool ban', 'Lit pool ban'],
    ['What is consolidated tape plan debate EU/US?', 'Timely post-trade data aggregation across venues', 'Tape backups', 'Tape storage', 'Duct tape'],
    ['What is best execution policy under MiFID II?', 'Firms take all sufficient steps for best client outcome', 'Cheapest broker always', 'Fastest broker always', 'Internalizing always'],
    ['What is algorithmic trading controls under MiFID II?', 'Kill switches, thresholds, testing, and compliance sign-off', 'No controls', 'Only HFT', 'Only retail'],
    ['What is MAR market soundings regime?', 'Handling inside information during investment recommendations', 'Sounding rockets', 'Sound engineering', 'Market sounding music'],
    ['What is position limits under REMIT/MiFID for commodities?', 'Limits to prevent market abuse on derivatives', 'Employee position limits', 'Bank branch positions', 'Map positions'],
    ['What is EMIR 3.0 / EMIR Refit theme?', 'Reporting simplification and changes (ongoing evolution)', 'Third version deletes EMIR', 'Refit hardware', 'Emergency mirror'],
    ['What is Basel crypto standard group treatment?', 'Bank crypto exposures capital treatment with classification buckets', 'Bans all crypto', 'Ignores crypto', 'Only stablecoins'],
    ['What is prudential treatment of cryptoassets (Basel)?', 'Group 1 vs Group 2 with limits and deductions', 'Same as cash', 'Same as gold always', 'No treatment'],
    ['What is DLT pilot regime EU?', 'Sandbox-style permission for tokenized securities infrastructure', 'Deletes ledgers', 'Pilot for airlines', 'Distributed latency tuning'],
    ['What is T+1 settlement migration impact (US 2024)?', 'Shortens equities settlement increasing operational precision', 'Lengthens to T+7', 'Eliminates clearing', 'Only bonds'],
    ['What is CSDR buy-in regime?', 'Mandatory buy-in for settlement fails in EU securities', 'Buy-in for IPO', 'Buy-in for FX', 'Buy-in for payroll'],
  ],
};
