// [clue, answer, wrong1, wrong2, wrong3]
export type Fact = [string, string, string, string, string];

export const worldPolitics: Record<number, Fact[]> = {
  1: [
    ['Who leads a country?', 'President or Prime Minister', 'Teacher', 'Doctor', 'Chef'],
    ['What is a country?', 'A land with its own government', 'A big house', 'A playground', 'A store'],
    ['What color is the American flag?', 'Red, white, and blue', 'Green and yellow', 'Orange and purple', 'Pink and brown'],
    ['What do people do on Election Day?', 'Vote', 'Sleep', 'Swim', 'Cook'],
    ['What is a flag?', 'A symbol of a country', 'A type of food', 'A kind of animal', 'A color'],
    ['What is a law?', 'A rule everyone must follow', 'A type of game', 'A song', 'A book'],
    ['Where does a president live in the USA?', 'The White House', 'A castle', 'A farm', 'A school'],
    ['What is a capital city?', 'The main city of a country', 'The biggest park', 'A shopping mall', 'A zoo'],
    ['What shape is a stop sign?', 'Octagon', 'Circle', 'Square', 'Triangle'],
    ['What country has a maple leaf on its flag?', 'Canada', 'Mexico', 'Brazil', 'France'],
    ['Who makes laws in the United States?', 'Congress', 'Firefighters', 'Teachers', 'Doctors'],
    ['What do we call the leader of a city?', 'Mayor', 'King', 'Captain', 'Principal'],
    ['What is the capital of the United States?', 'Washington, D.C.', 'New York', 'Los Angeles', 'Chicago'],
    ['What animal is on the Mexican flag?', 'Eagle', 'Lion', 'Bear', 'Tiger'],
    ['How many stars are on the US flag?', '50', '13', '25', '100'],
    ['What is a king or queen?', 'A royal leader', 'A type of pet', 'A sport', 'A food'],
    ['What do police officers help with?', 'Keeping people safe', 'Cooking food', 'Building houses', 'Flying planes'],
    ['What is a community?', 'A group of people living together', 'A kind of toy', 'A tree', 'A game'],
    ['What do firefighters do?', 'Put out fires', 'Build roads', 'Teach math', 'Fly planes'],
    ['What continent is the USA on?', 'North America', 'Europe', 'Asia', 'Africa'],
    ['What is a neighbor?', 'Someone who lives near you', 'A type of fish', 'A planet', 'A car'],
    ['What is a citizen?', 'A member of a country', 'A kind of bird', 'A sport', 'A building'],
    ['What does a judge do?', 'Makes decisions about laws', 'Drives a bus', 'Fixes cars', 'Paints houses'],
    ['What is peace?', 'No fighting or war', 'A type of fruit', 'A dance', 'A toy'],
    ['What country is shaped like a boot?', 'Italy', 'Japan', 'India', 'Brazil'],
    ['What do we celebrate on the Fourth of July?', 'Independence Day', 'Halloween', 'Christmas', 'Easter'],
    ['What is a passport?', 'A travel document', 'A toy', 'A snack', 'A game'],
    ['What is a government?', 'A group that leads a country', 'A school subject', 'A type of weather', 'A sport'],
    ['Who helps sick people in a community?', 'Doctors and nurses', 'Pilots', 'Farmers', 'Painters'],
    ['What is a map?', 'A picture of a place', 'A type of hat', 'A musical instrument', 'A food'],
    ['What is the biggest country in the world?', 'Russia', 'Canada', 'China', 'Brazil'],
    ['What is a state?', 'A part of a country', 'A color', 'A planet', 'A type of car'],
    ['How many stripes are on the US flag?', '13', '50', '7', '20'],
    ['What color is the Canadian flag?', 'Red and white', 'Blue and green', 'Yellow and black', 'Purple and orange'],
    ['What is a volunteer?', 'Someone who helps for free', 'A type of animal', 'A building', 'A sport'],
    ['What is a border?', 'A line between countries', 'A type of flower', 'A dance move', 'A color'],
    ['What do mail carriers do?', 'Deliver letters', 'Build houses', 'Drive taxis', 'Cook food'],
    ['What continent is Japan on?', 'Asia', 'Europe', 'Africa', 'South America'],
    ['What is a parade?', 'People marching together', 'A type of soup', 'A school test', 'A kind of tree'],
    ['What holiday honors workers?', 'Labor Day', 'Valentines Day', 'New Years Day', 'Earth Day'],
    ['What language do people speak in France?', 'French', 'Spanish', 'German', 'Italian'],
    ['What is an island?', 'Land surrounded by water', 'A tall building', 'A mountain', 'A type of cloud'],
    ['What is a globe?', 'A round model of Earth', 'A type of lamp', 'A food', 'A hat'],
    ['What language do people speak in Mexico?', 'Spanish', 'French', 'English', 'Japanese'],
    ['What is a team?', 'People working together', 'A kind of plant', 'A type of rock', 'A shape'],
    ['Who was the first US president?', 'George Washington', 'Abraham Lincoln', 'Thomas Jefferson', 'John Adams'],
    ['What is the name of Englands royal family?', 'The Royal Family', 'The First Family', 'The Super Family', 'The Great Family'],
    ['What is a library?', 'A place to borrow books', 'A restaurant', 'A gym', 'A hospital'],
    ['What is a uniform?', 'Special clothes for a job', 'A type of dance', 'A food', 'A game'],
    ['What is a continent?', 'A large area of land', 'A type of ocean', 'A small island', 'A city'],
  ],
  2: [
    ['What is a democracy?', 'People choose their leaders', 'One person rules forever', 'No one is in charge', 'Animals pick leaders'],
    ['What is an election?', 'When people vote for leaders', 'A type of party', 'A school subject', 'A holiday'],
    ['What is the United Nations?', 'A group of countries working together', 'A sports league', 'A school club', 'A band'],
    ['How many continents are there?', '7', '5', '10', '3'],
    ['What is a president?', 'The leader of a country', 'A type of teacher', 'A baker', 'A pilot'],
    ['What does a governor lead?', 'A state', 'A school', 'A team', 'A club'],
    ['What is a ballot?', 'A paper used to vote', 'A type of ball', 'A hat', 'A toy'],
    ['What is the capital of England?', 'London', 'Paris', 'Dublin', 'Berlin'],
    ['What do ambassadors do?', 'Represent their country abroad', 'Cook food', 'Drive buses', 'Build bridges'],
    ['What is a monarchy?', 'A country led by a king or queen', 'A type of garden', 'A card game', 'A sport'],
    ['What is a national anthem?', 'A countrys official song', 'A lullaby', 'A pop song', 'A school chant'],
    ['What is a constitution?', 'The main rules of a country', 'A math test', 'A recipe book', 'A map'],
    ['What is a tax?', 'Money paid to the government', 'A type of candy', 'A game', 'A pet'],
    ['What is freedom of speech?', 'The right to share your ideas', 'A school rule', 'A type of singing', 'A dance'],
    ['What is a republic?', 'People elect representatives', 'A kingdom', 'A store', 'A park'],
    ['What is a treaty?', 'An agreement between countries', 'A school test', 'A type of tree', 'A recipe'],
    ['What country has a dragon on its flag?', 'Wales', 'Ireland', 'France', 'Spain'],
    ['What is a protest?', 'People showing they disagree', 'A party', 'A game show', 'A concert'],
    ['What is a senator?', 'An elected lawmaker', 'A teacher', 'A doctor', 'A scientist'],
    ['What ocean is between the USA and Europe?', 'Atlantic Ocean', 'Pacific Ocean', 'Indian Ocean', 'Arctic Ocean'],
    ['What is immigration?', 'Moving to a new country', 'Going to school', 'Shopping', 'Cooking'],
    ['What is the capital of France?', 'Paris', 'London', 'Rome', 'Madrid'],
    ['What is a dictator?', 'A leader with total control', 'A teacher', 'A coach', 'A librarian'],
    ['What is a refugee?', 'Someone fleeing danger', 'A tourist', 'A pilot', 'A farmer'],
    ['What is a political party?', 'A group with shared beliefs', 'A birthday party', 'A dance', 'A game'],
    ['What is a courthouse?', 'Where legal cases are heard', 'A bakery', 'A library', 'A gym'],
    ['What is the capital of Japan?', 'Tokyo', 'Beijing', 'Seoul', 'Bangkok'],
    ['What are human rights?', 'Freedoms everyone deserves', 'School supplies', 'Sports rules', 'Recipes'],
    ['What is a prime minister?', 'The head of a government', 'A math teacher', 'A chef', 'A pilot'],
    ['What is an army?', 'Soldiers who protect a country', 'A team of cooks', 'A group of singers', 'A band'],
    ['What is a colony?', 'Land controlled by another country', 'A group of ants', 'A school club', 'A garden'],
    ['What is the capital of China?', 'Beijing', 'Shanghai', 'Tokyo', 'Seoul'],
    ['What does the Statue of Liberty stand for?', 'Freedom', 'Cooking', 'Swimming', 'Shopping'],
    ['What is a debate?', 'A formal argument about ideas', 'A food fight', 'A sport', 'A joke'],
    ['What is a mayor?', 'The leader of a city', 'A farmer', 'A singer', 'A pilot'],
    ['What is a parliament?', 'A group that makes laws', 'A sports team', 'A music band', 'A school'],
    ['What country has the most people?', 'India', 'USA', 'Brazil', 'Russia'],
    ['What is a campaign?', 'Working to get elected', 'A camping trip', 'A card game', 'A painting'],
    ['What is a veto?', 'When a leader rejects a law', 'A dance move', 'A recipe', 'A pet'],
    ['What is a summit?', 'A meeting of leaders', 'A mountain peak', 'A dessert', 'A toy'],
    ['What is an embassy?', 'An office in a foreign country', 'A hotel', 'A restaurant', 'A school'],
    ['What does independence mean?', 'Being free and self-governing', 'Being very tall', 'Being fast', 'Being loud'],
    ['What is a territory?', 'Land belonging to a country', 'A type of game', 'A school subject', 'A pet'],
    ['What is a civil right?', 'A right of citizens', 'A school rule', 'A sport', 'A recipe'],
    ['What country is famous for the Eiffel Tower?', 'France', 'Germany', 'Italy', 'Spain'],
    ['What is a symbol?', 'Something that stands for an idea', 'A type of food', 'A sport', 'A dance'],
    ['What is a compromise?', 'Both sides give a little', 'A type of meal', 'A game', 'A car'],
    ['What are the branches of US government?', 'Executive, legislative, judicial', 'Red, blue, green', 'Land, sea, air', 'Left, right, center'],
    ['What is an ally?', 'A friendly partner country', 'An enemy', 'A stranger', 'A neighbor'],
    ['What is a bill in government?', 'A proposed law', 'A restaurant check', 'A dollar bill', 'A type of bird'],
  ],
  3: [
    ['What type of government does the UK have?', 'Constitutional monarchy', 'Dictatorship', 'Theocracy', 'Anarchy'],
    ['What is the European Union?', 'A union of European countries', 'A sports league', 'A music festival', 'A school system'],
    ['How many members does the UN Security Council have?', '15', '10', '20', '50'],
    ['What document starts with We the People?', 'US Constitution', 'Declaration of Independence', 'Bill of Rights', 'Magna Carta'],
    ['What is a federal system?', 'Power shared by national and state', 'One ruler has all power', 'No government at all', 'Only cities have power'],
    ['Who is the head of state in the UK?', 'The King or Queen', 'The President', 'The Governor', 'The Mayor'],
    ['What is NATO?', 'A military alliance', 'A trade deal', 'A sports league', 'A charity'],
    ['What is the capital of Germany?', 'Berlin', 'Munich', 'Hamburg', 'Vienna'],
    ['What is a coup?', 'An illegal overthrow of government', 'A type of car', 'A dessert', 'A sport'],
    ['What is a referendum?', 'A public vote on an issue', 'A type of court', 'A school exam', 'A festival'],
    ['How many states does the US have?', '50', '48', '52', '45'],
    ['What is the World Health Organization?', 'A UN health agency', 'A hospital chain', 'A fitness brand', 'A food company'],
    ['What is capitalism?', 'A free market economy', 'Government owns everything', 'No trade at all', 'Only farming'],
    ['What is socialism?', 'Government controls key industries', 'No government', 'Only private business', 'Ruled by a king'],
    ['What is an amendment?', 'A change to a constitution', 'A type of medicine', 'A dessert', 'A holiday'],
    ['What is the capital of Russia?', 'Moscow', 'St. Petersburg', 'Kiev', 'Warsaw'],
    ['What is a tariff?', 'A tax on imported goods', 'A type of ship', 'A holiday', 'A city'],
    ['What is a ceasefire?', 'An agreement to stop fighting', 'A type of fire', 'A festival', 'A weapon'],
    ['What is the Geneva Convention about?', 'Rules of war', 'Trade agreements', 'Space travel', 'Olympics'],
    ['What are midterm elections?', 'Elections between presidential ones', 'School tests', 'Sports games', 'Award shows'],
    ['What is the Bill of Rights?', 'First 10 amendments to the US Constitution', 'A tax form', 'A history book', 'A treaty'],
    ['What does the Secretary of State do?', 'Handles foreign affairs', 'Manages schools', 'Runs hospitals', 'Builds roads'],
    ['What is communism?', 'State owns all property', 'Everyone is a farmer', 'No laws exist', 'Only one city exists'],
    ['What is the capital of Australia?', 'Canberra', 'Sydney', 'Melbourne', 'Brisbane'],
    ['What is an executive order?', 'A directive from the president', 'A restaurant menu', 'A shopping list', 'A report card'],
    ['What is the World Bank?', 'A financial institution for development', 'A regular bank', 'A piggy bank', 'A video game'],
    ['What is a sanction?', 'A penalty against a country', 'A reward', 'A holiday', 'A type of food'],
    ['What is a coalition?', 'An alliance of groups', 'A type of coal', 'A sport', 'A building'],
    ['What country has the longest wall?', 'China', 'India', 'Russia', 'Mexico'],
    ['What is the ICC?', 'International Criminal Court', 'International Car Company', 'Internet Chat Center', 'Indian Cooking Club'],
    ['What is a filibuster?', 'A long speech to delay a vote', 'A type of steak', 'A card game', 'A sport'],
    ['What is foreign aid?', 'Help given to other countries', 'A type of bandage', 'A school subject', 'A toy'],
    ['What is a cabinet in government?', 'Top advisors to a leader', 'A piece of furniture', 'A type of car', 'A game'],
    ['What is the capital of Brazil?', 'Brasilia', 'Rio de Janeiro', 'Sao Paulo', 'Salvador'],
    ['What is a primary election?', 'Voting for party candidates', 'First day of school', 'A warm-up game', 'A morning class'],
    ['What is a political asylum?', 'Protection in another country', 'A hospital', 'A school', 'A prison'],
    ['What is the Electoral College?', 'System for electing US president', 'A university', 'A high school', 'A voting app'],
    ['What is a trade agreement?', 'A deal between countries on trade', 'A school project', 'A sports deal', 'A recipe swap'],
    ['What is the capital of India?', 'New Delhi', 'Mumbai', 'Kolkata', 'Chennai'],
    ['What does GDP stand for?', 'Gross Domestic Product', 'Great Daily Plan', 'General Data Program', 'Grand Design Project'],
    ['What is a lobbyist?', 'Someone who tries to influence laws', 'A hotel worker', 'A tennis player', 'A librarian'],
    ['What is the Red Cross?', 'A humanitarian organization', 'A hospital', 'A church', 'A school'],
    ['What is martial law?', 'Military controls civilian life', 'A type of sport', 'A school rule', 'A dance style'],
    ['What is a superpower?', 'A very influential nation', 'A comic book hero', 'A type of energy', 'A battery'],
    ['What is a peace treaty?', 'An agreement to end a war', 'A school project', 'A business deal', 'A sports award'],
    ['What is a Congress?', 'A legislative body in the US', 'A type of dance', 'A restaurant', 'A game'],
    ['What is the capital of South Korea?', 'Seoul', 'Tokyo', 'Beijing', 'Taipei'],
    ['What is a summit meeting?', 'A meeting of top leaders', 'A hiking trip', 'A cooking class', 'A school event'],
    ['What is the G7?', 'Group of 7 wealthy nations', 'A music band', 'A racing team', 'A TV channel'],
    ['What is a veto power?', 'The right to reject a decision', 'A superpower', 'A type of vote', 'A legal term for yes'],
  ],
  4: [
    ['What is the purpose of the UN General Assembly?', 'Discuss global issues', 'Play sports', 'Trade goods', 'Make movies'],
    ['What is an oligarchy?', 'Rule by a small group', 'Rule by one person', 'Rule by everyone', 'No rulers at all'],
    ['What is the capital of Egypt?', 'Cairo', 'Alexandria', 'Luxor', 'Giza'],
    ['What is a trade embargo?', 'A ban on trade with a country', 'A new shipping route', 'A trade fair', 'A tax reduction'],
    ['What is the Supreme Court?', 'Highest court in the US', 'A sports arena', 'A university', 'A TV show'],
    ['What is the ASEAN?', 'A Southeast Asian group of nations', 'A European political and economic union', 'A North Atlantic military alliance', 'A group of Arab nations'],
    ['What is gerrymandering?', 'Redrawing voting districts unfairly', 'A card game', 'A cooking style', 'A dance form'],
    ['How many justices sit on the US Supreme Court?', '9', '7', '12', '5'],
    ['What is a constitutional amendment?', 'A formal change to a constitution', 'A school award', 'A building plan', 'A holiday'],
    ['What is the African Union?', 'A union of African nations', 'A music festival', 'A sports event', 'A trade brand'],
    ['What is a theocracy?', 'Government based on religion', 'Government by scientists', 'Government by athletes', 'No government'],
    ['What is the Commonwealth of Nations?', 'Former British Empire members', 'A business', 'A sports team', 'A school network'],
    ['What is a diplomatic immunity?', 'Legal protection for diplomats', 'A vaccine', 'A shield', 'A firewall'],
    ['What is the capital of Mexico?', 'Mexico City', 'Cancun', 'Guadalajara', 'Monterrey'],
    ['What is the Arab League?', 'A group of Arab nations', 'A soccer league', 'A music band', 'A TV network'],
    ['What is a bipartisan agreement?', 'Both parties agree', 'One party decides', 'No parties agree', 'Judges decide'],
    ['What is the capital of Canada?', 'Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
    ['What is the IMF?', 'International Monetary Fund', 'Internet Media Forum', 'Indian Math Foundation', 'Irish Music Fest'],
    ['What is a republic versus a democracy?', 'Elected representatives vs direct vote', 'Same thing', 'Monarchy vs anarchy', 'Dictatorship vs monarchy'],
    ['What is the capital of Turkey?', 'Ankara', 'Istanbul', 'Izmir', 'Antalya'],
    ['What is the Kyoto Protocol about?', 'Reducing greenhouse gases', 'Trade agreements', 'Military alliances', 'Space exploration'],
    ['What does UNESCO protect?', 'Cultural and natural heritage', 'Borders', 'Trade routes', 'Currencies'],
    ['What is a non-aligned nation?', 'Not allied with major powers', 'A landlocked country', 'An island nation', 'A very large country'],
    ['What is a federal republic?', 'A union of states under one government', 'A single city state', 'A kingdom', 'An empire'],
    ['What is a totalitarian regime?', 'Government controls everything', 'People vote on all issues', 'No laws exist', 'Everyone leads equally'],
    ['What is propaganda?', 'Biased information to sway opinion', 'A news report', 'A textbook', 'A poem'],
    ['What is the Paris Agreement?', 'A climate change accord', 'A peace treaty', 'A trade deal', 'A sports pact'],
    ['What is a failed state?', 'A country that cannot function', 'A bankrupt business', 'A lost game', 'A broken machine'],
    ['What is a peacekeeping force?', 'Troops maintaining peace', 'An army at war', 'A police patrol', 'A marching band'],
    ['What is the capital of Argentina?', 'Buenos Aires', 'Lima', 'Santiago', 'Bogota'],
    ['What is apartheid?', 'Racial segregation in South Africa', 'A type of government', 'A music style', 'A sport'],
    ['What is a humanitarian crisis?', 'A disaster threatening many lives', 'A school event', 'A sports injury', 'A cooking failure'],
    ['What is the Hague?', 'A city for international courts', 'A beach', 'A mountain', 'A river'],
    ['What is a special envoy?', 'A diplomatic representative', 'A spy', 'A soldier', 'A trader'],
    ['What is the capital of Nigeria?', 'Abuja', 'Lagos', 'Accra', 'Nairobi'],
    ['What is a puppet state?', 'A country controlled by another', 'A toy store', 'A theater', 'A theme park'],
    ['What is separatism?', 'A movement to break away', 'A cooking method', 'A math concept', 'A music style'],
    ['What is a diplomatic crisis?', 'A serious dispute between nations', 'A math problem', 'A cooking error', 'A school test'],
    ['What is the WTO?', 'World Trade Organization', 'World Tennis Open', 'Western Travel Office', 'World Tech Order'],
    ['What is a buffer state?', 'A country between rival powers', 'A computer term', 'A sports position', 'A cooking tool'],
    ['What is the capital of Saudi Arabia?', 'Riyadh', 'Jeddah', 'Mecca', 'Dubai'],
    ['What is an annexation?', 'Taking over another territory', 'A math problem', 'A cooking technique', 'A dance style'],
    ['What is a bilateral agreement?', 'A deal between two countries', 'A one-sided deal', 'A group deal', 'No deal at all'],
    ['What is an armistice?', 'A truce to stop fighting', 'A weapon', 'A ship', 'An army base'],
    ['What is the capital of Kenya?', 'Nairobi', 'Lagos', 'Kampala', 'Addis Ababa'],
    ['What is a war crime?', 'A violation of war rules', 'A board game', 'A TV show', 'A sports foul'],
    ['What is a coalition government?', 'Multiple parties share power', 'One party rules alone', 'No parties exist', 'Military rules'],
    ['What is the Magna Carta?', 'A charter of rights from 1215', 'A ship', 'A type of map', 'A food recipe'],
    ['What is a no-fly zone?', 'Airspace where planes are banned', 'A park rule', 'An airport', 'A bird sanctuary'],
    ['What is the capital of South Africa?', 'Pretoria', 'Cape Town', 'Johannesburg', 'Durban'],
  ],
  5: [
    ['What is the difference between NATO and the UN?', 'NATO is military; UN is diplomatic', 'They are the same', 'NATO is for trade', 'UN is a sports body'],
    ['What is a unilateral action?', 'Done by one country alone', 'Done by two countries', 'Done by all countries', 'Done by no one'],
    ['What is the Treaty of Versailles?', 'Ended World War I', 'Started World War II', 'Founded the EU', 'Created NATO'],
    ['What is the Non-Proliferation Treaty?', 'Limits spread of nuclear weapons', 'Bans all trade', 'Promotes space travel', 'Limits immigration'],
    ['What is geopolitics?', 'Politics influenced by geography', 'Geology and politics combined', 'A board game', 'A type of map'],
    ['What is the Marshall Plan?', 'US aid to rebuild Europe after WWII', 'A military invasion', 'A trade embargo', 'A space program'],
    ['What is the Cold War?', 'US-Soviet rivalry without direct war', 'A winter battle', 'An ice hockey league', 'A frozen food company'],
    ['What is a proxy war?', 'A war fought through third parties', 'A board game war', 'A simulated battle', 'A cyber attack'],
    ['What is the European Parliament?', 'Elected EU legislative body', 'A UK court', 'A French school', 'A German bank'],
    ['What is soft power?', 'Influence through culture and diplomacy', 'Military strength', 'Economic pressure', 'Physical force'],
    ['What is the Bretton Woods system?', 'Post-WWII financial framework', 'A forest reserve', 'A timber company', 'A nature park'],
    ['What is the BRICS group?', 'Brazil, Russia, India, China, S. Africa', 'A building material', 'A toy brand', 'A video game'],
    ['What is extraterritoriality?', 'Exemption from local law', 'Living outside Earth', 'A space program', 'An astronomy term'],
    ['What is the Iron Curtain?', 'Cold War divide in Europe', 'A theater prop', 'A metal fabric', 'A security system'],
    ['What is a multilateral agreement?', 'A deal among many countries', 'A two-country deal', 'No deal', 'A one-country rule'],
    ['What is the Arab Spring?', 'Pro-democracy protests in Arab world', 'A season', 'A water source', 'A music festival'],
    ['What is the EU single market?', 'Free trade zone among EU members', 'A grocery store', 'A stock market', 'A shopping mall'],
    ['What is a territorial dispute?', 'Countries disagree over land', 'A sports argument', 'A school debate', 'A family feud'],
    ['What is the International Court of Justice?', 'UN court for state disputes', 'A TV show', 'A game', 'A university'],
    ['What is political polarization?', 'Growing divide between parties', 'A science experiment', 'A magnet concept', 'A cooking method'],
    ['What is a trade deficit?', 'Importing more than exporting', 'Exporting more', 'Balanced trade', 'No trade'],
    ['What is a diplomatic channel?', 'A way nations communicate', 'A TV channel', 'A river', 'A road'],
    ['What is the Truman Doctrine?', 'US policy to contain communism', 'A medical treatment', 'A school curriculum', 'A cooking style'],
    ['What is the Monroe Doctrine?', 'US opposed European colonialism in Americas', 'A cooking recipe', 'A sports rule', 'A music theory'],
    ['What is the right of self-determination?', 'Peoples choose their own government', 'Right to travel freely', 'Right to free food', 'Right to a car'],
    ['What is an international embargo?', 'A global ban on trade with a nation', 'A shipping company', 'A port', 'A customs office'],
    ['What is a diplomatic envoy?', 'A messenger between governments', 'A mail carrier', 'A soldier', 'A tourist'],
    ['What are economic sanctions?', 'Penalties to pressure a nation', 'Tax breaks', 'Free trade deals', 'Business loans'],
    ['What is the IAEA?', 'International Atomic Energy Agency', 'An airline', 'A bank', 'A school'],
    ['What is the Geneva Protocol?', 'Rules banning chemical weapons', 'A peace treaty', 'A cooking method', 'A sports rule'],
    ['What is political asylum?', 'Protection from persecution abroad', 'A hospital', 'A school', 'A government office'],
    ['What is a demilitarized zone?', 'Area where military is banned', 'A war zone', 'A military base', 'An airport'],
    ['What is a puppet government?', 'A government controlled by outsiders', 'A toy store', 'A theater group', 'A children show'],
    ['What is imperialism?', 'Extending power over other nations', 'A board game', 'A math concept', 'A cooking style'],
    ['What is colonialism?', 'Controlling another territory', 'A farming method', 'A school system', 'A music style'],
    ['What is the Schengen Area?', 'Passport-free travel zone in Europe', 'A German city', 'A mountain range', 'A river basin'],
    ['What is a humanitarian intervention?', 'Action to protect civilians abroad', 'A hospital visit', 'A school project', 'A cooking show'],
    ['What is the camp David Accord?', 'Peace deal between Egypt and Israel', 'A summer camp', 'A music festival', 'A military base'],
    ['What is realpolitik?', 'Practical politics over ideology', 'A video game', 'A school subject', 'A cooking term'],
    ['What is the OPEC?', 'Organization of Petroleum Exporting Countries', 'A tech company', 'A school network', 'A sports league'],
    ['What is a free trade agreement?', 'No tariffs between member nations', 'A charity event', 'A tax increase', 'A war pact'],
    ['What is the balance of power?', 'No one nation dominates', 'Equal population sizes', 'Same currency', 'Identical laws'],
    ['What is the League of Nations?', 'Predecessor of the United Nations', 'A sports league', 'A TV show', 'A musical group'],
    ['What is deterrence in politics?', 'Preventing attack through strength', 'A cleaning product', 'A fence', 'A type of law'],
    ['What is a war of attrition?', 'Wearing down the enemy over time', 'A quick battle', 'A board game', 'A school competition'],
    ['What is the Suez Crisis?', 'A 1956 conflict over the Suez Canal', 'A flood', 'A drought', 'A hurricane'],
    ['What is a hegemon?', 'A dominant state or power', 'A shape', 'A tool', 'A mineral'],
    ['What is the Yalta Conference?', 'WWII meeting of Allied leaders', 'A peace treaty', 'A science fair', 'A music show'],
    ['What is a nation-state?', 'A country with shared identity', 'Any large city', 'A kingdom only', 'A continent'],
    ['What is a unipolar world?', 'One dominant superpower', 'Two superpowers', 'Many equal powers', 'No powers at all'],
  ],
  6: [
    ['What is the Westphalian system?', 'State sovereignty principle from 1648', 'A German school', 'A cooking technique', 'A sports league'],
    ['What is the Responsibility to Protect?', 'Duty to prevent mass atrocities', 'A fire safety rule', 'A copyright law', 'A traffic regulation'],
    ['What is Mutually Assured Destruction?', 'Nuclear deterrence strategy', 'A game show', 'A demolition company', 'A military rank'],
    ['What is the Sykes-Picot Agreement?', 'Secret WWI Middle East partition', 'A trade deal', 'A peace prize', 'A shipping route'],
    ['What is a failed state index?', 'Ranks countries by instability', 'A stock market tool', 'A school report', 'A health chart'],
    ['What is the UNHCR?', 'UN Refugee Agency', 'A hospital chain', 'A music label', 'An airline'],
    ['What is balkanization?', 'Splitting a region into hostile parts', 'A cooking method', 'A dance style', 'A music genre'],
    ['What is the Helsinki Accords?', 'Cold War agreement on borders', 'A music festival', 'A school pact', 'A sports treaty'],
    ['What is the Shanghai Cooperation Organisation?', 'Eurasian political and security group', 'A trade company', 'A sports league', 'A tech firm'],
    ['What is the status of forces agreement?', 'Rules for foreign troops on local soil', 'A gym membership', 'A fitness plan', 'A diet chart'],
    ['What is the Balfour Declaration?', 'British support for Jewish homeland', 'A cooking recipe', 'A music score', 'A building plan'],
    ['What is a kleptocracy?', 'Government by corrupt rulers', 'Rule by scientists', 'Rule by athletes', 'Rule by artists'],
    ['What is the Dayton Agreement?', 'Ended the Bosnian War', 'A car deal', 'A movie script', 'A music award'],
    ['What is the Nuclear Test Ban Treaty?', 'Prohibits nuclear weapons testing', 'Bans nuclear energy', 'Limits space travel', 'Restricts mining'],
    ['What is diplomatic recognition?', 'Officially accepting a government', 'A greeting card', 'An award ceremony', 'A school diploma'],
    ['What is the concept of jus ad bellum?', 'Right to go to war', 'A type of juice', 'A legal contract', 'A school course'],
    ['What is the petrodollar?', 'Oil traded in US dollars', 'A type of coin', 'A piggy bank', 'A gas station'],
    ['What is the ASEAN Regional Forum?', 'Asia-Pacific security dialogue', 'A TV channel', 'A cooking show', 'A sports tournament'],
    ['What is a transitional government?', 'Temporary government after upheaval', 'A moving company', 'A school trip', 'A travel agency'],
    ['What is the World Economic Forum?', 'Global leaders discuss economic issues', 'A stock exchange', 'A bank', 'A casino'],
    ['What is the African Continental Free Trade Area?', 'African trade zone', 'A nature reserve', 'A school network', 'A sports league'],
    ['What is a truth and reconciliation commission?', 'Body to address past wrongs', 'A church group', 'A school committee', 'A sports board'],
    ['What is the Belt and Road Initiative?', 'Chinas global infrastructure plan', 'A fashion brand', 'A fitness program', 'A cooking show'],
    ['What is the Quad alliance?', 'US, India, Japan, Australia group', 'A math term', 'A card game', 'A music quartet'],
    ['What is AUKUS?', 'Australia-UK-US security pact', 'A shoe brand', 'A programming language', 'A board game'],
    ['What is lawfare?', 'Using legal systems as a weapon', 'A type of war', 'A game', 'A school debate'],
    ['What is the right to return?', 'Right of refugees to go home', 'A library policy', 'A store policy', 'A school rule'],
    ['What is a color revolution?', 'Peaceful regime change movement', 'A painting class', 'A fashion trend', 'A music genre'],
    ['What is the Five Eyes alliance?', 'Intelligence sharing: US, UK, CA, AU, NZ', 'An eye doctor chain', 'A camera brand', 'A TV network'],
    ['What is a frozen conflict?', 'Unresolved but halted fighting', 'A winter sport', 'An ice cream brand', 'A science experiment'],
    ['What is the Rome Statute?', 'Treaty creating the ICC', 'An Italian recipe', 'A music piece', 'A travel guide'],
    ['What is shuttle diplomacy?', 'Mediator travels between parties', 'A space program', 'A bus service', 'A basketball move'],
    ['What is a casus belli?', 'Justification for war', 'A Latin dessert', 'A type of dance', 'A school grade'],
    ['What is the Good Friday Agreement?', 'Peace deal in Northern Ireland', 'A holiday recipe', 'A movie deal', 'A church event'],
    ['What is a truth commission?', 'Investigates human rights abuses', 'A lie detector', 'A school exam', 'A quiz show'],
    ['What is the CTBT?', 'Comprehensive Nuclear-Test-Ban Treaty', 'A computer language', 'A TV station', 'A bank code'],
    ['What is the Golan Heights dispute?', 'Land disputed by Israel and Syria', 'A ski resort', 'A mountain race', 'A hiking trail'],
    ['What is coercive diplomacy?', 'Using threats to achieve goals', 'Friendly negotiation', 'A cooking style', 'A dance form'],
    ['What is a bloc in world politics?', 'A group of allied nations', 'A building block', 'A city block', 'A wooden toy'],
    ['What is the principle of non-intervention?', 'Not interfering in other states', 'A medical rule', 'A sports rule', 'A cooking tip'],
    ['What is a rogue state?', 'A state that defies international norms', 'A pirate ship', 'A sports team', 'A game character'],
    ['What is the Nuremberg Trials?', 'WWII war crimes tribunal', 'A science fair', 'A cooking contest', 'A spelling bee'],
    ['What is the domino theory?', 'One nation falling to communism triggers others', 'A board game', 'A pizza brand', 'A math theorem'],
    ['What is the JCPOA?', 'Iran nuclear deal', 'A car brand', 'A school test', 'A phone model'],
    ['What is an exiled government?', 'Government operating from abroad', 'A holiday trip', 'A school exchange', 'A sports camp'],
    ['What is a mandate system?', 'League of Nations territory management', 'A homework rule', 'A voting method', 'A sports draft'],
    ['What is the Potsdam Conference?', 'Post-WWII Allied meeting in Germany', 'A music festival', 'A cooking show', 'A car race'],
    ['What is a sphere of influence?', 'Area under a powers sway', 'A geometry term', 'A type of ball', 'A weather pattern'],
    ['What is the doctrine of preemption?', 'Striking before being attacked', 'A school rule', 'A cooking method', 'A traffic law'],
    ['What is the Concert of Europe?', 'Post-Napoleonic balance of power', 'A music festival', 'An orchestra', 'A dance show'],
  ],
};

export { fintech } from './fintech';
