// [clue, answer, wrong1, wrong2, wrong3]
export type Fact = [string, string, string, string, string];

export const worldPolitics: Record<number, Fact[]> = {
  1: [
    ['Who leads a country?', 'President or Prime Minister', 'Teacher', 'Doctor', 'Chef'],
    ['What is a country?', 'A land with its own government', 'A big house', 'A playground', 'A store'],
    ['What color is the American flag?', 'Red, white, and blue', 'Green and yellow', 'Orange and purple', 'Pink and brown'],
    ['What do people do on Election Day?', 'Vote', 'Sleep', 'Swim', 'Cook'],
    ['What is a flag?', 'A symbol of a country', 'A type of food', 'A kind of animal', 'A color'],
    ['What is a law?', 'A rule everyone must follow', 'A type of game', 'A song', 'A book'],
    ['Where does a president live in the USA?', 'The White House', 'A castle', 'A farm', 'A school'],
    ['What is a capital city?', 'The main city of a country', 'The biggest park', 'A shopping mall', 'A zoo'],
    ['What shape is a stop sign?', 'Octagon', 'Circle', 'Square', 'Triangle'],
    ['What country has a maple leaf on its flag?', 'Canada', 'Mexico', 'Brazil', 'France'],
    ['Who makes laws in the United States?', 'Congress', 'Firefighters', 'Teachers', 'Doctors'],
    ['What do we call the leader of a city?', 'Mayor', 'King', 'Captain', 'Principal'],
    ['What is the capital of the United States?', 'Washington, D.C.', 'New York', 'Los Angeles', 'Chicago'],
    ['What animal is on the Mexican flag?', 'Eagle', 'Lion', 'Bear', 'Tiger'],
    ['How many stars are on the US flag?', '50', '13', '25', '100'],
    ['What is a king or queen?', 'A royal leader', 'A type of pet', 'A sport', 'A food'],
    ['What do police officers help with?', 'Keeping people safe', 'Cooking food', 'Building houses', 'Flying planes'],
    ['What is a community?', 'A group of people living together', 'A kind of toy', 'A tree', 'A game'],
    ['What do firefighters do?', 'Put out fires', 'Build roads', 'Teach math', 'Fly planes'],
    ['What continent is the USA on?', 'North America', 'Europe', 'Asia', 'Africa'],
    ['What is a neighbor?', 'Someone who lives near you', 'A type of fish', 'A planet', 'A car'],
    ['What is a citizen?', 'A member of a country', 'A kind of bird', 'A sport', 'A building'],
    ['What does a judge do?', 'Makes decisions about laws', 'Drives a bus', 'Fixes cars', 'Paints houses'],
    ['What is peace?', 'No fighting or war', 'A type of fruit', 'A dance', 'A toy'],
    ['What country is shaped like a boot?', 'Italy', 'Japan', 'India', 'Brazil'],
    ['What do we celebrate on the Fourth of July?', 'Independence Day', 'Halloween', 'Christmas', 'Easter'],
    ['What is a passport?', 'A travel document', 'A toy', 'A snack', 'A game'],
    ['What is a government?', 'A group that leads a country', 'A school subject', 'A type of weather', 'A sport'],
    ['Who helps sick people in a community?', 'Doctors and nurses', 'Pilots', 'Farmers', 'Painters'],
    ['What is a map?', 'A picture of a place', 'A type of hat', 'A musical instrument', 'A food'],
    ['What is the biggest country in the world?', 'Russia', 'Canada', 'China', 'Brazil'],
    ['What is a state?', 'A part of a country', 'A color', 'A planet', 'A type of car'],
    ['How many stripes are on the US flag?', '13', '50', '7', '20'],
    ['What color is the Canadian flag?', 'Red and white', 'Blue and green', 'Yellow and black', 'Purple and orange'],
    ['What is a volunteer?', 'Someone who helps for free', 'A type of animal', 'A building', 'A sport'],
    ['What is a border?', 'A line between countries', 'A type of flower', 'A dance move', 'A color'],
    ['What do mail carriers do?', 'Deliver letters', 'Build houses', 'Drive taxis', 'Cook food'],
    ['What continent is Japan on?', 'Asia', 'Europe', 'Africa', 'South America'],
    ['What is a parade?', 'People marching together', 'A type of soup', 'A school test', 'A kind of tree'],
    ['What holiday honors workers?', 'Labor Day', 'Valentines Day', 'New Years Day', 'Earth Day'],
    ['What language do people speak in France?', 'French', 'Spanish', 'German', 'Italian'],
    ['What is an island?', 'Land surrounded by water', 'A tall building', 'A mountain', 'A type of cloud'],
    ['What is a globe?', 'A round model of Earth', 'A type of lamp', 'A food', 'A hat'],
    ['What language do people speak in Mexico?', 'Spanish', 'French', 'English', 'Japanese'],
    ['What is a team?', 'People working together', 'A kind of plant', 'A type of rock', 'A shape'],
    ['Who was the first US president?', 'George Washington', 'Abraham Lincoln', 'Thomas Jefferson', 'John Adams'],
    ['What is the name of Englands royal family?', 'The Royal Family', 'The First Family', 'The Super Family', 'The Great Family'],
    ['What is a library?', 'A place to borrow books', 'A restaurant', 'A gym', 'A hospital'],
    ['What is a uniform?', 'Special clothes for a job', 'A type of dance', 'A food', 'A game'],
    ['What is a continent?', 'A large area of land', 'A type of ocean', 'A small island', 'A city'],
  ],
  2: [
    ['What is a democracy?', 'People choose their leaders', 'One person rules forever', 'No one is in charge', 'Animals pick leaders'],
    ['What is an election?', 'When people vote for leaders', 'A type of party', 'A school subject', 'A holiday'],
    ['What is the United Nations?', 'A group of countries working together', 'A sports league', 'A school club', 'A band'],
    ['How many continents are there?', '7', '5', '10', '3'],
    ['What is a president?', 'The leader of a country', 'A type of teacher', 'A baker', 'A pilot'],
    ['What does a governor lead?', 'A state', 'A school', 'A team', 'A club'],
    ['What is a ballot?', 'A paper used to vote', 'A type of ball', 'A hat', 'A toy'],
    ['What is the capital of England?', 'London', 'Paris', 'Dublin', 'Berlin'],
    ['What do ambassadors do?', 'Represent their country abroad', 'Cook food', 'Drive buses', 'Build bridges'],
    ['What is a monarchy?', 'A country led by a king or queen', 'A type of garden', 'A card game', 'A sport'],
    ['What is a national anthem?', 'A countrys official song', 'A lullaby', 'A pop song', 'A school chant'],
    ['What is a constitution?', 'The main rules of a country', 'A math test', 'A recipe book', 'A map'],
    ['What is a tax?', 'Money paid to the government', 'A type of candy', 'A game', 'A pet'],
    ['What is freedom of speech?', 'The right to share your ideas', 'A school rule', 'A type of singing', 'A dance'],
    ['What is a republic?', 'People elect representatives', 'A kingdom', 'A store', 'A park'],
    ['What is a treaty?', 'An agreement between countries', 'A school test', 'A type of tree', 'A recipe'],
    ['What country has a dragon on its flag?', 'Wales', 'Ireland', 'France', 'Spain'],
    ['What is a protest?', 'People showing they disagree', 'A party', 'A game show', 'A concert'],
    ['What is a senator?', 'An elected lawmaker', 'A teacher', 'A doctor', 'A scientist'],
    ['What ocean is between the USA and Europe?', 'Atlantic Ocean', 'Pacific Ocean', 'Indian Ocean', 'Arctic Ocean'],
    ['What is immigration?', 'Moving to a new country', 'Going to school', 'Shopping', 'Cooking'],
    ['What is the capital of France?', 'Paris', 'London', 'Rome', 'Madrid'],
    ['What is a dictator?', 'A leader with total control', 'A teacher', 'A coach', 'A librarian'],
    ['What is a refugee?', 'Someone fleeing danger', 'A tourist', 'A pilot', 'A farmer'],
    ['What is a political party?', 'A group with shared beliefs', 'A birthday party', 'A dance', 'A game'],
    ['What is a courthouse?', 'Where legal cases are heard', 'A bakery', 'A library', 'A gym'],
    ['What is the capital of Japan?', 'Tokyo', 'Beijing', 'Seoul', 'Bangkok'],
    ['What are human rights?', 'Freedoms everyone deserves', 'School supplies', 'Sports rules', 'Recipes'],
    ['What is a prime minister?', 'The head of a government', 'A math teacher', 'A chef', 'A pilot'],
    ['What is an army?', 'Soldiers who protect a country', 'A team of cooks', 'A group of singers', 'A band'],
    ['What is a colony?', 'Land controlled by another country', 'A group of ants', 'A school club', 'A garden'],
    ['What is the capital of China?', 'Beijing', 'Shanghai', 'Tokyo', 'Seoul'],
    ['What does the Statue of Liberty stand for?', 'Freedom', 'Cooking', 'Swimming', 'Shopping'],
    ['What is a debate?', 'A formal argument about ideas', 'A food fight', 'A sport', 'A joke'],
    ['What is a mayor?', 'The leader of a city', 'A farmer', 'A singer', 'A pilot'],
    ['What is a parliament?', 'A group that makes laws', 'A sports team', 'A music band', 'A school'],
    ['What country has the most people?', 'India', 'USA', 'Brazil', 'Russia'],
    ['What is a campaign?', 'Working to get elected', 'A camping trip', 'A card game', 'A painting'],
    ['What is a veto?', 'When a leader rejects a law', 'A dance move', 'A recipe', 'A pet'],
    ['What is a summit?', 'A meeting of leaders', 'A mountain peak', 'A dessert', 'A toy'],
    ['What is an embassy?', 'An office in a foreign country', 'A hotel', 'A restaurant', 'A school'],
    ['What does independence mean?', 'Being free and self-governing', 'Being very tall', 'Being fast', 'Being loud'],
    ['What is a territory?', 'Land belonging to a country', 'A type of game', 'A school subject', 'A pet'],
    ['What is a civil right?', 'A right of citizens', 'A school rule', 'A sport', 'A recipe'],
    ['What country is famous for the Eiffel Tower?', 'France', 'Germany', 'Italy', 'Spain'],
    ['What is a symbol?', 'Something that stands for an idea', 'A type of food', 'A sport', 'A dance'],
    ['What is a compromise?', 'Both sides give a little', 'A type of meal', 'A game', 'A car'],
    ['What are the branches of US government?', 'Executive, legislative, judicial', 'Red, blue, green', 'Land, sea, air', 'Left, right, center'],
    ['What is an ally?', 'A friendly partner country', 'An enemy', 'A stranger', 'A neighbor'],
    ['What is a bill in government?', 'A proposed law', 'A restaurant check', 'A dollar bill', 'A type of bird'],
  ],
  3: [
    ['What type of government does the UK have?', 'Constitutional monarchy', 'Dictatorship', 'Theocracy', 'Anarchy'],
    ['What is the European Union?', 'A union of European countries', 'A sports league', 'A music festival', 'A school system'],
    ['How many members does the UN Security Council have?', '15', '10', '20', '50'],
    ['What document starts with We the People?', 'US Constitution', 'Declaration of Independence', 'Bill of Rights', 'Magna Carta'],
    ['What is a federal system?', 'Power shared by national and state', 'One ruler has all power', 'No government at all', 'Only cities have power'],
    ['Who is the head of state in the UK?', 'The King or Queen', 'The President', 'The Governor', 'The Mayor'],
    ['What is NATO?', 'A military alliance', 'A trade deal', 'A sports league', 'A charity'],
    ['What is the capital of Germany?', 'Berlin', 'Munich', 'Hamburg', 'Vienna'],
    ['What is a coup?', 'An illegal overthrow of government', 'A type of car', 'A dessert', 'A sport'],
    ['What is a referendum?', 'A public vote on an issue', 'A type of court', 'A school exam', 'A festival'],
    ['How many states does the US have?', '50', '48', '52', '45'],
    ['What is the World Health Organization?', 'A UN health agency', 'A hospital chain', 'A fitness brand', 'A food company'],
    ['What is capitalism?', 'A free market economy', 'Government owns everything', 'No trade at all', 'Only farming'],
    ['What is socialism?', 'Government controls key industries', 'No government', 'Only private business', 'Ruled by a king'],
    ['What is an amendment?', 'A change to a constitution', 'A type of medicine', 'A dessert', 'A holiday'],
    ['What is the capital of Russia?', 'Moscow', 'St. Petersburg', 'Kiev', 'Warsaw'],
    ['What is a tariff?', 'A tax on imported goods', 'A type of ship', 'A holiday', 'A city'],
    ['What is a ceasefire?', 'An agreement to stop fighting', 'A type of fire', 'A festival', 'A weapon'],
    ['What is the Geneva Convention about?', 'Rules of war', 'Trade agreements', 'Space travel', 'Olympics'],
    ['What are midterm elections?', 'Elections between presidential ones', 'School tests', 'Sports games', 'Award shows'],
    ['What is the Bill of Rights?', 'First 10 amendments to the US Constitution', 'A tax form', 'A history book', 'A treaty'],
    ['What does the Secretary of State do?', 'Handles foreign affairs', 'Manages schools', 'Runs hospitals', 'Builds roads'],
    ['What is communism?', 'State owns all property', 'Everyone is a farmer', 'No laws exist', 'Only one city exists'],
    ['What is the capital of Australia?', 'Canberra', 'Sydney', 'Melbourne', 'Brisbane'],
    ['What is an executive order?', 'A directive from the president', 'A restaurant menu', 'A shopping list', 'A report card'],
    ['What is the World Bank?', 'A financial institution for development', 'A regular bank', 'A piggy bank', 'A video game'],
    ['What is a sanction?', 'A penalty against a country', 'A reward', 'A holiday', 'A type of food'],
    ['What is a coalition?', 'An alliance of groups', 'A type of coal', 'A sport', 'A building'],
    ['What country has the longest wall?', 'China', 'India', 'Russia', 'Mexico'],
    ['What is the ICC?', 'International Criminal Court', 'International Car Company', 'Internet Chat Center', 'Indian Cooking Club'],
    ['What is a filibuster?', 'A long speech to delay a vote', 'A type of steak', 'A card game', 'A sport'],
    ['What is foreign aid?', 'Help given to other countries', 'A type of bandage', 'A school subject', 'A toy'],
    ['What is a cabinet in government?', 'Top advisors to a leader', 'A piece of furniture', 'A type of car', 'A game'],
    ['What is the capital of Brazil?', 'Brasilia', 'Rio de Janeiro', 'Sao Paulo', 'Salvador'],
    ['What is a primary election?', 'Voting for party candidates', 'First day of school', 'A warm-up game', 'A morning class'],
    ['What is a political asylum?', 'Protection in another country', 'A hospital', 'A school', 'A prison'],
    ['What is the Electoral College?', 'System for electing US president', 'A university', 'A high school', 'A voting app'],
    ['What is a trade agreement?', 'A deal between countries on trade', 'A school project', 'A sports deal', 'A recipe swap'],
    ['What is the capital of India?', 'New Delhi', 'Mumbai', 'Kolkata', 'Chennai'],
    ['What does GDP stand for?', 'Gross Domestic Product', 'Great Daily Plan', 'General Data Program', 'Grand Design Project'],
    ['What is a lobbyist?', 'Someone who tries to influence laws', 'A hotel worker', 'A tennis player', 'A librarian'],
    ['What is the Red Cross?', 'A humanitarian organization', 'A hospital', 'A church', 'A school'],
    ['What is martial law?', 'Military controls civilian life', 'A type of sport', 'A school rule', 'A dance style'],
    ['What is a superpower?', 'A very influential nation', 'A comic book hero', 'A type of energy', 'A battery'],
    ['What is a peace treaty?', 'An agreement to end a war', 'A school project', 'A business deal', 'A sports award'],
    ['What is a Congress?', 'A legislative body in the US', 'A type of dance', 'A restaurant', 'A game'],
    ['What is the capital of South Korea?', 'Seoul', 'Tokyo', 'Beijing', 'Taipei'],
    ['What is a summit meeting?', 'A meeting of top leaders', 'A hiking trip', 'A cooking class', 'A school event'],
    ['What is the G7?', 'Group of 7 wealthy nations', 'A music band', 'A racing team', 'A TV channel'],
    ['What is a veto power?', 'The right to reject a decision', 'A superpower', 'A type of vote', 'A legal term for yes'],
  ],
  4: [
    ['What is the purpose of the UN General Assembly?', 'Discuss global issues', 'Play sports', 'Trade goods', 'Make movies'],
    ['What is an oligarchy?', 'Rule by a small group', 'Rule by one person', 'Rule by everyone', 'No rulers at all'],
    ['What is the capital of Egypt?', 'Cairo', 'Alexandria', 'Luxor', 'Giza'],
    ['What is a trade embargo?', 'A ban on trade with a country', 'A new shipping route', 'A trade fair', 'A tax reduction'],
    ['What is the Supreme Court?', 'Highest court in the US', 'A sports arena', 'A university', 'A TV show'],
    ['What is the ASEAN?', 'A Southeast Asian group of nations', 'An airline', 'A sports league', 'A music award'],
    ['What is gerrymandering?', 'Redrawing voting districts unfairly', 'A card game', 'A cooking style', 'A dance form'],
    ['How many justices sit on the US Supreme Court?', '9', '7', '12', '5'],
    ['What is a constitutional amendment?', 'A formal change to a constitution', 'A school award', 'A building plan', 'A holiday'],
    ['What is the African Union?', 'A union of African nations', 'A music festival', 'A sports event', 'A trade brand'],
    ['What is a theocracy?', 'Government based on religion', 'Government by scientists', 'Government by athletes', 'No government'],
    ['What is the Commonwealth of Nations?', 'Former British Empire members', 'A business', 'A sports team', 'A school network'],
    ['What is a diplomatic immunity?', 'Legal protection for diplomats', 'A vaccine', 'A shield', 'A firewall'],
    ['What is the capital of Mexico?', 'Mexico City', 'Cancun', 'Guadalajara', 'Monterrey'],
    ['What is the Arab League?', 'A group of Arab nations', 'A soccer league', 'A music band', 'A TV network'],
    ['What is a bipartisan agreement?', 'Both parties agree', 'One party decides', 'No parties agree', 'Judges decide'],
    ['What is the capital of Canada?', 'Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
    ['What is the IMF?', 'International Monetary Fund', 'Internet Media Forum', 'Indian Math Foundation', 'Irish Music Fest'],
    ['What is a republic versus a democracy?', 'Elected representatives vs direct vote', 'Same thing', 'Monarchy vs anarchy', 'Dictatorship vs monarchy'],
    ['What is the capital of Turkey?', 'Ankara', 'Istanbul', 'Izmir', 'Antalya'],
    ['What is the Kyoto Protocol about?', 'Reducing greenhouse gases', 'Trade agreements', 'Military alliances', 'Space exploration'],
    ['What does UNESCO protect?', 'Cultural and natural heritage', 'Borders', 'Trade routes', 'Currencies'],
    ['What is a non-aligned nation?', 'Not allied with major powers', 'A landlocked country', 'An island nation', 'A very large country'],
    ['What is a federal republic?', 'A union of states under one government', 'A single city state', 'A kingdom', 'An empire'],
    ['What is a totalitarian regime?', 'Government controls everything', 'People vote on all issues', 'No laws exist', 'Everyone leads equally'],
    ['What is propaganda?', 'Biased information to sway opinion', 'A news report', 'A textbook', 'A poem'],
    ['What is the Paris Agreement?', 'A climate change accord', 'A peace treaty', 'A trade deal', 'A sports pact'],
    ['What is a failed state?', 'A country that cannot function', 'A bankrupt business', 'A lost game', 'A broken machine'],
    ['What is a peacekeeping force?', 'Troops maintaining peace', 'An army at war', 'A police patrol', 'A marching band'],
    ['What is the capital of Argentina?', 'Buenos Aires', 'Lima', 'Santiago', 'Bogota'],
    ['What is apartheid?', 'Racial segregation in South Africa', 'A type of government', 'A music style', 'A sport'],
    ['What is a humanitarian crisis?', 'A disaster threatening many lives', 'A school event', 'A sports injury', 'A cooking failure'],
    ['What is the Hague?', 'A city for international courts', 'A beach', 'A mountain', 'A river'],
    ['What is a special envoy?', 'A diplomatic representative', 'A spy', 'A soldier', 'A trader'],
    ['What is the capital of Nigeria?', 'Abuja', 'Lagos', 'Accra', 'Nairobi'],
    ['What is a puppet state?', 'A country controlled by another', 'A toy store', 'A theater', 'A theme park'],
    ['What is separatism?', 'A movement to break away', 'A cooking method', 'A math concept', 'A music style'],
    ['What is a diplomatic crisis?', 'A serious dispute between nations', 'A math problem', 'A cooking error', 'A school test'],
    ['What is the WTO?', 'World Trade Organization', 'World Tennis Open', 'Western Travel Office', 'World Tech Order'],
    ['What is a buffer state?', 'A country between rival powers', 'A computer term', 'A sports position', 'A cooking tool'],
    ['What is the capital of Saudi Arabia?', 'Riyadh', 'Jeddah', 'Mecca', 'Dubai'],
    ['What is an annexation?', 'Taking over another territory', 'A math problem', 'A cooking technique', 'A dance style'],
    ['What is a bilateral agreement?', 'A deal between two countries', 'A one-sided deal', 'A group deal', 'No deal at all'],
    ['What is an armistice?', 'A truce to stop fighting', 'A weapon', 'A ship', 'An army base'],
    ['What is the capital of Kenya?', 'Nairobi', 'Lagos', 'Kampala', 'Addis Ababa'],
    ['What is a war crime?', 'A violation of war rules', 'A board game', 'A TV show', 'A sports foul'],
    ['What is a coalition government?', 'Multiple parties share power', 'One party rules alone', 'No parties exist', 'Military rules'],
    ['What is the Magna Carta?', 'A charter of rights from 1215', 'A ship', 'A type of map', 'A food recipe'],
    ['What is a no-fly zone?', 'Airspace where planes are banned', 'A park rule', 'An airport', 'A bird sanctuary'],
    ['What is the capital of South Africa?', 'Pretoria', 'Cape Town', 'Johannesburg', 'Durban'],
  ],
  5: [
    ['What is the difference between NATO and the UN?', 'NATO is military; UN is diplomatic', 'They are the same', 'NATO is for trade', 'UN is a sports body'],
    ['What is a unilateral action?', 'Done by one country alone', 'Done by two countries', 'Done by all countries', 'Done by no one'],
    ['What is the Treaty of Versailles?', 'Ended World War I', 'Started World War II', 'Founded the EU', 'Created NATO'],
    ['What is the Non-Proliferation Treaty?', 'Limits spread of nuclear weapons', 'Bans all trade', 'Promotes space travel', 'Limits immigration'],
    ['What is geopolitics?', 'Politics influenced by geography', 'Geology and politics combined', 'A board game', 'A type of map'],
    ['What is the Marshall Plan?', 'US aid to rebuild Europe after WWII', 'A military invasion', 'A trade embargo', 'A space program'],
    ['What is the Cold War?', 'US-Soviet rivalry without direct war', 'A winter battle', 'An ice hockey league', 'A frozen food company'],
    ['What is a proxy war?', 'A war fought through third parties', 'A board game war', 'A simulated battle', 'A cyber attack'],
    ['What is the European Parliament?', 'Elected EU legislative body', 'A UK court', 'A French school', 'A German bank'],
    ['What is soft power?', 'Influence through culture and diplomacy', 'Military strength', 'Economic pressure', 'Physical force'],
    ['What is the Bretton Woods system?', 'Post-WWII financial framework', 'A forest reserve', 'A timber company', 'A nature park'],
    ['What is the BRICS group?', 'Brazil, Russia, India, China, S. Africa', 'A building material', 'A toy brand', 'A video game'],
    ['What is extraterritoriality?', 'Exemption from local law', 'Living outside Earth', 'A space program', 'An astronomy term'],
    ['What is the Iron Curtain?', 'Cold War divide in Europe', 'A theater prop', 'A metal fabric', 'A security system'],
    ['What is a multilateral agreement?', 'A deal among many countries', 'A two-country deal', 'No deal', 'A one-country rule'],
    ['What is the Arab Spring?', 'Pro-democracy protests in Arab world', 'A season', 'A water source', 'A music festival'],
    ['What is the EU single market?', 'Free trade zone among EU members', 'A grocery store', 'A stock market', 'A shopping mall'],
    ['What is a territorial dispute?', 'Countries disagree over land', 'A sports argument', 'A school debate', 'A family feud'],
    ['What is the International Court of Justice?', 'UN court for state disputes', 'A TV show', 'A game', 'A university'],
    ['What is political polarization?', 'Growing divide between parties', 'A science experiment', 'A magnet concept', 'A cooking method'],
    ['What is a trade deficit?', 'Importing more than exporting', 'Exporting more', 'Balanced trade', 'No trade'],
    ['What is a diplomatic channel?', 'A way nations communicate', 'A TV channel', 'A river', 'A road'],
    ['What is the Truman Doctrine?', 'US policy to contain communism', 'A medical treatment', 'A school curriculum', 'A cooking style'],
    ['What is the Monroe Doctrine?', 'US opposed European colonialism in Americas', 'A cooking recipe', 'A sports rule', 'A music theory'],
    ['What is the right of self-determination?', 'Peoples choose their own government', 'Right to travel freely', 'Right to free food', 'Right to a car'],
    ['What is an international embargo?', 'A global ban on trade with a nation', 'A shipping company', 'A port', 'A customs office'],
    ['What is a diplomatic envoy?', 'A messenger between governments', 'A mail carrier', 'A soldier', 'A tourist'],
    ['What are economic sanctions?', 'Penalties to pressure a nation', 'Tax breaks', 'Free trade deals', 'Business loans'],
    ['What is the IAEA?', 'International Atomic Energy Agency', 'An airline', 'A bank', 'A school'],
    ['What is the Geneva Protocol?', 'Rules banning chemical weapons', 'A peace treaty', 'A cooking method', 'A sports rule'],
    ['What is political asylum?', 'Protection from persecution abroad', 'A hospital', 'A school', 'A government office'],
    ['What is a demilitarized zone?', 'Area where military is banned', 'A war zone', 'A military base', 'An airport'],
    ['What is a puppet government?', 'A government controlled by outsiders', 'A toy store', 'A theater group', 'A children show'],
    ['What is imperialism?', 'Extending power over other nations', 'A board game', 'A math concept', 'A cooking style'],
    ['What is colonialism?', 'Controlling another territory', 'A farming method', 'A school system', 'A music style'],
    ['What is the Schengen Area?', 'Passport-free travel zone in Europe', 'A German city', 'A mountain range', 'A river basin'],
    ['What is a humanitarian intervention?', 'Action to protect civilians abroad', 'A hospital visit', 'A school project', 'A cooking show'],
    ['What is the camp David Accord?', 'Peace deal between Egypt and Israel', 'A summer camp', 'A music festival', 'A military base'],
    ['What is realpolitik?', 'Practical politics over ideology', 'A video game', 'A school subject', 'A cooking term'],
    ['What is the OPEC?', 'Organization of Petroleum Exporting Countries', 'A tech company', 'A school network', 'A sports league'],
    ['What is a free trade agreement?', 'No tariffs between member nations', 'A charity event', 'A tax increase', 'A war pact'],
    ['What is the balance of power?', 'No one nation dominates', 'Equal population sizes', 'Same currency', 'Identical laws'],
    ['What is the League of Nations?', 'Predecessor of the United Nations', 'A sports league', 'A TV show', 'A musical group'],
    ['What is deterrence in politics?', 'Preventing attack through strength', 'A cleaning product', 'A fence', 'A type of law'],
    ['What is a war of attrition?', 'Wearing down the enemy over time', 'A quick battle', 'A board game', 'A school competition'],
    ['What is the Suez Crisis?', 'A 1956 conflict over the Suez Canal', 'A flood', 'A drought', 'A hurricane'],
    ['What is a hegemon?', 'A dominant state or power', 'A shape', 'A tool', 'A mineral'],
    ['What is the Yalta Conference?', 'WWII meeting of Allied leaders', 'A peace treaty', 'A science fair', 'A music show'],
    ['What is a nation-state?', 'A country with shared identity', 'Any large city', 'A kingdom only', 'A continent'],
    ['What is a unipolar world?', 'One dominant superpower', 'Two superpowers', 'Many equal powers', 'No powers at all'],
  ],
  6: [
    ['What is the Westphalian system?', 'State sovereignty principle from 1648', 'A German school', 'A cooking technique', 'A sports league'],
    ['What is the Responsibility to Protect?', 'Duty to prevent mass atrocities', 'A fire safety rule', 'A copyright law', 'A traffic regulation'],
    ['What is Mutually Assured Destruction?', 'Nuclear deterrence strategy', 'A game show', 'A demolition company', 'A military rank'],
    ['What is the Sykes-Picot Agreement?', 'Secret WWI Middle East partition', 'A trade deal', 'A peace prize', 'A shipping route'],
    ['What is a failed state index?', 'Ranks countries by instability', 'A stock market tool', 'A school report', 'A health chart'],
    ['What is the UNHCR?', 'UN Refugee Agency', 'A hospital chain', 'A music label', 'An airline'],
    ['What is balkanization?', 'Splitting a region into hostile parts', 'A cooking method', 'A dance style', 'A music genre'],
    ['What is the Helsinki Accords?', 'Cold War agreement on borders', 'A music festival', 'A school pact', 'A sports treaty'],
    ['What is the Shanghai Cooperation Organisation?', 'Eurasian political and security group', 'A trade company', 'A sports league', 'A tech firm'],
    ['What is the status of forces agreement?', 'Rules for foreign troops on local soil', 'A gym membership', 'A fitness plan', 'A diet chart'],
    ['What is the Balfour Declaration?', 'British support for Jewish homeland', 'A cooking recipe', 'A music score', 'A building plan'],
    ['What is a kleptocracy?', 'Government by corrupt rulers', 'Rule by scientists', 'Rule by athletes', 'Rule by artists'],
    ['What is the Dayton Agreement?', 'Ended the Bosnian War', 'A car deal', 'A movie script', 'A music award'],
    ['What is the Nuclear Test Ban Treaty?', 'Prohibits nuclear weapons testing', 'Bans nuclear energy', 'Limits space travel', 'Restricts mining'],
    ['What is diplomatic recognition?', 'Officially accepting a government', 'A greeting card', 'An award ceremony', 'A school diploma'],
    ['What is the concept of jus ad bellum?', 'Right to go to war', 'A type of juice', 'A legal contract', 'A school course'],
    ['What is the petrodollar?', 'Oil traded in US dollars', 'A type of coin', 'A piggy bank', 'A gas station'],
    ['What is the ASEAN Regional Forum?', 'Asia-Pacific security dialogue', 'A TV channel', 'A cooking show', 'A sports tournament'],
    ['What is a transitional government?', 'Temporary government after upheaval', 'A moving company', 'A school trip', 'A travel agency'],
    ['What is the World Economic Forum?', 'Global leaders discuss economic issues', 'A stock exchange', 'A bank', 'A casino'],
    ['What is the African Continental Free Trade Area?', 'African trade zone', 'A nature reserve', 'A school network', 'A sports league'],
    ['What is a truth and reconciliation commission?', 'Body to address past wrongs', 'A church group', 'A school committee', 'A sports board'],
    ['What is the Belt and Road Initiative?', 'Chinas global infrastructure plan', 'A fashion brand', 'A fitness program', 'A cooking show'],
    ['What is the Quad alliance?', 'US, India, Japan, Australia group', 'A math term', 'A card game', 'A music quartet'],
    ['What is AUKUS?', 'Australia-UK-US security pact', 'A shoe brand', 'A programming language', 'A board game'],
    ['What is lawfare?', 'Using legal systems as a weapon', 'A type of war', 'A game', 'A school debate'],
    ['What is the right to return?', 'Right of refugees to go home', 'A library policy', 'A store policy', 'A school rule'],
    ['What is a color revolution?', 'Peaceful regime change movement', 'A painting class', 'A fashion trend', 'A music genre'],
    ['What is the Five Eyes alliance?', 'Intelligence sharing: US, UK, CA, AU, NZ', 'An eye doctor chain', 'A camera brand', 'A TV network'],
    ['What is a frozen conflict?', 'Unresolved but halted fighting', 'A winter sport', 'An ice cream brand', 'A science experiment'],
    ['What is the Rome Statute?', 'Treaty creating the ICC', 'An Italian recipe', 'A music piece', 'A travel guide'],
    ['What is shuttle diplomacy?', 'Mediator travels between parties', 'A space program', 'A bus service', 'A basketball move'],
    ['What is a casus belli?', 'Justification for war', 'A Latin dessert', 'A type of dance', 'A school grade'],
    ['What is the Good Friday Agreement?', 'Peace deal in Northern Ireland', 'A holiday recipe', 'A movie deal', 'A church event'],
    ['What is a truth commission?', 'Investigates human rights abuses', 'A lie detector', 'A school exam', 'A quiz show'],
    ['What is the CTBT?', 'Comprehensive Nuclear-Test-Ban Treaty', 'A computer language', 'A TV station', 'A bank code'],
    ['What is the Golan Heights dispute?', 'Land disputed by Israel and Syria', 'A ski resort', 'A mountain race', 'A hiking trail'],
    ['What is coercive diplomacy?', 'Using threats to achieve goals', 'Friendly negotiation', 'A cooking style', 'A dance form'],
    ['What is a bloc in world politics?', 'A group of allied nations', 'A building block', 'A city block', 'A wooden toy'],
    ['What is the principle of non-intervention?', 'Not interfering in other states', 'A medical rule', 'A sports rule', 'A cooking tip'],
    ['What is a rogue state?', 'A state that defies international norms', 'A pirate ship', 'A sports team', 'A game character'],
    ['What is the Nuremberg Trials?', 'WWII war crimes tribunal', 'A science fair', 'A cooking contest', 'A spelling bee'],
    ['What is the domino theory?', 'One nation falling to communism triggers others', 'A board game', 'A pizza brand', 'A math theorem'],
    ['What is the JCPOA?', 'Iran nuclear deal', 'A car brand', 'A school test', 'A phone model'],
    ['What is an exiled government?', 'Government operating from abroad', 'A holiday trip', 'A school exchange', 'A sports camp'],
    ['What is a mandate system?', 'League of Nations territory management', 'A homework rule', 'A voting method', 'A sports draft'],
    ['What is the Potsdam Conference?', 'Post-WWII Allied meeting in Germany', 'A music festival', 'A cooking show', 'A car race'],
    ['What is a sphere of influence?', 'Area under a powers sway', 'A geometry term', 'A type of ball', 'A weather pattern'],
    ['What is the doctrine of preemption?', 'Striking before being attacked', 'A school rule', 'A cooking method', 'A traffic law'],
    ['What is the Concert of Europe?', 'Post-Napoleonic balance of power', 'A music festival', 'An orchestra', 'A dance show'],
  ],
};

export const tech: Record<number, Fact[]> = {
  1: [
    ['What do you use to call someone far away?', 'A phone', 'A book', 'A spoon', 'A chair'],
    ['What is a computer?', 'A machine that processes information', 'A type of food', 'A toy car', 'A hat'],
    ['What is the internet?', 'A network connecting computers', 'A fishing net', 'A spider web', 'A blanket'],
    ['What do you watch videos on?', 'A screen', 'A pillow', 'A plate', 'A wall'],
    ['What is a tablet?', 'A portable touchscreen computer', 'A writing pad', 'A medicine', 'A snack'],
    ['What do you use to type on a computer?', 'A keyboard', 'A paintbrush', 'A hammer', 'A fork'],
    ['What is an app?', 'A program on a phone or tablet', 'A type of apple', 'A hat', 'A shoe'],
    ['What do headphones do?', 'Let you listen to sound privately', 'Cook food', 'Wash clothes', 'Water plants'],
    ['What is a mouse in computing?', 'A device to move the cursor', 'A small animal', 'A cheese holder', 'A trap'],
    ['What is Wi-Fi?', 'Wireless internet connection', 'A type of food', 'A radio station', 'A hat brand'],
    ['What does a printer do?', 'Puts images or text on paper', 'Cooks food', 'Washes dishes', 'Plays music'],
    ['What is a password?', 'A secret code to log in', 'A type of pasta', 'A game', 'A song'],
    ['What is a selfie?', 'A photo you take of yourself', 'A type of fish', 'A dance move', 'A snack'],
    ['What is email?', 'Electronic mail sent online', 'A type of snail', 'A mailbox', 'A postcard'],
    ['What is a video game?', 'An electronic game you play on screen', 'A board game', 'A card game', 'A sport'],
    ['What is a camera on a phone for?', 'Taking photos and videos', 'Making calls only', 'Sending texts', 'Playing games'],
    ['What is a charger?', 'It gives power to a device', 'A type of horse', 'A cooking tool', 'A toy'],
    ['What does a speaker do?', 'Plays sound out loud', 'Cooks food', 'Washes hands', 'Drives a car'],
    ['What is a touchscreen?', 'A screen you control by touching', 'A type of paint', 'A mirror', 'A window'],
    ['What is a robot?', 'A machine that can do tasks', 'A type of insect', 'A planet', 'A tree'],
    ['What is a website?', 'A page on the internet', 'A spiderweb', 'A fishing net', 'A bird nest'],
    ['What do you click to go to a website?', 'A link', 'A button on a shirt', 'A zipper', 'A doorbell'],
    ['What is a monitor?', 'A computer screen', 'A lizard', 'A teacher', 'A guard'],
    ['What is a USB cable?', 'A cord to connect devices', 'A jump rope', 'A belt', 'A shoelace'],
    ['What is a download?', 'Getting a file from the internet', 'Going downhill', 'A type of frown', 'A raindrop'],
    ['What is a search engine?', 'A tool to find things online', 'A car engine', 'A train', 'A washing machine'],
    ['What is Google?', 'A search engine', 'A type of glasses', 'A dance move', 'A candy'],
    ['What is YouTube?', 'A website to watch videos', 'A tube of paint', 'A water pipe', 'A musical instrument'],
    ['What is a screenshot?', 'A picture of your screen', 'A sports shot', 'A camera lens', 'A movie scene'],
    ['What is Bluetooth?', 'Wireless connection between devices', 'A blue tooth fairy', 'A dental tool', 'A crayon'],
    ['What is an emoji?', 'A small digital picture in messages', 'A type of fish', 'A music note', 'A letter'],
    ['What is a battery?', 'Stores power for devices', 'A cooking pan', 'A baseball term', 'A game'],
    ['What is a smartwatch?', 'A watch that connects to your phone', 'A regular clock', 'A bracelet', 'A ring'],
    ['What is a QR code?', 'A pattern a phone can scan', 'A type of music', 'A math problem', 'A puzzle'],
    ['What is a laptop?', 'A portable computer', 'A tray for food', 'A pillow', 'A desk'],
    ['What is streaming?', 'Watching or listening online live', 'A river flowing', 'Fishing', 'Swimming'],
    ['What is a digital photo?', 'A picture stored on a device', 'A painted picture', 'A drawn sketch', 'A sculpture'],
    ['What is an alarm on a phone?', 'A sound that wakes you up', 'A type of music', 'A game', 'A flashlight'],
    ['What is a text message?', 'Words sent from phone to phone', 'A school book', 'A letter in the mail', 'A newspaper'],
    ['What is a GPS?', 'A system that shows your location', 'A type of gas', 'A game console', 'A remote control'],
    ['What is a smart TV?', 'A TV connected to the internet', 'A very clever TV', 'A tiny TV', 'A radio'],
    ['What is an icon on a screen?', 'A small picture you tap or click', 'A type of statue', 'A building', 'A hat'],
    ['What is a game console?', 'A device for playing video games', 'A type of table', 'A musical keyboard', 'A bookshelf'],
    ['What is a microphone?', 'Records or amplifies your voice', 'A tiny phone', 'A small bike', 'A mini piano'],
    ['What is a flashlight on a phone?', 'A light built into the phone', 'A camera', 'A speaker', 'A button'],
    ['What is a remote control?', 'A device to control a TV from far', 'A toy car controller', 'A phone', 'A key'],
    ['What is a drone?', 'A flying robot', 'A bee sound', 'A type of music', 'A boring speech'],
    ['What does a webcam do?', 'Records video from a computer', 'Takes only photos', 'Plays music', 'Prints documents'],
    ['What is a voice assistant?', 'Software that answers questions by voice', 'A singing teacher', 'A microphone', 'A speaker'],
    ['What is an e-book?', 'A book you read on a device', 'An electric book', 'A glowing book', 'A talking book'],
  ],
  2: [
    ['What is a file on a computer?', 'A stored piece of information', 'A folder for papers', 'A nail file', 'A tool'],
    ['What is a folder on a computer?', 'A place to organize files', 'A paper binder', 'A type of envelope', 'A mailbox'],
    ['What is a notification?', 'An alert from an app', 'A note on paper', 'A type of music', 'A letter'],
    ['What is coding?', 'Writing instructions for computers', 'A secret spy language', 'A card game', 'A type of knitting'],
    ['What is a browser?', 'A program to access the internet', 'A type of hat', 'A search party', 'A shopping cart'],
    ['What is copy and paste?', 'Duplicating text or images', 'A type of glue', 'A cooking method', 'An art supply'],
    ['What does save mean on a computer?', 'Keep your work stored', 'Rescue someone', 'A type of box', 'A piggy bank'],
    ['What is a home screen?', 'The main screen on a device', 'A houses TV', 'A door screen', 'A window screen'],
    ['What is Siri?', 'Apples voice assistant', 'A type of bird', 'A song', 'A dance'],
    ['What does undo mean on a computer?', 'Reverse the last action', 'Delete everything', 'Turn off the computer', 'Close all apps'],
    ['What is an update?', 'A newer version of software', 'A climbing move', 'A type of grade', 'A news report'],
    ['What is a sensor?', 'A device that detects changes', 'A type of smell', 'A feeling', 'A taste'],
    ['What is airplane mode?', 'Turns off wireless signals', 'Makes the phone fly', 'A flight game', 'A paper airplane app'],
    ['What is a cloud in tech?', 'Online storage for data', 'A fluffy white sky thing', 'A type of computer', 'A printer brand'],
    ['What is a video call?', 'Talking to someone on screen live', 'Calling a movie theater', 'Sending a video file', 'A TV show'],
    ['What is zoom used for?', 'Video meetings', 'Making things bigger', 'Racing cars', 'Taking photos'],
    ['What is an upload?', 'Sending a file to the internet', 'Going up in an elevator', 'A type of hairstyle', 'A sports move'],
    ['What is a spam email?', 'Unwanted junk email', 'A ham email', 'A recipe email', 'A friendly email'],
    ['What is storage on a device?', 'Space to keep files and apps', 'A closet', 'A garage', 'A backpack'],
    ['What is a URL?', 'A web address', 'A type of code', 'A game', 'A sound'],
    ['What is drag and drop?', 'Moving items on screen by holding', 'A type of dance', 'A sports move', 'A cooking method'],
    ['What is a GIF?', 'A short animated image', 'A type of present', 'A toy', 'A food'],
    ['What is a pop-up on a screen?', 'A window that appears suddenly', 'A type of book', 'A toy', 'A balloon'],
    ['What is a login?', 'Entering your account with a name and password', 'A type of wood', 'A cabin', 'A tree trunk'],
    ['What is an avatar?', 'A digital picture representing you', 'A movie only', 'A type of fruit', 'A hat'],
    ['What is a hashtag?', 'A label starting with the # symbol', 'A type of tag game', 'A price tag', 'A name tag'],
    ['What does refresh mean?', 'Reload a page', 'Take a shower', 'Drink water', 'Start a new game'],
    ['What is a playlist?', 'A list of songs or videos to play', 'A to-do list', 'A shopping list', 'A recipe card'],
    ['What is a pixel?', 'A tiny dot on a screen', 'A fairy', 'A bug', 'A star'],
    ['What is a meme?', 'A funny shared image or video', 'A type of song', 'A dessert', 'A dance move'],
    ['What is a podcast?', 'An audio show online', 'A type of pea', 'A space capsule', 'A storage box'],
    ['What is an ad online?', 'A message trying to sell something', 'A math addition', 'A computer virus', 'A friend request'],
    ['What is a bookmark in a browser?', 'A saved link to a website', 'A paper strip in a book', 'A ribbon', 'A sticker'],
    ['What is a cursor?', 'The arrow you move on screen', 'A type of spell', 'A race car', 'A pencil'],
    ['What is face recognition?', 'Tech that identifies faces', 'A mirror', 'A sticker filter', 'A drawing tool'],
    ['What is a memory card?', 'A chip that stores data', 'A card game', 'A greeting card', 'A flash card'],
    ['What is dark mode?', 'A display setting with dark colors', 'Night time only feature', 'A scary mode', 'A broken screen'],
    ['What is a screenshot different from a photo?', 'It captures whats on the screen', 'It uses a camera', 'It prints paper', 'It records video'],
    ['What is a software bug?', 'A mistake in a program', 'An insect in the computer', 'A computer virus', 'A worm'],
    ['What is autofill?', 'Auto-completing forms or text', 'Filling a gas tank', 'Filling a pool', 'Auto-cooking'],
    ['What is a sticker in messaging?', 'A fun digital image to send', 'A price label', 'A name tag', 'A stamp'],
    ['What is a digital assistant?', 'An AI helper on a device', 'A robot maid', 'A phone case', 'A charger'],
    ['What is a power button?', 'Turns a device on or off', 'A strong button', 'A game button', 'A doorbell'],
    ['What is a VR headset?', 'A device for virtual reality', 'Fancy sunglasses', 'A bike helmet', 'A music player'],
    ['What is 3D printing?', 'Making real objects from a printer', 'Printing in color', 'Printing very fast', 'Printing photos'],
    ['What is a stylus?', 'A pen for touchscreens', 'A type of music', 'A hairstyle', 'A flower'],
    ['What is a filter on a photo?', 'An effect that changes how it looks', 'A coffee maker', 'A water cleaner', 'A fish net'],
    ['What is a toolbar?', 'A row of buttons in software', 'A physical toolbox', 'A type of candy', 'A shelf'],
    ['What is a ringtone?', 'A sound when your phone rings', 'A ring shape tone', 'A doorbell', 'A musical key'],
    ['What is an operating system?', 'Main software running a device', 'A hospital system', 'A train schedule', 'A school plan'],
  ],
  3: [
    ['What does HTML stand for?', 'HyperText Markup Language', 'How To Make Lasagna', 'Happy Turtles Make Lunch', 'High Tech Machine Logic'],
    ['What is software?', 'Programs that run on a computer', 'The soft part of a computer', 'A pillow for laptops', 'A blanket for phones'],
    ['What is hardware?', 'Physical parts of a computer', 'Hard-to-use software', 'A hardware store', 'A tough phone case'],
    ['What is a programming language?', 'A language to write code in', 'A foreign language', 'A computer brand', 'A type of math'],
    ['What is a virus on a computer?', 'Harmful software', 'A sick computer', 'A small bug inside', 'A broken screen'],
    ['What does CPU stand for?', 'Central Processing Unit', 'Computer Power Unit', 'Central Printing Unit', 'Cool Phone Upgrade'],
    ['What is RAM?', 'Temporary memory in a computer', 'A male sheep', 'A battering device', 'A type of truck'],
    ['What is social media?', 'Online platforms to share content', 'A newspaper', 'A TV channel', 'A radio station'],
    ['What is a server?', 'A computer that provides data to others', 'A restaurant worker', 'A tennis move', 'A type of tray'],
    ['What is AI?', 'Artificial Intelligence', 'Actual Insects', 'Automatic Ice', 'Amazing Ideas'],
    ['What is a database?', 'An organized collection of data', 'A baseball base', 'A data fish', 'A type of desk'],
    ['What is an algorithm?', 'A set of steps to solve a problem', 'A type of drum', 'A dance move', 'A math symbol'],
    ['What is the cloud in computing?', 'Remote servers for data storage', 'Fluffy white things in the sky', 'A weather app', 'A fog machine'],
    ['What is a firewall?', 'Security system for networks', 'A wall made of fire', 'A fire station', 'A campfire ring'],
    ['What is a byte?', 'A unit of digital data', 'A small bite of food', 'A bug bite', 'A dog sound'],
    ['What does PDF stand for?', 'Portable Document Format', 'Pretty Darn Fun', 'Printed Digital File', 'Paper Document Finder'],
    ['What is an IP address?', 'A devices unique internet address', 'A type of real address', 'A phone number', 'A zip code'],
    ['What is a pixel in images?', 'The smallest unit of a digital image', 'A fairy character', 'A type of paint', 'A crayon color'],
    ['What is WiFi short for?', 'Wireless Fidelity', 'Wide Finder', 'Wired Files', 'Web Friendly'],
    ['What is encryption?', 'Scrambling data for security', 'A type of puzzle', 'A magic trick', 'A math game'],
    ['What is the difference between www and http?', 'www is the web; http is the protocol', 'They are the same', 'www is faster', 'http is a website'],
    ['What is a router?', 'A device that directs internet traffic', 'A woodworking tool', 'A map app', 'A road sign'],
    ['What is open source software?', 'Free software anyone can modify', 'A door opener', 'A lock pick', 'A window cleaner'],
    ['What is a megabyte?', 'About one million bytes', 'A big animal bite', 'A type of insect', 'A large meal'],
    ['What is Scratch in programming?', 'A visual coding language for kids', 'A scratch card', 'A cat scratch', 'A DJ technique'],
    ['What is a domain name?', 'A websites address name', 'A kingdom', 'A type of game', 'A brand'],
    ['What is GPS technology?', 'Satellite-based location tracking', 'A gaming console', 'A TV station', 'A radio signal'],
    ['What is a SIM card?', 'A chip for phone network access', 'A type of game card', 'A credit card', 'A gift card'],
    ['What is a gigabyte?', 'About one billion bytes', 'A giant insect', 'A large bite', 'A big meal'],
    ['What is malware?', 'Malicious software', 'A bad shopping mall', 'A broken mail', 'A sick fish'],
    ['What is JavaScript?', 'A popular programming language', 'A coffee recipe', 'A type of handwriting', 'A movie script'],
    ['What is Python in tech?', 'A programming language', 'Only a snake', 'A calculator', 'A video game'],
    ['What is a GIF file?', 'An animated image format', 'A type of gift', 'A greeting card', 'A music file'],
    ['What is a plug-in?', 'Extra software that adds features', 'An electrical plug', 'A bathtub plug', 'A type of cable'],
    ['What is a digital footprint?', 'Your online activity trail', 'A computer shoe', 'A screen step', 'A foot scanner'],
    ['What is phishing?', 'Tricking people to steal info', 'A type of fishing', 'A phone app', 'A video game'],
    ['What is a terabyte?', 'About one trillion bytes', 'A scary bite', 'A dinosaur', 'A huge meal'],
    ['What is an ethernet cable?', 'A wired internet connection', 'A phone charger', 'A TV wire', 'A jump rope'],
    ['What is Bluetooth named after?', 'A Viking king', 'The color blue', 'A dentist', 'A music note'],
    ['What is binary code?', 'Code using only 0s and 1s', 'A two-wheeled bike code', 'A twin language', 'A pair of numbers'],
    ['What is a cache?', 'Temporary stored data', 'A hidden treasure', 'A type of cash', 'A basket'],
    ['What is a screenshot saved as?', 'An image file', 'A text file', 'An audio file', 'A video file'],
    ['What is an SSD?', 'A fast storage drive', 'A slow disk', 'A sound system', 'A screen display'],
    ['What is a motherboard?', 'Main circuit board of a computer', 'A surfboard', 'A skateboard', 'A snowboard'],
    ['What is a browser extension?', 'An add-on for web browsers', 'A hair extension', 'A phone cord', 'A power strip'],
    ['What is a USB flash drive?', 'A small portable storage device', 'A flashlight', 'A pen', 'A key chain'],
    ['What does URL stand for?', 'Uniform Resource Locator', 'Universal Radio Link', 'Ultra Rapid Loader', 'Unique Reference Label'],
    ['What is a chatbot?', 'A program that chats like a human', 'A talking cat', 'A chat room', 'A phone app only'],
    ['What is bandwidth?', 'Data transfer capacity', 'A music bands width', 'A rubber band', 'A watch band'],
    ['What is lag in technology?', 'A delay in response', 'A type of exercise', 'A game level', 'A computer brand'],
  ],
  4: [
    ['What is machine learning?', 'Computers learning from data', 'Robots going to school', 'A sewing machine', 'A washing cycle'],
    ['What is a VPN?', 'Virtual Private Network', 'Very Private Note', 'Video Phone Number', 'Virtual Play Net'],
    ['What is CSS?', 'Cascading Style Sheets', 'Computer Screen Saver', 'Cool Super Software', 'Central System Setup'],
    ['What is an API?', 'Application Programming Interface', 'A Personal Invention', 'Apple Pie Inc', 'Advanced Phone Input'],
    ['What is the dark web?', 'Hidden part of the internet', 'A dark-themed website', 'The internet at night', 'A scary app'],
    ['What is two-factor authentication?', 'Two steps to verify identity', 'Two passwords', 'A math formula', 'A science experiment'],
    ['What is cloud computing?', 'Using remote servers for computing', 'Computing in the sky', 'A weather app', 'A flying computer'],
    ['What is virtual reality?', 'A simulated digital environment', 'A dream world', 'A TV show', 'A hallucination'],
    ['What is augmented reality?', 'Digital info overlaid on real world', 'Extra large screens', 'A magnifying glass', 'A telescope'],
    ['What is a neural network?', 'AI system inspired by the brain', 'A brain scan', 'A type of wire', 'A fishing net'],
    ['What is DevOps?', 'Combining development and operations', 'A video game', 'A type of robot', 'A coding language'],
    ['What is GitHub?', 'A platform for code collaboration', 'A type of hat', 'A social media app', 'A search engine'],
    ['What is a container in tech?', 'Isolated environment for software', 'A lunch box', 'A shipping crate', 'A storage bin'],
    ['What is responsive design?', 'Websites that adapt to screen size', 'Fast-loading sites', 'Websites that talk back', 'Interactive games'],
    ['What does IoT stand for?', 'Internet of Things', 'Inside of Technology', 'Information on Track', 'Incredible Online Tool'],
    ['What is a podcast different from radio?', 'On-demand and online', 'Live only', 'Uses AM waves', 'Requires antenna'],
    ['What is a compiler?', 'Translates code to machine language', 'A book collector', 'A list maker', 'A data sorter'],
    ['What is debugging?', 'Finding and fixing code errors', 'Removing real bugs', 'A pest control tool', 'An insect repellent'],
    ['What is a data center?', 'A facility housing many servers', 'A library', 'A school', 'An office'],
    ['What is cryptocurrency?', 'Digital money using encryption', 'A type of crossword', 'A secret code', 'A treasure map'],
    ['What is blockchain?', 'A chain of linked data blocks', 'A type of chain link', 'A building block game', 'A block party'],
    ['What is a chatbot trained on?', 'Large amounts of text data', 'Spoken conversations only', 'Music files', 'Video games'],
    ['What is biometric security?', 'Using body features to verify', 'A gym membership', 'A health check', 'A diet plan'],
    ['What is the difference between 4G and 5G?', '5G is faster', '4G is newer', 'They are the same speed', '5G uses wires'],
    ['What is a DDoS attack?', 'Overloading a server with traffic', 'Downloading files quickly', 'A type of game', 'A virus scan'],
    ['What is a CMS?', 'Content Management System', 'Computer Memory Store', 'Central Music System', 'Counting Math Software'],
    ['What is SEO?', 'Search Engine Optimization', 'Super Electronic Output', 'Secure Email Option', 'System Error Override'],
    ['What is a tech stack?', 'The set of technologies used', 'A pile of computers', 'A stack of phones', 'A data tower'],
    ['What is agile development?', 'Iterative software development', 'Fast typing', 'Quick drawing', 'Speed reading'],
    ['What is a sprint in software?', 'A short development cycle', 'Running a race', 'A speed test', 'A type of phone'],
    ['What is version control?', 'Tracking changes to code', 'Checking software versions', 'Controlling updates', 'A game mode'],
    ['What is a pull request?', 'Asking to merge code changes', 'Pulling a cable', 'A download request', 'A data transfer'],
    ['What is artificial neural network?', 'Computing system like the brain', 'A brain transplant', 'A fishing technique', 'A knitting pattern'],
    ['What is a smart home?', 'A house with connected devices', 'A very organized house', 'A school for homes', 'A dollhouse'],
    ['What is NFC technology?', 'Near Field Communication', 'New Fancy Computer', 'No Free Calls', 'National Football Club'],
    ['What is e-commerce?', 'Buying and selling online', 'Electronic comics', 'Email trading', 'Energy commerce'],
    ['What is UX design?', 'Designing user experiences', 'A type of art', 'A fashion design', 'A building plan'],
    ['What is a digital signature?', 'Electronic proof of identity', 'Typing your name', 'A scanned autograph', 'A stamp'],
    ['What is ransomware?', 'Malware demanding payment', 'A charity app', 'A banking tool', 'A coupon app'],
    ['What is open data?', 'Data anyone can use freely', 'A door that opens', 'An open book', 'A public library'],
    ['What is a bot?', 'An automated software program', 'A small robot toy', 'A type of boat', 'A baseball bat'],
    ['What is a LAN?', 'Local Area Network', 'Large Animal Noise', 'Long Access Number', 'Laser Aim Navigator'],
    ['What is latency?', 'Delay in data transfer', 'A type of coffee', 'Being late', 'A sleeping state'],
    ['What is a proxy server?', 'An intermediary server', 'A replacement computer', 'A backup phone', 'A fake website'],
    ['What is DNS?', 'Domain Name System', 'Digital Number Service', 'Data Network Security', 'Direct Name Search'],
    ['What is a GPU?', 'Graphics Processing Unit', 'General Power Unit', 'Grand Pixel Utility', 'Game Play Upgrade'],
    ['What is a hash function?', 'Converts data to fixed-size value', 'A cooking method', 'A breakfast food', 'A type of key'],
    ['What is a web crawler?', 'A program that indexes websites', 'A bug on a webpage', 'A slow website', 'A spider game'],
    ['What is a CDN?', 'Content Delivery Network', 'Computer Data Node', 'Central Design Net', 'Cloud Data Nexus'],
    ['What is microservices?', 'Small independent services', 'Tiny computers', 'Microscope software', 'Mini apps'],
  ],
  5: [
    ['What is a SQL database?', 'A relational database using SQL', 'A quiz game', 'A type of sequel', 'A spy tool'],
    ['What is an SSL certificate?', 'Secures website connections', 'A school certificate', 'A driving license', 'A birth certificate'],
    ['What is a REST API?', 'A web service using HTTP methods', 'A relaxation app', 'A sleep tracker', 'A break timer'],
    ['What is big data?', 'Extremely large data sets', 'A large USB drive', 'A tall computer', 'A heavy laptop'],
    ['What is Docker?', 'A platform for containerization', 'A boat dock', 'A type of whale', 'A clothing brand'],
    ['What is a NoSQL database?', 'Non-relational database', 'A silent database', 'A no-question database', 'A secret database'],
    ['What is TCP/IP?', 'Internet communication protocol', 'A typing test', 'A phone plan', 'A TV channel'],
    ['What is quantum computing?', 'Computing using quantum mechanics', 'A very fast laptop', 'A physics class', 'A math formula'],
    ['What is natural language processing?', 'AI understanding human language', 'Teaching nature to talk', 'A language school', 'A voice recorder'],
    ['What is a microcontroller?', 'A small computer on a single chip', 'A tiny remote control', 'A mini keyboard', 'A small screen'],
    ['What is Kubernetes?', 'A container orchestration system', 'A Greek island', 'A type of cube', 'A robot name'],
    ['What is a man-in-the-middle attack?', 'Intercepting communication', 'A basketball position', 'A relay race', 'A board game move'],
    ['What is a zero-day vulnerability?', 'A flaw exploited before patching', 'A holiday bug', 'A countdown timer', 'A New Years virus'],
    ['What is data mining?', 'Extracting patterns from data', 'Digging for computers', 'A Minecraft mode', 'Gold panning'],
    ['What is a full-stack developer?', 'Works on front and back end', 'Stacks computers', 'Builds shelves', 'A pancake chef'],
    ['What is edge computing?', 'Processing data near its source', 'Computing on a cliff', 'A type of surfing', 'A rock climbing app'],
    ['What is WebSocket?', 'Protocol for real-time communication', 'A web plug', 'An internet cable', 'A browser game'],
    ['What is a load balancer?', 'Distributes traffic across servers', 'A weighing scale', 'A gym device', 'A balance beam'],
    ['What is OAuth?', 'An authorization protocol', 'A type of oath', 'A password manager', 'A login screen'],
    ['What is a tech IPO?', 'Initial public stock offering', 'A new phone model', 'A startup idea', 'A tech conference'],
    ['What is Git?', 'A version control system', 'A type of exercise', 'A musical instrument', 'A card game'],
    ['What is CI/CD?', 'Continuous Integration/Delivery', 'Computer Input/Output', 'Chat Interface/Design', 'Code Index/Data'],
    ['What is a regex?', 'A pattern for text searching', 'A type of dinosaur', 'A card game', 'A math formula'],
    ['What is a webhook?', 'Automated HTTP callback', 'A fishing hook on the web', 'A browser plugin', 'A bookmark'],
    ['What is serverless computing?', 'Cloud runs code without servers', 'No computers needed', 'Computing without power', 'A broken server'],
    ['What is a binary tree?', 'A data structure with two branches', 'A tree with two trunks', 'A binary code plant', 'A digital forest'],
    ['What is an ORM?', 'Object-Relational Mapping', 'Online Relay Message', 'Optical Reading Machine', 'Operating Room Monitor'],
    ['What is SSH?', 'Secure Shell protocol', 'Super Speed Hosting', 'Secret Safe Hub', 'System Setup Help'],
    ['What is a race condition?', 'Bug from concurrent processes', 'A car racing game', 'A speed test', 'A running event'],
    ['What is TypeScript?', 'JavaScript with static types', 'A typing test', 'A handwriting font', 'A typewriter app'],
    ['What is GraphQL?', 'A query language for APIs', 'A graphing tool', 'A drawing app', 'A chart maker'],
    ['What is a monorepo?', 'One repository for multiple projects', 'A single file', 'A lone developer', 'A solo project'],
    ['What is infrastructure as code?', 'Managing servers through code', 'Building with robots', 'A construction app', 'A blueprint scanner'],
    ['What is a middleware?', 'Software between client and server', 'A jacket', 'A middle seat', 'A fence'],
    ['What is cross-site scripting?', 'Injecting code into websites', 'Writing on two papers', 'A penmanship exercise', 'A typing game'],
    ['What is CORS?', 'Cross-Origin Resource Sharing', 'Computer Online Repair Service', 'Central Operating Room System', 'Coded Output Reading Software'],
    ['What is a service mesh?', 'Infrastructure for service communication', 'A fishing net', 'A wire fence', 'A screen door'],
    ['What is horizontal scaling?', 'Adding more machines', 'Making screens wider', 'A landscape mode', 'A stretching exercise'],
    ['What is a dead letter queue?', 'Queue for failed messages', 'A ghost mailbox', 'An old post office', 'A returned package'],
    ['What is event-driven architecture?', 'System responding to events', 'A calendar app', 'A party planner', 'A scheduling tool'],
    ['What is observability in tech?', 'Monitoring system internals', 'Watching TV', 'A telescope', 'A security camera'],
    ['What is a reverse proxy?', 'A server forwarding client requests', 'A backward mirror', 'A backwards proxy vote', 'An upside-down server'],
    ['What is object-oriented programming?', 'Code organized around objects', 'Programming physical things', 'A 3D coding style', 'A virtual museum'],
    ['What is a design pattern?', 'Reusable solution to coding problems', 'A fashion template', 'A wallpaper style', 'A painting method'],
    ['What is a JWT?', 'JSON Web Token', 'Just Wait There', 'Java Web Tool', 'Joint Work Team'],
    ['What is functional programming?', 'Code using pure functions', 'A fitness app', 'A working program', 'A practical course'],
    ['What is dependency injection?', 'Providing objects a class needs', 'A medical procedure', 'A fuel system', 'A water pipe'],
    ['What is refactoring?', 'Improving code without changing behavior', 'Rebuilding a factory', 'Restarting a computer', 'Rewriting a book'],
    ['What is a canary deployment?', 'Gradual rollout to some users', 'A bird app', 'A yellow website', 'A singing program'],
    ['What is a feature flag?', 'Toggle to enable/disable features', 'A country flag', 'A red flag warning', 'A finish line marker'],
  ],
  6: [
    ['What is a Turing machine?', 'A theoretical computing model', 'A washing machine', 'A time machine', 'A sewing machine'],
    ['What is Byzantine fault tolerance?', 'Handling unreliable components', 'A Greek architecture style', 'A type of wall', 'A castle defense'],
    ['What is a consensus algorithm?', 'Agreement among distributed nodes', 'A voting app', 'A survey tool', 'A group chat'],
    ['What is sharding?', 'Splitting a database across servers', 'Breaking glass', 'Cutting paper', 'Chopping wood'],
    ['What is CAP theorem?', 'Consistency, Availability, Partition tradeoff', 'A hat theory', 'A bottle rule', 'A cap size chart'],
    ['What is eventual consistency?', 'Data syncs over time', 'Immediate accuracy', 'Perfect alignment', 'Constant updating'],
    ['What is a Merkle tree?', 'Hash tree for data verification', 'A type of oak tree', 'A Christmas tree', 'A family tree'],
    ['What is a smart contract?', 'Self-executing code on blockchain', 'A clever legal deal', 'An auto-signing pen', 'An AI lawyer'],
    ['What is homomorphic encryption?', 'Computing on encrypted data', 'A type of geometry', 'A biology concept', 'A chemistry formula'],
    ['What is a bloom filter?', 'Probabilistic data membership test', 'A flower detector', 'A photo filter', 'An air cleaner'],
    ['What is a Raft protocol?', 'A consensus algorithm', 'A water transport protocol', 'A boat building guide', 'A swimming method'],
    ['What is ACID in databases?', 'Atomicity, Consistency, Isolation, Durability', 'A chemical compound', 'A sour taste', 'A battery liquid'],
    ['What is a side-channel attack?', 'Exploiting system information leaks', 'Attacking from the side', 'A sports play', 'A flanking maneuver'],
    ['What is MapReduce?', 'Parallel data processing model', 'A geography tool', 'A navigation app', 'A drawing program'],
    ['What is a state machine?', 'A model of system states', 'A government computer', 'A US map app', 'A state capital quiz'],
    ['What is a garbage collector in code?', 'Frees unused memory automatically', 'A trash pickup app', 'A recycling bot', 'A cleaning robot'],
    ['What is a buffer overflow?', 'Writing data past allocated memory', 'A cup overflowing', 'Too many buffers', 'A full swimming pool'],
    ['What is WebAssembly?', 'Low-level code running in browsers', 'A web building kit', 'An HTML editor', 'A website builder'],
    ['What is gRPC?', 'A high-performance RPC framework', 'A chat protocol', 'A gaming system', 'A graphics card'],
    ['What is the halting problem?', 'Whether a program will ever stop', 'A traffic issue', 'A pause button', 'A freeze error'],
    ['What is memoization?', 'Caching function results', 'Memorizing things', 'A memory test', 'A study technique'],
    ['What is a semaphore in computing?', 'A signal for resource access control', 'A flag system', 'A traffic light', 'A train signal'],
    ['What is tail recursion?', 'Recursion as last function operation', 'Chasing a tail', 'A spiral staircase', 'An animal behavior'],
    ['What is a microkernel?', 'Minimal OS core', 'A tiny popcorn kernel', 'A small seed', 'A mini nut'],
    ['What is the OSI model?', 'Seven-layer networking framework', 'A fashion model', 'A building model', 'A car model'],
    ['What is a container orchestrator?', 'Manages multiple containers', 'A music conductor', 'A shipping manager', 'A storage organizer'],
    ['What is a deadlock?', 'Processes blocking each other', 'A locked door', 'A broken key', 'A jammed lock'],
    ['What is polymorphism?', 'Objects taking many forms', 'A shape-shifting animal', 'A color change', 'A metamorphosis'],
    ['What is a lambda function?', 'An anonymous inline function', 'A Greek letter', 'A math formula', 'A type of ray'],
    ['What is a hash collision?', 'Two inputs producing same hash', 'Two cars crashing', 'A broken code', 'A mixed signal'],
    ['What is an immutable data structure?', 'Cannot be changed after creation', 'A very strong building', 'A permanent marker', 'A carved stone'],
    ['What is time complexity?', 'How runtime scales with input', 'A clock speed', 'A watch complication', 'A calendar system'],
    ['What is space complexity?', 'How memory scales with input', 'A room measurement', 'A space shuttle term', 'A storage unit size'],
    ['What is a qubit?', 'A quantum computing bit', 'A tiny cube', 'A puzzle piece', 'A game token'],
    ['What is federated learning?', 'Training models across devices', 'A government school', 'A union class', 'A group study'],
    ['What is zero-knowledge proof?', 'Proving truth without revealing data', 'An empty test', 'A blank paper proof', 'A silent witness'],
    ['What is a directed acyclic graph?', 'A one-way graph with no cycles', 'A bike path', 'A hiking trail', 'A road map'],
    ['What is an ELT pipeline?', 'Extract, Load, Transform data flow', 'An electrical circuit', 'A water system', 'A train route'],
    ['What is chaos engineering?', 'Testing systems by introducing failures', 'A messy workshop', 'A tornado study', 'A demolition job'],
    ['What is a monolith in software?', 'A single large application', 'A stone monument', 'A big rock', 'A tall building'],
    ['What is idempotency?', 'Same result regardless of repeats', 'A type of identity', 'A math constant', 'A chemical property'],
    ['What is blue-green deployment?', 'Two identical production environments', 'A color palette', 'A paint technique', 'A garden layout'],
    ['What is a circuit breaker pattern?', 'Prevents cascading failures', 'An electrical switch', 'A fuse box', 'A power strip'],
    ['What is observability vs monitoring?', 'Understanding why vs knowing what', 'Same concept', 'Monitoring is deeper', 'Neither is useful'],
    ['What is a service worker?', 'Script for offline web capabilities', 'A repair technician', 'A customer agent', 'A delivery person'],
    ['What is differential privacy?', 'Adding noise to protect individual data', 'A privacy screen', 'A math difference', 'A locked folder'],
    ['What is a distributed ledger?', 'Shared record across many nodes', 'A shared notebook', 'A group calendar', 'A public diary'],
    ['What is ABI in computing?', 'Application Binary Interface', 'A type of battery', 'A naming convention', 'A cable type'],
    ['What is a persistent data structure?', 'Preserves previous versions', 'A structure that never breaks', 'A hard drive', 'A strong building'],
    ['What is formal verification?', 'Mathematically proving code correctness', 'A dress code check', 'A spelling test', 'A security scan'],
  ],
};
