// [clue, answer, wrong1, wrong2, wrong3]
export type Fact = [string, string, string, string, string];

export const wrm: Record<number, Fact[]> = {
  1: [
    ['Christmas is celebrated by?', 'Christians', 'Buddhists', 'Sikhs', 'Hindus only'],
    ['A mosque is where Muslims go to?', 'Pray', 'Swim', 'Cook', 'Sleep'],
    ['Diwali is known as the festival of?', 'Lights', 'Water', 'Snow', 'Sand'],
    ['A church is a place of worship for?', 'Christians', 'Hindus', 'Buddhists', 'Sikhs'],
    ['Hanukkah is celebrated by?', 'Jewish people', 'Muslims', 'Buddhists', 'Hindus'],
    ['What color is often linked with Islam?', 'Green', 'Red', 'Purple', 'Orange'],
    ['A synagogue is a holy place for?', 'Jewish people', 'Muslims', 'Hindus', 'Buddhists'],
    ['Who is baby Jesus\'s mother?', 'Mary', 'Sarah', 'Ruth', 'Hannah'],
    ['The star and crescent is a symbol of?', 'Islam', 'Christianity', 'Buddhism', 'Judaism'],
    ['A temple is used for worship in?', 'Hinduism', 'Only Islam', 'Only Judaism', 'Only Sikhism'],
    ['Muslims fast during which month?', 'Ramadan', 'December', 'March', 'July'],
    ['The cross is a symbol of?', 'Christianity', 'Islam', 'Buddhism', 'Hinduism'],
    ['What holiday celebrates Jesus\'s birth?', 'Christmas', 'Easter', 'Diwali', 'Eid'],
    ['Buddha taught people to be?', 'Kind and peaceful', 'Angry', 'Greedy', 'Selfish'],
    ['Ganesha has the head of an?', 'Elephant', 'Lion', 'Eagle', 'Fish'],
    ['On Eid children often receive?', 'Gifts and sweets', 'Homework', 'Punishments', 'Nothing'],
    ['A Buddhist monk often wears a robe of?', 'Orange or saffron', 'Black leather', 'Silver', 'Gold armor'],
    ['What animal is sacred to Hindus?', 'Cow', 'Cat', 'Dog', 'Parrot'],
    ['Christmas trees are decorated with?', 'Ornaments and lights', 'Food only', 'Rocks', 'Shoes'],
    ['Prayer beads are used in?', 'Many religions', 'No religions', 'Only cooking', 'Only sports'],
    ['Noah built a big?', 'Ark (boat)', 'Car', 'Plane', 'House'],
    ['Easter celebrates what event?', 'Jesus rising from the dead', 'Harvest', 'New Year', 'Fasting'],
    ['The word "Bible" means?', 'Book', 'Water', 'Fire', 'Stone'],
    ['A menorah is used in?', 'Judaism', 'Islam', 'Buddhism', 'Hinduism'],
    ['Karma means your actions have?', 'Consequences', 'No effect', 'Only good results', 'Nothing'],
    ['A guru is a?', 'Teacher or guide', 'Weapon', 'Building', 'Animal'],
    ['Sikhs wear a turban called a?', 'Dastar', 'Fedora', 'Beret', 'Sombrero'],
    ['What is a pilgrimage?', 'A religious journey', 'A type of food', 'A dance', 'A game'],
    ['Angels are found in stories of?', 'Many religions', 'No religions', 'Only science', 'Only math'],
    ['Incense is often burned during?', 'Worship and prayer', 'Cooking meals', 'Playing sports', 'Driving'],
    ['A priest works in a?', 'Church', 'Gym', 'Factory', 'Stadium'],
    ['The Torah is written in?', 'Hebrew', 'French', 'Spanish', 'German'],
    ['Buddhists meditate to find?', 'Inner peace', 'Treasure', 'Food', 'Toys'],
    ['A stupa is a Buddhist?', 'Monument or shrine', 'Vehicle', 'Weapon', 'Animal'],
    ['The Golden Temple is holy to?', 'Sikhs', 'Christians', 'Buddhists only', 'Muslims only'],
    ['What shape is the Star of David?', 'Six-pointed star', 'Circle', 'Square', 'Triangle'],
    ['Eid al-Fitr marks the end of?', 'Ramadan fasting', 'Winter', 'Summer', 'School'],
    ['Monks live in a?', 'Monastery', 'Shopping mall', 'Airport', 'Stadium'],
    ['A hymn is a religious?', 'Song', 'Dance', 'Painting', 'Sculpture'],
    ['What is frankincense?', 'A fragrant resin', 'A metal', 'A fruit', 'A fish'],
    ['Vesak celebrates the life of?', 'Buddha', 'Zeus', 'Thor', 'Poseidon'],
    ['Lakshmi is the Hindu goddess of?', 'Wealth and fortune', 'War', 'Thunder', 'Ocean'],
    ['A minaret is a tall tower on a?', 'Mosque', 'Castle', 'School', 'Bank'],
    ['Prayer mats are commonly used by?', 'Muslims', 'Only swimmers', 'Only runners', 'Only chefs'],
    ['Langar is a free community meal in?', 'Sikhism', 'Only Judaism', 'Only Buddhism', 'Only Shinto'],
    ['Baptism uses?', 'Water', 'Fire', 'Sand', 'Rocks'],
    ['The Quran was revealed to Prophet?', 'Muhammad (PBUH)', 'Ibrahim', 'Musa', 'Isa'],
    ['Bells are rung in many?', 'Churches and temples', 'Oceans', 'Deserts', 'Forests'],
    ['Who is the founder of Buddhism?', 'Siddhartha Gautama', 'Confucius', 'Laozi', 'Guru Nanak'],
    ['A rosary is used for?', 'Counting prayers', 'Counting money', 'Counting steps', 'Counting days'],
  ],
  2: [
    ['The Bible has two main parts called?', 'Old and New Testament', 'Volume 1 and 2', 'Part A and B', 'Top and Bottom'],
    ['Vishnu is a major god in?', 'Hinduism', 'Christianity', 'Judaism', 'Shinto'],
    ['The story of Rama is told in the?', 'Ramayana', 'Bible', 'Quran', 'Torah'],
    ['In Norse mythology, who is king of gods?', 'Odin', 'Zeus', 'Ra', 'Vishnu'],
    ['What is the holy book of Sikhism?', 'Guru Granth Sahib', 'Bible', 'Quran', 'Torah'],
    ['Lent is a 40-day period before?', 'Easter', 'Christmas', 'Diwali', 'Eid'],
    ['Shiva is known as the destroyer in?', 'Hinduism', 'Greek mythology', 'Norse mythology', 'Roman mythology'],
    ['A totem pole is important to?', 'Indigenous peoples', 'Only Buddhists', 'Only Muslims', 'Only Jews'],
    ['What is a parable?', 'A teaching story', 'A type of boat', 'A song', 'A weapon'],
    ['Passover is a festival in?', 'Judaism', 'Islam', 'Hinduism', 'Buddhism'],
    ['The Tripitaka is a sacred text of?', 'Buddhism', 'Judaism', 'Christianity', 'Islam'],
    ['Brahma is the creator god in?', 'Hinduism', 'Christianity', 'Islam', 'Greek mythology'],
    ['An imam leads prayers in?', 'Islam', 'Christianity', 'Judaism', 'Sikhism'],
    ['The lotus flower is sacred in?', 'Buddhism and Hinduism', 'Only Christianity', 'Only Islam', 'Only Judaism'],
    ['Good Friday remembers Jesus\'s?', 'Crucifixion', 'Birth', 'Baptism', 'Wedding'],
    ['What does "hallelujah" mean?', 'Praise God', 'Goodbye', 'Sorry', 'Thank you'],
    ['Ganesh Chaturthi celebrates?', 'Lord Ganesha', 'Lord Shiva', 'Lord Vishnu', 'Lord Brahma'],
    ['A cathedral is a large?', 'Church', 'Mosque', 'Temple', 'Synagogue'],
    ['Confucius was a teacher from?', 'China', 'Egypt', 'Greece', 'Rome'],
    ['The Talmud is studied in?', 'Judaism', 'Islam', 'Hinduism', 'Buddhism'],
    ['What is a sacred river in Hinduism?', 'The Ganges', 'The Thames', 'The Nile', 'The Amazon'],
    ['Navaratri lasts for how many nights?', 'Nine', 'Three', 'Five', 'Seven'],
    ['A dreidel is a spinning top used during?', 'Hanukkah', 'Easter', 'Diwali', 'Eid'],
    ['John the Baptist baptized?', 'Jesus', 'Moses', 'Abraham', 'David'],
    ['In Hinduism, the soul is called?', 'Atman', 'Karma', 'Dharma', 'Moksha'],
    ['A prophet speaks?', 'God\'s message', 'Only jokes', 'Only songs', 'Only recipes'],
    ['Ash Wednesday marks the start of?', 'Lent', 'Advent', 'Easter week', 'Pentecost'],
    ['Sukkot involves building a?', 'Temporary shelter', 'Stone castle', 'Iron bridge', 'Glass tower'],
    ['Meditation is practiced in?', 'Many religions', 'No religions', 'Only in sports', 'Only in school'],
    ['The story of David and Goliath is in?', 'The Bible', 'The Quran only', 'The Vedas', 'The Tripitaka'],
    ['Muharram is the first month of the?', 'Islamic calendar', 'Gregorian calendar', 'Hindu calendar', 'Jewish calendar'],
    ['A puja is a Hindu?', 'Prayer ritual', 'Weapon', 'Vehicle', 'Dance move'],
    ['Rosh Hashanah is the Jewish?', 'New Year', 'Day of rest', 'Harvest festival', 'Wedding ceremony'],
    ['A mandala is a circular?', 'Design used in meditation', 'Weapon', 'Vehicle', 'Animal'],
    ['The Pope lives in?', 'Vatican City', 'London', 'Paris', 'Tokyo'],
    ['Samsara means the cycle of?', 'Birth and rebirth', 'Cooking', 'Swimming', 'Reading'],
    ['An altar is found in many?', 'Places of worship', 'Only kitchens', 'Only bedrooms', 'Only gardens'],
    ['Yom Kippur is a day of?', 'Fasting and atonement', 'Feasting only', 'Dancing only', 'Sports only'],
    ['The Mahabharata is an epic from?', 'India', 'Greece', 'Rome', 'Egypt'],
    ['Sabbath is a day of rest in?', 'Judaism and Christianity', 'Only Islam', 'Only Buddhism', 'Only Sikhism'],
    ['Advent is the period before?', 'Christmas', 'Easter', 'Pentecost', 'Lent'],
    ['Krishna is known for playing the?', 'Flute', 'Drum', 'Guitar', 'Trumpet'],
    ['Purim celebrates a rescue told in?', 'Book of Esther', 'Book of Genesis', 'Book of Psalms', 'Book of Job'],
    ['A pagoda is a tiered tower in?', 'East Asian traditions', 'European tradition', 'African tradition', 'South American'],
    ['Communion involves bread and?', 'Wine or grape juice', 'Milk', 'Soup', 'Honey'],
    ['Nirvana in Buddhism means?', 'End of suffering', 'A planet', 'A food', 'A country'],
    ['Palm Sunday involves?', 'Palm branches', 'Palm trees only', 'Only cooking', 'Only dancing'],
    ['Epiphany celebrates the visit of the?', 'Three Wise Men', 'Shepherds only', 'Angels only', 'Prophets only'],
    ['A conch shell is used in?', 'Hindu worship', 'Christian worship only', 'Jewish worship only', 'No worship'],
    ['Navratri celebrates the goddess?', 'Durga', 'Lakshmi only', 'Saraswati only', 'Parvati only'],
  ],
  3: [
    ['Zeus is the Greek god of?', 'Thunder and sky', 'The sea', 'The underworld', 'Wine'],
    ['Mount Olympus is home to gods in?', 'Greek mythology', 'Norse mythology', 'Egyptian mythology', 'Hindu mythology'],
    ['Thor is the Norse god of?', 'Thunder', 'Mischief', 'Wisdom', 'Beauty'],
    ['Anubis is the Egyptian god of?', 'The dead', 'The sun', 'The Nile', 'Farming'],
    ['Poseidon is the Greek god of?', 'The sea', 'Thunder', 'War', 'Wine'],
    ['Hades rules the Greek?', 'Underworld', 'Sky', 'Ocean', 'Forest'],
    ['In Norse myth, the world tree is?', 'Yggdrasil', 'Olympus', 'Eden', 'Babylon'],
    ['Medusa had snakes for?', 'Hair', 'Hands', 'Feet', 'Eyes'],
    ['Ra is the Egyptian god of?', 'The sun', 'The moon', 'The earth', 'The sea'],
    ['Hercules had to complete how many labors?', '12', '5', '10', '20'],
    ['The Minotaur lived in a?', 'Labyrinth', 'Castle', 'Forest', 'Mountain'],
    ['Loki is the Norse god of?', 'Mischief and trickery', 'Thunder', 'Wisdom', 'Beauty'],
    ['Athena is the Greek goddess of?', 'Wisdom and war', 'Love', 'Harvest', 'Moon'],
    ['Osiris is the Egyptian god of the?', 'Afterlife', 'Sun', 'Desert', 'River'],
    ['The Trojan War was fought over?', 'Helen of Troy', 'Gold only', 'Land only', 'Animals only'],
    ['Odin sacrificed his eye for?', 'Wisdom', 'Strength', 'Speed', 'Youth'],
    ['The Sphinx asks travelers a?', 'Riddle', 'Song', 'Dance', 'Recipe'],
    ['Apollo is the Greek god of?', 'Music and the sun', 'War', 'The sea', 'Death'],
    ['Isis is an Egyptian goddess of?', 'Magic and healing', 'War', 'Thunder', 'Chaos'],
    ['Freya is a Norse goddess of?', 'Love and beauty', 'Thunder', 'Mischief', 'Death'],
    ['Perseus slew?', 'Medusa', 'The Minotaur', 'The Hydra', 'Cerberus'],
    ['Artemis is the Greek goddess of?', 'The hunt and moon', 'Love', 'War', 'Wine'],
    ['Theseus defeated the?', 'Minotaur', 'Medusa', 'Hydra', 'Sphinx'],
    ['Hanuman in Hindu myth is a?', 'Monkey god', 'Fish god', 'Bird god', 'Snake god'],
    ['Ares is the Greek god of?', 'War', 'Peace', 'Harvest', 'The sea'],
    ['Fenrir is a giant wolf in?', 'Norse mythology', 'Greek mythology', 'Egyptian mythology', 'Hindu mythology'],
    ['The phoenix rises from?', 'Ashes', 'Water', 'Earth', 'Ice'],
    ['Pegasus is a winged?', 'Horse', 'Dog', 'Cat', 'Lion'],
    ['Aphrodite is the Greek goddess of?', 'Love and beauty', 'War', 'Wisdom', 'The hunt'],
    ['The Norse rainbow bridge is called?', 'Bifrost', 'Asgard', 'Valhalla', 'Midgard'],
    ['Cerberus guards the entrance to?', 'The Greek underworld', 'Asgard', 'Mount Olympus', 'Egypt'],
    ['Horus has the head of a?', 'Falcon', 'Jackal', 'Cat', 'Crocodile'],
    ['Dionysus is the Greek god of?', 'Wine and festivity', 'War', 'Wisdom', 'The sun'],
    ['Mjolnir is the hammer of?', 'Thor', 'Odin', 'Loki', 'Freya'],
    ['A Cyclops has how many eyes?', 'One', 'Two', 'Three', 'Four'],
    ['The Hydra regrew how many heads per cut?', 'Two', 'One', 'Three', 'Five'],
    ['The Golden Fleece was sought by?', 'Jason and the Argonauts', 'Hercules', 'Achilles', 'Odysseus'],
    ['Bastet is an Egyptian goddess with a?', 'Cat head', 'Falcon head', 'Snake head', 'Jackal head'],
    ['Valkyries chose warriors for?', 'Valhalla', 'Olympus', 'The pyramids', 'The Nile'],
    ['Demeter is the Greek goddess of?', 'Harvest and grain', 'War', 'The sea', 'The moon'],
    ['Aztec mythology includes the god?', 'Quetzalcoatl', 'Zeus', 'Odin', 'Vishnu'],
    ['Pan is the Greek god of?', 'The wild and shepherds', 'The ocean', 'Thunder', 'The dead'],
    ['Asgard is the home of gods in?', 'Norse mythology', 'Greek mythology', 'Egyptian mythology', 'Roman mythology'],
    ['Hermes is the Greek messenger?', 'God', 'King', 'Warrior', 'Farmer'],
    ['Anubis has the head of a?', 'Jackal', 'Cat', 'Falcon', 'Crocodile'],
    ['Chinese dragons symbolize?', 'Power and good fortune', 'Evil only', 'Laziness', 'Fear'],
    ['Hera is the Greek goddess of?', 'Marriage and family', 'War', 'The hunt', 'Wine'],
    ['The Vedas are the oldest scriptures of?', 'Hinduism', 'Buddhism', 'Christianity', 'Islam'],
    ['Ganesha is the Hindu remover of?', 'Obstacles', 'Mountains', 'Oceans', 'Forests'],
    ['Sobek is the Egyptian god with a?', 'Crocodile head', 'Cat head', 'Falcon head', 'Jackal head'],
  ],
  4: [
    ['Shinto is the traditional religion of?', 'Japan', 'China', 'India', 'Egypt'],
    ['The Bhagavad Gita is part of which epic?', 'Mahabharata', 'Ramayana', 'Iliad', 'Odyssey'],
    ['Confucianism originated in?', 'China', 'Japan', 'Korea', 'India'],
    ['Taoism teaches harmony with the?', 'Tao (the Way)', 'Stars', 'Ocean only', 'Mountains only'],
    ['The Odyssey tells the journey of?', 'Odysseus', 'Achilles', 'Hercules', 'Perseus'],
    ['Achilles had a famous weak spot on his?', 'Heel', 'Shoulder', 'Knee', 'Elbow'],
    ['Valhalla is the hall for fallen warriors in?', 'Norse mythology', 'Greek mythology', 'Egyptian mythology', 'Hindu mythology'],
    ['The Iliad describes events of the?', 'Trojan War', 'Persian War', 'Punic War', 'Gallic War'],
    ['The Parthenon was a temple for?', 'Athena', 'Zeus', 'Poseidon', 'Ares'],
    ['Jainism teaches extreme?', 'Non-violence (ahimsa)', 'Warfare', 'Wealth', 'Speed'],
    ['Shinto worship sites are called?', 'Shrines', 'Mosques', 'Churches', 'Cathedrals'],
    ['The Book of the Dead is from?', 'Ancient Egypt', 'Ancient Greece', 'Ancient Rome', 'Ancient China'],
    ['Pandora\'s box released?', 'All evils into the world', 'Only butterflies', 'Only gold', 'Only water'],
    ['Prometheus stole what from the gods?', 'Fire', 'Water', 'Gold', 'Fruit'],
    ['The Jade Emperor rules heaven in?', 'Chinese mythology', 'Greek mythology', 'Norse mythology', 'Hindu mythology'],
    ['Brahman in Hinduism is the?', 'Supreme cosmic power', 'A prayer bead', 'A holy river', 'A festival'],
    ['Aboriginal Dreamtime explains?', 'Creation of the world', 'Only cooking', 'Only farming', 'Only fishing'],
    ['Reincarnation is the belief of being?', 'Reborn after death', 'Immortal', 'Invisible', 'Frozen forever'],
    ['An oracle in ancient Greece gave?', 'Prophecies', 'Food', 'Weapons', 'Clothing'],
    ['Gilgamesh is a hero from?', 'Mesopotamia', 'Greece', 'Egypt', 'Rome'],
    ['A ziggurat was a temple in?', 'Mesopotamia', 'Greece', 'Rome', 'Japan'],
    ['Amaterasu is the sun goddess in?', 'Shinto mythology', 'Greek mythology', 'Norse mythology', 'Hindu mythology'],
    ['Myths often explain?', 'Natural phenomena', 'Only recipes', 'Only jokes', 'Only sports'],
    ['Mayan mythology includes the Popol?', 'Vuh', 'Veh', 'Van', 'Var'],
    ['Achilles was dipped in the River?', 'Styx', 'Nile', 'Thames', 'Ganges'],
    ['King Midas could turn things to?', 'Gold', 'Silver', 'Stone', 'Water'],
    ['Icarus flew too close to the?', 'Sun', 'Moon', 'Earth', 'Stars'],
    ['The Flood story appears in?', 'Many different cultures', 'Only one book', 'No cultures', 'Only modern times'],
    ['In Buddhism the Eightfold Path leads to?', 'Enlightenment', 'Wealth', 'Fame', 'Power'],
    ['Animism believes natural objects have?', 'Spirits', 'No value', 'Only color', 'Only weight'],
    ['The Dead Sea Scrolls contain?', 'Ancient Jewish texts', 'Greek plays', 'Roman laws', 'Chinese poems'],
    ['A torii gate marks the entrance to?', 'A Shinto shrine', 'A mosque', 'A church', 'A synagogue'],
    ['Yin and yang come from?', 'Chinese philosophy', 'Greek philosophy', 'Norse mythology', 'Egyptian mythology'],
    ['Celtic mythology includes fairy folk?', 'Sidhe', 'Olympians', 'Aesir', 'Devas'],
    ['Egyptian pharaohs were considered?', 'God-kings', 'Ordinary citizens', 'Only warriors', 'Only farmers'],
    ['The swastika was originally a?', 'Sacred symbol in many cultures', 'Modern invention', 'Greek letter', 'Egyptian tool'],
    ['A griot in West Africa is a?', 'Storyteller and historian', 'Warrior', 'Farmer', 'Fisher'],
    ['Ancestor worship is common in?', 'Many Asian and African cultures', 'No cultures', 'Only Europe', 'Only America'],
    ['The Avesta is the holy book of?', 'Zoroastrianism', 'Islam', 'Buddhism', 'Sikhism'],
    ['A rosary is used for counting?', 'Prayers', 'Money', 'Steps', 'Days'],
    ['Trickster figures appear in myths of?', 'Many cultures worldwide', 'Only Greek myth', 'Only Norse myth', 'Only one culture'],
    ['The lotus position is used in?', 'Meditation', 'Swimming', 'Running', 'Cooking'],
    ['Guru Nanak traveled widely to?', 'Spread his teachings', 'Find gold', 'Build castles', 'Race horses'],
    ['Hindu temples often have a?', 'Gopuram (tower)', 'Minaret', 'Steeple', 'Dome only'],
    ['Dervishes are associated with?', 'Sufi Islam', 'Buddhism', 'Hinduism', 'Sikhism'],
    ['Maori creation includes Sky Father and?', 'Earth Mother', 'Fire Brother', 'Ice Sister', 'Wind Son'],
    ['The labors of Hercules tested his?', 'Strength and courage', 'Cooking', 'Singing', 'Math'],
    ['Nirvana is the highest goal in?', 'Buddhism', 'Christianity', 'Judaism', 'Shinto'],
    ['The Aztecs sacrificed to the?', 'Sun god', 'Moon goddess only', 'Star king', 'Wind spirit only'],
    ['Sisyphus was punished by rolling a?', 'Boulder uphill forever', 'Ball of yarn', 'Wheel of cheese', 'Barrel of water'],
  ],
  5: [
    ['Zoroastrianism originated in?', 'Ancient Persia', 'Ancient Egypt', 'Ancient China', 'Ancient Greece'],
    ['Martin Luther started the?', 'Protestant Reformation', 'Olympic Games', 'Renaissance art', 'French Revolution'],
    ['The Crusades were fought over control of?', 'The Holy Land', 'The North Pole', 'The Amazon', 'Australia'],
    ['Sufism is a mystical tradition within?', 'Islam', 'Christianity', 'Buddhism', 'Sikhism'],
    ['The Epic of Gilgamesh comes from?', 'Mesopotamia', 'Rome', 'China', 'Aztec Empire'],
    ['The Pope is the head of the?', 'Catholic Church', 'Anglican Church', 'Orthodox Church', 'All churches'],
    ['Karma is central to?', 'Hinduism and Buddhism', 'Only Shinto', 'Only Judaism', 'Only Norse myth'],
    ['The Dalai Lama is a leader in?', 'Tibetan Buddhism', 'Shinto', 'Hinduism', 'Christianity'],
    ['Theravada and Mahayana are branches of?', 'Buddhism', 'Hinduism', 'Islam', 'Christianity'],
    ['The Tao Te Ching was written by?', 'Laozi (Lao Tzu)', 'Confucius', 'Buddha', 'Muhammad'],
    ['Orthodox Christianity split from Rome in?', '1054 AD', '500 BC', '1500 AD', '200 AD'],
    ['Sunni and Shia are branches of?', 'Islam', 'Christianity', 'Buddhism', 'Hinduism'],
    ['The Book of Mormon is sacred to?', 'Latter-day Saints', 'Catholics', 'Baptists', 'Anglicans'],
    ['The five Ks are symbols of?', 'Sikhism', 'Christianity', 'Islam', 'Buddhism'],
    ['A fatwa is a?', 'Islamic legal ruling', 'Hindu prayer', 'Buddhist chant', 'Jewish festival'],
    ['Shinto has no single?', 'Founder', 'Temple', 'Prayer', 'Festival'],
    ['The Baha\'i Faith originated in?', '19th century Persia', 'Ancient Greece', 'Medieval Europe', 'Ancient China'],
    ['Dharma in Hinduism means?', 'Duty and moral law', 'Food', 'Money', 'Sleep'],
    ['Calvinism emphasizes?', 'Predestination', 'Free will only', 'Reincarnation', 'Polytheism'],
    ['Purgatory is a concept in?', 'Catholicism', 'Buddhism', 'Hinduism', 'Shinto'],
    ['Rumi was a famous?', 'Sufi poet', 'Greek philosopher', 'Norse warrior', 'Egyptian pharaoh'],
    ['The Kabbalah is a mystical tradition in?', 'Judaism', 'Islam', 'Buddhism', 'Sikhism'],
    ['Ahimsa means?', 'Non-violence', 'Warfare', 'Strength', 'Speed'],
    ['Pentecost celebrates the coming of the?', 'Holy Spirit', 'Christ child', 'Angels', 'Prophets'],
    ['Confucius emphasized?', 'Filial piety and virtue', 'War', 'Isolation', 'Wealth above all'],
    ['A mantra is a?', 'Sacred phrase or sound', 'Weapon', 'Building', 'Animal'],
    ['Hajj takes place in the month of?', 'Dhul Hijjah', 'Ramadan', 'Muharram', 'Shawwal'],
    ['Moksha means liberation from?', 'The cycle of rebirth', 'Gravity', 'Sleep', 'Hunger'],
    ['Hasidic Judaism originated in?', 'Eastern Europe', 'Japan', 'Australia', 'South America'],
    ['The caste system is historically linked to?', 'Hinduism', 'Christianity', 'Islam', 'Buddhism'],
    ['Holi celebrates the victory of?', 'Good over evil', 'Night over day', 'Cold over heat', 'Salt over sugar'],
    ['Monasticism is found in?', 'Multiple religions', 'Only one religion', 'No religions', 'Only sports'],
    ['Shabbat begins at?', 'Sunset on Friday', 'Sunrise Monday', 'Noon Wednesday', 'Midnight Thursday'],
    ['The Analects are teachings of?', 'Confucius', 'Buddha', 'Laozi', 'Muhammad'],
    ['Liberation theology combines?', 'Faith and social justice', 'Only prayer', 'Only fasting', 'Only reading'],
    ['The Nicene Creed defines?', 'Christian beliefs', 'Jewish law', 'Hindu ritual', 'Buddhist practice'],
    ['Ancestor veneration is important in?', 'Many East Asian cultures', 'No cultures', 'Only modern West', 'Only Antarctica'],
    ['Saraswati is the Hindu goddess of?', 'Knowledge and arts', 'War', 'Death', 'Fire'],
    ['Sacred groves are natural worship sites in?', 'Many traditional religions', 'No religions', 'Only modern faiths', 'Only one country'],
    ['Eschatology studies?', 'End times and afterlife', 'Cooking methods', 'Music theory', 'Sports rules'],
    ['A mikveh is a ritual bath in?', 'Judaism', 'Islam', 'Buddhism', 'Sikhism'],
    ['The Reformation led to the rise of?', 'Protestant churches', 'The Roman Empire', 'Greek philosophy', 'Egyptian art'],
    ['Stained glass windows are common in?', 'Christian churches', 'Mosques', 'Buddhist temples', 'Shinto shrines'],
    ['Indigenous Australian religion includes?', 'Dreamtime stories', 'Greek myths', 'Norse sagas', 'Roman tales'],
    ['The Bhagavad Gita is a dialogue between?', 'Arjuna and Krishna', 'Rama and Sita', 'Shiva and Parvati', 'Brahma and Vishnu'],
    ['A minaret is used for?', 'The call to prayer', 'Storing food', 'Hanging bells', 'Displaying art'],
    ['Monks take vows of?', 'Poverty and obedience', 'Wealth', 'Fame', 'War'],
    ['Nirvana Day commemorates?', 'Buddha\'s passing', 'Jesus\'s birth', 'Muhammad\'s journey', 'Moses on Sinai'],
    ['The Eightfold Path belongs to?', 'Buddhism', 'Christianity', 'Islam', 'Judaism'],
    ['Ash Wednesday is practiced in?', 'Christianity', 'Buddhism', 'Hinduism', 'Shinto'],
  ],
  6: [
    ['Syncretism means the blending of?', 'Religious beliefs', 'Colors', 'Foods', 'Fabrics'],
    ['Monotheism is belief in?', 'One God', 'Many gods', 'No god', 'Nature spirits only'],
    ['Polytheism is belief in?', 'Many gods', 'One God', 'No god', 'Science only'],
    ['An allegory is a story with?', 'Hidden deeper meaning', 'No meaning', 'Only humor', 'Only facts'],
    ['Interfaith dialogue promotes?', 'Understanding between religions', 'Competition', 'War', 'Isolation'],
    ['Secularism separates?', 'Religion and government', 'Food and drink', 'Art and music', 'Sports and games'],
    ['Hermeneutics is the study of?', 'Interpretation of texts', 'Animal behavior', 'Weather patterns', 'Cooking'],
    ['Gnosticism claimed hidden?', 'Spiritual knowledge', 'Recipes', 'Maps', 'Weapons'],
    ['The Dead Sea Scrolls date to around?', '2000 years ago', '200 years ago', '20 years ago', '5000 years ago'],
    ['Iconoclasm is the destruction of?', 'Religious images', 'Food', 'Clothing', 'Furniture'],
    ['Theodicy asks why?', 'Evil exists if God is good', 'The sky is blue', 'Water is wet', 'Fire is hot'],
    ['Pantheism believes God is?', 'Everything in nature', 'Only in temples', 'Only in churches', 'Only in mosques'],
    ['Agnosticism holds that God\'s existence is?', 'Unknown or unknowable', 'Certain', 'Impossible', 'Irrelevant'],
    ['Comparative religion studies?', 'Similarities across faiths', 'Only one faith', 'Only myths', 'Only modern beliefs'],
    ['A schism is a?', 'Split within a religion', 'Merger of religions', 'A prayer', 'A festival'],
    ['Ecumenism promotes?', 'Unity among Christians', 'Division', 'Competition', 'Isolation'],
    ['Deism believes God created but does not?', 'Intervene in the world', 'Exist', 'Matter', 'Sleep'],
    ['Mysticism seeks direct?', 'Experience of the divine', 'Food', 'Money', 'Fame'],
    ['Proselytizing means trying to?', 'Convert others', 'Cook food', 'Build houses', 'Play sports'],
    ['Liturgy refers to?', 'Formal public worship', 'Private meditation', 'Silent reading', 'Secret prayer'],
    ['Soteriology studies?', 'Salvation and deliverance', 'Animals', 'Stars', 'Rocks'],
    ['A creation myth explains?', 'How the world began', 'Only cooking', 'Only building', 'Only painting'],
    ['Dualism sees the universe as?', 'Two opposing forces', 'One force', 'No forces', 'Random chaos'],
    ['Immanence means God is?', 'Present within the world', 'Far away only', 'Nonexistent', 'Sleeping'],
    ['Transcendence means God is?', 'Beyond the physical world', 'Only physical', 'Only visible', 'Only material'],
    ['Covenant is a sacred?', 'Agreement or bond', 'Weapon', 'Animal', 'Building'],
    ['Dogma refers to?', 'Established religious beliefs', 'Scientific theories', 'Math formulas', 'Cooking recipes'],
    ['A sacrament is a?', 'Sacred rite in Christianity', 'Hindu festival', 'Buddhist chant', 'Islamic pilgrimage'],
    ['The Upanishads explore?', 'Hindu philosophical concepts', 'Greek drama', 'Norse battle', 'Egyptian farming'],
    ['Talmudic debate involves?', 'Rigorous textual analysis', 'Only singing', 'Only dancing', 'Only cooking'],
    ['Canon law governs?', 'The Catholic Church', 'Only governments', 'Only armies', 'Only schools'],
    ['Apostolic succession traces?', 'Leadership from apostles', 'Trade routes', 'Family recipes', 'Musical scores'],
    ['Jihad primarily means?', 'Inner spiritual struggle', 'Only warfare', 'Only peace', 'Only prayer'],
    ['Theosophy blends?', 'Eastern and Western spirituality', 'Only cooking', 'Only farming', 'Only mining'],
    ['The Baha\'i Faith emphasizes?', 'Unity of all religions', 'Only one religion', 'No religions', 'Anti-religion'],
    ['A hagiography is a story of?', 'A saint\'s life', 'A villain', 'A scientist', 'A politician'],
    ['Midrash is a Jewish method of?', 'Interpreting scripture', 'Cooking food', 'Building houses', 'Making clothes'],
    ['Catechism teaches?', 'Principles of Christian faith', 'Math', 'Science', 'Geography'],
    ['A reliquary holds?', 'Sacred relics', 'Food', 'Weapons', 'Tools'],
    ['Dharma in Buddhism means?', 'The Buddha\'s teachings', 'Money', 'Power', 'Fame'],
    ['Penance involves?', 'Atonement for sins', 'Celebration', 'Feasting', 'Dancing'],
    ['A cosmogony describes the?', 'Origin of the universe', 'End of time', 'Middle ages', 'Future only'],
    ['Asceticism involves?', 'Self-denial for spiritual growth', 'Self-indulgence', 'Laziness', 'Excess'],
    ['Theocracy is government by?', 'Religious authority', 'Military', 'Scientists', 'Athletes'],
    ['Pluralism accepts?', 'Multiple beliefs coexisting', 'Only one belief', 'No beliefs', 'Forced conversion'],
    ['Apologetics is the defense of?', 'Religious doctrine', 'Sports teams', 'Political parties', 'Science only'],
    ['Predestination holds that God has?', 'Already determined events', 'No plans', 'Only good plans', 'No knowledge'],
    ['Animism holds that natural objects have?', 'Spiritual essence', 'No value', 'Only weight', 'Only color'],
    ['Theocentric means centered on?', 'God', 'Humans', 'Nature', 'Science'],
    ['An eschatological view concerns?', 'The end of the world', 'The beginning only', 'The middle only', 'Nothing'],
  ],
};

export const science: Record<number, Fact[]> = {
  1: [
    ['How many legs does a spider have?', '8', '6', '4', '10'],
    ['What falls from clouds when it rains?', 'Water drops', 'Rocks', 'Sand', 'Leaves'],
    ['A baby dog is called a?', 'Puppy', 'Kitten', 'Calf', 'Foal'],
    ['We breathe in?', 'Oxygen', 'Carbon dioxide', 'Nitrogen only', 'Helium'],
    ['The sun gives us?', 'Light and heat', 'Only cold', 'Only darkness', 'Only rain'],
    ['A caterpillar becomes a?', 'Butterfly', 'Fish', 'Bird', 'Frog'],
    ['How many seasons are there?', '4', '2', '6', '8'],
    ['Plants need sunlight, water, and?', 'Soil', 'Candy', 'Plastic', 'Metal'],
    ['We hear with our?', 'Ears', 'Eyes', 'Nose', 'Hands'],
    ['What covers most of Earth\'s surface?', 'Water', 'Sand', 'Ice only', 'Lava'],
    ['Baby cats are called?', 'Kittens', 'Puppies', 'Cubs', 'Chicks'],
    ['Leaves on trees are usually?', 'Green', 'Blue', 'Always red', 'Always purple'],
    ['A fish breathes using?', 'Gills', 'Lungs', 'Nose', 'Mouth only'],
    ['We see with our?', 'Eyes', 'Ears', 'Tongue', 'Skin'],
    ['The moon shines at?', 'Night', 'Only morning', 'Only noon', 'Only afternoon'],
    ['Ice is?', 'Frozen water', 'Frozen milk', 'Frozen juice', 'Frozen oil'],
    ['A hen lays?', 'Eggs', 'Milk', 'Honey', 'Wool'],
    ['We smell with our?', 'Nose', 'Ears', 'Feet', 'Hands'],
    ['Which animal says "moo"?', 'Cow', 'Dog', 'Cat', 'Horse'],
    ['Clouds are made of?', 'Tiny water droplets', 'Dust only', 'Smoke only', 'Cotton'],
    ['Baby chickens are called?', 'Chicks', 'Puppies', 'Kittens', 'Lambs'],
    ['How many fingers do most people have?', '10', '8', '12', '6'],
    ['The Earth goes around the?', 'Sun', 'Moon', 'Stars', 'Mars'],
    ['A snowflake is made of?', 'Ice crystals', 'Sand', 'Dust', 'Salt'],
    ['Flowers can be?', 'Many different colors', 'Only white', 'Only red', 'Only blue'],
    ['We taste with our?', 'Tongue', 'Nose', 'Ears', 'Eyes'],
    ['What is a baby horse called?', 'Foal', 'Puppy', 'Kitten', 'Cub'],
    ['Trees give us?', 'Oxygen and shade', 'Only noise', 'Only heat', 'Only sand'],
    ['Bees make?', 'Honey', 'Milk', 'Cheese', 'Butter'],
    ['A tadpole grows into a?', 'Frog', 'Fish', 'Bird', 'Snake'],
    ['The bones in your body form the?', 'Skeleton', 'Muscles', 'Skin', 'Blood'],
    ['How many eyes do most people have?', '2', '1', '3', '4'],
    ['What makes a rainbow?', 'Sunlight and rain', 'Only wind', 'Only clouds', 'Only snow'],
    ['Which is hotter: the sun or the moon?', 'The sun', 'The moon', 'They are the same', 'Neither'],
    ['A magnet can attract?', 'Iron and steel', 'Wood', 'Plastic', 'Glass'],
    ['What do cows give us?', 'Milk', 'Eggs', 'Honey', 'Wool'],
    ['Dinosaurs lived?', 'A very long time ago', 'Last year', 'Last week', 'Yesterday'],
    ['Rain comes from?', 'Clouds', 'The ground', 'Trees', 'Rocks'],
    ['Insects have how many legs?', '6', '4', '8', '2'],
    ['What protects your brain?', 'Your skull', 'Your ribs', 'Your knee', 'Your elbow'],
    ['A seed grows into a?', 'Plant', 'Rock', 'Cloud', 'Star'],
    ['Sharks live in the?', 'Ocean', 'Desert', 'Forest', 'Mountains'],
    ['The Earth spins causing?', 'Day and night', 'Only rain', 'Only wind', 'Only clouds'],
    ['Frogs can live in water and on?', 'Land', 'Only in water', 'Only in air', 'Only underground'],
    ['Penguins are birds that cannot?', 'Fly', 'Swim', 'Walk', 'Eat'],
    ['We need food for?', 'Energy', 'Only taste', 'Only fun', 'Only smell'],
    ['What body part pumps blood?', 'The heart', 'The brain', 'The lungs', 'The stomach'],
    ['Wool comes from?', 'Sheep', 'Cows', 'Chickens', 'Pigs'],
    ['Which sense helps you feel hot and cold?', 'Touch', 'Sight', 'Hearing', 'Smell'],
    ['Stars look tiny because they are very?', 'Far away', 'Small', 'Cold', 'New'],
  ],
  2: [
    ['The planet closest to the sun is?', 'Mercury', 'Venus', 'Earth', 'Mars'],
    ['What force pulls things down to Earth?', 'Gravity', 'Magnetism', 'Electricity', 'Wind'],
    ['Water boils at what temperature?', '100°C', '50°C', '200°C', '0°C'],
    ['Solid, liquid, and gas are states of?', 'Matter', 'Energy', 'Light', 'Sound'],
    ['Plants give off which gas?', 'Oxygen', 'Carbon dioxide', 'Helium', 'Neon'],
    ['How many senses do humans have?', '5', '3', '7', '10'],
    ['Ice is water in which state?', 'Solid', 'Liquid', 'Gas', 'Plasma'],
    ['The sun is actually a?', 'Star', 'Planet', 'Moon', 'Comet'],
    ['Mars is called the?', 'Red Planet', 'Blue Planet', 'Green Planet', 'Yellow Planet'],
    ['The largest planet in our solar system is?', 'Jupiter', 'Saturn', 'Neptune', 'Mars'],
    ['What gas do humans breathe out?', 'Carbon dioxide', 'Oxygen', 'Helium', 'Nitrogen only'],
    ['An herbivore eats only?', 'Plants', 'Meat', 'Rocks', 'Sand'],
    ['A carnivore eats only?', 'Meat', 'Plants', 'Sunlight', 'Rocks'],
    ['An omnivore eats?', 'Both plants and meat', 'Only plants', 'Only meat', 'Only insects'],
    ['How many planets are in our solar system?', '8', '7', '9', '10'],
    ['What is Earth\'s natural satellite?', 'The Moon', 'Mars', 'The Sun', 'Venus'],
    ['Steam is water in which state?', 'Gas', 'Solid', 'Liquid', 'Plasma'],
    ['Roots help a plant get?', 'Water and nutrients', 'Sunlight', 'Air only', 'Nothing'],
    ['A thermometer measures?', 'Temperature', 'Weight', 'Length', 'Speed'],
    ['Earth\'s surface is mostly covered by?', 'Oceans', 'Deserts', 'Forests', 'Ice'],
    ['Rocks are?', 'Hard and made of minerals', 'Soft like cotton', 'Living things', 'Made of air'],
    ['A compass needle points?', 'North', 'South', 'East', 'West'],
    ['Lightning is a form of?', 'Electricity', 'Water', 'Air', 'Soil'],
    ['Sound needs a medium like?', 'Air or water', 'Vacuum', 'Only metal', 'Only glass'],
    ['Saturn is famous for its?', 'Rings', 'Red color', 'Blue oceans', 'Green forests'],
    ['Mammals feed their babies?', 'Milk', 'Seeds', 'Water only', 'Sunlight'],
    ['Reptiles are usually?', 'Cold-blooded', 'Warm-blooded', 'Made of water', 'Made of air'],
    ['Birds have?', 'Feathers', 'Fur', 'Scales only', 'Fins'],
    ['The biggest land animal is the?', 'Elephant', 'Giraffe', 'Hippo', 'Rhino'],
    ['The largest animal ever is the?', 'Blue whale', 'Elephant', 'Shark', 'T-Rex'],
    ['Evaporation turns liquid into?', 'Gas', 'Solid', 'Plasma', 'Nothing'],
    ['Condensation turns gas into?', 'Liquid', 'Solid', 'Plasma', 'Nothing'],
    ['A rainbow has how many main colors?', '7', '3', '5', '10'],
    ['Bamboo is the fastest growing?', 'Plant', 'Animal', 'Rock', 'Mineral'],
    ['Chameleons can change their?', 'Color', 'Size', 'Shape', 'Weight'],
    ['Dolphins are actually?', 'Mammals', 'Fish', 'Reptiles', 'Birds'],
    ['Bats are the only mammals that can?', 'Fly', 'Swim', 'Run fast', 'Climb'],
    ['Venus is the hottest planet because of?', 'Its thick atmosphere', 'Being closest to sun', 'Its rings', 'Its moons'],
    ['Earth\'s core is mostly made of?', 'Iron and nickel', 'Water', 'Air', 'Sand'],
    ['A food chain shows how?', 'Energy passes between things', 'Clouds form', 'Rocks break', 'Wind blows'],
    ['Amphibians can live in water and on?', 'Land', 'Only water', 'Only air', 'Only underground'],
    ['Butterflies taste with their?', 'Feet', 'Tongue', 'Wings', 'Eyes'],
    ['An octopus has how many arms?', '8', '6', '10', '4'],
    ['Camels store fat in their?', 'Humps', 'Legs', 'Tail', 'Ears'],
    ['A group of fish is called a?', 'School', 'Herd', 'Flock', 'Pack'],
    ['Hibernation means?', 'Long winter sleep', 'Summer activity', 'Spring cleaning', 'Autumn eating'],
    ['Migration means animals?', 'Travel long distances', 'Stay in one place', 'Sleep', 'Eat more'],
    ['The water cycle includes evaporation and?', 'Condensation', 'Radiation', 'Reflection', 'Absorption only'],
    ['Fossils are remains of?', 'Ancient living things', 'Modern buildings', 'Clouds', 'Rainbows'],
    ['The atmosphere is the?', 'Layer of air around Earth', 'Layer of water', 'Layer of rock', 'Layer of fire'],
  ],
  3: [
    ['Photosynthesis is how plants make?', 'Food using sunlight', 'Animals', 'Rocks', 'Clouds'],
    ['Sound travels fastest through?', 'Solids', 'Gases', 'Vacuums', 'Space'],
    ['Friction creates?', 'Heat', 'Cold', 'Vacuum', 'Darkness'],
    ['Dinosaurs went extinct about?', '66 million years ago', '1000 years ago', '100 years ago', '1 million years ago'],
    ['A frog is an?', 'Amphibian', 'Reptile', 'Mammal', 'Fish'],
    ['Magnets attract?', 'Iron and steel', 'Wood', 'Plastic', 'Glass'],
    ['Your skeleton has about how many bones?', '206', '100', '50', '500'],
    ['The three rock types are igneous, sedimentary and?', 'Metamorphic', 'Magnetic', 'Electric', 'Liquid'],
    ['The water cycle ends with?', 'Precipitation', 'Magnetism', 'Gravity only', 'Electricity'],
    ['A habitat is where an animal?', 'Naturally lives', 'Is built', 'Is written about', 'Is sung about'],
    ['Volcanoes release?', 'Lava and ash', 'Only water', 'Only ice', 'Only air'],
    ['Earthquakes happen when?', 'Tectonic plates shift', 'Clouds crash', 'Stars fall', 'Wind stops'],
    ['The Amazon rainforest is known for?', 'Biodiversity', 'Only sand', 'Only ice', 'Only rocks'],
    ['Chlorophyll makes plants?', 'Green', 'Blue', 'Red', 'Purple'],
    ['Vertebrates have a?', 'Backbone', 'No bones', 'Shells only', 'Wings only'],
    ['Invertebrates do not have a?', 'Backbone', 'Heart', 'Eyes', 'Legs'],
    ['Light travels faster than?', 'Sound', 'Nothing', 'Gravity', 'Magnetism'],
    ['A food web shows?', 'Many connected food chains', 'Only one animal', 'Only water flow', 'Only air flow'],
    ['Soil is made of?', 'Minerals and organic matter', 'Only rocks', 'Only sand', 'Only clay'],
    ['The Sahara is a large?', 'Desert', 'Ocean', 'Forest', 'Mountain range'],
    ['Stalactites hang from?', 'Cave ceilings', 'Cave floors', 'Trees', 'Clouds'],
    ['The ozone layer protects us from?', 'UV radiation', 'Only rain', 'Only wind', 'Only cold'],
    ['A pulley is a simple?', 'Machine', 'Animal', 'Plant', 'Mineral'],
    ['Gears help transfer?', 'Motion and force', 'Water', 'Air only', 'Heat only'],
    ['The tongue can detect umami which is?', 'Savory taste', 'Spicy taste', 'Cold taste', 'Dry taste'],
    ['A balanced diet includes proteins, carbs and?', 'Fats and vitamins', 'Only sugar', 'Only water', 'Only salt'],
    ['Metamorphosis means?', 'Body transformation', 'No change', 'Growing bigger only', 'Shrinking'],
    ['Coral reefs are built by tiny?', 'Animals (coral polyps)', 'Rocks only', 'Plants only', 'Bacteria only'],
    ['Decomposers break down?', 'Dead organic matter', 'Living animals', 'Rocks', 'Metal'],
    ['Fungi include mushrooms and?', 'Mold', 'Fish', 'Birds', 'Mammals'],
    ['Conductors allow electricity to?', 'Flow through them', 'Stop completely', 'Freeze', 'Evaporate'],
    ['Insulators block?', 'Electricity flow', 'Food', 'Water always', 'Sound always'],
    ['A lever helps?', 'Lift heavy objects', 'Cook food', 'Play music', 'Read books'],
    ['Erosion wears away land by?', 'Wind or water', 'Sleeping', 'Cooking', 'Singing'],
    ['Weathering breaks rocks through?', 'Natural processes', 'Cooking', 'Painting', 'Singing'],
    ['A compass works because Earth is a?', 'Giant magnet', 'Giant bubble', 'Giant balloon', 'Giant wheel'],
    ['Renewable resources can be?', 'Replaced naturally', 'Used only once', 'Never used', 'Found in space only'],
    ['Non-renewable resources will eventually?', 'Run out', 'Grow forever', 'Come from space', 'Create themselves'],
    ['A producer in a food chain is usually a?', 'Plant', 'Predator', 'Scavenger', 'Decomposer'],
    ['A consumer eats?', 'Other organisms', 'Sunlight', 'Rocks', 'Air'],
    ['Photosynthesis needs sunlight, water, and?', 'Carbon dioxide', 'Oxygen', 'Nitrogen only', 'Helium'],
    ['Photosynthesis produces oxygen and?', 'Glucose (sugar)', 'Salt', 'Metal', 'Acid'],
    ['The heart pumps?', 'Blood', 'Air', 'Water', 'Food'],
    ['Lungs help us?', 'Breathe', 'Digest', 'See', 'Hear'],
    ['The stomach helps?', 'Digest food', 'Pump blood', 'Think', 'See'],
    ['Red blood cells carry?', 'Oxygen', 'Carbon dioxide only', 'Food only', 'Water only'],
    ['White blood cells fight?', 'Infections', 'Only cold', 'Only heat', 'Only hunger'],
    ['Teeth help us?', 'Chew food', 'Hear sounds', 'See things', 'Smell flowers'],
    ['The small intestine absorbs?', 'Nutrients', 'Only water', 'Only air', 'Only salt'],
    ['Muscles help us?', 'Move', 'Only sleep', 'Only eat', 'Only breathe'],
  ],
  4: [
    ['Vaccines help the body build?', 'Immunity', 'Gravity', 'Friction', 'Magnetism'],
    ['A hypothesis is a?', 'Testable prediction', 'Final fact', 'Wild guess', 'Proven law'],
    ['The largest organ of the human body is?', 'Skin', 'Liver', 'Brain', 'Heart'],
    ['Earth revolves around the Sun in about?', '365 days', '30 days', '7 days', '100 days'],
    ['Saturn is famous for its beautiful?', 'Rings', 'Red spot', 'Blue color', 'Green surface'],
    ['Evaporation turns liquid water into?', 'Water vapor', 'Ice', 'Rock', 'Sand'],
    ['A food chain starts with?', 'Producers (plants)', 'Predators', 'Humans', 'Fungi'],
    ['A thermometer measures?', 'Temperature', 'Weight', 'Speed', 'Distance'],
    ['The nervous system is controlled by the?', 'Brain', 'Stomach', 'Feet', 'Skin'],
    ['The circulatory system moves?', 'Blood through the body', 'Food only', 'Air only', 'Water only'],
    ['The respiratory system helps us?', 'Breathe', 'Digest', 'Move', 'Think only'],
    ['The digestive system breaks down?', 'Food for energy', 'Only water', 'Only air', 'Only light'],
    ['Tides are caused mainly by?', 'The Moon\'s gravity', 'The Sun\'s color', 'Wind only', 'Rain only'],
    ['Earthquakes are measured on the?', 'Richter scale', 'Fahrenheit scale', 'Celsius scale', 'pH scale'],
    ['Fossils help scientists learn about?', 'Ancient life', 'Future weather', 'Current music', 'Modern art'],
    ['Common cloud types include cirrus, stratus and?', 'Cumulus', 'Nimbus only', 'Fog only', 'Mist only'],
    ['The water table is the level of?', 'Underground water', 'Ocean surface', 'Cloud height', 'Mountain peak'],
    ['Kinetic energy is energy of?', 'Motion', 'Rest', 'Color', 'Sound only'],
    ['Potential energy is?', 'Stored energy', 'Lost energy', 'Destroyed energy', 'Created energy'],
    ['Electricity flows through a?', 'Circuit', 'Vacuum', 'Empty space', 'Water always'],
    ['A battery converts chemical energy to?', 'Electrical energy', 'Only heat', 'Only light', 'Only sound'],
    ['Solar panels convert sunlight to?', 'Electricity', 'Water', 'Food', 'Air'],
    ['Wind turbines convert wind to?', 'Electricity', 'Water', 'Heat', 'Sound'],
    ['The Moon orbits Earth in about?', '27-28 days', '365 days', '7 days', '1 day'],
    ['Ecosystems include living and?', 'Non-living things', 'Only animals', 'Only plants', 'Only water'],
    ['A biome is a large area with similar?', 'Climate and life', 'Only buildings', 'Only roads', 'Only parks'],
    ['The tundra biome is very?', 'Cold and treeless', 'Hot and dry', 'Warm and wet', 'Mild and green'],
    ['Tropical rainforests are?', 'Warm and very wet', 'Cold and dry', 'Snowy', 'Desert-like'],
    ['Density measures mass per?', 'Volume', 'Color', 'Temperature', 'Speed'],
    ['Speed is distance divided by?', 'Time', 'Weight', 'Height', 'Width'],
    ['Transparent materials let light?', 'Pass through', 'Stop completely', 'Bend always', 'Absorb all'],
    ['Opaque materials?', 'Block light', 'Let all light through', 'Bend light only', 'Create light'],
    ['A prism separates white light into?', 'A spectrum of colors', 'Only white', 'Only black', 'Only gray'],
    ['Reflection is when light bounces off a?', 'Surface', 'Hole', 'Nothing', 'Vacuum'],
    ['Refraction is the bending of?', 'Light', 'Solid objects', 'Rocks', 'Metal'],
    ['The Moon has no?', 'Atmosphere', 'Craters', 'Rocks', 'Dust'],
    ['Mercury is the?', 'Smallest planet', 'Largest planet', 'Hottest planet', 'Coldest planet'],
    ['Neptune is very?', 'Cold and windy', 'Hot', 'Dry', 'Close to the sun'],
    ['Uranus rotates on its?', 'Side', 'Top', 'Bottom', 'Back'],
    ['Asteroids are mostly between?', 'Mars and Jupiter', 'Earth and Moon', 'Venus and Mercury', 'Saturn and Uranus'],
    ['A comet\'s tail is made of?', 'Gas and dust', 'Water', 'Rocks only', 'Metal'],
    ['The Milky Way is our?', 'Galaxy', 'Solar system', 'Planet', 'Moon'],
    ['Gravity keeps planets orbiting the?', 'Sun', 'Moon', 'Earth', 'Stars randomly'],
    ['An atom is the basic unit of?', 'Matter', 'Energy', 'Sound', 'Color'],
    ['Molecules are made of two or more?', 'Atoms', 'Cells', 'Organs', 'Tissues'],
    ['The periodic table lists all known?', 'Chemical elements', 'Animals', 'Plants', 'Countries'],
    ['Oxygen makes up about what percent of air?', '21%', '78%', '50%', '5%'],
    ['Nitrogen makes up about what percent of air?', '78%', '21%', '50%', '5%'],
    ['A lunar eclipse: Earth is between?', 'The Sun and Moon', 'Mars and Jupiter', 'Stars', 'Venus and Mercury'],
    ['A solar eclipse: the Moon is between?', 'Earth and the Sun', 'Mars and Earth', 'Jupiter and Saturn', 'The stars'],
  ],
  5: [
    ['The chemical symbol for water is?', 'H₂O', 'CO₂', 'O₂', 'NaCl'],
    ['DNA stands for?', 'Deoxyribonucleic acid', 'Digital Network Access', 'Direct Neuron Array', 'Data Node Atom'],
    ['The speed of light is about?', '300,000 km/s', '300 km/s', '3,000 km/s', '30 km/s'],
    ['Mitosis is a type of?', 'Cell division', 'Breathing', 'Digestion', 'Hearing'],
    ['Newton\'s first law is about?', 'Inertia', 'Only gravity', 'Magnetism', 'Heat'],
    ['Photons are particles of?', 'Light', 'Water', 'Sound', 'Earth'],
    ['The periodic table organizes?', 'Chemical elements', 'Animals', 'Countries', 'Sports'],
    ['Chemical formula for carbon dioxide?', 'CO₂', 'H₂O', 'NaCl', 'O₂'],
    ['Chemical formula for table salt?', 'NaCl', 'H₂O', 'CO₂', 'O₂'],
    ['Cells are the basic unit of?', 'Life', 'Rocks', 'Water', 'Light'],
    ['Plant cells have a cell wall and?', 'Chloroplasts', 'Bones', 'Muscles', 'Teeth'],
    ['Animal cells do not have?', 'Cell walls', 'Nuclei', 'Membranes', 'Cytoplasm'],
    ['The nucleus controls the?', 'Cell\'s activities', 'Weather', 'Gravity', 'Magnetism'],
    ['Chromosomes are found in the?', 'Nucleus', 'Stomach', 'Lungs', 'Heart'],
    ['Humans have how many chromosome pairs?', '23', '10', '46', '12'],
    ['Genes determine?', 'Inherited traits', 'Only hair color', 'Only height', 'Only weight'],
    ['Photosynthesis happens in?', 'Chloroplasts', 'Nucleus', 'Mitochondria', 'Ribosomes'],
    ['Mitochondria are the?', 'Powerhouse of the cell', 'Brain of the cell', 'Wall of the cell', 'Door of the cell'],
    ['An ecosystem includes living and non-living?', 'Things in an area', 'Books', 'Classes', 'Countries only'],
    ['A pH of 7 is?', 'Neutral', 'Very acidic', 'Very basic', 'Impossible'],
    ['Acids have a pH?', 'Below 7', 'Above 7', 'Exactly 7', 'Exactly 14'],
    ['Bases have a pH?', 'Above 7', 'Below 7', 'Exactly 7', 'Exactly 0'],
    ['Newton\'s third law: every action has an?', 'Equal and opposite reaction', 'No reaction', 'Random reaction', 'Delayed reaction'],
    ['Gravity is stronger on?', 'Earth than the Moon', 'The Moon', 'Mars than Earth', 'Same everywhere'],
    ['Mass is measured in?', 'Kilograms', 'Meters', 'Liters', 'Seconds'],
    ['Volume is measured in?', 'Liters or cubic cm', 'Kilograms', 'Newtons', 'Watts'],
    ['Force is measured in?', 'Newtons', 'Kilograms', 'Meters', 'Liters'],
    ['The chemical symbol for gold is?', 'Au', 'Ag', 'Fe', 'Cu'],
    ['The chemical symbol for silver is?', 'Ag', 'Au', 'Fe', 'Cu'],
    ['The chemical symbol for iron is?', 'Fe', 'Au', 'Ag', 'Cu'],
    ['Photosynthesis uses sunlight, water, and?', 'Carbon dioxide', 'Oxygen', 'Nitrogen', 'Helium'],
    ['Respiration releases?', 'Energy from glucose', 'Only water', 'Only light', 'Only heat'],
    ['The three states of matter are solid, liquid and?', 'Gas', 'Plasma only', 'Vacuum', 'Energy'],
    ['An element has only one type of?', 'Atom', 'Molecule', 'Cell', 'Organ'],
    ['A compound has two or more?', 'Different elements bonded', 'Same atoms', 'Only gases', 'Only liquids'],
    ['A mixture can be?', 'Separated physically', 'Never separated', 'Only one substance', 'A single element'],
    ['Thermal energy flows from?', 'Hot to cold', 'Cold to hot', 'Same temperature', 'Nowhere'],
    ['Conduction transfers heat through?', 'Direct contact', 'Empty space', 'Light waves', 'Sound waves'],
    ['Convection transfers heat through?', 'Fluid movement', 'Direct contact', 'Radiation', 'Sound'],
    ['Radiation transfers heat through?', 'Electromagnetic waves', 'Contact', 'Fluid movement', 'Sound'],
    ['The Earth\'s crust is the?', 'Outermost layer', 'Core', 'Mantle', 'Inner core'],
    ['The mantle is?', 'Below the crust', 'Above the crust', 'The center', 'The atmosphere'],
    ['The core is the?', 'Center of the Earth', 'Surface', 'Atmosphere', 'Ocean floor'],
    ['Plate tectonics explains how?', 'Continents move', 'Clouds form', 'Rain falls', 'Wind blows'],
    ['Pangaea was the?', 'Supercontinent', 'Super ocean', 'Super volcano', 'Super storm'],
    ['Fossils mostly form in?', 'Sedimentary rock', 'Igneous rock only', 'Metamorphic only', 'All rocks equally'],
    ['Natural selection means survival of the?', 'Fittest', 'Largest only', 'Fastest only', 'Tallest only'],
    ['Charles Darwin proposed?', 'Natural selection', 'Gravity', 'Relativity', 'Atomic theory'],
    ['Adaptation is when organisms?', 'Adjust to their environment', 'Stay the same', 'Grow bigger only', 'Sleep more'],
    ['Renewable energy comes from sources that?', 'Replenish naturally', 'Run out fast', 'Are nuclear only', 'Are coal only'],
  ],
  6: [
    ['A black hole\'s gravity is so strong that?', 'Light cannot escape', 'Sound gets louder', 'Water boils', 'Time speeds up'],
    ['The theory of relativity was proposed by?', 'Einstein', 'Newton', 'Galileo', 'Darwin'],
    ['Natural selection was described by?', 'Darwin', 'Einstein', 'Newton', 'Pasteur'],
    ['Tectonic plates moving apart create?', 'Mid-ocean ridges', 'Only deserts', 'Only ice caps', 'Only clouds'],
    ['CRISPR is related to?', 'Gene editing', 'Space travel', 'Cooking', 'Architecture'],
    ['Renewable energy includes?', 'Solar and wind', 'Only coal', 'Only oil', 'Only gas'],
    ['Entropy in physics relates to?', 'Disorder', 'Speed', 'Color', 'Taste'],
    ['The Doppler effect changes?', 'Frequency of waves', 'Only color', 'Only taste', 'Only smell'],
    ['An alloy is a mixture of?', 'Metals', 'Gases', 'Liquids only', 'Plants'],
    ['Sublimation turns a solid directly into?', 'Gas', 'Liquid', 'Plasma', 'Another solid'],
    ['Tectonic plates float on the?', 'Asthenosphere', 'Clouds', 'Water', 'Air'],
    ['The EM spectrum includes radio, visible light and?', 'X-rays', 'Only sound', 'Only heat', 'Only touch'],
    ['Nuclear energy comes from splitting or fusing?', 'Atoms', 'Molecules', 'Cells', 'Rocks'],
    ['Fission splits atoms while fusion?', 'Combines atoms', 'Splits atoms too', 'Does nothing', 'Breaks molecules'],
    ['A supernova is the explosion of a?', 'Star', 'Planet', 'Moon', 'Asteroid'],
    ['Neutron stars are incredibly?', 'Dense', 'Light', 'Thin', 'Cold'],
    ['Absolute zero is the coldest?', 'Possible temperature', 'Day', 'Night', 'Month'],
    ['The Kelvin scale starts at?', 'Absolute zero', 'Water freezing', 'Water boiling', 'Room temperature'],
    ['RNA stands for?', 'Ribonucleic acid', 'Regular Nucleic Atom', 'Random Neural Access', 'Real Network Array'],
    ['Enzymes are biological?', 'Catalysts', 'Fuels', 'Walls', 'Colors'],
    ['Osmosis moves water through a?', 'Semipermeable membrane', 'Solid wall', 'Vacuum', 'Wire'],
    ['Diffusion moves particles from?', 'High to low concentration', 'Low to high', 'Same to same', 'Nowhere'],
    ['The Hubble Telescope orbits?', 'Earth', 'The Moon', 'Mars', 'The Sun'],
    ['A light-year measures?', 'Distance', 'Time', 'Weight', 'Speed'],
    ['The closest star after the Sun is?', 'Proxima Centauri', 'Sirius', 'Betelgeuse', 'Polaris'],
    ['Red blood cells lack a?', 'Nucleus', 'Hemoglobin', 'Membrane', 'Shape'],
    ['Hemoglobin carries?', 'Oxygen in blood', 'Only water', 'Only food', 'Only waste'],
    ['Antibodies are produced by?', 'White blood cells', 'Red blood cells', 'Platelets', 'Plasma only'],
    ['Photovoltaic cells convert?', 'Sunlight to electricity', 'Wind to heat', 'Water to gas', 'Sound to light'],
    ['Geothermal energy comes from?', 'Earth\'s internal heat', 'Wind', 'Sun', 'Moon'],
    ['Ocean acidification is caused by?', 'Excess CO₂ in oceans', 'Too much salt', 'Too much fish', 'Too much sand'],
    ['Greenhouse gases trap?', 'Heat in the atmosphere', 'Cold', 'Sound', 'Light only'],
    ['The ozone layer is mostly in the?', 'Stratosphere', 'Troposphere', 'Mesosphere', 'Thermosphere'],
    ['CFCs deplete the?', 'Ozone layer', 'Water table', 'Soil nutrients', 'Forest canopy'],
    ['Biodiversity refers to the variety of?', 'Life in an ecosystem', 'Rocks', 'Clouds', 'Minerals only'],
    ['Genetic mutation is a change in?', 'DNA sequence', 'Only behavior', 'Only size', 'Only color'],
    ['The Richter scale is?', 'Logarithmic', 'Linear', 'Exponential only', 'Random'],
    ['P-waves in earthquakes travel through?', 'Solids and liquids', 'Only air', 'Only water', 'Only space'],
    ['S-waves cannot travel through?', 'Liquids', 'Solids', 'Air', 'Rock'],
    ['Half-life is the time for half to?', 'Decay', 'Grow', 'Freeze', 'Evaporate'],
    ['Carbon dating determines?', 'Age of organic materials', 'Only rock age', 'Only star age', 'Only water age'],
    ['Bioaccumulation means toxins?', 'Build up in organisms', 'Disappear', 'Evaporate', 'Neutralize'],
    ['Plate tectonics theory developed in the?', '1960s', '1860s', '1760s', '2060s'],
    ['Dark matter makes up about?', '27% of the universe', '5%', '68%', '90%'],
    ['Dark energy makes up about?', '68% of the universe', '5%', '27%', '1%'],
    ['Stem cells can become?', 'Many different cell types', 'Only one type', 'Nothing', 'Only blood'],
    ['Epigenetics studies changes in?', 'Gene expression', 'Only diet', 'Only exercise', 'Only sleep'],
    ['A catalyst speeds reactions without being?', 'Consumed', 'Used', 'Heated', 'Mixed'],
    ['Bioluminescence is light from?', 'Living organisms', 'Only machines', 'Only fire', 'Only electricity'],
    ['The scientific method starts with?', 'Observation and question', 'Conclusion', 'Experiment', 'Publishing'],
  ],
};
