// [clue, answer, wrong1, wrong2, wrong3]
export type Fact = [string, string, string, string, string];

export const worldHistory: Record<number, Fact[]> = {
  1: [
    ['Ancient Egypt is famous for?', 'Pyramids', 'Skyscrapers', 'Igloos', 'Domes'],
    ['Who was the first president of the USA?', 'George Washington', 'Abraham Lincoln', 'Thomas Jefferson', 'John Adams'],
    ['What did people ride before cars?', 'Horses', 'Elephants', 'Camels', 'Dolphins'],
    ['Which country built the Great Wall?', 'China', 'Japan', 'India', 'Korea'],
    ['Columbus sailed from which country?', 'Spain', 'Portugal', 'England', 'France'],
    ['What is the famous clock tower in London?', 'Big Ben', 'Eiffel Tower', 'Tower Bridge', 'Clock Palace'],
    ['Ancient Romans spoke which language?', 'Latin', 'Greek', 'French', 'Spanish'],
    ['Who reached America in 1492?', 'Columbus', 'Magellan', 'Da Gama', 'Drake'],
    ['Cleopatra was a queen of which country?', 'Egypt', 'Greece', 'Rome', 'Persia'],
    ['What year did humans first walk on the Moon?', '1969', '1959', '1975', '1980'],
    ['Knights wore what to protect themselves?', 'Armor', 'Capes', 'Shields only', 'Helmets only'],
    ['The Titanic was a famous what?', 'Ship', 'Train', 'Airplane', 'Bridge'],
    ['Ancient Greeks held the first what?', 'Olympics', 'World Cup', 'Marathon', 'Carnival'],
    ['Vikings sailed in what type of boat?', 'Longships', 'Canoes', 'Rafts', 'Sailboats'],
    ['What material did Stone Age people use for tools?', 'Stone', 'Iron', 'Plastic', 'Glass'],
    ['A pharaoh was a ruler of which place?', 'Egypt', 'China', 'Greece', 'Persia'],
    ['What is the oldest type of writing called?', 'Cuneiform', 'Alphabet', 'Morse code', 'Braille'],
    ['The Statue of Liberty was a gift from?', 'France', 'England', 'Spain', 'Italy'],
    ['What did pirates search for?', 'Treasure', 'Food', 'Animals', 'Maps'],
    ['The Eiffel Tower is in which city?', 'Paris', 'London', 'Rome', 'Berlin'],
    ['Who painted the Mona Lisa?', 'Leonardo da Vinci', 'Picasso', 'Michelangelo', 'Van Gogh'],
    ['Which toy from ancient China flies in the sky?', 'Kite', 'Balloon', 'Frisbee', 'Boomerang'],
    ['What did ancient people live in before houses?', 'Caves', 'Tents', 'Trees', 'Boats'],
    ['A castle had a water trench called a?', 'Moat', 'River', 'Pool', 'Canal'],
    ['What did ancient Egyptians use to write?', 'Hieroglyphics', 'Alphabet', 'Numbers', 'Symbols'],
    ['Which famous ship sank in 1912?', 'Titanic', 'Mayflower', 'Santa Maria', 'Lusitania'],
    ['Who built the Sphinx?', 'Ancient Egyptians', 'Ancient Greeks', 'Romans', 'Persians'],
    ['Samurai warriors came from which country?', 'Japan', 'China', 'Korea', 'Mongolia'],
    ['What did people use before electricity for light?', 'Candles', 'Flashlights', 'Lamps only', 'Matches'],
    ['A gladiator fought in which building?', 'Colosseum', 'Parthenon', 'Pantheon', 'Forum'],
    ['Where is the oldest known civilization area?', 'Mesopotamia', 'Egypt', 'China', 'India'],
    ['Who invented the light bulb?', 'Thomas Edison', 'Ben Franklin', 'Nikola Tesla', 'James Watt'],
    ['Ancient people drew on walls called what?', 'Cave paintings', 'Murals', 'Posters', 'Graffiti'],
    ['What did ancient sailors use to find direction?', 'Stars', 'Maps', 'Radios', 'Compasses'],
    ['Where did the ancient Olympic Games take place?', 'Greece', 'Rome', 'Egypt', 'Persia'],
    ['A knight\'s home was called a?', 'Castle', 'Mansion', 'Palace', 'Fort'],
    ['The wheel was one of the first what?', 'Inventions', 'Toys', 'Weapons', 'Foods'],
    ['Who wrote the first set of laws?', 'Hammurabi', 'Caesar', 'Pharaoh', 'Zeus'],
    ['What did Native Americans live in?', 'Teepees', 'Igloos', 'Cabins', 'Tents'],
    ['Ancient China invented which explosive?', 'Gunpowder', 'Dynamite', 'Fireworks only', 'TNT'],
    ['The Colosseum is in which city?', 'Rome', 'Athens', 'Paris', 'London'],
    ['What tells time and was used in ancient Egypt?', 'Sundial', 'Clock', 'Hourglass', 'Watch'],
    ['Who were the rulers of ancient Rome?', 'Emperors', 'Kings', 'Pharaohs', 'Sultans'],
    ['What did people use before paper?', 'Papyrus', 'Cloth', 'Wood', 'Leaves'],
    ['What ancient country had the city of Athens?', 'Greece', 'Rome', 'Persia', 'Egypt'],
    ['Who was the Roman god of the sea?', 'Neptune', 'Zeus', 'Mars', 'Apollo'],
    ['What was a medieval market day called?', 'Fair', 'Carnival', 'Festival', 'Parade'],
    ['Ancient people who herded animals were called?', 'Nomads', 'Farmers', 'Hunters', 'Knights'],
    ['What did ancient Greeks build on hilltops?', 'Temples', 'Houses', 'Bridges', 'Towers'],
    ['The Great Pyramid is near which river?', 'Nile', 'Amazon', 'Tigris', 'Ganges'],
  ],
  2: [
    ['The Ice Age was a time of extreme what?', 'Cold', 'Heat', 'Rain', 'Wind'],
    ['Who built the Hanging Gardens?', 'Babylonians', 'Egyptians', 'Greeks', 'Romans'],
    ['Marco Polo traveled to which country?', 'China', 'India', 'Japan', 'Egypt'],
    ['The Wright Brothers invented what?', 'Airplane', 'Car', 'Train', 'Bicycle'],
    ['What were Egyptian kings called?', 'Pharaohs', 'Emperors', 'Sultans', 'Kings'],
    ['Neil Armstrong was the first person on the?', 'Moon', 'Mars', 'Sun', 'Jupiter'],
    ['What was the first animal sent to space?', 'Dog', 'Cat', 'Monkey', 'Mouse'],
    ['The ancient city of Troy is famous for which war?', 'Trojan War', 'Roman War', 'Greek War', 'Persian War'],
    ['What did Benjamin Franklin fly in a storm?', 'Kite', 'Balloon', 'Flag', 'Plane'],
    ['Abraham Lincoln freed the?', 'Enslaved people', 'Prisoners', 'Animals', 'Soldiers'],
    ['The printing press was invented by?', 'Gutenberg', 'Edison', 'Newton', 'Da Vinci'],
    ['Queen Victoria ruled which country?', 'England', 'France', 'Spain', 'Germany'],
    ['What road connected Rome to other cities?', 'Appian Way', 'Silk Road', 'King Road', 'Royal Path'],
    ['Florence Nightingale was famous for which job?', 'Nursing', 'Teaching', 'Cooking', 'Painting'],
    ['The Vikings came from which region?', 'Scandinavia', 'Britain', 'France', 'Spain'],
    ['What did ancient Mayans build?', 'Pyramids', 'Castles', 'Bridges', 'Dams'],
    ['Rosa Parks refused to give up her what?', 'Bus seat', 'Job', 'House', 'Book'],
    ['The first bicycle was called?', 'Velocipede', 'Wheelie', 'Pedaler', 'Roller'],
    ['Ancient Greek soldiers were called?', 'Hoplites', 'Legions', 'Samurai', 'Knights'],
    ['Magellan\'s crew was first to do what?', 'Sail around Earth', 'Fly', 'Climb Everest', 'Cross a desert'],
    ['The Roman Empire fell in which century?', '5th', '3rd', '8th', '10th'],
    ['What animal helped trade on the Silk Road?', 'Camel', 'Horse', 'Elephant', 'Donkey'],
    ['The Liberty Bell is in which US city?', 'Philadelphia', 'New York', 'Boston', 'Washington'],
    ['Who first flew solo across the Atlantic?', 'Amelia Earhart', 'Wright Brothers', 'Lindbergh', 'Earhart'],
    ['The main language of the Roman Empire was?', 'Latin', 'Greek', 'Italian', 'French'],
    ['The Aztecs lived in which modern country?', 'Mexico', 'Peru', 'Brazil', 'Chile'],
    ['Pocahontas was from which group of people?', 'Native Americans', 'Pilgrims', 'British', 'Spanish'],
    ['The Sphinx has the body of which animal?', 'Lion', 'Eagle', 'Horse', 'Bull'],
    ['What did Romans build to carry water?', 'Aqueducts', 'Bridges', 'Tunnels', 'Pipes'],
    ['King Tutankhamun ruled which country?', 'Egypt', 'Persia', 'Greece', 'Babylon'],
    ['Paul Revere warned colonists about which army?', 'British', 'French', 'Spanish', 'German'],
    ['What is Stonehenge made of?', 'Stone', 'Wood', 'Metal', 'Clay'],
    ['The Panama Canal connects which two oceans?', 'Atlantic and Pacific', 'Indian and Arctic', 'Atlantic and Indian', 'Pacific and Arctic'],
    ['Who invented the telephone?', 'Alexander Graham Bell', 'Edison', 'Tesla', 'Morse'],
    ['Medieval knights jousted on what animal?', 'Horse', 'Donkey', 'Camel', 'Elephant'],
    ['The first US flag had how many stars?', '13', '10', '15', '50'],
    ['An ancient Greek marketplace was called?', 'Agora', 'Forum', 'Bazaar', 'Market'],
    ['What was the Silk Road used for?', 'Trade', 'War', 'Travel only', 'Farming'],
    ['The Incas lived in which continent?', 'South America', 'Africa', 'Asia', 'Europe'],
    ['The first vaccines were made by?', 'Edward Jenner', 'Louis Pasteur', 'Edison', 'Darwin'],
    ['What sport began in ancient Greece?', 'Wrestling', 'Football', 'Tennis', 'Cricket'],
    ['The Tower of London once held what?', 'Prisoners', 'Gold', 'Animals', 'Books'],
    ['Which empire built Machu Picchu?', 'Inca', 'Aztec', 'Maya', 'Spanish'],
    ['What did sailors fear in old stories?', 'Sea monsters', 'Storms only', 'Pirates only', 'Ice'],
    ['Who was the god of thunder in Norse myths?', 'Thor', 'Odin', 'Loki', 'Zeus'],
    ['The Parthenon was built for which goddess?', 'Athena', 'Aphrodite', 'Hera', 'Artemis'],
    ['What did medieval blacksmiths make?', 'Swords', 'Books', 'Food', 'Clothes'],
    ['The Renaissance means what in French?', 'Rebirth', 'Art', 'Beauty', 'Light'],
    ['Egyptian mummies were wrapped in?', 'Linen', 'Cotton', 'Silk', 'Wool'],
    ['Who discovered fire is not proven but early humans used?', 'Flint', 'Matches', 'Lighters', 'Glass'],
  ],
  3: [
    ['The French Revolution began in which year?', '1789', '1776', '1801', '1750'],
    ['Who was the first emperor of China?', 'Qin Shi Huang', 'Kublai Khan', 'Sun Tzu', 'Confucius'],
    ['The Magna Carta was signed in which year?', '1215', '1066', '1300', '1415'],
    ['What war lasted from 1914 to 1918?', 'World War I', 'World War II', 'Civil War', 'Cold War'],
    ['The Renaissance started in which country?', 'Italy', 'France', 'England', 'Spain'],
    ['Who discovered penicillin?', 'Alexander Fleming', 'Louis Pasteur', 'Marie Curie', 'Darwin'],
    ['The Berlin Wall fell in which year?', '1989', '1979', '1991', '1985'],
    ['Julius Caesar was assassinated in which month?', 'March', 'June', 'January', 'October'],
    ['What was the first satellite in space called?', 'Sputnik', 'Apollo', 'Voyager', 'Explorer'],
    ['The Hundred Years War was between which two?', 'England and France', 'Spain and Portugal', 'Rome and Greece', 'Russia and Germany'],
    ['Who led the Mongol Empire?', 'Genghis Khan', 'Kublai Khan', 'Attila', 'Alexander'],
    ['The Industrial Revolution began in which country?', 'England', 'France', 'Germany', 'USA'],
    ['What ancient wonder was in Alexandria?', 'Lighthouse', 'Pyramid', 'Statue', 'Garden'],
    ['Who was queen of France during the revolution?', 'Marie Antoinette', 'Joan of Arc', 'Catherine', 'Elizabeth'],
    ['The Rosetta Stone helped translate which script?', 'Hieroglyphics', 'Latin', 'Greek', 'Cuneiform'],
    ['Which empire was ruled by sultans?', 'Ottoman', 'Roman', 'British', 'Mongol'],
    ['The Boston Tea Party protested what?', 'Taxes', 'Slavery', 'War', 'Trade'],
    ['Who was the first Black president of South Africa?', 'Nelson Mandela', 'Desmond Tutu', 'Kofi Annan', 'Robert Mugabe'],
    ['The Cold War was mainly between the US and?', 'Soviet Union', 'China', 'Britain', 'Germany'],
    ['What was the first civilization in Mesopotamia?', 'Sumer', 'Babylon', 'Assyria', 'Persia'],
    ['The Trojan Horse was a trick used in which war?', 'Trojan War', 'Persian War', 'Roman War', 'Greek War'],
    ['The Napoleonic Wars ended in which year?', '1815', '1789', '1830', '1800'],
    ['The Great Depression started in which decade?', '1930s', '1920s', '1940s', '1910s'],
    ['Who was the Sun King of France?', 'Louis XIV', 'Louis XVI', 'Napoleon', 'Charlemagne'],
    ['The feudal system was common in which period?', 'Medieval', 'Ancient', 'Modern', 'Bronze Age'],
    ['What document declared US independence?', 'Declaration of Independence', 'Constitution', 'Bill of Rights', 'Magna Carta'],
    ['Who was the last pharaoh of Egypt?', 'Cleopatra', 'Ramesses', 'Tutankhamun', 'Nefertiti'],
    ['The Reformation was led by?', 'Martin Luther', 'John Calvin', 'Henry VIII', 'Pope Leo'],
    ['What event started World War I?', 'Assassination of Archduke Ferdinand', 'Invasion of Poland', 'Bombing of London', 'Sinking of Lusitania'],
    ['The Spanish Armada was defeated in?', '1588', '1600', '1492', '1550'],
    ['Who built the Taj Mahal?', 'Shah Jahan', 'Akbar', 'Babur', 'Aurangzeb'],
    ['The ancient Greeks invented which government?', 'Democracy', 'Monarchy', 'Dictatorship', 'Republic'],
    ['Nero was emperor of which empire?', 'Roman', 'Greek', 'Persian', 'Ottoman'],
    ['Who improved the steam engine?', 'James Watt', 'Edison', 'Tesla', 'Ford'],
    ['The Battle of Hastings was in which year?', '1066', '1215', '1000', '1100'],
    ['What was the largest empire by land area?', 'Mongol Empire', 'Roman Empire', 'British Empire', 'Ottoman Empire'],
    ['The Mayflower brought settlers to?', 'America', 'Australia', 'India', 'Africa'],
    ['Who was the first to reach the North Pole?', 'Robert Peary', 'Amundsen', 'Scott', 'Shackleton'],
    ['The Suez Canal connects which two seas?', 'Mediterranean and Red Sea', 'Black and Caspian', 'Baltic and North', 'Red and Arabian'],
    ['Morse code was used in which war to send messages?', 'World War II', 'World War I only', 'Civil War only', 'Cold War'],
    ['The United Nations was founded in which year?', '1945', '1950', '1939', '1960'],
    ['Who wrote the Communist Manifesto?', 'Karl Marx', 'Lenin', 'Stalin', 'Engels alone'],
    ['The Emancipation Proclamation freed?', 'Enslaved people', 'Prisoners', 'Soldiers', 'Workers'],
    ['What powered early factories?', 'Steam', 'Electricity', 'Wind', 'Water only'],
    ['Alexander the Great was from?', 'Macedonia', 'Greece', 'Persia', 'Egypt'],
    ['The first modern Olympics were in?', '1896', '1900', '1880', '1910'],
    ['Who was the leader of Nazi Germany?', 'Adolf Hitler', 'Mussolini', 'Stalin', 'Franco'],
    ['What city was buried by a volcano?', 'Pompeii', 'Rome', 'Athens', 'Troy'],
    ['The Treaty of Versailles ended which war?', 'World War I', 'World War II', 'Civil War', 'Franco-Prussian War'],
    ['Who was the first woman to win a Nobel Prize?', 'Marie Curie', 'Mother Teresa', 'Rosa Parks', 'Florence Nightingale'],
  ],
  4: [
    ['The Crusades were fought over which city?', 'Jerusalem', 'Rome', 'Constantinople', 'Mecca'],
    ['What year did World War II end?', '1945', '1944', '1946', '1943'],
    ['The Aztec capital was called?', 'Tenochtitlan', 'Cusco', 'Machu Picchu', 'Tikal'],
    ['Who led India\'s nonviolent independence movement?', 'Gandhi', 'Nehru', 'Bose', 'Tagore'],
    ['The Black Death killed about what fraction of Europe?', 'One third', 'One half', 'One quarter', 'One tenth'],
    ['What empire controlled most of the Mediterranean?', 'Roman', 'Greek', 'Ottoman', 'Persian'],
    ['The American Civil War started in which year?', '1861', '1850', '1870', '1865'],
    ['Who was the first to reach the South Pole?', 'Amundsen', 'Scott', 'Shackleton', 'Peary'],
    ['The Opium Wars involved China and which country?', 'Britain', 'France', 'Japan', 'Russia'],
    ['What type of government did Sparta have?', 'Oligarchy', 'Democracy', 'Monarchy', 'Republic'],
    ['The Louisiana Purchase was bought from?', 'France', 'Spain', 'Britain', 'Mexico'],
    ['Who discovered gravity from a falling apple legend?', 'Isaac Newton', 'Galileo', 'Einstein', 'Copernicus'],
    ['The Enlightenment promoted what over tradition?', 'Reason', 'Religion', 'Monarchy', 'War'],
    ['The Meiji Restoration modernized which country?', 'Japan', 'China', 'Korea', 'India'],
    ['Who wrote the 95 Theses?', 'Martin Luther', 'John Calvin', 'Henry VIII', 'Zwingli'],
    ['The War of 1812 was between the US and?', 'Britain', 'France', 'Spain', 'Mexico'],
    ['What was the capital of the Byzantine Empire?', 'Constantinople', 'Rome', 'Athens', 'Antioch'],
    ['The Bolshevik Revolution happened in which country?', 'Russia', 'France', 'Germany', 'China'],
    ['Who explored the Pacific and reached Australia?', 'Captain Cook', 'Columbus', 'Magellan', 'Drake'],
    ['The Spanish conquered which empire in Peru?', 'Inca', 'Aztec', 'Maya', 'Olmec'],
    ['What is Hammurabi most known for?', 'Code of laws', 'Pyramids', 'Conquests', 'Temples'],
    ['The Trail of Tears forced relocation of which people?', 'Native Americans', 'African Americans', 'Mexicans', 'British'],
    ['Who was the famous Carthaginian general?', 'Hannibal', 'Scipio', 'Caesar', 'Alexander'],
    ['The Gold Rush of 1849 was in which US state?', 'California', 'Texas', 'Alaska', 'Colorado'],
    ['The Mughal Empire was in which region?', 'Indian subcontinent', 'Middle East', 'China', 'Southeast Asia'],
    ['Who sailed around Africa to reach India?', 'Vasco da Gama', 'Columbus', 'Magellan', 'Drake'],
    ['The Peloponnesian War was between Athens and?', 'Sparta', 'Thebes', 'Corinth', 'Troy'],
    ['What weapon changed warfare in World War I?', 'Machine gun', 'Sword', 'Cannon', 'Bow'],
    ['The Ottoman Empire ended after which war?', 'World War I', 'World War II', 'Crimean War', 'Balkan War'],
    ['The Boxer Rebellion took place in which country?', 'China', 'Japan', 'Korea', 'India'],
    ['D-Day took place on the beaches of?', 'Normandy', 'Sicily', 'Dunkirk', 'Calais'],
    ['The Zulu Kingdom was in which part of Africa?', 'Southern', 'Northern', 'Western', 'Eastern'],
    ['Who was emperor during Rome\'s golden age?', 'Augustus', 'Nero', 'Caligula', 'Trajan'],
    ['The Scramble for Africa happened in which century?', '19th', '18th', '20th', '17th'],
    ['What was the Manhattan Project?', 'Atomic bomb program', 'Space program', 'Spy program', 'Tank program'],
    ['The Tokugawa shogunate ruled which country?', 'Japan', 'China', 'Korea', 'Mongolia'],
    ['Who wrote the Declaration of Independence?', 'Thomas Jefferson', 'Washington', 'Franklin', 'Adams'],
    ['The Crimean War was fought on which peninsula?', 'Crimea', 'Iberian', 'Italian', 'Balkan'],
    ['What disease devastated Native Americans?', 'Smallpox', 'Plague', 'Cholera', 'Malaria'],
    ['The Congress of Vienna reorganized which continent?', 'Europe', 'Asia', 'Africa', 'Americas'],
    ['Who was the last emperor of China?', 'Puyi', 'Qin Shi Huang', 'Kangxi', 'Yongle'],
    ['The Haitian Revolution freed which group?', 'Enslaved people', 'Prisoners', 'Soldiers', 'Peasants'],
    ['What city was divided by a wall from 1961 to 1989?', 'Berlin', 'Vienna', 'Warsaw', 'Prague'],
    ['The Inquisition began in which country?', 'Spain', 'Italy', 'France', 'Portugal'],
    ['Who unified Italy in the 1800s?', 'Garibaldi', 'Mussolini', 'Caesar', 'Napoleon'],
    ['The Sepoy Mutiny took place in which year?', '1857', '1847', '1867', '1877'],
    ['What ancient trade route linked China to Rome?', 'Silk Road', 'Spice Route', 'Gold Road', 'Tea Trail'],
    ['Who was the first European to reach India by sea?', 'Vasco da Gama', 'Columbus', 'Cook', 'Drake'],
    ['The Triangular Trade involved slaves, goods, and?', 'Raw materials', 'Weapons', 'Ships', 'Animals'],
    ['Who discovered the Americas for Portugal?', 'Cabral', 'Columbus', 'Magellan', 'Da Gama'],
  ],
  5: [
    ['The Congress of Berlin in 1878 addressed which area?', 'Balkans', 'Africa', 'Asia', 'Middle East'],
    ['Who led the Haitian Revolution?', 'Toussaint Louverture', 'Napoleon', 'Bolivar', 'Dessalines'],
    ['The Balfour Declaration supported a homeland for?', 'Jewish people', 'Arabs', 'Kurds', 'Armenians'],
    ['What year was the Berlin Conference on Africa?', '1884', '1878', '1890', '1900'],
    ['The Dreyfus Affair took place in which country?', 'France', 'Germany', 'Britain', 'Russia'],
    ['Who founded the Maurya Empire?', 'Chandragupta Maurya', 'Ashoka', 'Bindusara', 'Harsha'],
    ['The Treaty of Tordesillas divided the world between?', 'Spain and Portugal', 'England and France', 'Rome and Persia', 'Dutch and Spanish'],
    ['What was the main cause of the Thirty Years War?', 'Religion', 'Land', 'Trade', 'Succession'],
    ['The Safavid Empire was in modern-day?', 'Iran', 'Turkey', 'Iraq', 'Egypt'],
    ['Who was the leader of the Bolshevik Revolution?', 'Lenin', 'Stalin', 'Trotsky', 'Marx'],
    ['The Meiji Constitution was modeled after which country?', 'Germany', 'Britain', 'France', 'USA'],
    ['What was the Long March in China?', 'Communist retreat', 'Trade route', 'Military parade', 'Building project'],
    ['The Battle of Thermopylae involved 300 from?', 'Sparta', 'Athens', 'Thebes', 'Corinth'],
    ['The Reconquista was the reclaiming of Spain from?', 'Moors', 'Romans', 'Franks', 'Vikings'],
    ['The Weimar Republic governed which country?', 'Germany', 'Austria', 'France', 'Italy'],
    ['Who was the last Mughal emperor?', 'Bahadur Shah Zafar', 'Aurangzeb', 'Shah Jahan', 'Akbar'],
    ['The Sykes-Picot Agreement divided which region?', 'Middle East', 'Africa', 'Asia', 'Balkans'],
    ['What was the main export of the Mali Empire?', 'Gold', 'Salt', 'Ivory', 'Silk'],
    ['The Boer Wars were fought in which country?', 'South Africa', 'Kenya', 'Nigeria', 'Egypt'],
    ['The Peace of Westphalia ended which war?', 'Thirty Years War', 'Hundred Years War', 'Seven Years War', 'Napoleonic Wars'],
    ['What dynasty built the Forbidden City?', 'Ming', 'Qing', 'Song', 'Tang'],
    ['The Russo-Japanese War was in which year?', '1905', '1895', '1910', '1900'],
    ['Who founded the Ottoman Empire?', 'Osman I', 'Suleiman', 'Mehmed II', 'Selim I'],
    ['The Treaty of Nanking ended which war?', 'First Opium War', 'Boxer Rebellion', 'Taiping War', 'Second Opium War'],
    ['What was the capital of the Inca Empire?', 'Cusco', 'Lima', 'Quito', 'La Paz'],
    ['The Glorious Revolution was in which country?', 'England', 'France', 'Spain', 'Netherlands'],
    ['Who wrote The Art of War?', 'Sun Tzu', 'Confucius', 'Lao Tzu', 'Genghis Khan'],
    ['The Partition of Bengal occurred in which year?', '1905', '1900', '1910', '1915'],
    ['What was the primary religion of the Gupta Empire?', 'Hinduism', 'Buddhism', 'Islam', 'Jainism'],
    ['The Seven Years War involved most of?', 'Europe', 'Asia', 'Africa', 'Americas'],
    ['Who was the first Caliph of Islam?', 'Abu Bakr', 'Umar', 'Uthman', 'Ali'],
    ['The Edict of Nantes granted tolerance to?', 'Protestants', 'Catholics', 'Jews', 'Muslims'],
    ['What ancient kingdom was in modern Ethiopia?', 'Aksum', 'Kush', 'Mali', 'Ghana'],
    ['The Monroe Doctrine warned Europe against?', 'Colonizing the Americas', 'Trading with Asia', 'Attacking Africa', 'Building navies'],
    ['Who was Saladin?', 'Sultan who recaptured Jerusalem', 'Ottoman sultan', 'Mongol leader', 'Persian king'],
    ['The Qing dynasty was the last dynasty of?', 'China', 'Japan', 'Korea', 'Vietnam'],
    ['Who was the first female pharaoh?', 'Hatshepsut', 'Cleopatra', 'Nefertiti', 'Isis'],
    ['The Zimmermann Telegram was sent to?', 'Mexico', 'Japan', 'Russia', 'Spain'],
    ['What was significant about the Gutenberg Bible?', 'First printed book in Europe', 'Oldest bible', 'Largest bible', 'Golden bible'],
    ['The Hanseatic League was a group of?', 'Trading cities', 'Kingdoms', 'Churches', 'Universities'],
    ['Who unified Germany in 1871?', 'Bismarck', 'Kaiser Wilhelm', 'Frederick', 'Metternich'],
    ['The Abbasid Caliphate was centered in?', 'Baghdad', 'Damascus', 'Cairo', 'Mecca'],
    ['What rebellion did Spartacus lead?', 'Slave revolt', 'Army revolt', 'Senate revolt', 'Peasant revolt'],
    ['The Council of Trent was part of?', 'Counter-Reformation', 'Renaissance', 'Crusades', 'Reformation'],
    ['Who named the Pacific Ocean?', 'Magellan', 'Columbus', 'Cook', 'Drake'],
    ['The Battle of Lepanto was fought in which year?', '1571', '1588', '1550', '1600'],
    ['What was the main crop of colonial Virginia?', 'Tobacco', 'Cotton', 'Corn', 'Wheat'],
    ['The Khmer Empire was in modern-day?', 'Cambodia', 'Vietnam', 'Thailand', 'Laos'],
    ['Who was the first to use gunpowder in war?', 'Chinese', 'Mongols', 'Europeans', 'Arabs'],
    ['The East India Company was chartered in?', '1600', '1500', '1700', '1650'],
  ],
  6: [
    ['The Diet of Worms examined which reformer?', 'Martin Luther', 'Calvin', 'Zwingli', 'Knox'],
    ['Who wrote Leviathan?', 'Thomas Hobbes', 'John Locke', 'Rousseau', 'Voltaire'],
    ['The Decembrist Revolt took place in which country?', 'Russia', 'France', 'Germany', 'Poland'],
    ['What was the significance of the Battle of Zama?', 'Ended Second Punic War', 'Started Roman Empire', 'Ended Rome', 'Started Carthage'],
    ['The Fatimid Caliphate was based in which city?', 'Cairo', 'Baghdad', 'Damascus', 'Mecca'],
    ['Who founded the Jesuit order?', 'Ignatius of Loyola', 'Francis Xavier', 'Thomas More', 'Erasmus'],
    ['The Treaty of Ghent ended which war?', 'War of 1812', 'Seven Years War', 'Napoleonic Wars', 'Civil War'],
    ['What was the Domesday Book?', 'English land survey', 'Bible translation', 'Law code', 'Tax record'],
    ['The Khmer Empire built which famous temple?', 'Angkor Wat', 'Borobudur', 'Prambanan', 'Bagan'],
    ['The Investiture Controversy was between popes and?', 'Holy Roman Emperors', 'French kings', 'English lords', 'Italian dukes'],
    ['The Risorgimento was the unification of?', 'Italy', 'Germany', 'Spain', 'Greece'],
    ['Who wrote The Prince?', 'Machiavelli', 'Hobbes', 'Locke', 'Dante'],
    ['The Code Napoleon reformed which country\'s law?', 'France', 'Germany', 'Italy', 'Spain'],
    ['The Battle of Marathon was in which year?', '490 BC', '480 BC', '500 BC', '460 BC'],
    ['The Delian League was led by which city-state?', 'Athens', 'Sparta', 'Corinth', 'Thebes'],
    ['What civilization built Great Zimbabwe?', 'Shona', 'Zulu', 'Bantu', 'Swahili'],
    ['The Taiping Rebellion was in which country?', 'China', 'Japan', 'India', 'Korea'],
    ['The War of the Roses was between which families?', 'Lancaster and York', 'Tudor and Stuart', 'Windsor and Plantagenet', 'Bourbon and Valois'],
    ['The Umayyad Caliphate was based in?', 'Damascus', 'Baghdad', 'Cairo', 'Mecca'],
    ['Who led Parliamentarians in the English Civil War?', 'Oliver Cromwell', 'Charles I', 'Henry VIII', 'Raleigh'],
    ['The Congress System was established after?', 'Napoleonic Wars', 'World War I', 'Crimean War', 'Seven Years War'],
    ['Who was Ramesses II?', 'Egyptian pharaoh', 'Greek king', 'Roman emperor', 'Persian ruler'],
    ['The Gupta Empire is known as India\'s what age?', 'Golden Age', 'Iron Age', 'Silver Age', 'Bronze Age'],
    ['The Ashanti Empire was in modern-day?', 'Ghana', 'Nigeria', 'Mali', 'Senegal'],
    ['Who was the Spartan king at Thermopylae?', 'Leonidas', 'Xerxes', 'Pericles', 'Agamemnon'],
    ['The Carolingian Empire was founded by?', 'Charlemagne', 'Clovis', 'Pepin', 'Louis'],
    ['The Sassanid Empire was in modern-day?', 'Iran', 'Turkey', 'Egypt', 'Iraq'],
    ['Who was the first shogun of Japan?', 'Minamoto no Yoritomo', 'Tokugawa', 'Oda Nobunaga', 'Toyotomi'],
    ['The Edict of Milan legalized which religion?', 'Christianity', 'Islam', 'Judaism', 'Buddhism'],
    ['The Song Dynasty invented which navigation tool?', 'Compass', 'Astrolabe', 'Sextant', 'Telescope'],
    ['Who built the Suez Canal?', 'Ferdinand de Lesseps', 'Napoleon', 'British Empire', 'Egyptians'],
    ['The Battle of Agincourt was won by?', 'England', 'France', 'Spain', 'Germany'],
    ['What ancient people invented the alphabet?', 'Phoenicians', 'Greeks', 'Romans', 'Egyptians'],
    ['The Mughal Empire was founded by?', 'Babur', 'Akbar', 'Shah Jahan', 'Aurangzeb'],
    ['Who codified Roman law in the Byzantine Empire?', 'Justinian', 'Constantine', 'Theodosius', 'Augustus'],
    ['The Hanseatic League traded mainly in which sea?', 'Baltic', 'Mediterranean', 'North Sea', 'Black Sea'],
    ['What year was the fall of Constantinople?', '1453', '1492', '1400', '1500'],
    ['Who defeated Napoleon at Waterloo?', 'Wellington', 'Nelson', 'Blucher', 'Alexander'],
    ['The Achaemenid Empire was founded by?', 'Cyrus the Great', 'Darius', 'Xerxes', 'Cambyses'],
    ['The Reconquista ended in which year?', '1492', '1500', '1480', '1510'],
    ['Who discovered the ruins of Troy?', 'Heinrich Schliemann', 'Howard Carter', 'Evans', 'Champollion'],
    ['What treaty established state sovereignty in 1648?', 'Peace of Westphalia', 'Treaty of Versailles', 'Treaty of Vienna', 'Treaty of Paris'],
    ['The Ptolemaic dynasty ruled which country?', 'Egypt', 'Greece', 'Persia', 'Rome'],
    ['Who was the first Holy Roman Emperor?', 'Charlemagne', 'Otto I', 'Frederick', 'Henry'],
    ['The Seljuk Turks defeated Byzantines at?', 'Manzikert', 'Constantinople', 'Antioch', 'Nicaea'],
    ['What was the significance of the Battle of Tours?', 'Stopped Muslim advance into Europe', 'Ended Roman Empire', 'Started Crusades', 'United France'],
    ['The Chola Dynasty ruled in which region?', 'South India', 'North India', 'Central Asia', 'Southeast Asia'],
    ['Who was Ibn Battuta?', 'Moroccan traveler', 'Arab scientist', 'Persian poet', 'Turkish sultan'],
    ['The Golden Horde was a branch of which empire?', 'Mongol', 'Ottoman', 'Persian', 'Roman'],
    ['The Aztec sun stone was used as a?', 'Calendar', 'Weapon', 'Shield', 'Altar'],
  ],
};

export const subcontinentHistory: Record<number, Fact[]> = {
  1: [
    ['The national flower of Pakistan is?', 'Jasmine', 'Rose', 'Lily', 'Tulip'],
    ['The Taj Mahal is in which country?', 'India', 'Pakistan', 'Bangladesh', 'Nepal'],
    ['Pakistan\'s Independence Day is on?', 'August 14', 'August 15', 'March 23', 'December 25'],
    ['India\'s Independence Day is on?', 'August 15', 'August 14', 'January 26', 'October 2'],
    ['What colors are on the Pakistan flag?', 'Green and white', 'Red and blue', 'Orange and green', 'Blue and white'],
    ['The capital of Pakistan is?', 'Islamabad', 'Karachi', 'Lahore', 'Peshawar'],
    ['The capital of India is?', 'New Delhi', 'Mumbai', 'Kolkata', 'Chennai'],
    ['Quaid-e-Azam means?', 'Great Leader', 'Brave King', 'Wise Man', 'Strong Ruler'],
    ['Which river flows through Lahore?', 'Ravi', 'Indus', 'Chenab', 'Ganges'],
    ['The national animal of Pakistan is?', 'Markhor', 'Tiger', 'Lion', 'Eagle'],
    ['The national animal of India is?', 'Bengal tiger', 'Elephant', 'Peacock', 'Lion'],
    ['Bangladesh was once part of?', 'Pakistan', 'India', 'Myanmar', 'Nepal'],
    ['The Indian flag has a wheel called?', 'Ashoka Chakra', 'Dharma Wheel', 'Sun Wheel', 'Star Wheel'],
    ['What language is spoken most in Pakistan?', 'Urdu', 'Arabic', 'Hindi', 'Persian'],
    ['What is the tallest mountain in Pakistan?', 'K2', 'Everest', 'Nanga Parbat', 'Broad Peak'],
    ['The national bird of Pakistan is?', 'Chukar', 'Eagle', 'Parrot', 'Peacock'],
    ['Who is the Father of the Nation in Pakistan?', 'Quaid-e-Azam', 'Allama Iqbal', 'Liaquat Ali Khan', 'Ayub Khan'],
    ['Who is the Father of the Nation in India?', 'Mahatma Gandhi', 'Nehru', 'Tagore', 'Bose'],
    ['The largest city in Pakistan is?', 'Karachi', 'Lahore', 'Islamabad', 'Faisalabad'],
    ['Cricket is the most popular sport in?', 'Pakistan and India', 'China and Japan', 'USA and Canada', 'France and Germany'],
    ['What fruit is Pakistan famous for?', 'Mango', 'Apple', 'Banana', 'Orange'],
    ['The Indus River flows through?', 'Pakistan', 'India only', 'Bangladesh', 'Nepal'],
    ['Lahore is famous for which fort?', 'Lahore Fort', 'Red Fort', 'Agra Fort', 'Bala Hissar'],
    ['The Badshahi Mosque is in which city?', 'Lahore', 'Karachi', 'Islamabad', 'Delhi'],
    ['Bangladesh\'s capital is?', 'Dhaka', 'Chittagong', 'Kolkata', 'Sylhet'],
    ['Holi is a festival of which country?', 'India', 'Pakistan', 'Sri Lanka', 'Nepal'],
    ['Eid is celebrated by which religion?', 'Islam', 'Hinduism', 'Buddhism', 'Christianity'],
    ['Sri Lanka is an island near which country?', 'India', 'Pakistan', 'Bangladesh', 'Myanmar'],
    ['The national sport of Pakistan is?', 'Hockey', 'Cricket', 'Football', 'Kabaddi'],
    ['What body of water is south of Pakistan?', 'Arabian Sea', 'Indian Ocean', 'Bay of Bengal', 'Red Sea'],
    ['Chapati is a type of?', 'Bread', 'Rice', 'Soup', 'Fruit'],
    ['The Ganges River is sacred to?', 'Hindus', 'Muslims', 'Buddhists', 'Sikhs'],
    ['What is the national language of Bangladesh?', 'Bengali', 'Urdu', 'Hindi', 'English'],
    ['The Himalayas are in which direction from Pakistan?', 'North', 'South', 'East', 'West'],
    ['Diwali is a festival of?', 'Lights', 'Colors', 'Water', 'Music'],
    ['Who was the first Prime Minister of Pakistan?', 'Liaquat Ali Khan', 'Jinnah', 'Ayub Khan', 'Bhutto'],
    ['The Pakistan flag has a crescent and a?', 'Star', 'Moon', 'Sun', 'Circle'],
    ['What board game was invented in India?', 'Chess', 'Checkers', 'Ludo', 'Monopoly'],
    ['The national anthem of Pakistan is in which language?', 'Urdu', 'Arabic', 'English', 'Punjabi'],
    ['Tea is a popular drink in which region?', 'South Asia', 'North America', 'Europe only', 'Africa only'],
    ['The Karakoram Highway connects Pakistan and?', 'China', 'India', 'Afghanistan', 'Iran'],
    ['What instrument is famous in Indian music?', 'Sitar', 'Guitar', 'Piano', 'Drums'],
    ['The Mohenjo-daro ruins are in which country?', 'Pakistan', 'India', 'Bangladesh', 'Nepal'],
    ['What sweet is famous in South Asia?', 'Gulab Jamun', 'Cake', 'Pudding', 'Cookies'],
    ['Pakistan shares a border with India and?', 'Afghanistan', 'Nepal', 'Bangladesh', 'Myanmar'],
    ['The longest river in India is?', 'Ganges', 'Indus', 'Yamuna', 'Brahmaputra'],
    ['What is the currency of India?', 'Rupee', 'Dollar', 'Pound', 'Taka'],
    ['Biryani is a popular dish in?', 'South Asia', 'Europe', 'North America', 'Australia'],
    ['The Mughal Empire was in which part of the world?', 'South Asia', 'Europe', 'Africa', 'East Asia'],
    ['What is the currency of Pakistan?', 'Rupee', 'Dollar', 'Taka', 'Dinar'],
  ],
  2: [
    ['The British ruled India for about how many years?', '200', '100', '300', '50'],
    ['Who was the first woman PM of Pakistan?', 'Benazir Bhutto', 'Fatima Jinnah', 'Hina Khar', 'Maryam Nawaz'],
    ['The Indus Valley Civilization is how old?', '5000 years', '2000 years', '1000 years', '500 years'],
    ['Who built the Shalimar Gardens?', 'Shah Jahan', 'Akbar', 'Aurangzeb', 'Babur'],
    ['What was the old name of Sri Lanka?', 'Ceylon', 'Burma', 'Siam', 'Persia'],
    ['The Red Fort is in which Indian city?', 'Delhi', 'Mumbai', 'Kolkata', 'Jaipur'],
    ['Allama Iqbal was a famous?', 'Poet', 'Soldier', 'King', 'Scientist'],
    ['The Pakistan Resolution was passed in which city?', 'Lahore', 'Karachi', 'Delhi', 'Dhaka'],
    ['How many provinces does Pakistan have?', 'Four', 'Three', 'Five', 'Six'],
    ['Which Mughal emperor built the Taj Mahal?', 'Shah Jahan', 'Akbar', 'Jahangir', 'Babur'],
    ['The Khyber Pass connects Pakistan and?', 'Afghanistan', 'India', 'China', 'Iran'],
    ['Mahatma Gandhi promoted what type of protest?', 'Nonviolent', 'Armed', 'Silent', 'Written'],
    ['The flag of Bangladesh is mostly which color?', 'Green', 'Red', 'Blue', 'White'],
    ['What metal was used in Indus Valley tools?', 'Bronze', 'Iron', 'Gold', 'Steel'],
    ['The famous Faisal Mosque is in?', 'Islamabad', 'Lahore', 'Karachi', 'Mecca'],
    ['Who was the last Mughal emperor?', 'Bahadur Shah Zafar', 'Aurangzeb', 'Shah Jahan', 'Akbar'],
    ['Bengal was divided by the British in?', '1905', '1900', '1910', '1857'],
    ['What advanced feature did Mohenjo-daro have?', 'Drainage system', 'Electricity', 'Roads', 'Schools'],
    ['The Mughal Empire lasted about how many centuries?', 'Three', 'Two', 'Five', 'One'],
    ['Pakistan became independent in which year?', '1947', '1945', '1950', '1940'],
    ['India became independent in which year?', '1947', '1948', '1946', '1950'],
    ['Which sea is west of India?', 'Arabian Sea', 'Bay of Bengal', 'Red Sea', 'Caspian Sea'],
    ['The Thar Desert is in which region?', 'Sindh and Rajasthan', 'Punjab', 'Bengal', 'Kashmir'],
    ['Who was Tipu Sultan?', 'Ruler of Mysore', 'Mughal emperor', 'British general', 'Sikh leader'],
    ['The Grand Trunk Road was built by?', 'Sher Shah Suri', 'Akbar', 'British', 'Shah Jahan'],
    ['Bangladesh became independent in which year?', '1971', '1965', '1975', '1947'],
    ['Quaid-e-Azam\'s real name was?', 'Muhammad Ali Jinnah', 'Liaquat Ali Khan', 'Allama Iqbal', 'Ayub Khan'],
    ['Who wrote Pakistan\'s national anthem?', 'Hafeez Jalandhari', 'Allama Iqbal', 'Faiz Ahmed Faiz', 'Ghalib'],
    ['The Lahore Resolution was passed in which year?', '1940', '1930', '1947', '1935'],
    ['What river runs through Dhaka?', 'Buriganga', 'Ganges', 'Indus', 'Meghna'],
    ['Akbar the Great was known for being?', 'Tolerant', 'Cruel', 'Shy', 'Weak'],
    ['The Wagah border is between Pakistan and?', 'India', 'Afghanistan', 'China', 'Iran'],
    ['The first capital of Pakistan was?', 'Karachi', 'Lahore', 'Islamabad', 'Dhaka'],
    ['What is the highest civilian award in Pakistan?', 'Nishan-e-Pakistan', 'Hilal-e-Pakistan', 'Sitara-e-Quaid', 'Tamgha-e-Imtiaz'],
    ['Rabindranath Tagore was from which country?', 'India', 'Pakistan', 'Bangladesh', 'Sri Lanka'],
    ['The national flower of India is?', 'Lotus', 'Rose', 'Jasmine', 'Sunflower'],
    ['Taxila was an ancient center of?', 'Learning', 'Trade', 'Warfare', 'Religion only'],
    ['Who was Ranjit Singh?', 'Sikh ruler of Punjab', 'Mughal emperor', 'British officer', 'Hindu king'],
    ['The Pakistan Army was formed in which year?', '1947', '1940', '1950', '1956'],
    ['What sport did Jahangir Khan play?', 'Squash', 'Cricket', 'Hockey', 'Tennis'],
    ['The Swat Valley is in which province?', 'Khyber Pakhtunkhwa', 'Punjab', 'Sindh', 'Balochistan'],
    ['Subhas Chandra Bose was also known as?', 'Netaji', 'Mahatma', 'Pandit', 'Sardar'],
    ['The Indus River empties into which sea?', 'Arabian Sea', 'Bay of Bengal', 'Indian Ocean', 'Red Sea'],
    ['What ancient city was near modern Islamabad?', 'Taxila', 'Mohenjo-daro', 'Harappa', 'Lothal'],
    ['The Mughal capital before Delhi was?', 'Agra', 'Lahore', 'Fatehpur Sikri', 'Kabul'],
    ['Sindh was conquered by Muhammad bin Qasim in?', '712', '800', '650', '900'],
    ['The Bengal famine occurred during which decade?', '1940s', '1930s', '1920s', '1950s'],
    ['What is the currency of Bangladesh?', 'Taka', 'Rupee', 'Dollar', 'Dinar'],
    ['The Hunza Valley is in which part of Pakistan?', 'North', 'South', 'East', 'West'],
    ['Who was the national poet of Pakistan?', 'Allama Iqbal', 'Faiz Ahmed Faiz', 'Ghalib', 'Hafeez Jalandhari'],
  ],
  3: [
    ['The Battle of Plassey was in which year?', '1757', '1765', '1800', '1857'],
    ['Who founded the Mughal Empire?', 'Babur', 'Akbar', 'Shah Jahan', 'Humayun'],
    ['The Jallianwala Bagh massacre was in which year?', '1919', '1920', '1915', '1910'],
    ['What was the Two-Nation Theory?', 'Separate Muslim and Hindu nations', 'One united India', 'British rule forever', 'Communist state'],
    ['The Lucknow Pact was between Congress and?', 'Muslim League', 'British', 'Sikhs', 'Hindus'],
    ['Who was the first Governor-General of Pakistan?', 'Muhammad Ali Jinnah', 'Liaquat Ali Khan', 'Ayub Khan', 'Iskander Mirza'],
    ['The Khilafat Movement supported which empire?', 'Ottoman', 'Mughal', 'British', 'Persian'],
    ['Sir Syed Ahmad Khan founded which university?', 'Aligarh', 'Delhi', 'Calcutta', 'Lahore'],
    ['The Simon Commission was boycotted because?', 'No Indian members', 'Too expensive', 'Too slow', 'Unfair report'],
    ['The Quit India Movement was launched in?', '1942', '1940', '1945', '1935'],
    ['Which Mughal emperor was called World Seizer?', 'Jahangir', 'Akbar', 'Shah Jahan', 'Babur'],
    ['The Rowlatt Act limited which freedom?', 'Civil liberties', 'Trade', 'Religion', 'Education'],
    ['The INA was founded by?', 'Subhas Chandra Bose', 'Gandhi', 'Nehru', 'Jinnah'],
    ['Who was the viceroy during Partition?', 'Lord Mountbatten', 'Lord Curzon', 'Lord Wavell', 'Lord Irwin'],
    ['The Cripps Mission came to India in?', '1942', '1940', '1945', '1935'],
    ['The Aligarh Movement promoted what?', 'Modern education for Muslims', 'Armed revolt', 'Hindu unity', 'British loyalty'],
    ['Who led the Faraizi Movement?', 'Haji Shariatullah', 'Titu Mir', 'Syed Ahmad', 'Shah Waliullah'],
    ['The Round Table Conferences were held in?', 'London', 'Delhi', 'Lahore', 'Calcutta'],
    ['Aurangzeb was the last great Mughal ruler?', 'Yes', 'No', 'He was the first', 'He was Sikh'],
    ['The Treaty of Amritsar was signed in?', '1809', '1800', '1820', '1849'],
    ['Who was known as the Tiger of Mysore?', 'Tipu Sultan', 'Akbar', 'Ranjit Singh', 'Hyder Ali'],
    ['The Doctrine of Lapse was introduced by?', 'Lord Dalhousie', 'Lord Curzon', 'Lord Wellesley', 'Lord Hastings'],
    ['The Sepoy Mutiny started in which year?', '1857', '1847', '1867', '1860'],
    ['Who founded the Indian National Congress?', 'Allan Octavian Hume', 'Gandhi', 'Nehru', 'Tilak'],
    ['The Muslim League was founded in which year?', '1906', '1900', '1910', '1920'],
    ['The Morley-Minto Reforms introduced what?', 'Separate electorates', 'Full independence', 'Joint rule', 'New taxes'],
    ['Shah Waliullah translated the Quran into?', 'Persian', 'Urdu', 'Arabic', 'Turkish'],
    ['The Salt March was led by?', 'Gandhi', 'Nehru', 'Bose', 'Jinnah'],
    ['Who was the first president of Muslim League?', 'Aga Khan III', 'Jinnah', 'Liaquat Ali Khan', 'Nawab Salimullah'],
    ['The Montagu-Chelmsford Reforms were in?', '1919', '1909', '1925', '1935'],
    ['Sher Shah Suri introduced which coin?', 'Rupee', 'Dinar', 'Mohur', 'Anna'],
    ['The Non-Cooperation Movement was in?', '1920', '1919', '1922', '1930'],
    ['Who was Mumtaz Mahal?', 'Shah Jahan\'s wife', 'Akbar\'s wife', 'Babur\'s wife', 'Jahangir\'s wife'],
    ['The Cabinet Mission came in which year?', '1946', '1942', '1945', '1940'],
    ['The first Battle of Panipat was in?', '1526', '1556', '1600', '1500'],
    ['Who defeated the Marathas at Panipat in 1761?', 'Ahmad Shah Durrani', 'Aurangzeb', 'Babur', 'Tipu Sultan'],
    ['The Indian Councils Act was passed in?', '1909', '1900', '1919', '1905'],
    ['Bahadur Shah Zafar was exiled to?', 'Rangoon', 'London', 'Kabul', 'Mecca'],
    ['The Swadeshi Movement was about?', 'Buying Indian goods', 'Armed revolt', 'British trade', 'Foreign education'],
    ['Who was the founder of the Sikh religion?', 'Guru Nanak', 'Guru Gobind Singh', 'Ranjit Singh', 'Banda Singh'],
    ['The Objectives Resolution of Pakistan was in?', '1949', '1947', '1950', '1956'],
    ['Who was the second Prime Minister of India?', 'Lal Bahadur Shastri', 'Indira Gandhi', 'Rajiv Gandhi', 'Patel'],
    ['The Durand Line separates Pakistan and?', 'Afghanistan', 'India', 'Iran', 'China'],
    ['What was the capital of the Sikh Empire?', 'Lahore', 'Amritsar', 'Delhi', 'Peshawar'],
    ['The Government of India Act was passed in?', '1935', '1930', '1940', '1925'],
    ['Who introduced Permanent Settlement in Bengal?', 'Lord Cornwallis', 'Lord Dalhousie', 'Lord Wellesley', 'Lord Curzon'],
    ['Who was the first president of India?', 'Rajendra Prasad', 'Nehru', 'Gandhi', 'Patel'],
    ['Who was Muhammad bin Tughlaq known for?', 'Shifting the capital', 'Building mosques', 'Winning wars', 'Writing poetry'],
    ['The Simla Conference was held in?', '1945', '1940', '1946', '1942'],
    ['Who painted Mughal miniature artworks?', 'Court artists', 'British painters', 'Persian poets', 'Sufi saints'],
  ],
  4: [
    ['The Third Battle of Panipat was in which year?', '1761', '1757', '1800', '1526'],
    ['Who was Amir Khusrow?', 'Poet and musician', 'Mughal emperor', 'British officer', 'Sufi saint'],
    ['The Subsidiary Alliance was introduced by?', 'Lord Wellesley', 'Lord Dalhousie', 'Lord Cornwallis', 'Lord Curzon'],
    ['The Partition of Bengal aimed to?', 'Divide Hindu and Muslim areas', 'Unite India', 'Help trade', 'Build railways'],
    ['The Lucknow Pact was in which year?', '1916', '1920', '1906', '1910'],
    ['Who was Rani Lakshmi Bai?', 'Queen who fought in 1857 revolt', 'Mughal queen', 'British ally', 'Sikh leader'],
    ['The Delhi Sultanate began in which year?', '1206', '1300', '1100', '1400'],
    ['What system did Mughals use for revenue?', 'Mansabdari', 'Zamindari', 'Ryotwari', 'Feudal'],
    ['The Treaty of Lahore followed which war?', 'First Anglo-Sikh War', 'Maratha War', 'Mysore War', 'Afghan War'],
    ['Who was Mir Jafar?', 'Traitor at Battle of Plassey', 'Mughal general', 'Sikh warrior', 'Sufi saint'],
    ['The East India Company was founded in?', '1600', '1700', '1500', '1650'],
    ['What was jizya?', 'Tax on non-Muslims', 'Land tax', 'Trade tax', 'Military tax'],
    ['The Regulating Act was passed in?', '1773', '1784', '1800', '1757'],
    ['Who built Fatehpur Sikri?', 'Akbar', 'Shah Jahan', 'Babur', 'Jahangir'],
    ['The Wahabi Movement was against?', 'British and Sikh rule', 'Mughal rule', 'Hindu rule', 'Afghan rule'],
    ['Who wrote Tuzuk-e-Jahangiri?', 'Jahangir', 'Akbar', 'Babur', 'Shah Jahan'],
    ['The Permanent Settlement mainly affected?', 'Bengal', 'Punjab', 'Sindh', 'Madras'],
    ['What language did Mughal courts use?', 'Persian', 'Urdu', 'Arabic', 'Turkish'],
    ['The Revolt of 1857 started in which city?', 'Meerut', 'Delhi', 'Lucknow', 'Kolkata'],
    ['Who was Dara Shikoh?', 'Shah Jahan\'s eldest son', 'Akbar\'s general', 'Aurangzeb\'s son', 'Babur\'s brother'],
    ['The Moplah Rebellion was in which region?', 'Kerala', 'Bengal', 'Punjab', 'Sindh'],
    ['Who founded the Slave Dynasty?', 'Qutb-ud-din Aibak', 'Iltutmish', 'Balban', 'Razia Sultan'],
    ['The Punjab was annexed by the British in?', '1849', '1857', '1840', '1860'],
    ['What was the Zamindari system?', 'Landlord-based revenue', 'Farmer taxation', 'Trade system', 'Military service'],
    ['The Chauri Chaura incident led Gandhi to?', 'Call off Non-Cooperation', 'Start a war', 'Leave India', 'Join British'],
    ['Who was Syed Ameer Ali?', 'Muslim political leader', 'Hindu reformer', 'Sikh general', 'British officer'],
    ['The Indian Independence Act was passed in?', '1947', '1946', '1945', '1950'],
    ['What was the Ryotwari system?', 'Direct farmer taxation', 'Landlord revenue', 'Village taxation', 'Military levy'],
    ['The Bengal Renaissance promoted?', 'Modernization and reform', 'War', 'Isolation', 'Monarchy'],
    ['Who was Shah Abdul Latif Bhittai?', 'Sindhi Sufi poet', 'Mughal emperor', 'Punjabi warrior', 'Bengali leader'],
    ['What was Din-i-Ilahi?', 'Akbar\'s syncretic religion', 'Sufi order', 'Hindu sect', 'Muslim school'],
    ['The Calcutta Madrasa was founded by?', 'Warren Hastings', 'Cornwallis', 'Wellesley', 'Curzon'],
    ['Who was Chand Bibi?', 'Defender of Ahmednagar', 'Mughal empress', 'British spy', 'Sikh queen'],
    ['The Pitt\'s India Act was in which year?', '1784', '1773', '1800', '1793'],
    ['What was the Mahalwari system?', 'Village-based revenue', 'Farmer taxation', 'Landlord system', 'Trade levy'],
    ['Who translated Upanishads into Persian?', 'Dara Shikoh', 'Akbar', 'Aurangzeb', 'Shah Jahan'],
    ['The Radcliffe Line divided which countries?', 'India and Pakistan', 'India and China', 'Pakistan and Afghanistan', 'India and Bangladesh'],
    ['The Nizam of Hyderabad wanted to?', 'Stay independent', 'Join Pakistan', 'Join Britain', 'Declare war'],
    ['Who was Bulleh Shah?', 'Punjabi Sufi poet', 'Mughal general', 'Sindhi ruler', 'Bengali writer'],
    ['Direct Action Day was in which year?', '1946', '1947', '1940', '1945'],
    ['What was the Khudai Khidmatgar movement?', 'Pashtun nonviolent resistance', 'Armed revolt', 'Hindu reform', 'Sikh militancy'],
    ['Who was the architect of Pakistan\'s 1956 Constitution?', 'Chaudhry Muhammad Ali', 'Jinnah', 'Liaquat Ali Khan', 'Ayub Khan'],
    ['The One Unit policy merged West Pakistan in?', '1955', '1950', '1960', '1947'],
    ['What led to the creation of Bangladesh?', '1971 war', '1965 war', 'Kargil war', 'British partition'],
    ['The Simla Agreement was signed in?', '1972', '1970', '1965', '1975'],
    ['Who was Zulfikar Ali Bhutto?', 'Prime Minister of Pakistan', 'Army chief', 'Indian PM', 'Bengali leader'],
    ['The Communal Award of 1932 expanded what?', 'Separate electorates', 'Joint electorates', 'British seats', 'Trade rights'],
    ['The Aligarh Movement was in which century?', '19th', '18th', '20th', '17th'],
    ['What was the August Offer of 1940?', 'British proposal for India', 'Pakistan demand', 'Hindu plan', 'Muslim proposal'],
    ['The Civil Disobedience Movement was in?', '1930', '1920', '1940', '1942'],
  ],
  5: [
    ['The Treaty of Surat was between Mughals and?', 'British', 'French', 'Dutch', 'Portuguese'],
    ['Who was Ibrahim Lodi?', 'Last Delhi Sultan', 'First Mughal', 'Sikh king', 'Bengali ruler'],
    ['The Battle of Haldighati involved which Rajput?', 'Maharana Pratap', 'Rana Sanga', 'Prithviraj', 'Man Singh'],
    ['What was the Ilbert Bill controversy about?', 'Indian judges trying Europeans', 'Land reform', 'Army service', 'Tax collection'],
    ['The Khilji Dynasty\'s most famous ruler was?', 'Alauddin Khilji', 'Jalaluddin Khilji', 'Qutbuddin Khilji', 'Mubarak Khilji'],
    ['Who was Raziya Sultan?', 'First female Muslim ruler of Delhi', 'Mughal empress', 'British queen', 'Sikh leader'],
    ['The Second Battle of Panipat was between?', 'Akbar and Hemu', 'Babur and Lodi', 'Durrani and Marathas', 'British and Mughals'],
    ['What was the Diwani right?', 'Revenue collection right', 'Military command', 'Trade monopoly', 'Land ownership'],
    ['The Indigo Revolt was against?', 'Forced indigo cultivation', 'Land tax', 'Slavery', 'British education'],
    ['Who was Ahmad Sirhindi?', 'Islamic scholar and reformer', 'Mughal general', 'Sikh guru', 'Hindu saint'],
    ['The Tughlaq Dynasty ruled from which city?', 'Delhi', 'Agra', 'Lahore', 'Deccan'],
    ['What was the Karachi Resolution of 1943?', 'Demand for Pakistan borders', 'Army formation', 'Trade agreement', 'Education reform'],
    ['The Vernacular Press Act was in?', '1878', '1870', '1885', '1900'],
    ['Who founded the Bahmani Sultanate?', 'Alauddin Bahman Shah', 'Muhammad Shah', 'Firoz Shah', 'Mahmud Shah'],
    ['What was the Charter Act of 1833?', 'End of Company trade monopoly', 'Start of railways', 'Army reform', 'Land reform'],
    ['The Minto-Morley Reforms gave Muslims?', 'Separate electorates', 'Full independence', 'Army control', 'Land rights'],
    ['Who was Wajid Ali Shah?', 'Last Nawab of Awadh', 'Mughal emperor', 'Sikh ruler', 'Bengali leader'],
    ['The Deccan Riots were in which year?', '1875', '1857', '1880', '1900'],
    ['What was the significance of Plassey?', 'British control of Bengal', 'Mughal revival', 'Sikh expansion', 'Maratha victory'],
    ['The Wood\'s Despatch was about?', 'Education reform', 'Military reform', 'Trade policy', 'Land revenue'],
    ['Who was Syed Ahmad Barelvi?', 'Leader of jihad movement', 'Mughal emperor', 'Hindu reformer', 'British officer'],
    ['The Tashkent Declaration ended which war?', '1965 India-Pakistan War', '1971 war', 'Kargil conflict', 'Kashmir war'],
    ['What was the Rowlatt Satyagraha?', 'Protest against Rowlatt Act', 'Tax revolt', 'Army mutiny', 'Trade boycott'],
    ['The Chishtiyya Sufi order was founded in?', 'Chisht, Afghanistan', 'Delhi, India', 'Baghdad, Iraq', 'Mecca, Arabia'],
    ['Who was Malik Ambar?', 'Deccan military leader', 'Mughal general', 'Sikh warrior', 'British spy'],
    ['What was the significance of the Battle of Buxar?', 'British supremacy confirmed', 'Mughal revival', 'Sikh victory', 'Maratha expansion'],
    ['Who established the Sayyid Dynasty?', 'Khizr Khan', 'Bahlol Lodi', 'Firoz Tughlaq', 'Sikandar Lodi'],
    ['The Liaquat-Nehru Pact was about?', 'Minority rights', 'Trade', 'Military alliance', 'Border dispute'],
    ['The Sindh Madrasa was founded by?', 'Hassan Ali Effendi', 'Sir Syed', 'Shah Waliullah', 'Jinnah'],
    ['Who was Mir Chakar Rind?', 'Baloch tribal chief', 'Mughal governor', 'Sindhi ruler', 'Punjabi warrior'],
    ['Pakistan\'s 1973 Constitution was under?', 'Zulfikar Ali Bhutto', 'Ayub Khan', 'Yahya Khan', 'Zia ul Haq'],
    ['The Swadeshi Movement started in which year?', '1905', '1910', '1900', '1920'],
    ['Who was Sir Syed Ahmad Khan?', 'Muslim educational reformer', 'British officer', 'Hindu leader', 'Sikh general'],
    ['The Shimla Deputation was in which year?', '1906', '1909', '1905', '1910'],
    ['What did the Nehru Report propose?', 'Dominion status for India', 'Full independence', 'Partition plan', 'Military rule'],
    ['The Fourteen Points were issued by?', 'Jinnah', 'Gandhi', 'Nehru', 'Iqbal'],
    ['Who was Haji Shariatullah?', 'Bengali Islamic reformer', 'Mughal prince', 'Sindhi poet', 'Punjabi leader'],
    ['The Lahore Resolution called for?', 'Separate Muslim states', 'United India', 'British rule', 'Hindu nation'],
    ['What was the Objectives Resolution?', 'Guiding principles of Pakistan', 'War declaration', 'Trade agreement', 'Army constitution'],
    ['The first constitution of Pakistan was in?', '1956', '1947', '1950', '1962'],
    ['Who was Fatima Jinnah?', 'Sister of Quaid-e-Azam', 'Wife of Jinnah', 'Daughter of Jinnah', 'PM of Pakistan'],
    ['The Unionist Party was prominent in which region?', 'Punjab', 'Sindh', 'Bengal', 'NWFP'],
    ['The age of consent bill was controversial for?', 'Setting marriage age', 'Voting rights', 'Education', 'Property rights'],
    ['What triggered the 1857 revolt\'s immediate cause?', 'Greased cartridges', 'Tax increase', 'Land grab', 'Religious ban'],
    ['The Allahabad Address of 1930 was by?', 'Allama Iqbal', 'Jinnah', 'Gandhi', 'Nehru'],
    ['Who was the first Chief of Army Staff of Pakistan?', 'General Gracey', 'General Ayub', 'General Zia', 'General Tikka'],
    ['The Khaksar Movement was led by?', 'Allama Mashriqi', 'Jinnah', 'Iqbal', 'Gandhi'],
    ['What was the Communal Award?', 'Separate electorates for minorities', 'Joint rule', 'British withdrawal', 'Trade reform'],
    ['The Balochistan became a province in?', '1970', '1947', '1955', '1962'],
    ['Who was Liaquat Ali Khan?', 'First PM of Pakistan', 'First president', 'Army chief', 'Governor-General'],
  ],
  6: [
    ['The Sayyid Brothers were kingmakers of which era?', 'Mughal', 'Delhi Sultanate', 'British', 'Sikh'],
    ['Who was Nizam-ul-Mulk Asaf Jah?', 'Founder of Hyderabad state', 'Mughal emperor', 'British governor', 'Sikh king'],
    ['The Treaty of Mangalore was between Tipu and?', 'British', 'French', 'Marathas', 'Mughals'],
    ['What was the Doctrine of Paramountcy?', 'British supremacy over states', 'Indian self-rule', 'Muslim leadership', 'Trade monopoly'],
    ['The Aligarh Institute Gazette was published by?', 'Sir Syed Ahmad Khan', 'Iqbal', 'Jinnah', 'Hafeez'],
    ['Who was Murshid Quli Khan?', 'First Nawab of Bengal', 'Mughal emperor', 'Sikh ruler', 'Delhi sultan'],
    ['The Carnatic Wars were between French and?', 'British', 'Mughals', 'Marathas', 'Dutch'],
    ['The Battle of Wandiwash was significant for?', 'French defeat in India', 'British defeat', 'Mughal victory', 'Sikh rise'],
    ['The Treaty of Bassein was signed by?', 'Peshwa Baji Rao II', 'Tipu Sultan', 'Ranjit Singh', 'Nizam'],
    ['Who was Shah Ismail Shaheed?', 'Fighter at Balakot', 'Mughal prince', 'Sikh warrior', 'British spy'],
    ['The Young Bengal Movement was led by?', 'Henry Derozio', 'Ram Mohan Roy', 'Tagore', 'Bose'],
    ['The Widow Remarriage Act was passed in?', '1856', '1829', '1860', '1870'],
    ['Who was Ziauddin Barani?', 'Medieval Indian historian', 'Mughal poet', 'Sufi saint', 'Delhi sultan'],
    ['The Permanent Settlement was in which year?', '1793', '1800', '1773', '1784'],
    ['Who was Khwaja Moinuddin Chishti?', 'Sufi saint of Ajmer', 'Delhi sultan', 'Mughal general', 'Sikh guru'],
    ['The Maratha Confederacy fell at?', 'Third Battle of Panipat', 'Plassey', 'Buxar', 'Wandiwash'],
    ['The Ryotwari system originated in which region?', 'Madras', 'Bengal', 'Punjab', 'Sindh'],
    ['The Bengal partition was reversed in?', '1911', '1910', '1915', '1920'],
    ['Who was Saadat Hasan Manto?', 'Partition-era writer', 'Mughal poet', 'British official', 'Sikh historian'],
    ['The Panchsheel Agreement was between India and?', 'China', 'Pakistan', 'Nepal', 'Sri Lanka'],
    ['The Subsidiary Alliance weakened states by?', 'Banning own armies', 'Raising taxes', 'Closing courts', 'Seizing trade'],
    ['Who was Ahmad Shah Abdali?', 'Afghan ruler and conqueror', 'Mughal emperor', 'Sikh king', 'British general'],
    ['The Treaty of Purandar forced Shivaji to cede to?', 'Mughals', 'British', 'French', 'Portuguese'],
    ['The Deccan Education Society was founded by?', 'Tilak and Agarkar', 'Gandhi', 'Nehru', 'Tagore'],
    ['Who was Titu Mir?', 'Bengali resistance leader', 'Mughal prince', 'Sindhi poet', 'Sikh warrior'],
    ['The Muslim League\'s first session was in?', 'Dhaka', 'Lahore', 'Karachi', 'Delhi'],
    ['The Montford Reforms key feature was?', 'Dyarchy', 'Full rule', 'Partition', 'Republic'],
    ['The Rawalpindi Conspiracy was in?', '1951', '1947', '1955', '1962'],
    ['Who was General Ayub Khan?', 'First military ruler of Pakistan', 'Indian general', 'British officer', 'Afghan leader'],
    ['The RCD was a pact with Pakistan, Iran, and?', 'Turkey', 'Afghanistan', 'Saudi Arabia', 'Iraq'],
    ['What was the Agartala Conspiracy Case?', 'Alleged Bengali separatism', 'Army coup plot', 'Trade scandal', 'Spy case'],
    ['The Legal Framework Order was issued by?', 'Yahya Khan', 'Ayub Khan', 'Bhutto', 'Zia'],
    ['Who led Pakistan in the 1965 war?', 'Ayub Khan', 'Yahya Khan', 'Bhutto', 'Zia'],
    ['The Tashkent Declaration was mediated by?', 'Soviet Union', 'USA', 'China', 'Britain'],
    ['What was the Six Points Movement?', 'Bengali autonomy demand', 'Sindhi rights', 'Baloch freedom', 'Pashtun demand'],
    ['The Hamoodur Rahman Commission investigated?', '1971 war defeat', '1965 war', 'Kargil conflict', 'Army coup'],
    ['The Basic Democracies system was introduced by?', 'Ayub Khan', 'Yahya Khan', 'Bhutto', 'Zia'],
    ['What was EBDO?', 'Elective Bodies Disqualification Order', 'Economic Board', 'Defense Order', 'Education Bureau'],
    ['General Zia-ul-Haq came to power in?', '1977', '1969', '1971', '1980'],
    ['The Lahore Declaration of 1999 was between?', 'India and Pakistan', 'Pakistan and China', 'India and Bangladesh', 'Pakistan and Afghanistan'],
    ['What did the 18th Amendment do?', 'Gave provinces more power', 'Created army rule', 'Changed capital', 'Ended democracy'],
    ['The Kargil conflict was in which year?', '1999', '1998', '2000', '2001'],
    ['Who was Pakistan\'s first female foreign minister?', 'Hina Rabbani Khar', 'Benazir Bhutto', 'Fatima Jinnah', 'Asma Jahangir'],
    ['The first Chief Justice of Pakistan was?', 'Abdul Rashid', 'Muhammad Munir', 'Alvin Cornelius', 'Hamoodur Rahman'],
    ['The Pitt\'s India Act regulated?', 'East India Company', 'Trade routes', 'Army affairs', 'Tax collection'],
    ['The Ilbert Bill was about?', 'Indian judges over Europeans', 'Land reform', 'Tax policy', 'Army recruitment'],
    ['Who was the first President of Pakistan?', 'Iskander Mirza', 'Ayub Khan', 'Jinnah', 'Liaquat Ali Khan'],
    ['The Lahore Resolution was presented by?', 'A.K. Fazlul Huq', 'Jinnah', 'Iqbal', 'Liaquat Ali Khan'],
    ['The Indus Waters Treaty was signed in?', '1960', '1955', '1965', '1972'],
    ['Who was Field Marshal Ayub Khan\'s successor?', 'Yahya Khan', 'Bhutto', 'Zia', 'Musharraf'],
  ],
};

export const geography: Record<number, Fact[]> = {
  1: [
    ['How many continents are there?', '7', '5', '6', '8'],
    ['How many oceans are there?', '5', '3', '4', '7'],
    ['The largest ocean is the?', 'Pacific', 'Atlantic', 'Indian', 'Arctic'],
    ['The largest continent is?', 'Asia', 'Africa', 'Europe', 'North America'],
    ['Which direction does the Sun rise from?', 'East', 'West', 'North', 'South'],
    ['What is the biggest country by area?', 'Russia', 'Canada', 'China', 'USA'],
    ['What is the smallest continent?', 'Australia', 'Europe', 'Antarctica', 'South America'],
    ['A large body of salt water is called?', 'Ocean', 'Lake', 'River', 'Pond'],
    ['A very high landform is called a?', 'Mountain', 'Valley', 'Plain', 'Hill'],
    ['What is the frozen continent?', 'Antarctica', 'Arctic', 'Greenland', 'Iceland'],
    ['Rain comes from what in the sky?', 'Clouds', 'Sun', 'Stars', 'Moon'],
    ['The Sahara is a famous?', 'Desert', 'Forest', 'Ocean', 'Mountain'],
    ['Land surrounded by water on all sides is?', 'Island', 'Peninsula', 'Cape', 'Bay'],
    ['The North Pole is in the?', 'Arctic', 'Antarctic', 'Pacific', 'Atlantic'],
    ['A map shows what?', 'Places', 'Time', 'Weather only', 'Animals'],
    ['Earth has how many poles?', 'Two', 'One', 'Three', 'Four'],
    ['The color blue on a map usually shows?', 'Water', 'Forest', 'Desert', 'Mountains'],
    ['Rivers flow into the?', 'Sea or ocean', 'Sky', 'Mountains', 'Desert'],
    ['What shape is the Earth?', 'Sphere', 'Flat', 'Cube', 'Cone'],
    ['What is the longest river in the world?', 'Nile', 'Amazon', 'Mississippi', 'Yangtze'],
    ['Many trees growing together form a?', 'Forest', 'Desert', 'Ocean', 'Mountain'],
    ['Penguins live on which continent?', 'Antarctica', 'Africa', 'Asia', 'Europe'],
    ['A compass points to which direction?', 'North', 'South', 'East', 'West'],
    ['The Amazon is a famous?', 'River', 'Mountain', 'Desert', 'Lake'],
    ['Volcanoes produce hot liquid called?', 'Lava', 'Water', 'Oil', 'Mud'],
    ['Kangaroos live on which continent?', 'Australia', 'Africa', 'Asia', 'South America'],
    ['Mount Everest is the tallest?', 'Mountain', 'Building', 'Tree', 'Tower'],
    ['The equator divides Earth into how many halves?', 'Two', 'Three', 'Four', 'Six'],
    ['Which country has the most people?', 'India', 'China', 'USA', 'Brazil'],
    ['A desert is very?', 'Dry', 'Wet', 'Cold', 'Green'],
    ['Which planet do we live on?', 'Earth', 'Mars', 'Venus', 'Jupiter'],
    ['The Atlantic is a type of?', 'Ocean', 'River', 'Lake', 'Sea'],
    ['Snow falls in which type of weather?', 'Cold', 'Hot', 'Windy', 'Rainy'],
    ['A very large piece of moving ice is called?', 'Glacier', 'Iceberg', 'Snowball', 'Frost'],
    ['Africa is a?', 'Continent', 'Country', 'City', 'Ocean'],
    ['What keeps us on the ground?', 'Gravity', 'Wind', 'Magnets', 'Air'],
    ['Cacti grow in which type of place?', 'Desert', 'Forest', 'Ocean', 'Mountain'],
    ['What is the capital of the United States?', 'Washington D.C.', 'New York', 'Los Angeles', 'Chicago'],
    ['The North and South Poles are very?', 'Cold', 'Hot', 'Wet', 'Dry'],
    ['Land next to the sea is called?', 'Coast', 'Valley', 'Plain', 'Hill'],
    ['What is the second largest continent?', 'Africa', 'Asia', 'Europe', 'North America'],
    ['A lake is surrounded by?', 'Land', 'Ocean', 'Rivers', 'Mountains only'],
    ['What is the largest island in the world?', 'Greenland', 'Australia', 'Madagascar', 'Borneo'],
    ['Coral reefs are found in the?', 'Ocean', 'Lake', 'River', 'Desert'],
    ['The South Pole is on which continent?', 'Antarctica', 'Arctic', 'Australia', 'Africa'],
    ['Rain, snow, and hail are types of?', 'Precipitation', 'Wind', 'Sunshine', 'Clouds'],
    ['A globe is a model of?', 'Earth', 'Moon', 'Sun', 'Mars'],
    ['Brazil is in which continent?', 'South America', 'North America', 'Europe', 'Africa'],
    ['The sun sets in which direction?', 'West', 'East', 'North', 'South'],
    ['An area with very many trees is called a?', 'Jungle', 'Desert', 'Prairie', 'Tundra'],
  ],
  2: [
    ['The Great Barrier Reef is near which country?', 'Australia', 'Brazil', 'Japan', 'India'],
    ['The Sahara is the largest hot desert on which continent?', 'Africa', 'Asia', 'Australia', 'South America'],
    ['The Nile River is in which continent?', 'Africa', 'Asia', 'Europe', 'South America'],
    ['Mount Everest is in which mountain range?', 'Himalayas', 'Andes', 'Alps', 'Rockies'],
    ['How many states does the United States have?', '50', '48', '52', '45'],
    ['What is the capital of France?', 'Paris', 'London', 'Rome', 'Madrid'],
    ['The Amazon Rainforest is in which continent?', 'South America', 'Africa', 'Asia', 'North America'],
    ['What ocean is between America and Europe?', 'Atlantic', 'Pacific', 'Indian', 'Arctic'],
    ['Japan is made up of many?', 'Islands', 'Mountains', 'Lakes', 'Rivers'],
    ['The Mississippi River is in which country?', 'United States', 'Canada', 'Mexico', 'Brazil'],
    ['What is the driest continent?', 'Antarctica', 'Africa', 'Australia', 'Asia'],
    ['The Great Wall is in which country?', 'China', 'Japan', 'India', 'Korea'],
    ['Imaginary lines going east-west on a map are?', 'Latitude', 'Longitude', 'Equator', 'Meridian'],
    ['The Indian Ocean is south of which continent?', 'Asia', 'Europe', 'Africa', 'North America'],
    ['A peninsula is land surrounded on how many sides?', 'Three', 'Two', 'Four', 'One'],
    ['What is the capital of Japan?', 'Tokyo', 'Osaka', 'Kyoto', 'Beijing'],
    ['The Andes Mountains are in which continent?', 'South America', 'North America', 'Europe', 'Asia'],
    ['What is the deepest ocean?', 'Pacific', 'Atlantic', 'Indian', 'Arctic'],
    ['The Danube River flows through which continent?', 'Europe', 'Asia', 'Africa', 'South America'],
    ['An archipelago is a group of?', 'Islands', 'Mountains', 'Lakes', 'Rivers'],
    ['The Gobi Desert is in which continent?', 'Asia', 'Africa', 'Australia', 'Europe'],
    ['What is the capital of Australia?', 'Canberra', 'Sydney', 'Melbourne', 'Perth'],
    ['The Mediterranean Sea is between Europe and?', 'Africa', 'Asia', 'Australia', 'Americas'],
    ['Imaginary lines going north-south on a map are?', 'Longitude', 'Latitude', 'Equator', 'Tropics'],
    ['The Yangtze River is in which country?', 'China', 'India', 'Japan', 'Russia'],
    ['What is the largest lake in Africa?', 'Lake Victoria', 'Lake Chad', 'Lake Tanganyika', 'Lake Malawi'],
    ['The Rocky Mountains are in which country?', 'United States', 'Canada only', 'Mexico', 'Brazil'],
    ['A plateau is a flat area that is?', 'Elevated', 'Below sea level', 'Underwater', 'Moving'],
    ['What is the capital of Brazil?', 'Brasilia', 'Rio de Janeiro', 'Sao Paulo', 'Salvador'],
    ['The Congo River is in which continent?', 'Africa', 'South America', 'Asia', 'Europe'],
    ['The Pacific Ring of Fire is known for?', 'Volcanoes', 'Forests', 'Deserts', 'Rivers'],
    ['What is the smallest country in the world?', 'Vatican City', 'Monaco', 'San Marino', 'Liechtenstein'],
    ['The Ganges River is in which country?', 'India', 'Pakistan', 'Bangladesh only', 'Nepal'],
    ['An oasis is found in a?', 'Desert', 'Forest', 'Mountain', 'Ocean'],
    ['What is the capital of Canada?', 'Ottawa', 'Toronto', 'Vancouver', 'Montreal'],
    ['The Red Sea is between Africa and?', 'Asia', 'Europe', 'Australia', 'Americas'],
    ['The Kalahari Desert is in which continent?', 'Africa', 'Asia', 'Australia', 'South America'],
    ['A narrow waterway between two land masses is?', 'Strait', 'Bay', 'Gulf', 'Canal'],
    ['The Thames River is in which city?', 'London', 'Paris', 'Berlin', 'Rome'],
    ['Hawaii is a US state made of?', 'Islands', 'Mountains', 'Plains', 'Deserts'],
    ['What is the capital of China?', 'Beijing', 'Shanghai', 'Hong Kong', 'Tokyo'],
    ['The Ural Mountains separate Europe and?', 'Asia', 'Africa', 'Americas', 'Australia'],
    ['A bay is a body of water partly enclosed by?', 'Land', 'Ice', 'Sand', 'Rocks only'],
    ['What is the capital of Egypt?', 'Cairo', 'Alexandria', 'Luxor', 'Giza'],
    ['The Dead Sea is the lowest point on?', 'Earth', 'Asia only', 'Middle East only', 'Africa'],
    ['The Black Forest is in which country?', 'Germany', 'France', 'Austria', 'Switzerland'],
    ['What is the capital of Mexico?', 'Mexico City', 'Cancun', 'Guadalajara', 'Monterrey'],
    ['The Tigris and Euphrates rivers are in?', 'Middle East', 'Africa', 'Europe', 'South Asia'],
    ['A delta forms at the mouth of a?', 'River', 'Lake', 'Ocean', 'Mountain'],
    ['What is the capital of Russia?', 'Moscow', 'St. Petersburg', 'Kiev', 'Minsk'],
  ],
  3: [
    ['The Prime Meridian passes through which city?', 'Greenwich', 'Paris', 'New York', 'Rome'],
    ['The largest freshwater lake by area is?', 'Lake Superior', 'Lake Victoria', 'Lake Baikal', 'Lake Michigan'],
    ['The Tropic of Cancer is at what latitude?', '23.5 degrees north', '23.5 degrees south', '45 degrees north', '66.5 degrees north'],
    ['The Mariana Trench is in which ocean?', 'Pacific', 'Atlantic', 'Indian', 'Arctic'],
    ['The Strait of Gibraltar separates Europe from?', 'Africa', 'Asia', 'Americas', 'Australia'],
    ['Lake Baikal is the deepest lake in which country?', 'Russia', 'China', 'Canada', 'USA'],
    ['What is the longest mountain range on land?', 'Andes', 'Himalayas', 'Rockies', 'Alps'],
    ['The Suez Canal is in which country?', 'Egypt', 'Turkey', 'Panama', 'Israel'],
    ['The International Date Line is near which degree?', '180th meridian', '0 degrees', '90th meridian', '45th meridian'],
    ['What is the capital of South Africa (executive)?', 'Pretoria', 'Cape Town', 'Johannesburg', 'Durban'],
    ['The Alps are in which continent?', 'Europe', 'Asia', 'South America', 'Africa'],
    ['The Caspian Sea is actually the largest?', 'Lake', 'Sea', 'Ocean', 'Bay'],
    ['What is the capital of Argentina?', 'Buenos Aires', 'Santiago', 'Lima', 'Montevideo'],
    ['The Ring of Fire is in which ocean?', 'Pacific', 'Atlantic', 'Indian', 'Arctic'],
    ['The Mekong River flows through how many countries?', 'Six', 'Four', 'Eight', 'Three'],
    ['What is the highest waterfall in the world?', 'Angel Falls', 'Niagara Falls', 'Victoria Falls', 'Iguazu Falls'],
    ['The Panama Canal connects which two oceans?', 'Atlantic and Pacific', 'Indian and Pacific', 'Atlantic and Indian', 'Arctic and Pacific'],
    ['Mount Kilimanjaro is in which country?', 'Tanzania', 'Kenya', 'Uganda', 'Ethiopia'],
    ['What is the largest country in Africa by area?', 'Algeria', 'Congo', 'Sudan', 'Nigeria'],
    ['The Strait of Hormuz is near which gulf?', 'Persian Gulf', 'Gulf of Mexico', 'Gulf of Aden', 'Gulf of Oman'],
    ['The Danube flows into which sea?', 'Black Sea', 'Mediterranean', 'Caspian', 'Baltic'],
    ['What type of climate is near the equator?', 'Tropical', 'Arctic', 'Desert', 'Temperate'],
    ['The Atacama is the driest what?', 'Desert', 'Forest', 'Mountain', 'Valley'],
    ['The Great Lakes are between the US and?', 'Canada', 'Mexico', 'Cuba', 'Britain'],
    ['What is the capital of Turkey?', 'Ankara', 'Istanbul', 'Izmir', 'Antalya'],
    ['The Volga is the longest river in which continent?', 'Europe', 'Asia', 'Africa', 'South America'],
    ['The Mojave Desert is in which country?', 'United States', 'Mexico', 'Australia', 'Egypt'],
    ['What is the capital of Kenya?', 'Nairobi', 'Mombasa', 'Kampala', 'Addis Ababa'],
    ['The Bering Strait separates Asia from?', 'North America', 'Europe', 'Africa', 'South America'],
    ['The largest island in the Mediterranean is?', 'Sicily', 'Crete', 'Sardinia', 'Cyprus'],
    ['The Congo Basin is mostly covered by?', 'Rainforest', 'Desert', 'Grassland', 'Tundra'],
    ['What is the capital of Thailand?', 'Bangkok', 'Hanoi', 'Jakarta', 'Manila'],
    ['The Sahel region is south of which desert?', 'Sahara', 'Gobi', 'Kalahari', 'Atacama'],
    ['The Zambezi River has which famous waterfall?', 'Victoria Falls', 'Angel Falls', 'Niagara', 'Iguazu'],
    ['What is the capital of Germany?', 'Berlin', 'Munich', 'Hamburg', 'Frankfurt'],
    ['The Patagonia region is in which continent?', 'South America', 'Europe', 'Africa', 'Australia'],
    ['Lake Titicaca is the highest navigable lake in?', 'South America', 'Asia', 'Africa', 'Europe'],
    ['What is the capital of Nigeria?', 'Abuja', 'Lagos', 'Accra', 'Dakar'],
    ['The tundra is found near which pole?', 'North', 'South', 'Both equally', 'Neither'],
    ['The English Channel separates England and?', 'France', 'Ireland', 'Spain', 'Belgium'],
    ['The driest desert in the world is?', 'Atacama', 'Sahara', 'Gobi', 'Mojave'],
    ['Mount Fuji is in which country?', 'Japan', 'China', 'Korea', 'Nepal'],
    ['What is the capital of Indonesia?', 'Jakarta', 'Bali', 'Surabaya', 'Bandung'],
    ['The Strait of Malacca is between Malaysia and?', 'Sumatra', 'Borneo', 'Java', 'Philippines'],
    ['The Outback is in which country?', 'Australia', 'South Africa', 'Brazil', 'India'],
    ['What is the capital of Saudi Arabia?', 'Riyadh', 'Mecca', 'Medina', 'Jeddah'],
    ['The Mackenzie River is in which country?', 'Canada', 'USA', 'Russia', 'Australia'],
    ['The Horn of Africa includes Somalia and?', 'Ethiopia', 'Nigeria', 'Ghana', 'Kenya'],
    ['The Ross Ice Shelf is in?', 'Antarctica', 'Arctic', 'Greenland', 'Iceland'],
    ['What is the capital of South Korea?', 'Seoul', 'Busan', 'Tokyo', 'Pyongyang'],
  ],
  4: [
    ['The Tropic of Capricorn passes through how many continents?', 'Three', 'Two', 'Four', 'Five'],
    ['The deepest point in the ocean is?', 'Challenger Deep', 'Mariana Trench only', 'Puerto Rico Trench', 'Java Trench'],
    ['The Horn of Africa juts into which ocean?', 'Indian', 'Atlantic', 'Pacific', 'Arctic'],
    ['Lake Chad is shrinking in which continent?', 'Africa', 'Asia', 'Europe', 'South America'],
    ['What is the capital of Colombia?', 'Bogota', 'Lima', 'Quito', 'Caracas'],
    ['The Deccan Plateau is in which country?', 'India', 'Pakistan', 'China', 'Iran'],
    ['The Carpathian Mountains are in which continent?', 'Europe', 'Asia', 'Africa', 'South America'],
    ['What is the longest river in Asia?', 'Yangtze', 'Ganges', 'Mekong', 'Indus'],
    ['The Aral Sea is between Kazakhstan and?', 'Uzbekistan', 'Turkmenistan', 'Tajikistan', 'Kyrgyzstan'],
    ['Mount Elbrus is the highest peak in?', 'Europe', 'Asia', 'Africa', 'South America'],
    ['What is the capital of Peru?', 'Lima', 'Bogota', 'Quito', 'Santiago'],
    ['The Sundarbans mangrove forest is in?', 'Bangladesh and India', 'Myanmar', 'Thailand', 'Indonesia'],
    ['The Pennines are mountains in which country?', 'England', 'Scotland', 'France', 'Germany'],
    ['What is the largest country in South America?', 'Brazil', 'Argentina', 'Colombia', 'Peru'],
    ['The Ob River is in which country?', 'Russia', 'China', 'Canada', 'India'],
    ['The Great Rift Valley is in which continent?', 'Africa', 'Asia', 'Europe', 'South America'],
    ['What is the capital of Iran?', 'Tehran', 'Baghdad', 'Riyadh', 'Kabul'],
    ['The Gobi Desert spans Mongolia and?', 'China', 'Russia', 'Kazakhstan', 'India'],
    ['The Orinoco River is in which continent?', 'South America', 'Africa', 'Asia', 'Europe'],
    ['What is the smallest ocean?', 'Arctic', 'Indian', 'Atlantic', 'Pacific'],
    ['The Atlas Mountains are in which continent?', 'Africa', 'Europe', 'Asia', 'South America'],
    ['Lake Tanganyika is in which continent?', 'Africa', 'Asia', 'South America', 'Europe'],
    ['The Drakensberg Mountains are in?', 'South Africa', 'Kenya', 'Tanzania', 'Nigeria'],
    ['The Huang He River is also known as?', 'Yellow River', 'Red River', 'Blue River', 'White River'],
    ['What is the capital of the Philippines?', 'Manila', 'Bangkok', 'Jakarta', 'Hanoi'],
    ['The fjords are found in which country?', 'Norway', 'Sweden', 'Denmark', 'Finland'],
    ['Borneo is shared by how many countries?', 'Three', 'Two', 'Four', 'One'],
    ['What is the capital of Pakistan?', 'Islamabad', 'Karachi', 'Lahore', 'Peshawar'],
    ['The Pyrenees separate France and?', 'Spain', 'Italy', 'Germany', 'Switzerland'],
    ['The Okavango Delta is in which country?', 'Botswana', 'South Africa', 'Namibia', 'Zimbabwe'],
    ['The second longest river in the world is?', 'Amazon', 'Yangtze', 'Mississippi', 'Congo'],
    ['The Appalachian Mountains are in which country?', 'United States', 'Canada', 'Mexico', 'Brazil'],
    ['Lake Malawi is in which continent?', 'Africa', 'Asia', 'South America', 'Europe'],
    ['What is the capital of Ethiopia?', 'Addis Ababa', 'Nairobi', 'Mogadishu', 'Khartoum'],
    ['The Karakoram Range is in which region?', 'South Asia', 'East Asia', 'Central Asia', 'Middle East'],
    ['The Murray River is the longest in?', 'Australia', 'New Zealand', 'Indonesia', 'Papua New Guinea'],
    ['What is the capital of Vietnam?', 'Hanoi', 'Ho Chi Minh City', 'Bangkok', 'Manila'],
    ['The Namib Desert is in which continent?', 'Africa', 'Asia', 'Australia', 'South America'],
    ['The Caucasus Mountains separate Europe and?', 'Asia', 'Africa', 'Americas', 'Australia'],
    ['What is the capital of Malaysia?', 'Kuala Lumpur', 'Singapore', 'Jakarta', 'Bangkok'],
    ['The Brahmaputra River starts in?', 'Tibet', 'Nepal', 'India', 'Bangladesh'],
    ['The Pampas are grasslands in?', 'Argentina', 'Brazil', 'Chile', 'Peru'],
    ['What is the capital of Iraq?', 'Baghdad', 'Tehran', 'Damascus', 'Riyadh'],
    ['The Arabian Desert is the largest desert in?', 'Asia', 'Africa', 'Europe', 'Australia'],
    ['What is the capital of Chile?', 'Santiago', 'Lima', 'Buenos Aires', 'Montevideo'],
    ['The Hindu Kush mountains are in?', 'Afghanistan and Pakistan', 'India', 'China', 'Iran'],
    ['The Maldives is in which ocean?', 'Indian', 'Pacific', 'Atlantic', 'Arctic'],
    ['What is the capital of Morocco?', 'Rabat', 'Casablanca', 'Marrakech', 'Fez'],
    ['The Siberian plains are in which country?', 'Russia', 'China', 'Mongolia', 'Kazakhstan'],
    ['The Thar Desert is in which two countries?', 'India and Pakistan', 'Iran and Iraq', 'Egypt and Libya', 'China and Mongolia'],
  ],
  5: [
    ['The Roaring Forties are winds at which latitude?', '40 degrees south', '40 degrees north', '60 degrees south', '30 degrees south'],
    ['What is the largest delta in the world?', 'Ganges-Brahmaputra', 'Nile', 'Mississippi', 'Mekong'],
    ['The Kamchatka Peninsula is in which country?', 'Russia', 'Japan', 'Canada', 'Alaska'],
    ['Lake Ladoga is the largest lake in?', 'Europe', 'Asia', 'Africa', 'North America'],
    ['What is the capital of Kazakhstan?', 'Astana', 'Almaty', 'Tashkent', 'Bishkek'],
    ['The Irrawaddy River is in which country?', 'Myanmar', 'Thailand', 'Vietnam', 'Laos'],
    ['What is the highest plateau in the world?', 'Tibetan Plateau', 'Deccan Plateau', 'Colorado Plateau', 'Ethiopian Plateau'],
    ['The Strait of Magellan is near which continent?', 'South America', 'Africa', 'Asia', 'Australia'],
    ['The Dasht-e-Kavir is a desert in?', 'Iran', 'Iraq', 'Saudi Arabia', 'Pakistan'],
    ['What is the capital of Mongolia?', 'Ulaanbaatar', 'Astana', 'Bishkek', 'Lhasa'],
    ['The Blue Nile starts in which country?', 'Ethiopia', 'Sudan', 'Uganda', 'Egypt'],
    ['What is the capital of Myanmar?', 'Naypyidaw', 'Yangon', 'Mandalay', 'Bangkok'],
    ['The Falkland Islands are near which continent?', 'South America', 'Africa', 'Europe', 'Australia'],
    ['The Helmand River is in which country?', 'Afghanistan', 'Pakistan', 'Iran', 'Iraq'],
    ['What is the world\'s largest archipelago nation?', 'Indonesia', 'Philippines', 'Japan', 'Malaysia'],
    ['The Kalahari Desert spans how many countries?', 'Three', 'Two', 'Four', 'One'],
    ['The Drake Passage is between South America and?', 'Antarctica', 'Africa', 'Australia', 'Arctic'],
    ['What is the capital of Bangladesh?', 'Dhaka', 'Chittagong', 'Kolkata', 'Delhi'],
    ['The Taklamakan Desert is in which country?', 'China', 'Mongolia', 'Kazakhstan', 'Iran'],
    ['The Lena River flows into which ocean?', 'Arctic', 'Pacific', 'Atlantic', 'Indian'],
    ['What is the capital of Nepal?', 'Kathmandu', 'Dhaka', 'Colombo', 'Thimphu'],
    ['The Nullarbor Plain is in which country?', 'Australia', 'South Africa', 'Argentina', 'India'],
    ['The Strait of Bosporus is in which city?', 'Istanbul', 'Athens', 'Rome', 'Cairo'],
    ['What is the capital of Sri Lanka?', 'Colombo', 'Kandy', 'Dhaka', 'Chennai'],
    ['The Kunlun Mountains are in which country?', 'China', 'India', 'Nepal', 'Mongolia'],
    ['The Fraser River is in which country?', 'Canada', 'USA', 'Russia', 'Australia'],
    ['What is the capital of Afghanistan?', 'Kabul', 'Islamabad', 'Tehran', 'Tashkent'],
    ['Lake Turkana is in which country?', 'Kenya', 'Tanzania', 'Ethiopia', 'Uganda'],
    ['What is the highest peak in Africa?', 'Kilimanjaro', 'Mount Kenya', 'Atlas Peak', 'Ras Dashen'],
    ['The Pamir Mountains are called the Roof of the?', 'World', 'East', 'Sky', 'Mountains'],
    ['The Euphrates River starts in which country?', 'Turkey', 'Iraq', 'Syria', 'Iran'],
    ['What is the capital of Uzbekistan?', 'Tashkent', 'Samarkand', 'Bukhara', 'Astana'],
    ['The Dardanelles strait is in which country?', 'Turkey', 'Greece', 'Egypt', 'Italy'],
    ['What is the capital of Jordan?', 'Amman', 'Beirut', 'Damascus', 'Baghdad'],
    ['The Sargasso Sea is unique because it has no?', 'Land borders', 'Fish', 'Waves', 'Salt'],
    ['The Indus River starts in which region?', 'Tibet', 'Kashmir', 'Punjab', 'Nepal'],
    ['The Siachen Glacier is in which mountain range?', 'Karakoram', 'Himalayas', 'Hindu Kush', 'Andes'],
    ['The Gulf of Aden is near which country?', 'Yemen', 'Oman', 'Iran', 'Egypt'],
    ['The Makran Coast is in which country?', 'Pakistan', 'Iran', 'Oman', 'India'],
    ['The Sundarbans contain which type of forest?', 'Mangrove', 'Tropical', 'Coniferous', 'Deciduous'],
    ['The Karakoram Pass is between India and?', 'China', 'Pakistan', 'Nepal', 'Afghanistan'],
    ['What is the capital of Tanzania?', 'Dodoma', 'Dar es Salaam', 'Nairobi', 'Kampala'],
    ['The Zambezi River flows into which ocean?', 'Indian', 'Atlantic', 'Pacific', 'Arctic'],
    ['The Great Sandy Desert is in?', 'Australia', 'Africa', 'Asia', 'Middle East'],
    ['What is the capital of Venezuela?', 'Caracas', 'Bogota', 'Lima', 'Quito'],
    ['The Tian Shan mountains are in which region?', 'Central Asia', 'South Asia', 'East Asia', 'Middle East'],
    ['The Kerguelen Islands are in which ocean?', 'Indian', 'Pacific', 'Atlantic', 'Arctic'],
    ['The Mackenzie Delta is in which country?', 'Canada', 'Russia', 'USA', 'Norway'],
    ['The Tigris River starts in which country?', 'Turkey', 'Iraq', 'Syria', 'Iran'],
    ['What is the capital of Cuba?', 'Havana', 'Santiago', 'San Juan', 'Nassau'],
  ],
  6: [
    ['The Mercator projection distorts which regions most?', 'Poles', 'Equator', 'Tropics', 'Coasts'],
    ['The largest volcanic lake in the world is?', 'Lake Toba', 'Crater Lake', 'Lake Kivu', 'Lake Nyos'],
    ['The Kerguelen Plateau is in which ocean?', 'Indian', 'Pacific', 'Atlantic', 'Arctic'],
    ['Lake Volta is a reservoir in which country?', 'Ghana', 'Nigeria', 'Mali', 'Senegal'],
    ['What is the capital of Turkmenistan?', 'Ashgabat', 'Tashkent', 'Dushanbe', 'Bishkek'],
    ['The Danakil Depression is in which country?', 'Ethiopia', 'Eritrea', 'Djibouti', 'Somalia'],
    ['The Yenisei River flows into which ocean?', 'Arctic', 'Pacific', 'Atlantic', 'Indian'],
    ['The highest navigable lake in the world is?', 'Titicaca', 'Baikal', 'Victoria', 'Superior'],
    ['The Sunda Strait separates Java from?', 'Sumatra', 'Borneo', 'Bali', 'Sulawesi'],
    ['The Rub al Khali desert is mostly in?', 'Saudi Arabia', 'Oman', 'Yemen', 'UAE'],
    ['What is the capital of Laos?', 'Vientiane', 'Hanoi', 'Phnom Penh', 'Bangkok'],
    ['The Maldives are threatened by?', 'Rising sea levels', 'Earthquakes', 'Drought', 'Volcanoes'],
    ['The Limpopo River is in which continent?', 'Africa', 'Asia', 'South America', 'Europe'],
    ['What is the capital of Kyrgyzstan?', 'Bishkek', 'Tashkent', 'Astana', 'Dushanbe'],
    ['The Ogallala Aquifer is in which country?', 'United States', 'Canada', 'Mexico', 'Brazil'],
    ['The Weddell Sea is near which continent?', 'Antarctica', 'South America', 'Africa', 'Australia'],
    ['The largest plateau in Africa is?', 'East African Plateau', 'Saharan Plateau', 'Ethiopian Plateau', 'Karoo Plateau'],
    ['The Syr Darya river flows into which sea?', 'Aral Sea', 'Caspian Sea', 'Black Sea', 'Red Sea'],
    ['What is the capital of Ecuador?', 'Quito', 'Guayaquil', 'Lima', 'Bogota'],
    ['The Zagros Mountains are in which country?', 'Iran', 'Iraq', 'Turkey', 'Pakistan'],
    ['The Ob River flows into which ocean?', 'Arctic', 'Pacific', 'Indian', 'Atlantic'],
    ['What is the capital of Tajikistan?', 'Dushanbe', 'Tashkent', 'Bishkek', 'Kabul'],
    ['The Chagos Archipelago is in which ocean?', 'Indian', 'Pacific', 'Atlantic', 'Arctic'],
    ['Lake Balkhash is in which country?', 'Kazakhstan', 'Uzbekistan', 'Russia', 'Kyrgyzstan'],
    ['What is the capital of Bolivia?', 'Sucre', 'La Paz', 'Santa Cruz', 'Cochabamba'],
    ['The Barents Sea is part of which ocean?', 'Arctic', 'Atlantic', 'Pacific', 'Indian'],
    ['The Western Ghats are in which country?', 'India', 'Pakistan', 'Sri Lanka', 'Nepal'],
    ['The driest inhabited continent is?', 'Australia', 'Africa', 'Asia', 'Europe'],
    ['The Strait of Messina separates Italy from?', 'Sicily', 'Sardinia', 'Corsica', 'Malta'],
    ['The Amu Darya once flowed into which sea?', 'Aral Sea', 'Caspian Sea', 'Black Sea', 'Red Sea'],
    ['What is the capital of Paraguay?', 'Asuncion', 'Montevideo', 'La Paz', 'Santiago'],
    ['McMurdo Station is on which continent?', 'Antarctica', 'Arctic', 'Australia', 'South America'],
    ['The Sargasso Sea is in which ocean?', 'Atlantic', 'Pacific', 'Indian', 'Arctic'],
    ['The largest island in the Indian Ocean is?', 'Madagascar', 'Sri Lanka', 'Sumatra', 'Borneo'],
    ['The Virunga Mountains have which rare animals?', 'Mountain gorillas', 'Snow leopards', 'Pandas', 'Polar bears'],
    ['The Dnieper River flows through which capital?', 'Kyiv', 'Moscow', 'Warsaw', 'Minsk'],
    ['What is the capital of Honduras?', 'Tegucigalpa', 'San Salvador', 'Managua', 'Guatemala City'],
    ['The Coral Sea is near which country?', 'Australia', 'Japan', 'Philippines', 'Indonesia'],
    ['What is the capital of Ghana?', 'Accra', 'Abuja', 'Dakar', 'Lome'],
    ['The Kerch Strait connects which two seas?', 'Black and Azov', 'Black and Caspian', 'Mediterranean and Black', 'Red and Arabian'],
    ['The Rwenzori Mountains are in which country?', 'Uganda', 'Kenya', 'Tanzania', 'Congo'],
    ['What is the capital of Mozambique?', 'Maputo', 'Beira', 'Lusaka', 'Harare'],
    ['The Labrador Current flows in which ocean?', 'Atlantic', 'Pacific', 'Arctic', 'Indian'],
    ['The Vinson Massif is the highest peak in?', 'Antarctica', 'Arctic', 'Greenland', 'Iceland'],
    ['What is the capital of Cameroon?', 'Yaounde', 'Douala', 'Lagos', 'Libreville'],
    ['The Gulf Stream originates in which gulf?', 'Gulf of Mexico', 'Gulf of Aden', 'Persian Gulf', 'Gulf of Guinea'],
    ['Torres Strait separates Australia from?', 'Papua New Guinea', 'Indonesia', 'New Zealand', 'Fiji'],
    ['What is the capital of Eritrea?', 'Asmara', 'Addis Ababa', 'Mogadishu', 'Djibouti'],
    ['Svalbard archipelago belongs to which country?', 'Norway', 'Denmark', 'Sweden', 'Finland'],
    ['The Fennoscandian Shield covers which region?', 'Scandinavia', 'Balkans', 'Iberia', 'Alps'],
  ],
};
