import type { Fact } from './group1';

export { nba } from './nba';
export { nhl } from './nhl';
export { canadianHistory } from './canadianHistory';

export const sports: Record<number, Fact[]> = {
  1: [
    ['How many players on a soccer team on the field?', '11', '9', '10', '12'],
    ['What sport do you play with a round orange ball?', 'Basketball', 'Football', 'Tennis', 'Golf'],
    ['What colour is a tennis ball?', 'Yellow-green', 'White', 'Orange', 'Red'],
    ['How many rings are on the Olympic flag?', '5', '3', '4', '6'],
    ['What sport does Dwayne "The Rock" Johnson come from?', 'WWE/Wrestling', 'Boxing', 'Football', 'MMA'],
    ['What do you hit in badminton?', 'Shuttlecock', 'Ball', 'Puck', 'Disc'],
    ['What do WWE wrestlers fight inside?', 'A ring', 'An octagon', 'A cage', 'A court'],
    ['In soccer, who can use their hands?', 'Goalkeeper', 'Striker', 'Midfielder', 'Defender'],
    ['What sport do Messi and Ronaldo play?', 'Football/Soccer', 'Tennis', 'Basketball', 'Rugby'],
    ['What sport is played with sticks and a ball on a grass field?', 'Field hockey', 'Tennis', 'Golf', 'Badminton'],
    ['What do you try to score in soccer?', 'Goal', 'Point', 'Basket', 'Run'],
    ['What do Formula 1 drivers race in?', 'Race cars', 'Motorcycles', 'Go-karts', 'Trucks'],
    ['How many holes are on a standard golf course?', '18', '9', '12', '15'],
    ['What do you throw in bowling?', 'Bowling ball', 'Pin', 'Disc', 'Stone'],
    ['What does WWE stand for?', 'World Wrestling Entertainment', 'World Wide Entertainment', 'Wrestling World Event', 'World Wrestling Exhibition'],
    ['Which sport uses a net and racket?', 'Tennis', 'Soccer', 'Swimming', 'Running'],
    ['What do runners run on at the Olympics?', 'Track', 'Road', 'Grass', 'Sand'],
    ['What sport do you ride a bicycle in?', 'Cycling', 'Swimming', 'Running', 'Rowing'],
    ['What do you kick in soccer?', 'Ball', 'Puck', 'Shuttlecock', 'Stone'],
    ['What do boxers wear on their hands?', 'Gloves', 'Mittens', 'Wraps', 'Nothing'],
    ['Where are the Olympics held?', 'Different country each time', 'Always in Greece', 'Always in USA', 'Always in France'],
    ['What is the most popular football league in England called?', 'Premier League', 'La Liga', 'Serie A', 'Bundesliga'],
    ['What do you do in a relay race?', 'Pass a baton', 'Kick a ball', 'Throw a disc', 'Hit a puck'],
    ['What animal is a race with horses called?', 'Horse racing', 'Dog racing', 'Cat racing', 'Bird racing'],
    ['What sport is played by hitting a small ball against a wall with a racket?', 'Squash', 'Tennis', 'Badminton', 'Table tennis'],
    ['What colour belt is highest in karate?', 'Black', 'White', 'Red', 'Yellow'],
    ['In which team sport do players tag opponents while chanting "kabaddi"?', 'Kabaddi', 'Rugby', 'Wrestling', 'Handball'],
    ['How many players on a basketball team on court?', '5', '6', '7', '4'],
    ['What do you score through in basketball?', 'Hoop/basket', 'Goal', 'Net', 'Ring'],
    ['What does a WWE referee count to for a pinfall?', '3', '5', '10', '7'],
    ['Which boxer was known as "The Greatest"?', 'Muhammad Ali', 'Mike Tyson', 'Floyd Mayweather', 'Manny Pacquiao'],
    ['What sport uses a white ball with dimples?', 'Golf', 'Tennis', 'Cricket', 'Baseball'],
    ['What do you call the person who runs a race?', 'Runner', 'Swimmer', 'Rider', 'Player'],
    ['What sport is Michael Phelps famous for?', 'Swimming', 'Running', 'Cycling', 'Gymnastics'],
    ['What sport is Usain Bolt famous for?', 'Sprinting', 'Swimming', 'Jumping', 'Throwing'],
    ['What do you wear to protect your head in cycling?', 'Helmet', 'Hat', 'Cap', 'Headband'],
    ['How many goals does a soccer net have on each end?', '1', '2', '3', '0'],
    ['What colour shirt does the Brazil football team wear?', 'Yellow', 'Blue', 'Green', 'White'],
    ['How many players are on a field hockey team?', '11', '9', '10', '12'],
    ['What NBA team plays in Toronto?', 'Raptors', 'Lakers', 'Celtics', 'Bulls'],
    ['What shape is the UFC fighting area?', 'Octagon', 'Circle', 'Square', 'Rectangle'],
    ['What is the most popular sport in Canada?', 'Ice hockey', 'Basketball', 'Soccer', 'Baseball'],
    ['Who is John Cena famous as?', 'WWE wrestler', 'Boxer', 'Football player', 'MMA fighter'],
    ['What sport is played with a heavy ball and pins?', 'Bowling', 'Cricket', 'Golf', 'Tennis'],
    ['What do tennis players hit the ball over?', 'Net', 'Wall', 'Fence', 'Rope'],
    ['In which sport do athletes jump over hurdles?', 'Track and field', 'Swimming', 'Cycling', 'Tennis'],
    ['What is the Olympic motto?', 'Faster, Higher, Stronger', 'Win at all costs', 'Be the best', 'Play fair'],
    ['Where were the ancient Olympics held?', 'Greece', 'Rome', 'Egypt', 'China'],
    ['What do you hit a golf ball with?', 'Golf club', 'Bat', 'Racket', 'Stick'],
    ['What is a marathon?', 'A very long running race', 'Short sprint', 'Swimming race', 'Cycling race'],
  ],
  2: [
    ['How long is an Olympic swimming pool?', '50 meters', '25 meters', '100 meters', '75 meters'],
    ['What country is soccer called "football" in?', 'Most countries', 'Only USA', 'Only Canada', 'Only Australia'],
    ['Which sport has a slam dunk?', 'Basketball', 'Tennis', 'Volleyball', 'Soccer'],
    ['What are the five Olympic ring colours?', 'Blue, yellow, black, green, red', 'Red, white, blue, green, gold', 'All rainbow', 'Red, blue, green, yellow, white'],
    ['How often are the Summer Olympics held?', 'Every 4 years', 'Every 2 years', 'Every year', 'Every 5 years'],
    ['What is the Tour de France?', 'Famous cycling race', 'Running race', 'Car race', 'Swimming race'],
    ['What is the biggest WWE event of the year called?', 'WrestleMania', 'Royal Rumble', 'SummerSlam', 'Survivor Series'],
    ['What is a "derby" in football?', 'A match between local rivals', 'A cup final', 'A friendly match', 'A league opener'],
    ['In which Olympic sport has Pakistan won the most gold medals?', 'Field hockey', 'Cricket', 'Squash', 'Wrestling'],
    ['What is the World Cup in soccer?', 'Global tournament every 4 years', 'Weekly league', 'Annual cup', 'Monthly match'],
    ['Which animal is on the Ferrari F1 logo?', 'Horse', 'Bull', 'Eagle', 'Lion'],
    ['What is The Undertaker\'s nickname in WWE?', 'The Deadman', 'The Animal', 'The Viper', 'The Beast'],
    ['How does a Formula 1 race start?', 'Lights go out', 'A flag drops', 'A horn sounds', 'A whistle blows'],
    ['What sport is Serena Williams famous for?', 'Tennis', 'Swimming', 'Golf', 'Running'],
    ['How many sets does a tennis player need to win (men\'s)?', '3 out of 5', '2 out of 3', '4 out of 7', '1'],
    ['What is a "penalty kick" in soccer?', 'Free kick from the penalty spot', 'Corner kick', 'Goal kick', 'Throw-in'],
    ['How long is a soccer match?', '90 minutes', '60 minutes', '120 minutes', '45 minutes'],
    ['What is a "hat-trick" in soccer?', '3 goals by one player in a match', '3 assists', '3 saves', '3 fouls'],
    ['What colour card means a player is sent off?', 'Red', 'Yellow', 'Green', 'Blue'],
    ['What colour card is a warning in soccer?', 'Yellow', 'Red', 'White', 'Blue'],
    ['What does FIFA stand for?', 'International Federation of Association Football', 'Football In Free Association', 'First International Football Awards', 'Federal Institute For Athletics'],
    ['What sport is LeBron James known for?', 'Basketball', 'Football', 'Baseball', 'Soccer'],
    ['What does "MMA" stand for?', 'Mixed Martial Arts', 'Modern Martial Arts', 'Multiple Martial Arts', 'Major Martial Arts'],
    ['How many quarters in a basketball game?', '4', '2', '3', '6'],
    ['What is "offside" in soccer?', 'Player ahead of last defender', 'Out of bounds', 'Handball', 'Foul play'],
    ['What surface is Wimbledon tennis played on?', 'Grass', 'Clay', 'Hard court', 'Carpet'],
    ['Where is Wimbledon held?', 'London, England', 'Paris, France', 'New York, USA', 'Melbourne, Australia'],
    ['What sport uses the term "ace"?', 'Tennis', 'Soccer', 'Swimming', 'Boxing'],
    ['In which weight class did Muhammad Ali box?', 'Heavyweight', 'Middleweight', 'Lightweight', 'Welterweight'],
    ['Which country dominated world squash for decades?', 'Pakistan', 'Egypt', 'England', 'Australia'],
    ['How many points is a 3-pointer in basketball?', '3', '2', '1', '4'],
    ['What sport is the "Tour de France" part of?', 'Cycling', 'Running', 'Swimming', 'Driving'],
    ['What sport uses a "shuttlecock"?', 'Badminton', 'Tennis', 'Squash', 'Table tennis'],
    ['How many wrestlers compete in a WWE Royal Rumble match?', '30', '20', '40', '25'],
    ['In kabaddi, what must the raider keep doing while in the other half?', 'Chanting "kabaddi"', 'Clapping', 'Running in circles', 'Holding breath silently'],
    ['What sport does Lionel Messi play?', 'Soccer/Football', 'Basketball', 'Tennis', 'Baseball'],
    ['Which country did Messi play for?', 'Argentina', 'Brazil', 'Spain', 'Portugal'],
    ['What sport is Tiger Woods famous for?', 'Golf', 'Tennis', 'Cricket', 'Swimming'],
    ['What is a "free throw" in basketball?', 'Uncontested shot from the line', 'Pass to teammate', 'Dribbling', 'A block'],
    ['What is a "corner kick" in soccer?', 'Kick from the corner arc', 'Centre kick', 'Penalty kick', 'Goal kick'],
    ['What colour is a basketball?', 'Orange', 'White', 'Brown', 'Red'],
    ['How many teams play in the English Premier League?', '20', '18', '16', '22'],
    ['Which country dominates table tennis?', 'China', 'Japan', 'Sweden', 'Germany'],
    ['What is the famous Saturday night hockey show in Canada called?', 'Hockey Night in Canada', 'Canadian Hockey League', 'Saturday Night Hockey', 'The Hockey Show'],
    ['What is a "knockout" in boxing?', 'When a fighter cannot get up before a count of 10', 'A lucky punch', 'The first punch', 'A disqualification'],
    ['What does the referee blow to stop play?', 'Whistle', 'Horn', 'Bell', 'Drum'],
    ['Which La Liga club plays in all-white kit?', 'Real Madrid', 'Barcelona', 'Atletico Madrid', 'Sevilla'],
    ['What is Stone Cold Steve Austin\'s famous finishing move?', 'Stone Cold Stunner', 'RKO', 'Chokeslam', 'Pedigree'],
    ['How many rounds are in a standard championship boxing match?', '12', '10', '15', '8'],
    ['In what year did the Toronto Raptors win the NBA Championship?', '2019', '2018', '2020', '2017'],
  ],
  3: [
    ['In what year were the first modern Olympics held?', '1896', '1900', '1888', '1912'],
    ['Where were the first modern Olympics held?', 'Athens, Greece', 'Paris, France', 'London, England', 'Rome, Italy'],
    ['What is Formula 1?', 'Top-level car racing series', 'Running event', 'Swimming event', 'Cycling race'],
    ['How many Grand Slam tennis tournaments are there?', '4', '3', '5', '6'],
    ['Name the four Grand Slam tennis events.', 'Australian, French, Wimbledon, US Open', 'Wimbledon, French, Indian Wells, US Open', 'Australian, French, Italian, US Open', 'Wimbledon, Rogers, French, US Open'],
    ['What surface is the French Open played on?', 'Clay', 'Grass', 'Hard court', 'Carpet'],
    ['What surface is the US Open played on?', 'Hard court', 'Grass', 'Clay', 'Carpet'],
    ['What surface is the Australian Open played on?', 'Hard court', 'Clay', 'Grass', 'Carpet'],
    ['What country hosts the Tour de France?', 'France', 'Italy', 'Spain', 'Belgium'],
    ['How long is a marathon in kilometres?', '42.195 km', '40 km', '50 km', '36 km'],
    ['How many Olympic gold medals has Pakistan won in hockey?', '3', '2', '4', '1'],
    ['Who is considered the greatest Pakistani squash player ever?', 'Jahangir Khan', 'Jansher Khan', 'Qamar Zaman', 'Hashim Khan'],
    ['Which WWE superstar had a famous undefeated WrestleMania streak?', 'The Undertaker', 'John Cena', 'Triple H', 'Shawn Michaels'],
    ['Which football club is nicknamed "The Gunners"?', 'Arsenal', 'Chelsea', 'Liverpool', 'Tottenham'],
    ['What was Mike Tyson famous for in boxing?', 'Youngest ever heavyweight champion', 'Longest reign as champion', 'Most knockouts in history', 'Undefeated career'],
    ['What country hosted the 2016 Summer Olympics?', 'Brazil', 'China', 'UK', 'Japan'],
    ['In which city were the 2016 Olympics held?', 'Rio de Janeiro', 'Sao Paulo', 'Beijing', 'Tokyo'],
    ['What is a "grand slam" in tennis?', 'Winning all four major tournaments in one year', 'Winning one tournament', 'Playing in all events', 'A powerful serve'],
    ['What does "UFC" stand for?', 'Ultimate Fighting Championship', 'United Fighting Club', 'Universal Fight Challenge', 'Ultra Fight Championship'],
    ['What martial art is used most in MMA?', 'Mixed styles', 'Only karate', 'Only boxing', 'Only wrestling'],
    ['Which WWE superstar\'s finishing move is called the "RKO"?', 'Randy Orton', 'John Cena', 'The Rock', 'Batista'],
    ['Which F1 circuit is known as "The Temple of Speed"?', 'Monza', 'Silverstone', 'Monaco', 'Spa'],
    ['What Brazilian martial art is commonly used in MMA?', 'Brazilian Jiu-Jitsu', 'Capoeira', 'Muay Thai', 'Judo'],
    ['How many Grand Slam titles did Roger Federer win?', '20', '22', '18', '14'],
    ['What sport did Michael Jordan play?', 'Basketball', 'Baseball', 'Football', 'Golf'],
    ['Which NBA team did Michael Jordan play for?', 'Chicago Bulls', 'LA Lakers', 'Boston Celtics', 'Miami Heat'],
    ['What country did Pelé play soccer for?', 'Brazil', 'Argentina', 'Portugal', 'Spain'],
    ['How many FIFA World Cups has Brazil won?', '5', '4', '6', '3'],
    ['Which footballer has won the most Ballon d\'Or awards?', 'Lionel Messi', 'Cristiano Ronaldo', 'Michel Platini', 'Johan Cruyff'],
    ['How many Hockey World Cup titles has Pakistan won?', '4', '3', '5', '2'],
    ['Which player hit the famous bouncing buzzer-beater to eliminate Philadelphia in the 2019 NBA Playoffs?', 'Kawhi Leonard', 'Kyle Lowry', 'Pascal Siakam', 'Fred VanVleet'],
    ['How high is a basketball hoop from the ground?', '10 feet', '8 feet', '12 feet', '9 feet'],
    ['What is The Rock\'s finishing move called in WWE?', 'Rock Bottom', 'Stone Cold Stunner', 'RKO', 'Chokeslam'],
    ['In kabaddi, what is the player who crosses to the opposing side called?', 'Raider', 'Striker', 'Attacker', 'Chaser'],
    ['What is "par" in golf?', 'Expected number of strokes for a hole', 'Bonus point', 'Penalty', 'Extra round'],
    ['What is the "undercard" in a boxing event?', 'Fights before the main event', 'The final round', 'Training before the fight', 'Post-fight interview'],
    ['Which country hosted the 2022 FIFA World Cup?', 'Qatar', 'Russia', 'Brazil', 'South Africa'],
    ['Who won the 2022 FIFA World Cup?', 'Argentina', 'France', 'Brazil', 'Germany'],
    ['What sport uses a "putter"?', 'Golf', 'Tennis', 'Hockey', 'Cricket'],
    ['What does "EPL" stand for?', 'English Premier League', 'European Players League', 'Elite Pro League', 'English Pro League'],
    ['What is the "Ballon d\'Or"?', 'Award for best soccer player', 'Golden ball used in finals', 'Trophy shape', 'Stadium name'],
    ['What is a "slam dunk" in basketball?', 'Jumping and putting ball directly in hoop', 'Three-point shot', 'Free throw', 'Layup'],
    ['Which club did Ronaldo move to from Real Madrid in 2018?', 'Juventus', 'Manchester United', 'PSG', 'Bayern Munich'],
    ['What is the WWE "Attitude Era" known for?', 'Edgy content in the late 1990s', 'Family-friendly shows', 'Olympic-style wrestling', 'Women-only matches'],
    ['What is a "love" score in tennis?', 'Zero points', 'Winning point', '15 points', '40 points'],
    ['What is "deuce" in tennis?', 'Score is tied at 40-40', 'Game over', 'Set point', 'Match point'],
    ['What does "advantage" mean in tennis?', 'Player needs one more point to win after deuce', 'Leading by two games', 'First serve won', 'Break point'],
    ['What is the "UEFA Champions League"?', 'Top European club soccer tournament', 'World Cup', 'Olympics soccer', 'Youth league'],
    ['Which F1 team is based in Maranello, Italy?', 'Ferrari', 'McLaren', 'Mercedes', 'Red Bull'],
    ['What colour are Ferrari F1 cars traditionally?', 'Red', 'Blue', 'Silver', 'Green'],
  ],
  4: [
    ['Who has won the most F1 World Championships?', 'Lewis Hamilton / Michael Schumacher', 'Ayrton Senna', 'Sebastian Vettel', 'Alain Prost'],
    ['How many F1 titles did Schumacher win?', '7', '5', '6', '8'],
    ['Which F1 team has the most Constructors titles?', 'Ferrari', 'Mercedes', 'McLaren', 'Williams'],
    ['Which Toronto Raptor won the NBA Slam Dunk Contest in 2000?', 'Vince Carter', 'Tracy McGrady', 'Chris Bosh', 'DeMar DeRozan'],
    ['How many gold medals did Usain Bolt win at Olympics?', '8', '6', '9', '10'],
    ['What is Usain Bolt\'s 100m world record time?', '9.58 seconds', '9.69 seconds', '9.72 seconds', '9.50 seconds'],
    ['In which year did Bolt set the 100m record?', '2009', '2008', '2012', '2011'],
    ['In which year did Pakistan first win Olympic gold in hockey?', '1960', '1964', '1956', '1968'],
    ['How many consecutive WrestleMania matches did The Undertaker win?', '21', '18', '25', '15'],
    ['How many Olympic golds has Michael Phelps won?', '23', '18', '28', '15'],
    ['Which country has won the most Olympic gold medals overall?', 'United States', 'China', 'Russia', 'Great Britain'],
    ['What is "match point" in tennis?', 'One point away from winning the match', 'First point', 'Tie break', 'Final game'],
    ['Who has won the most Wimbledon singles titles (men)?', 'Roger Federer', 'Novak Djokovic', 'Pete Sampras', 'Rafael Nadal'],
    ['How many Wimbledon titles has Federer won?', '8', '7', '6', '9'],
    ['Who holds the record for most Grand Slams (men)?', 'Novak Djokovic', 'Roger Federer', 'Rafael Nadal', 'Pete Sampras'],
    ['Who broke The Undertaker\'s WrestleMania streak?', 'Brock Lesnar', 'John Cena', 'Triple H', 'The Rock'],
    ['What finishing move is Triple H famous for in WWE?', 'Pedigree', 'Stunner', 'RKO', 'Tombstone'],
    ['How many world records has Usain Bolt set?', '3 (100m, 200m, 4x100m relay)', '5', '2', '7'],
    ['What is a "double fault" in tennis?', 'Both serves fail', 'Two fouls', 'Missing a volley', 'Out of bounds twice'],
    ['Which F1 driver was known as "The Professor"?', 'Alain Prost', 'Ayrton Senna', 'Niki Lauda', 'Nelson Piquet'],
    ['What does "seeded" mean in a tournament?', 'Ranked and placed in the draw', 'New player', 'Wild card entry', 'Champion'],
    ['Which boxer famously bit Evander Holyfield\'s ear?', 'Mike Tyson', 'Lennox Lewis', 'Muhammad Ali', 'George Foreman'],
    ['How many World Open titles did Pakistani squash player Jansher Khan win?', '8', '6', '10', '5'],
    ['Who has scored the most goals in FIFA World Cup history?', 'Miroslav Klose', 'Ronaldo (Brazil)', 'Pelé', 'Just Fontaine'],
    ['How many World Cup goals did Klose score?', '16', '15', '14', '18'],
    ['What is a "grand prix" in F1?', 'Individual race in the F1 season', 'Championship final', 'Practice session', 'Qualifying round'],
    ['Which team won the first-ever Premier League title in 1992-93?', 'Manchester United', 'Arsenal', 'Liverpool', 'Blackburn'],
    ['What does "ground and pound" mean in MMA?', 'Striking a downed opponent', 'Wrestling on the ground', 'Kicking technique', 'Running at an opponent'],
    ['How many laps is the Monaco Grand Prix?', '78', '50', '72', '60'],
    ['What makes the Monaco GP special?', 'Street circuit through Monte Carlo', 'Longest track', 'Most corners', 'Night race'],
    ['What is "Hell in a Cell" in WWE?', 'A match inside a roofed steel cage', 'A tag team match', 'A ladder match', 'A battle royal'],
    ['What is the "sweet science" a nickname for?', 'Boxing', 'Fencing', 'Chess', 'Wrestling'],
    ['What is "La Liga"?', 'Spanish top soccer league', 'Italian league', 'French league', 'German league'],
    ['What is "Serie A"?', 'Italian top soccer league', 'Spanish league', 'French league', 'German league'],
    ['What is the "Bundesliga"?', 'German top soccer league', 'Austrian league', 'Swiss league', 'Dutch league'],
    ['Which soccer club is known as "The Red Devils"?', 'Manchester United', 'Liverpool', 'Arsenal', 'Chelsea'],
    ['Which soccer club plays at the Santiago Bernabéu?', 'Real Madrid', 'Barcelona', 'Atletico Madrid', 'Valencia'],
    ['Which soccer club plays at Camp Nou?', 'Barcelona', 'Real Madrid', 'Sevilla', 'Villarreal'],
    ['Which Pakistani hockey player was nicknamed "Maradona of Hockey"?', 'Shahbaz Ahmed', 'Hassan Sardar', 'Samiullah Khan', 'Islahuddin Siddiqui'],
    ['How many players are on a kabaddi team on the court?', '7', '5', '9', '11'],
    ['Which F1 team did Ayrton Senna famously drive for?', 'McLaren', 'Ferrari', 'Williams', 'Lotus'],
    ['What sport is Cristiano Ronaldo famous for?', 'Soccer/Football', 'Basketball', 'Tennis', 'Swimming'],
    ['Which country is Ronaldo from?', 'Portugal', 'Brazil', 'Spain', 'Argentina'],
    ['Which country is Neymar from?', 'Brazil', 'Argentina', 'Portugal', 'Colombia'],
    ['What is "VAR" in soccer?', 'Video Assistant Referee', 'Visual Audio Review', 'Virtual Aid Referee', 'Video Analysis Replay'],
    ['What is an "own goal" in soccer?', 'Scoring in your own team\'s net', 'Assisted goal', 'Penalty goal', 'Header goal'],
    ['Which footballer scored a hat-trick in the 2022 World Cup final?', 'Kylian Mbappé', 'Lionel Messi', 'Olivier Giroud', 'Antoine Griezmann'],
    ['How many consecutive squash matches did Jahangir Khan win?', '555', '400', '300', '600'],
    ['Which F1 circuit features the famous "Eau Rouge" corner?', 'Spa-Francorchamps', 'Monza', 'Silverstone', 'Monaco'],
    ['Which Canadian hockey player is nicknamed "Sid the Kid"?', 'Sidney Crosby', 'Wayne Gretzky', 'Connor McDavid', 'Mario Lemieux'],
  ],
  5: [
    ['What is the fastest 200m time ever recorded?', '19.19 seconds by Usain Bolt', '19.32 seconds', '19.50 seconds', '19.72 seconds'],
    ['In which city did Bolt run 9.58 in the 100m?', 'Berlin', 'Beijing', 'London', 'Rio'],
    ['Who holds the women\'s 100m world record?', 'Florence Griffith-Joyner', 'Shelly-Ann Fraser-Pryce', 'Elaine Thompson', 'Marion Jones'],
    ['Who was named Finals MVP when the Toronto Raptors won the 2019 NBA Championship?', 'Kawhi Leonard', 'Kyle Lowry', 'Pascal Siakam', 'Marc Gasol'],
    ['At what age did Jahangir Khan become the youngest World Open squash champion?', '17', '19', '21', '15'],
    ['In which year did Pakistan win their last Hockey World Cup?', '1994', '1990', '1986', '1998'],
    ['Which WrestleMania main event is often called the greatest: Stone Cold vs who?', 'The Rock', 'Shawn Michaels', 'The Undertaker', 'Triple H'],
    ['In what year did Brock Lesnar end The Undertaker\'s WrestleMania streak?', '2014', '2012', '2016', '2010'],
    ['Which F1 driver won 4 consecutive World Championships from 2010-2013?', 'Sebastian Vettel', 'Lewis Hamilton', 'Fernando Alonso', 'Michael Schumacher'],
    ['What is the record for most goals in a soccer World Cup?', '13 by Just Fontaine in 1958', '10 by Pelé', '12 by Gerd Muller', '11 by Ronaldo'],
    ['What is the fastest F1 pit stop ever?', 'Under 2 seconds', '3 seconds', '5 seconds', '4 seconds'],
    ['Which F1 team holds the fastest pit stop record?', 'Red Bull Racing', 'Mercedes', 'Ferrari', 'McLaren'],
    ['Which boxer retired undefeated with a 50-0 record?', 'Floyd Mayweather Jr.', 'Muhammad Ali', 'Rocky Marciano', 'Manny Pacquiao'],
    ['Which club has won the most Premier League titles?', 'Manchester United', 'Liverpool', 'Arsenal', 'Chelsea'],
    ['How many Premier League titles has Manchester United won?', '13', '11', '15', '9'],
    ['Who is the fastest woman in Olympic 100m history?', 'Elaine Thompson-Herah', 'Florence Griffith-Joyner', 'Shelly-Ann Fraser-Pryce', 'Dina Asher-Smith'],
    ['Which WWE match type features ladders, tables, and chairs?', 'TLC match', 'Steel cage match', 'Iron man match', 'Last man standing'],
    ['Which UFC lightweight champion retired undefeated at 29-0?', 'Khabib Nurmagomedov', 'Conor McGregor', 'Tony Ferguson', 'Charles Oliveira'],
    ['Who was the first boxer to win the heavyweight title three separate times?', 'Muhammad Ali', 'Evander Holyfield', 'Lennox Lewis', 'Mike Tyson'],
    ['Which country has hosted the most Olympic Games?', 'United States', 'United Kingdom', 'France', 'Greece'],
    ['Which Pakistani squash player succeeded Jahangir Khan as World No. 1?', 'Jansher Khan', 'Qamar Zaman', 'Hashim Khan', 'Roshan Khan'],
    ['Which F1 driver has the most race wins in history?', 'Lewis Hamilton', 'Michael Schumacher', 'Sebastian Vettel', 'Alain Prost'],
    ['What does "photo finish" mean?', 'Race decided by a photograph at finish line', 'Taking team photos', 'Photography competition', 'Celebration photo'],
    ['Who has the most Premier League goals?', 'Alan Shearer', 'Wayne Rooney', 'Thierry Henry', 'Sergio Aguero'],
    ['How many EPL goals did Alan Shearer score?', '260', '230', '280', '210'],
    ['Whose catchphrase is "If ya smell what The Rock is cookin\'"?', 'The Rock', 'Stone Cold', 'John Cena', 'The Undertaker'],
    ['What sport did Muhammad Ali compete in?', 'Boxing', 'Wrestling', 'MMA', 'Judo'],
    ['What was Muhammad Ali\'s famous catchphrase?', 'Float like a butterfly, sting like a bee', 'I am the best', 'Just do it', 'Victory is mine'],
    ['What is the highest possible break in snooker?', '147', '155', '140', '130'],
    ['What is the "Davis Cup" for?', 'International men\'s tennis team event', 'Soccer trophy', 'Golf cup', 'Swimming relay'],
    ['Who has the most Champions League titles (club)?', 'Real Madrid', 'AC Milan', 'Liverpool', 'Barcelona'],
    ['How many Champions League titles has Real Madrid won?', '15', '13', '12', '10'],
    ['What is "doping" in sports?', 'Using banned substances to enhance performance', 'Training method', 'Diet plan', 'Recovery technique'],
    ['What organization conducts anti-doping tests?', 'WADA (World Anti-Doping Agency)', 'FIFA', 'IOC', 'WHO'],
    ['What is the "Olympic Village"?', 'Housing complex for athletes', 'Tourist area', 'Stadium name', 'Training center'],
    ['Who did Muhammad Ali fight in "The Rumble in the Jungle"?', 'George Foreman', 'Joe Frazier', 'Sonny Liston', 'Leon Spinks'],
    ['How many weight classes are in Olympic boxing?', '13', '10', '8', '15'],
    ['What is the "Commonwealth Games"?', 'Multi-sport event for Commonwealth nations', 'British Olympics', 'European Games', 'Asian Games'],
    ['How often are the Commonwealth Games held?', 'Every 4 years', 'Every 2 years', 'Every year', 'Every 5 years'],
    ['Which footballer has scored the most Champions League goals ever?', 'Cristiano Ronaldo', 'Lionel Messi', 'Raul', 'Robert Lewandowski'],
    ['Which country did Conor McGregor represent in the UFC?', 'Ireland', 'England', 'Scotland', 'USA'],
    ['What is "sudden death" in sports?', 'First to score wins in overtime', 'Last play of game', 'Penalty shootout', 'Fastest finish'],
    ['How long was Jahangir Khan\'s unbeaten run in squash?', 'Over 5 years (1981-1986)', '3 years', '7 years', '2 years'],
    ['Which club won the 2022-23 treble: Premier League, FA Cup, and Champions League?', 'Manchester City', 'Liverpool', 'Real Madrid', 'Chelsea'],
    ['Which Grand Slam has Rafael Nadal won most?', 'French Open', 'US Open', 'Wimbledon', 'Australian Open'],
    ['How many French Open titles did Nadal win?', '14', '12', '10', '8'],
    ['What is "esports"?', 'Competitive video gaming', 'Electronic sprinting', 'Online fitness', 'Virtual reality sport'],
    ['What was the "Fight of the Century" boxing match in 1971?', 'Muhammad Ali vs Joe Frazier', 'Ali vs Foreman', 'Tyson vs Holyfield', 'Lewis vs Tyson'],
    ['Which F1 team did Max Verstappen win his first championship with?', 'Red Bull Racing', 'Mercedes', 'Ferrari', 'McLaren'],
    ['Which Pakistani was the first-ever British Open squash champion?', 'Hashim Khan', 'Jahangir Khan', 'Roshan Khan', 'Azam Khan'],
  ],
  6: [
    ['What is the "offside rule" in soccer in detail?', 'Player behind last defender when ball is played', 'Near the goal', 'Past halfway', 'In the box'],
    ['When was the offside rule introduced in soccer?', '1863 (modified in 1925)', '1900', '1950', '1870'],
    ['What is "tiki-taka" in soccer?', 'Short passing possession style (Barcelona)', 'Long ball tactics', 'Defensive strategy', 'Counter-attacking'],
    ['Which coach popularized tiki-taka?', 'Pep Guardiola', 'Jose Mourinho', 'Jurgen Klopp', 'Carlo Ancelotti'],
    ['What is the "DRS" in Formula 1?', 'Drag Reduction System', 'Driver Radio Signal', 'Data Review System', 'Dynamic Racing Speed'],
    ['What does the DRS do in F1?', 'Opens rear wing flap to reduce drag', 'Boosts engine power', 'Activates brakes', 'Changes tyre grip'],
    ['What is a "safety car" in F1?', 'Car that leads pack during hazardous conditions', 'Backup race car', 'Medical car', 'Pace car for warm-up only'],
    ['What fuel do F1 cars use (2026 regs)?', 'Sustainable fuel blend', 'Regular petrol', 'Diesel', 'Pure electric'],
    ['What is the "ATP ranking" in tennis?', 'Association of Tennis Professionals ranking', 'All Tennis Players rank', 'Annual Tennis Points', 'Advanced Tennis Placing'],
    ['What is the "WTA" in tennis?', 'Women\'s Tennis Association', 'World Tennis Awards', 'Winning Tennis Athletes', 'Women\'s Training Academy'],
    ['Which Pakistani squash family produced multiple world champions across generations?', 'The Khan family (Hashim, Roshan, Jahangir, Jansher)', 'The Ahmed family', 'The Malik family', 'The Hussain family'],
    ['What is "kayfabe" in professional wrestling?', 'Maintaining the illusion that wrestling storylines are real', 'A finishing move', 'A tag team formation', 'A type of wrestling ring'],
    ['What is "VO2 max"?', 'Maximum oxygen uptake during exercise', 'Heart rate at rest', 'Lung capacity', 'Blood pressure measure'],
    ['What does a high VO2 max indicate?', 'Better aerobic fitness', 'Stronger muscles', 'Better flexibility', 'More speed'],
    ['What is "lactate threshold"?', 'Point where lactic acid builds faster than cleared', 'Maximum speed', 'Heart rate at rest', 'Warm-up point'],
    ['What is the "Fosbury Flop"?', 'High jump technique going back-first', 'Long jump style', 'Pole vault move', 'Diving technique'],
    ['Who invented the Fosbury Flop?', 'Dick Fosbury', 'Carl Lewis', 'Jesse Owens', 'Bob Beamon'],
    ['In what year did Fosbury debut his technique?', '1968 Olympics', '1972 Olympics', '1964 Olympics', '1976 Olympics'],
    ['In which decade did Pakistan dominate both Olympic and World Cup hockey?', '1960s-1980s', '1940s-1960s', '1980s-2000s', '1990s-2010s'],
    ['What boxing technique did Muhammad Ali call "rope-a-dope"?', 'Leaning on ropes to tire the opponent', 'A fast jab combination', 'A defensive footwork pattern', 'A way to dodge punches'],
    ['What is the "golden goal" rule?', 'First goal in extra time wins (now discontinued)', 'Goal with header', 'Penalty goal', 'Own goal counts double'],
    ['Why was the golden goal rule removed?', 'Teams played too defensively', 'Too exciting', 'Hard to officiate', 'Players complained'],
    ['What replaced golden goal in soccer?', 'Full extra time then penalties', 'Immediate penalties', 'Coin toss', 'Replay match'],
    ['What is "altitude training"?', 'Training at high elevation to boost red blood cells', 'Training on airplanes', 'High-jump training', 'Mountain climbing'],
    ['Why do athletes train at altitude?', 'Body produces more red blood cells', 'Better weather', 'Fewer distractions', 'Cheaper facilities'],
    ['What is the "biological passport" in anti-doping?', 'Tracking athlete blood values over time', 'Travel document', 'Medical certificate', 'ID card'],
    ['What is "blood doping"?', 'Increasing red blood cells artificially', 'Drug injection', 'Diet supplement', 'Blood donation'],
    ['What is a "rear naked choke" in MMA?', 'A submission hold applied from behind the opponent', 'A takedown move', 'A striking technique', 'A cage clinch'],
    ['What is the minimum weight of an F1 car with driver (approx)?', 'Around 800 kg', 'Around 500 kg', 'Around 1200 kg', 'Around 300 kg'],
    ['What is "progressive overload"?', 'Gradually increasing training demands', 'Immediate max effort', 'Reducing training', 'Constant same routine'],
    ['What is the "Montreal Screwjob" in WWE history?', 'Controversial 1997 finish where Vince McMahon changed the match result', 'A famous ladder match', 'A tag team betrayal', 'An injury angle'],
    ['What is "expected goals" (xG) in football analytics?', 'Statistical measure of chance quality based on shot data', 'Goals scored per game', 'Predicted final score', 'Average goals in a league'],
    ['What is a "PB" in athletics?', 'Personal Best', 'Professional Best', 'Point Bonus', 'Performance Badge'],
    ['What is "SB" in athletics results?', 'Season\'s Best', 'Silver Best', 'Special Best', 'Super Best'],
    ['What role did Islahuddin Siddiqui play in Pakistan hockey history?', 'Star forward and all-time leading goal scorer', 'Goalkeeper who never conceded', 'First Pakistani hockey captain', 'Coached Pakistan to World Cup'],
    ['What is "cryotherapy" used for in sport?', 'Cold treatment for recovery', 'Heat therapy', 'Massage type', 'Stretching routine'],
    ['What temperature is a cryotherapy chamber?', 'Around -110°C to -140°C', '-50°C', '-10°C', '-200°C'],
    ['What is the "hamstring" muscle group?', 'Muscles at back of thigh', 'Front of thigh', 'Calf muscles', 'Shin muscles'],
    ['What is an "ACL" injury?', 'Anterior Cruciate Ligament tear in knee', 'Ankle injury', 'Arm injury', 'Back injury'],
    ['Why are ACL injuries common in soccer?', 'Sudden direction changes stress the knee', 'Too much running', 'Ball impact', 'Poor shoes'],
    ['What is "interval training"?', 'Alternating high and low intensity exercise', 'Constant pace training', 'Stretching only', 'Weights only'],
    ['What is "HIIT"?', 'High-Intensity Interval Training', 'Heavy Impact Individual Training', 'Hard Interval Indoor Training', 'High Incline Intense Training'],
    ['What is the "anaerobic threshold"?', 'Exercise intensity where anaerobic metabolism dominates', 'Maximum heart rate', 'Resting state', 'Recovery point'],
    ['What is a "compound movement" in training?', 'Exercise using multiple joints and muscles', 'Single muscle exercise', 'Stretching', 'Cardio only'],
    ['What is "concentric contraction"?', 'Muscle shortens while generating force', 'Muscle lengthens', 'Muscle stays same length', 'No muscle movement'],
    ['What is "eccentric contraction"?', 'Muscle lengthens while under tension', 'Muscle shortens', 'Muscle stays same', 'No contraction'],
    ['What is the "Valsalva maneuver" in lifting?', 'Holding breath to stabilize core', 'Exhaling loudly', 'Counting reps', 'Stretching technique'],
    ['What is "RPE" in exercise science?', 'Rate of Perceived Exertion', 'Running Pace Estimate', 'Recovery Period End', 'Resting Pulse Evaluation'],
    ['What does the "RICE" method stand for?', 'Rest, Ice, Compression, Elevation', 'Run, Ice, Cool, Eat', 'Rest, Inject, Compress, Exercise', 'Recovery, Ice, Care, Elevate'],
    ['What is a "guillotine choke" in MMA?', 'A front headlock submission targeting the neck', 'A leg lock', 'An arm bar variation', 'A striking combination'],
  ],
};

export { popCulture } from './popCultureToronto';

