import type { Fact } from './group1';

/** NBA-focused trivia; difficulty scales by grade (1 = basics, 6 = records & rules). */
export const nba: Record<number, Fact[]> = {
  1: [
    ['How many players from one team are on the court at a time in the NBA?', '5', '4', '6', '7'],
    ['What do you shoot the basketball into to score?', 'The hoop (basket)', 'A goal', 'A net on the ground', 'A tunnel'],
    ['What shape is a basketball?', 'Round (sphere)', 'Square', 'Flat', 'Triangle'],
    ['What colour is a basketball usually?', 'Orange with black lines', 'All white', 'All green', 'Solid blue'],
    ['Which NBA team plays in Toronto?', 'Raptors', 'Maple Leafs', 'Blue Jays', 'Argonauts'],
    ['What is the name of the league for the best basketball in North America?', 'NBA', 'NFL', 'MLB', 'NHL'],
    ['How many points is a shot worth when made behind the three-point arc?', '3', '2', '1', '4'],
    ['How many points is a normal field goal inside the arc?', '2', '1', '3', '4'],
    ['What do you call bouncing the ball while moving?', 'Dribbling', 'Kicking', 'Throwing', 'Rolling'],
    ['Who tries to stop the other team from scoring?', 'Defense', 'Offense only', 'Fans only', 'Coach only'],
    ['What is the court surface usually made of?', 'Hardwood (wood)', 'Grass', 'Ice', 'Sand'],
    ['What is the name of the line under each basket?', 'Baseline', 'Sideline', 'Half-court line', 'Three-point line'],
    ['How many halves are in a standard NBA game (not counting overtime)?', '2', '1', '3', '4'],
    ['What does the referee toss to start the game?', 'Jump ball', 'Coin only', 'Ball only', 'Whistle only'],
    ['What do players wear on their feet?', 'Basketball shoes', 'Cleats', 'Skates', 'Sandals'],
    ['What protects the basket with a net?', 'Rim and backboard', 'Only a rope', 'A fence', 'A wall'],
    ['Which team wears purple and gold as classic colours?', 'Los Angeles Lakers', 'Boston Celtics', 'Chicago Bulls', 'Miami Heat'],
    ['Which team is famous for green and white uniforms?', 'Boston Celtics', 'Lakers', 'Heat', 'Nuggets'],
    ['Which player is often called "King James"?', 'LeBron James', 'Stephen Curry', 'Kevin Durant', 'Giannis Antetokounmpo'],
    ['Which player is famous for long three-pointers with the Warriors?', 'Stephen Curry', 'Shaq', 'Tim Duncan', 'Dirk Nowitzki'],
    ['What animal is in the Chicago Bulls logo?', 'A bull', 'A bear', 'A hawk', 'A deer'],
    ['What is a free throw worth?', '1 point', '2 points', '3 points', '0 points'],
    ['Where do free throws happen from?', 'The free-throw line', 'Half court', 'The corner', 'Out of bounds'],
    ['What is it called when you take too many steps without dribbling?', 'Traveling', 'Fouling', 'Blocking', 'Screening'],
    ['What is a pass to a teammate called?', 'A pass', 'A kick', 'A punt', 'A spike'],
    ['Which city is home to the Knicks?', 'New York', 'Los Angeles', 'Chicago', 'Houston'],
    ['Which city is home to the Lakers?', 'Los Angeles', 'New York', 'Boston', 'Dallas'],
    ['What does NBA stand for?', 'National Basketball Association', 'North American Ball Association', 'National Baseball Association', 'National Boxing Association'],
    ['How long is an NBA quarter (regulation)?', '12 minutes', '10 minutes', '15 minutes', '8 minutes'],
    ['What is the break between the second and third quarters called?', 'Halftime', 'Timeout', 'Overtime', 'Intermission only'],
    ['What is the name of the trophy for winning the NBA Finals?', "Larry O'Brien Championship Trophy", 'Stanley Cup', 'Vince Lombardi Trophy', 'Commissioner Cup'],
    ['Which team won its first NBA title in 2019?', 'Toronto Raptors', 'Lakers', 'Celtics', 'Warriors'],
    ['What is the name of the arena many Raptors home games are played in?', 'Scotiabank Arena', 'Rogers Centre', 'BMO Field', 'Air Canada Centre only forever'],
    ['Who is the NBA logo silhouette often said to resemble?', 'Jerry West (classic logo)', 'Michael Jordan', 'Magic Johnson', 'Larry Bird'],
    ['What is a slam dunk?', 'Forcefully putting the ball through the hoop', 'A three-pointer', 'A free throw', 'A pass'],
    ['What colour is the paint (lane) area often?', 'Often a different shade than the rest', 'Always pink', 'Always black', 'Always invisible'],
    ['What is a "block" in basketball?', 'Stopping an opponent\'s shot in the air', 'A foul', 'A timeout', 'A substitution'],
    ['What is a "steal" in basketball?', 'Taking the ball from the opponent', 'Missing a shot', 'Calling timeout', 'Fouling'],
    ['Which position usually plays closest to the basket on offense?', 'Center or forward', 'Point guard always', 'Referee', 'Coach'],
    ['Which position often brings the ball up the court?', 'Point guard', 'Center', 'Referee', 'Announcer'],
    ['What is an "assist"?', 'Pass that leads directly to a made basket', 'A block', 'A foul', 'A rebound'],
    ['What is a "rebound"?', 'Gaining the ball after a missed shot', 'Scoring from three', 'A timeout', 'A jump ball'],
    ['What is a "foul"?', 'Illegal contact by a player', 'A good pass', 'A made shot', 'A substitution'],
    ['How many feet high is a regulation basketball rim?', '10 feet', '8 feet', '12 feet', '9 feet'],
    ['What is the small arc around the basket called?', 'The restricted area (charge circle)', 'The penalty box', 'The dugout', 'The crease'],
    ['What does MVP usually mean in sports?', 'Most Valuable Player', 'Most Vertical Player', 'Main Video Person', 'Minimum Value Points'],
    ['What is the NBA championship series called?', 'The NBA Finals', 'The Super Bowl', 'The World Series', 'The Stanley Cup Finals'],
    ['Which conference is Toronto in?', 'Eastern Conference', 'Western Conference', 'Southern Conference', 'Northern Conference'],
    ['What is a "timeout"?', 'Official break called by a team or refs', 'A foul', 'A score', 'Halftime only'],
    ['What is "overtime"?', 'Extra period if the game is tied', 'Halftime', 'Practice', 'Pre-game'],
    ['What is a "layup"?', 'Close shot off the backboard or rim', 'Half-court shot', 'Free throw', 'Dunk only'],
  ],
  2: [
    ['How many quarters in a regulation NBA game?', '4', '2', '3', '6'],
    ['How many personal fouls usually foul a player out of an NBA game?', '6', '5', '7', '4'],
    ['What is a "technical foul"?', 'Non-contact foul for misconduct or rules', 'Any shooting foul', 'A dunk', 'A substitution'],
    ['What is a "double-double"?', '10+ in two stat categories (e.g. points and rebounds)', 'Two dunks', 'Two technicals', 'Two quarters played'],
    ['What is a "triple-double"?', '10+ in three stat categories', 'Three three-pointers', 'Three fouls', 'Three quarters'],
    ['Which player wore number 23 for the Chicago Bulls in six championship runs?', 'Michael Jordan', 'Scottie Pippen', 'Dennis Rodman', 'Steve Kerr'],
    ['Which team did Michael Jordan win six titles with?', 'Chicago Bulls', 'Lakers', 'Celtics', 'Heat'],
    ['Which center was known as "Shaq"?', 'Shaquille O\'Neal', 'Hakeem Olajuwon', 'Patrick Ewing', 'David Robinson'],
    ['Which team calls Madison Square Garden home?', 'New York Knicks', 'Nets', '76ers', 'Celtics'],
    ['Which team plays in Miami?', 'Heat', 'Magic', 'Hawks', 'Hornets'],
    ['Which team is from Dallas?', 'Mavericks', 'Rockets', 'Spurs', 'Pelicans'],
    ['What is the three-point line for?', 'Shots made from beyond it are worth 3 points', 'Out of bounds only', 'Bench area', 'Coach box'],
    ['What is a "pick and roll"?', 'Screen then roll to the basket', 'Full-court press', 'Zone defense only', 'Jump ball play'],
    ['What is "man-to-man" defense?', 'Each defender guards one opponent', 'Everyone guards one star', 'No defense', 'Zone only'],
    ['What is a "zone" defense?', 'Players guard an area instead of one player', 'Man-to-man', 'Press only', 'Full court always'],
    ['What is an "alley-oop"?', 'High pass finished with a dunk or layup in the air', 'Free throw', 'Three-pointer', 'Timeout'],
    ['What is a "buzzer beater"?', 'Shot made as time expires', 'Shot after foul', 'Practice shot', 'Warm-up shot'],
    ['Which trophy is for the NBA regular-season best record (team)?', 'Not a specific trophy — best record is a stat', 'Larry O\'Brien', 'MVP trophy', 'Rookie of the Year'],
    ['What is the "shot clock"?', 'Timer limiting how long a team can possess the ball', 'Game clock', 'Timeout clock', 'Halftime clock'],
    ['How many seconds on the NBA shot clock?', '24', '14', '30', '35'],
    ['What is "goaltending"?', 'Illegal interference with a shot on its way down', 'Blocking a dunk', 'A foul on the floor', 'Traveling'],
    ['What is "backcourt violation"?', 'Offensive team returns ball illegally across half court', 'Defense foul', 'Three seconds in lane', 'Shot clock'],
    ['What is "three seconds" violation often called?', 'Offensive three-second rule in the key', 'Five-second rule', 'Eight-second rule', 'Ten-second rule'],
    ['How many seconds to advance the ball past half court (NBA)?', '8', '5', '10', '24'],
    ['What is a "flagrant foul"?', 'Excessive or unnecessary contact', 'Any shooting foul', 'Technical only', 'Loose ball'],
    ['What is the "paint"?', 'The rectangular area around the basket', 'The three-point arc', 'The bench', 'The logo'],
    ['What is a "fast break"?', 'Quick transition after a change of possession', 'Slow offense', 'Timeout', 'Jump ball'],
    ['Which team is known as the "Warriors"?', 'Golden State', 'Oklahoma City', 'Portland', 'Utah'],
    ['Which team is the "Nuggets"?', 'Denver', 'Utah', 'Phoenix', 'Sacramento'],
    ['Which team is the "Bucks"?', 'Milwaukee', 'Minnesota', 'Memphis', 'Detroit'],
    ['Which team is the "76ers"?', 'Philadelphia', 'Boston', 'Washington', 'Charlotte'],
    ['What is a "sixth man"?', 'Key reserve who comes off the bench', 'Sixth foul', 'Sixth quarter', 'Sixth coach'],
    ['What is the "G League"?', 'NBA\'s official minor league', 'Video game league', 'College league', 'Street league'],
    ['What is a "max contract"?', 'Large salary deal up to a league maximum', 'Minimum salary', 'Rookie deal only', 'Two-way deal only'],
    ['What is a "two-way player"?', 'Splits time between NBA and G League', 'Plays two sports', 'Two-year rookie', 'Two-point specialist'],
    ['Which arena do the Lakers and Clippers both use (as of typical seasons)?', 'Crypto.com Arena (formerly Staples)', 'Madison Square Garden', 'United Center', 'TD Garden'],
    ['What is a "full timeout" in the NBA?', '75 seconds (team timeout)', '30 seconds', '2 minutes', '20 seconds'],
    ['What is "and-one"?', 'Made basket plus a foul — free throw chance', 'One point play', 'One timeout', 'One quarter'],
    ['What is "double dribble"?', 'Stopping dribble then dribbling again', 'Two players dribbling', 'Two balls', 'Two fouls'],
    ['What is "carrying" or "palming"?', 'Illegal dribbling by turning hand under the ball', 'Holding the rim', 'Hugging an opponent', 'Carrying the bench'],
    ['What is a "charge"?', 'Offensive foul when the defender has legal position', 'Blocking foul', 'Technical', 'Flagrant'],
    ['What is a "block" foul vs charge?', 'Defender not set — often a blocking foul', 'Always offense', 'Never a foul', 'Jump ball'],
    ['Which Spaniard won two NBA titles with the Lakers (2009–2010 era)?', 'Pau Gasol', 'Marc Gasol only later', 'Ricky Rubio', 'José Calderón'],
    ['Who is "The Greek Freak"?', 'Giannis Antetokounmpo', 'Luka Dončić', 'Nikola Jokić', 'Joel Embiid'],
    ['Which Serbian center won multiple MVPs with Denver?', 'Nikola Jokić', 'Vlade Divac', 'Peja Stojaković', 'Boban Marjanović'],
    ['Which Slovenian star plays for Dallas?', 'Luka Dončić', 'Goran Dragić', 'Jokić', 'Porziņģis'],
    ['What is a "rookie"?', 'First-year NBA player', 'A coach', 'A referee', 'Retired player'],
    ['What is the NBA Draft?', 'Annual event where teams select amateur players', 'Mid-season tournament only', 'All-Star game', 'Trade deadline'],
    ['What is "load management"?', 'Resting stars strategically for health', 'Carrying the ball', 'Weight training only', 'Salary cap'],
  ],
  3: [
    ['In what year did the Toronto Raptors win the NBA Finals?', '2019', '2018', '2020', '2017'],
    ['Who was Finals MVP when Toronto won in 2019?', 'Kawhi Leonard', 'Kyle Lowry', 'Pascal Siakam', 'Marc Gasol'],
    ['Which team did the Raptors beat in the 2019 Finals?', 'Golden State Warriors', 'Cleveland Cavaliers', 'Boston Celtics', 'Milwaukee Bucks'],
    ['How many NBA championships have the Boston Celtics won (most all-time, ties Lakers as of classic counts)?', '17 (tied historically with Lakers in many eras)', '15', '12', '20'],
    ['Which franchise is tied with Boston for the most NBA titles in many record books?', 'Los Angeles Lakers', 'Chicago Bulls', 'San Antonio Spurs', 'Miami Heat'],
    ['Who is the NBA\'s all-time leading scorer (regular season, career totals often cited)?', 'LeBron James', 'Kareem Abdul-Jabbar', 'Karl Malone', 'Kobe Bryant'],
    ['Who held the scoring record before LeBron James broke it?', 'Kareem Abdul-Jabbar', 'Michael Jordan', 'Wilt Chamberlain', 'Dirk Nowitzki'],
    ['Who won six Finals MVPs with the Bulls?', 'Michael Jordan', 'Scottie Pippen', 'Dennis Rodman', 'Horace Grant'],
    ['What is the "Dream Team"?', '1992 USA Olympic basketball team stacked with NBA stars', 'All rookies', 'G League select', 'WNBA crossover'],
    ['What is the "Malice at the Palace"?', '2004 brawl involving Pacers, Pistons, and fans', 'A movie', 'A trade', 'A draft'],
    ['What is the salary cap?', 'Limit on team payroll to promote parity', 'Rim height rule', 'Shot clock', 'Foul limit'],
    ['What is a "supermax" contract?', 'Designated veteran extension allowing higher pay', 'Minimum deal', 'Rookie scale only', 'G League pay'],
    ['What is the luxury tax?', 'Extra payment for teams far above the cap', 'Arena tax', 'Ticket tax', 'TV tax'],
    ['What is a "sign-and-trade"?', 'Player signs with team then is traded immediately', 'Free signing only', 'Draft trade', 'Coach trade'],
    ['What is restricted free agency?', 'Team can match offer sheets to keep the player', 'Player cannot sign', 'No contracts', 'Retirement'],
    ['What is unrestricted free agency?', 'Player can sign with any team', 'Must stay', 'Only one-year deals', 'No salary'],
    ['What is the play-in tournament?', 'Pre-playoff games for final seeds', 'All-Star weekend', 'Summer league', 'G League finals'],
    ['What is the In-Season Tournament (NBA Cup)?', 'Mid-season competition for a cup and prize pool', 'Summer league', 'Preseason only', 'Olympics'],
    ['Who won the first NBA In-Season Tournament MVP (2023)?', 'LeBron James', 'Giannis Antetokounmpo', 'Kevin Durant', 'Tyrese Haliburton'],
    ['What is "small ball"?', 'Lineup with smaller, quicker players', 'Only kids play', 'Mini hoop', 'Youth league'],
    ['What is "positionless basketball"?', 'Players switch roles and defend multiple positions', 'No positions on court', 'Goalkeepers', 'Pitchers'],
    ['What is an "iso" (isolation)?', 'Clear-out for one player to attack one-on-one', 'Isolation ward', 'Zone defense', 'Full press'],
    ['What is "spacing"?', 'Shooting threats spread the floor for drives', 'Crowding the paint', 'Bench spacing', 'Arena seats'],
    ['What is a "catch-and-shoot"?', 'Quick shot off a pass without dribbling', 'Alley-oop only', 'Post move', 'Hook only'],
    ['What is a "step-back" three?', 'Create space by stepping back before shooting', 'Step on line', 'Travel move', 'Free throw'],
    ['What is "Hack-a-Shaq"?', 'Intentional fouling poor free-throw shooters', 'Shaq\'s workout', 'Dunk contest', 'Charity event'],
    ['What is the hack-a rule change spirit?', 'Limit away-from-play fouls in last minutes', 'Unlimited fouls', 'No free throws', 'No fouls'],
    ['What is the All-Star Game?', 'Mid-season exhibition of star players', 'Finals game 7', 'Draft', 'Summer league'],
    ['What is the Slam Dunk Contest?', 'All-Star weekend event judging dunks', 'Three-point contest', 'Skills challenge', 'Rookie game'],
    ['What is the Three-Point Contest?', 'All-Star shooting competition from beyond the arc', 'Dunk contest', 'Horse', 'Layup line'],
    ['Which coach led the Warriors to multiple titles (2015, 2017, 2018)?', 'Steve Kerr', 'Phil Jackson', 'Gregg Popovich', 'Pat Riley'],
    ['Which coach is famous for the Spurs\' long dynasty?', 'Gregg Popovich', 'Steve Kerr', 'Erik Spoelstra', 'Doc Rivers'],
    ['What is "Hack-a-Ben" style strategy similar to?', 'Fouling poor shooters intentionally (historical pattern)', 'Ben Simmons only meme', 'Ben Wallace blocks', 'Big Ben clock'],
    ['What is a "10-day contract"?', 'Short NBA contract for injuries or tryouts', 'Rookie deal', 'Max deal', 'Coach contract'],
    ['What is two-way eligibility?', 'Player can appear in limited NBA games with G League time', 'Plays two positions only', 'Two teams same night', 'Two balls'],
    ['What is the combine?', 'Pre-draft athletic and skills testing', 'Trade deadline', 'All-Star', 'Ring ceremony'],
    ['What is "tanking" (controversial)?', 'Losing to improve draft odds', 'Winning every game', 'Defense only', 'Playoffs'],
    ['What are lottery odds?', 'Draft chances weighted by record', 'Playoff seeding', 'MVP voting', 'All-Star votes'],
    ['What is the "Rose Rule"?', 'Young star extension criteria (named after Derrick Rose)', 'No roses in arenas', 'Bench rule', 'Foul rule'],
    ['What is a "bird rights"?', 'Exception letting teams re-sign own free agents over cap', 'Bird mascot rule', 'Three-pointer', 'Timeout'],
    ['What is the mid-level exception?', 'Cap exception to sign a player near median salary', 'Half-court line', 'Mid-range only shot', 'Middle school league'],
    ['What is a "buyout"?', 'Player leaves team after waived contract terms', 'Buy a team', 'Buy tickets', 'Buyout clause in shoe deal'],
    ['What is "load management" criticism about?', 'Fans debate stars sitting nationally televised games', 'Too much practice', 'Too many dunks', 'Shoes'],
    ['Who is "The Process" often associated with?', 'Joel Embiid / 76ers rebuild era', 'LeBron', 'Curry', 'Jokić'],
    ['What is "Trust the Process"?', '76ers fan slogan during rebuild years', 'Warriors motto', 'Lakers motto', 'NBA rulebook'],
    ['What is a "unicorn" big man?', 'Tall player who shoots threes and handles like a guard', 'Mascot', 'Retired jersey', 'Trade clause'],
    ['What is "small forward" vs "power forward"?', 'Traditionally wing scorer vs stronger forward', 'Same thing', 'Guards only', 'Centers only'],
    ['What is a "stretch five"?', 'Center who shoots three-pointers', 'Center who never shoots', 'Point center only', 'Goalkeeper'],
    ['What is "switch everything"?', 'Defensive scheme swapping picks onto any matchup', 'Change jerseys', 'Rotate refs', 'Change arenas'],
  ],
  4: [
    ['Who holds the single-game scoring record (100 points)?', 'Wilt Chamberlain', 'Kobe Bryant', 'Michael Jordan', 'Devin Booker'],
    ['What was Kobe Bryant\'s famous 2006 single-game scoring total?', '81 points', '60', '70', '91'],
    ['Who has the most career assists in NBA history?', 'John Stockton', 'Jason Kidd', 'Chris Paul', 'Magic Johnson'],
    ['Who has the most career steals in NBA history?', 'John Stockton', 'Jason Kidd', 'Chris Paul', 'Michael Jordan'],
    ['Who has the most career rebounds?', 'Wilt Chamberlain / Bill Russell era debate — Chamberlain per game leader', 'Dennis Rodman', 'Shaq', 'Kareem'],
    ['What is true shooting percentage?', 'Shooting efficiency including threes and free throws', 'Only two-point %', 'Only wins', 'Steals per game'],
    ['What is PER (Player Efficiency Rating)?', 'All-in-one per-minute productivity rating', 'Personal error rate', 'Pass efficiency ratio', 'Points every round'],
    ['What is win shares?', 'Estimate of player contribution to team wins', 'Fantasy only', 'Playoff shares', 'Stock shares'],
    ['What is RAPTOR / LEBRON style metrics?', 'Modern plus-minus style impact stats', 'Dinosaur mascots', 'Arena noise', 'Ref grades'],
    ['What is a "heat check"?', 'Player keeps shooting after hot streak', 'Temperature check', 'Injury check', 'Drug test'],
    ['What is "ice in the veins"?', 'Clutch cold-blooded shooting moment', 'Injury treatment', 'Arena AC', 'Gatorade flavor'],
    ['What is the "Elam Ending"?', 'Target score ending used in All-Star game', 'Overtime rule 1950s', 'College only', 'FIBA never'],
    ['What is the Ted Stepien rule?', 'Limits trading first-round picks in consecutive years', 'Step-back rule', 'Stepien arena', 'Steph Curry rule'],
    ['What is the one-and-done rule context?', 'Players often wait one college year before draft age', 'One timeout', 'One dribble', 'One quarter'],
    ['What is the minimum draft age today (typical path)?', '19 during calendar year of draft', '18 always', '21', '16'],
    ['What is a "two-way" vs standard roster spot?', 'Limited NBA days with G League flexibility', 'Plays offense and defense', 'Two jerseys', 'Two agents'],
    ['What is the stretch provision?', 'Waiving player with cap hit spread over years', 'Stretch four player', 'Yoga rule', 'Injury list'],
    ['What is a poison pill contract (NBA trade slang)?', 'Rookie extension that complicates trade math', 'Toxic locker room', 'Fine only', 'Suspension'],
    ['What is the Stepien curse folklore?', 'Cleveland draft woes tied to past pick trades', 'Lakers curse', 'Knicks curse', 'Sonics curse'],
    ['What is the "We Believe" Warriors era?', '2007 eighth seed upsetting top-seeded Mavericks', '2015 dynasty', '1990s Bulls', 'Raptors 2019'],
    ['What is "Linsanity"?', 'Jeremy Lin\'s breakout Knicks stretch in 2012', 'Lingerie league', 'Lincoln NBA', 'Lynx WNBA'],
    ['What is "The Decision" (2010)?', 'LeBron James televised free-agency announcement', 'Lockout decision', 'Draft lottery', 'Sale of Sonics'],
    ['What is "The Block" (2016 Finals)?', 'LeBron\'s chase-down block on Andre Iguodala', 'Any block', 'Shaq block', 'Mutombo finger wag'],
    ['What is "The Shot" (Jordan over Ehlo)?', '1989 series-winning jumper vs Cavaliers', 'Ray Allen 2013', 'Kawhi 2019 bounce', 'Dirk fade'],
    ['What is the Malone–Stockton pick-and-roll fame?', 'Utah Jazz duo all-time greats', 'Lakers duo', 'Celtics duo', 'Heat duo'],
    ['What is the "Bad Boys" Pistons?', 'Late-80s / early-90s Detroit physical champions', 'Lakers showtime', 'Warriors small ball', 'Spurs boring'],
    ['What is Showtime Lakers?', '1980s fast-breaking Magic Johnson Lakers', 'Warriors 2015', 'Heatles', 'Process Sixers'],
    ['What is the "Heatles"?', 'LeBron-Wade-Bosh Miami Heat era', 'Miami volleyball', 'Beach league', 'Arena nickname'],
    ['What is "Trust the Process" draft pick low point?', '76ers bottomed out for high picks before Embiid era peak', 'Celtics rebuild', 'Knicks always winning', 'Lakers tank'],
    ['Who is Jerry West in front-office history?', 'Executive and logo figure; Clippers/Lakers ties', 'Only player', 'Only ref', 'Only owner'],
    ['What is Sam Presti known for?', 'Thunder GM with many draft picks accumulated', 'Heat coach', 'Raptors mascot', 'NBA commissioner'],
    ['What is "The Process" draft picks highlight?', 'Joel Embiid drafted third in 2014', 'Ben Simmons first', 'Fultz first', 'Tatum first'],
    ['What is the Kawhi Leonard trade (2018) known for?', 'Raptors traded DeMar DeRozan for Kawhi — title run', 'Lakers trade', 'Celtics trade', 'Nets trade'],
    ['What is the Paul George "Playoff P" narrative?', 'Nickname for George — debated clutch reputation', 'Payton nickname', 'Parker nickname', 'Pippen nickname'],
    ['What is "Playoff Jimmy"?', 'Jimmy Butler\'s elevated postseason performances', 'Jimmy Fallon', 'Jimmy Kimmel', 'Young Jimmy'],
    ['What is the "Bubble" championship (2020)?', 'Lakers title in Orlando COVID isolation campus', 'Spurs 1999', 'Heat 2006', 'Dirk 2011'],
    ['What is the "Greek Freak" draft story?', 'Giannis drafted 15th in 2013 from Greece', 'Undrafted', 'First pick', 'Second round'],
    ['What is Jokić draft trivia?', 'Second round, 41st pick in 2014', 'Lottery pick', 'Undrafted', 'First overall'],
    ['What is Dirk Nowitzki\'s one-team legacy?', '21 seasons with Dallas Mavericks', 'Lakers legend', 'Celtics legend', 'Heat lifer'],
    ['What is Tim Duncan\'s nickname?', 'The Big Fundamental', 'The King', 'The Beard', 'The Answer'],
    ['What is Allen Iverson\'s nickname?', 'The Answer', 'The King', 'The Process', 'The Greek Freak'],
    ['What is James Harden\'s nickname?', 'The Beard', 'The Answer', 'Chef', 'Slim Reaper'],
    ['What is Kevin Durant\'s nickname?', 'Slim Reaper / KD', 'The Beard', 'The Greek', 'The Joker'],
    ['What is Stephen Curry\'s nickname?', 'Chef Curry / Baby-Faced Assassin', 'The King', 'The Process', 'Magic'],
    ['What is Magic Johnson\'s real first name?', 'Earvin', 'Irving', 'Ervin Jr.', 'Elvin'],
    ['What is Larry Bird\'s home state legend?', 'Indiana / Hick from French Lick vibe', 'Boston-born', 'New York', 'Texas'],
    ['What is Reggie Miller famous for vs Knicks?', '8 points in 9 seconds (1995)', '81-point game', '100-point game', '60 triple-doubles'],
    ['What is Klay Thompson\'s single-quarter record?', '37 points in a quarter (2015)', '23 in quarter', '50 in quarter', '40 in quarter'],
    ['What is Wilt\'s single-season scoring average record?', '50.4 points per game (1961–62)', '35.4', '40.4', '45.0'],
    ['What is Oscar Robertson\'s 1961–62 season feat?', 'Averaged a triple-double for the season', '100 points one game', '10 steals per game', '20 blocks per game'],
  ],
  5: [
    ['What is true shooting formula conceptually?', 'Points per shooting attempt including FTs', 'FG% only', 'Wins only', 'Turnovers'],
    ['What is effective field goal percentage (eFG%)?', 'Adjusts for three-pointers being worth more', 'Only dunks', 'Only layups', 'Only mid-range'],
    ['What is usage rate?', 'Estimate of team plays used by a player while on court', 'Water bottle usage', 'Bench time', 'Timeout usage'],
    ['What is assist percentage?', 'Estimate of teammate baskets assisted while on floor', 'Assist-to-turnover only', 'Steal rate', 'Block rate'],
    ['What is rebound percentage?', 'Share of available rebounds grabbed', 'Rebound height', 'Rebound weight', 'Rebound speed'],
    ['What is defensive rating?', 'Points allowed per 100 possessions (lower is better)', 'Steals per game', 'Blocks only', 'Fouls'],
    ['What is offensive rating?', 'Points scored per 100 possessions (higher is better)', 'Three-point %', 'Free throw %', 'Age'],
    ['What is pace?', 'Possessions per game / speed of play', 'Heart rate', 'Shot clock only', 'Quarter length'],
    ['What is net rating?', 'Offensive rating minus defensive rating per 100', 'Wins minus losses', 'Home minus road', 'Salary minus tax'],
    ['What is clutch time (NBA.com definition style)?', 'Last 5 minutes, margin within 5 points', 'Last minute only', 'Overtime only', 'First quarter'],
    ['What is a "hammer" action?', 'Weak-side flare screen for corner three', 'Dunk only', 'Foul type', 'Timeout'],
    ['What is "Spain pick-and-roll"?', 'Stacked screen action with back screener', 'International rule', 'FIBA only', 'EuroLeague import'],
    ['What is "horns" set?', 'Two high post screens elbows shape', 'Defensive formation', 'Jump ball', 'Baseline inbound'],
    ['What is "Chicago" action?', 'Pin-down into dribble handoff', 'Windy City only rule', 'Bulls logo', 'Michael Jordan play'],
    ['What is "elevator doors"?', 'Two screeners close gap for shooter', 'Arena doors', 'Locker room', 'Trade deadline'],
    ['What is "veer-back"?', 'DHO variation timing', 'Backcourt violation', 'Ref signal', 'Shoe deal'],
    ['What is "ghost screen"?', 'Screener slips without contact to confuse defense', 'Technical foul', 'Flagrant', 'Ejection'],
    ['What is "ice" side pick-and-roll coverage?', 'Force ball-handler baseline with weak-side help', 'Cooling fans', 'Ice pack injury', 'Hockey'],
    ['What is "weak" vs "blue" terminology (coaching)?', 'Different ICE tagging schemes — weak push baseline', 'Jersey colours', 'Mood', 'Arena lights'],
    ['What is a "drop" coverage?', 'Big hangs back in paint vs pick-and-roll', 'Player drops ball', 'Salary drop', 'Standings drop'],
    ['What is "hedging"?', 'Big briefly shows high then recovers', 'Gardening', 'Salary cap hedge', 'Stock market'],
    ['What is "blitzing" the pick-and-roll?', 'Two defenders aggressively trap ball-handler', 'One-on-one', 'Zone only', 'Man only'],
    ['What is "switching 1 through 5"?', 'All players capable of switching any screen', 'Jersey numbers', 'Quarter switch', 'Arena switch'],
    ['What is "rim protection" analytics?', 'Contesting shots at basket / deterrence', 'Rim paint colour', 'Net height', 'Backboard glass'],
    ['What is "deflection" hustle stat?', 'Getting hands on passes / loose ball disruptions', 'Missed shots', 'Made threes', 'Rebounds'],
    ['What is box plus-minus (BPM)?', 'Estimate of points per 100 vs league average', 'Rebounds in paint', 'Blocks per minute', 'Salary'],
    ['What is VORP?', 'Value Over Replacement Player estimate', 'Vertical jump', 'Volume of rebounds', 'Violations'],
    ['What is WS/48?', 'Win shares per 48 minutes', 'Wins per 48 games', 'Weight stat', 'Walk score'],
    ['What is the Colangelo burner scandal context?', 'Twitter controversy involving 76ers front office', 'Lakers trade', 'Knicks owner', 'Sarver Suns'],
    ['What is Robert Sarver controversy outcome?', 'Suns owner suspended/fined/sold team process (NBA response era)', 'Lifetime award', 'Expansion owner', 'Player fine'],
    ['What is Donald Sterling 2014 outcome?', 'Clippers owner banned for recorded comments; sale forced', 'Suspended one game', 'Promoted', 'Coach hire'],
    ['What is Tim Donaghy scandal?', 'Referee gambling on games officiated', 'Sterling assistant', 'Lockout', 'China game'],
    ['What is the 2011 NBA lockout about?', 'CBA dispute between owners and players', 'Arena strikes', 'China only', 'COVID'],
    ['What is the Harden trade tree meme?', 'Many picks swapped in long-running Rockets/Nets deals', 'Family tree', 'Christmas tree', 'Org chart'],
    ['What is the "Process" Hinkie resignation context?', 'Sixers front office change ending extreme tank strategy era', 'Lakers hire', 'Knicks hire', 'Celtics hire'],
    ['What is "player empowerment era"?', 'Stars force trades / team-up via free agency', 'Owners only era', 'No trades', 'No agency'],
    ['What is a "no-trade clause"?', 'Contract provision limiting trades', 'Clause in shoe deal', 'TV clause', 'G League clause'],
    ['What is a "trade kicker"?', 'Bonus if player is traded', 'Kick ball violation', 'Technical', 'Fine'],
    ['What is "stretch" waiver?', 'Spreading waived salary on cap', 'Stretch four', 'Yoga', 'Injury'],
    ['What is the Gilbert Arenas rule?', 'Poison pill restriction for early Bird extensions', 'Gun locker room incident policy', 'Arenas name', 'Wizards tax'],
    ['What is the Arenas locker room incident (2009–10)?', 'Wizards guns in locker room discipline saga', 'Lakers fight', 'Celtics fight', 'Knicks fight'],
    ['What is "one shining moment"?', 'NCAA tournament closing montage song', 'NBA Finals song', 'All-Star song', 'Draft song'],
    ['What is the G League Ignite program (historical)?', 'Paid path for prospects skipping college (ended later)', 'Video game', 'Charity', 'All-Star'],
    ['What is Overtime Elite?', 'Alternate pre-NBA development league path', 'NBA overtime rule', 'G League name', 'WNBA rule'],
    ['What is "two-timeline" Lakers criticism?', 'Trying to contend while keeping future picks', 'Two clocks', 'Two refs', 'Two balls'],
    ['What is the Stepien rule again in plain words?', 'Can\'t trade away first-rounders in consecutive future years without exceptions', 'Can\'t trade players', 'Can\'t trade coaches', 'Can\'t trade arenas'],
    ['What is cap smoothing (2016 CBA context)?', 'Gradual cap spike handling (owners/players debate)', 'Floor waxing', 'Salary flat', 'Tax removal'],
    ['What is the repeater tax?', 'Higher luxury tax for teams paying tax repeatedly', 'Tax on repeat dunks', 'Tax on repeat fouls', 'Ticket tax'],
    ['What is the apron (second tax line)?', 'Higher CBA restrictions beyond luxury tax apron', 'Arena apron', 'Bench apron', 'Paint apron'],
    ['What is the second apron impact (new CBA era)?', 'Limits mid-level signings and trade aggregations for high-payroll teams', 'Second overtime', 'Second ref', 'Second ball'],
  ],
  6: [
    ['What is RAPM / RPM style metric goal?', 'Regularized adjusted plus-minus for impact', 'Rapid assist per minute', 'Random advanced points model', 'Referee performance model'],
    ['What is EPM (Estimated Plus-Minus) style?', 'Model-based impact per 100 possessions', 'Errors per minute', 'Endorsements per million', 'Extra pass metric'],
    ['What is DARKO / daily plus-minus style modeling?', 'Bayesian updating of player impact over time', 'Stadium lighting model', 'Draft randomness', 'D-League stats'],
    ['What is LEBRON metric naming nod?', 'LeBron-era impact modeling naming (analyst metric)', 'LeBron-only stat', 'LeBron height', 'LeBron age curve'],
    ['What is "luck" adjusted net rating?', '3PT% variance and opponent shooting normalization debates', 'Coin flips', 'Ref luck', 'Lottery luck'],
    ['What is shot quality modeling?', 'Expected points per shot based on location/defense', 'Only dunks', 'Only free throws', 'Only turnovers'],
    ['What is tracking data (Second Spectrum era)?', 'Player/ball movement cameras for advanced stats', 'Ticket scanning', 'Drug testing', 'TV ratings'],
    ['What is player tracking speed / distance?', 'Feet run, accelerations, top sprint speed in games', 'Flight miles', 'Uber rides', 'Bench distance'],
    ['What is "gravity" on offense?', 'Shooting threat pulling defenders away', 'Newton gravity', 'Arena fans', 'Jersey sales'],
    ['What is "paint touch" analytics?', 'Drives and post entries measuring rim pressure', 'Paint drying time', 'Arena paint brand', 'Court repaint'],
    ['What is "advantage creation" studies?', 'How stars draw help to open teammates', 'Ref advantage', 'Home court', 'Salary cap'],
    ['What is "low man wins" help-defense rule?', 'The lower defender in stance often takes charge risk', 'Jump ball rule', 'Height rule', 'Salary rule'],
    ['What is "x-out" rotation?', 'Weak-side defenders exchange assignments on skip pass', 'X on jersey', 'X-ray injury', 'XL shirt'],
    ['What is "ice" vs "weak" tagging history?', 'Evolution of pick-and-roll coverages in NBA coaching', 'Cooling tech', 'Jersey tags', 'Social media'],
    ['What is "delay" action in Spain pick-and-roll?', 'Third player timing after double screen', 'Game delay', 'Shot clock delay', 'Trade delay'],
    ['What is "Chicago" vs "Miami" series actions naming?', 'Common NBA playcall families from strong organizations', 'Weather patterns', 'City population', 'Airport codes'],
    ['What is "veer" vs "stay" dribble handoff reads?', 'Ball-handler reads defender angle on DHO', 'Water veer', 'Car veer', 'Bike veer'],
    ['What is "ghost" vs "flip" screen taxonomy?', 'Modern screening taxonomy for analytics tagging', 'Haunted arena', 'Coin flip', 'Phone flip'],
    ['What is "short roll" navigation?', 'Big rolling to pocket vs long roll deep', 'Short pass', 'Short clock', 'Short player'],
    ['What is "Spain" back screener purpose?', 'Freeing roller with second screen wave', 'Tourism ad', 'Spanish language', 'FIBA only'],
    ['What is "Horns Flare"?', 'Horns set with flare screen weak side', 'Bull horns mascot', 'Devil horns', 'Car horns'],
    ['What is "Chicago zoom" action?', 'Chicago action with zoom cut terminology (coaching)', 'Map zoom', 'Camera zoom', 'Lens zoom'],
    ['What is "Delay Chicago"?', 'Delay entry into Chicago series', 'Airport delay', 'Rain delay', 'Visa delay'],
    ['What is "Elbow series"?', 'Actions starting from high post elbows', 'Elbow injury report', 'Elbow pass', 'Elbow foul'],
    ['What is "ATO" (after timeout) playbook importance?', 'Coaches draw special plays out of timeouts', 'Automatic ejection', 'Average timeout output', 'Assist-to-offense'],
    ['What is "SLOB" / "BLOB"?', 'Sideline / baseline out-of-bounds plays', 'Blob fish mascot', 'Slow lob', 'Super long bounce'],
    ['What is "hammer" weak-side tag in film room?', 'Corner three setup via back screen', 'Tool name', 'Foul hammer', 'Judge hammer'],
    ['What is "Chicago exit" counters?', 'Defensive counters to Chicago series', 'Highway exit', 'Subway exit', 'Fire exit'],
    ['What is "stack" alignment terminology?', 'Players lined vertically for stagger screens', 'Stack overflow', 'Stack salary', 'Stack coaches'],
    ['What is "Spain short roll" counter?', 'Adjust roller path vs switching', 'Spain vacation', 'Spanish short story', 'Short Spanish'],
    ['What is "fourth quarter lineup" analytics?', 'Closing five-man unit effectiveness', 'Fourth jersey', 'Fourth ref', 'Fourth arena'],
    ['What is "clutch" WPA style thinking?', 'Win probability added in clutch minutes', 'Waterproof rating', 'WPA wifi', 'Wins per assist'],
    ['What is "game theory" on hack-a?', 'Endgame fouling strategy Nash equilibrium debates', 'Video game', 'Theory of relativity', 'Music theory'],
    ['What is "incentive alignment" in tanking debate?', 'Lottery odds reform to reduce losing incentives', 'Player bonuses', 'Coach bonuses', 'Owner profits'],
    ['What is "flattened lottery odds" (2019 reform)?', 'Worst record less guaranteed at #1 pick', 'Flat basketball', 'Flat salary', 'Flat Earth'],
    ['What is play-in impact on tanking?', 'Middle seeds compete — changes marginal incentives', 'Play-in to G League', 'Play-in to Olympics', 'Play-in to NFL'],
    ['What is cap spike 2016 effect?', 'Sudden cap jump changed free agency (Durant to Warriors era)', 'Spike Lee', 'Spike ball', 'Volleyball'],
    ['What is "designated rookie max"?', 'Rose rule style escalators for young superstars', 'Rookie hazing max', 'Max roster 15', 'Max shoes'],
    ['What is "designated veteran player" extension?', 'Allows higher raises for qualifying veterans', 'Veteran minimum only', 'Rookie scale', 'Two-way'],
    ['What is "Bird rights" cap hold?', 'Placeholder amount on cap until free agency resolved', 'Bird mascot costume', 'Larry Bird jersey', 'Pigeon rights'],
    ['What is "Gilbert Arenas" mid-level poison context?', 'Historic CBA quirks with extensions — trivia for CBA wonks', 'Arenas gun rule only', 'Wizards tax', 'Magic rule'],
    ['What is "Harden rule" (gather step / natural motion)?', 'Interpretation changes on fouling jump shooters over time', 'Step-back ban', 'Beard tax', 'Free throw clock'],
    ['What is "transition take foul" rule?', 'Clear path foul-like penalty to discourage break-stopping fouls', 'Takeout food', 'Take three', 'Take five'],
    ['What is "flopping" fine history?', 'League fines after video review for embellishment', 'Floor mopping', 'Flip phone', 'Flop era music'],
    ['What is "load management" policy evolution?', 'League mandates minimum games for awards (new era rules)', 'Management books', 'Manager firing', 'Loading docks'],
    ['What is "In-Season Tournament" court design debate?', 'Distinctive courts — branding and player adjustment talk', 'Court TV', 'Court size', 'Court color blind'],
    ['What is "challenge" system (coaches challenge)?', 'Limited replay challenges on calls', 'Challenge trade', 'Challenge game', 'Challenge fan'],
    ['What is "clear path foul" rule precision?', 'Fast break foul criteria with free throws and possession', 'Clear path to bench', 'Clear path to trade', 'Clear paint'],
    ['What is "hosting" All-Star weekend economics?', 'City impact studies — tourism vs arena costs', 'Hosting podcast', 'Hosting server', 'Hosting award show'],
    ['What is "Rookie Scale" contract structure?', 'Slotted pay by draft pick number in collective agreement', 'Rookie wall myth', 'Rookie of Year vote', 'Rookie age'],
  ],
};
