import type { Fact } from './group1';

/** NHL-focused trivia; workplace-appropriate tone; difficulty scales by grade. */
export const nhl: Record<number, Fact[]> = {
  1: [
    ['What sport does the NHL feature?', 'Ice hockey', 'Basketball', 'Baseball', 'Soccer'],
    ['What does NHL stand for?', 'National Hockey League', 'National Hoops League', 'Northern Hockey League', 'National Helmet League'],
    ['How many skaters per team are on the ice during standard play?', '5', '4', '6', '7'],
    ['Who guards the net?', 'Goaltender (goalie)', 'Quarterback', 'Pitcher', 'Referee'],
    ['What do players score into?', 'The net', 'A hoop', 'End zone', 'Hole'],
    ['What surface is NHL hockey played on?', 'Ice', 'Grass', 'Clay', 'Sand'],
    ['What is the rubber disc called?', 'Puck', 'Ball', 'Shuttlecock', 'Stone'],
    ['What do players use to control the puck?', 'A stick', 'A bat', 'A racket', 'Bare hands'],
    ['What are the vertical posts and crossbar called together?', 'The goal frame', 'The wicket', 'The uprights', 'The baseline'],
    ['What is it called when the puck fully crosses the goal line legally?', 'A goal', 'A touchdown', 'A basket', 'A point'],
    ['Which Canadian city is home to the Maple Leafs?', 'Toronto', 'Montreal', 'Vancouver', 'Calgary'],
    ['Which Canadian city is home to the Canadiens?', 'Montreal', 'Toronto', 'Ottawa', 'Quebec City'],
    ['Which Canadian city is home to the Oilers?', 'Edmonton', 'Calgary', 'Winnipeg', 'Regina'],
    ['Which Canadian city is home to the Flames?', 'Calgary', 'Edmonton', 'Vancouver', 'Victoria'],
    ['Which Canadian city is home to the Canucks?', 'Vancouver', 'Seattle', 'Portland', 'Victoria'],
    ['Which Canadian city is home to the Senators?', 'Ottawa', 'Toronto', 'Kingston', 'Hamilton'],
    ['Which Canadian city is home to the Jets?', 'Winnipeg', 'Saskatoon', 'Regina', 'Thunder Bay'],
    ['What trophy do teams compete for in the Stanley Cup Playoffs?', 'Stanley Cup', 'Vince Lombardi Trophy', "Larry O'Brien Trophy", 'Commissioner Cup'],
    ['How many periods are in a regulation NHL game?', '3', '2', '4', '5'],
    ['What is the short break between periods often called?', 'Intermission', 'Halftime only', 'Timeout', 'Overtime'],
    ['What happens if the game is tied after regulation?', 'Overtime (and possibly shootout depending on season rules)', 'Coin toss', 'Replay full game', 'Shared win'],
    ['What is a face-off?', 'Official drops puck between two centers to restart play', 'A fight', 'A penalty shot', 'A substitution'],
    ['What is icing (simple idea)?', 'Shooting puck from behind center red line past goal line without touch', 'Decorating the rink', 'Goal celebration', 'Penalty for fighting'],
    ['What is offside in hockey (simple)?', 'Attacking player enters zone before puck', 'Player behind net', 'Goalie leaves crease', 'Too many passes'],
    ['What is a power play?', 'Team has player advantage after opponent penalty', 'Extra practice', 'Playoff round', 'Shootout only'],
    ['What is a penalty kill?', 'Short-handed team defending a power play', 'Deleting penalties', 'Coach timeout', 'Video review'],
    ['What is the crease around the net mainly for?', 'Protecting the goalie and defining goalie interference rules', 'Face-off circle', 'Bench area', 'Penalty box'],
    ['What is the penalty box?', 'Where penalized players sit for their minor/major time', 'Equipment room', 'Coach office', 'VIP seats'],
    ['What does a referee use to stop play?', 'Whistle', 'Bell', 'Horn', 'Clap'],
    ['What are the lines across the ice called (examples)?', 'Blue lines, red center line, goal lines', 'Yard lines', 'Service lines', 'Hash marks only'],
    ['What is a hat trick?', 'Three goals by one player in a game', 'Three assists', 'Three fights', 'Three saves'],
    ['What is a save?', 'Goalie stops puck from entering net', 'Player passes puck', 'Coach challenge', 'Bench minor'],
    ['What is an assist?', 'Pass or play leading directly to a goal', 'Goal itself', 'Fight won', 'Face-off win'],
    ['What is a body check?', 'Legal shoulder-to-body hit on puck carrier', 'Illegal always', 'Goalie move', 'Shot type'],
    ['What is a slap shot?', 'Full wind-up shot with stick flex', 'Gentle tap-in', 'Backhand flip', 'Wraparound only'],
    ['What is a wrist shot?', 'Quick release using wrist snap', 'Only from blue line', 'Goalie clearance', 'Penalty shot'],
    ['What is a breakaway?', 'Skater alone vs goalie on rush', 'Power play setup', 'Icing', 'Offside'],
    ['What is empty net?', 'Goalie pulled for extra attacker late in game', 'No fans', 'Broken glass', 'Practice drill'],
    ['Which U.S. expansion team began play near Seattle in 2021?', 'Kraken', 'Golden Knights', 'Coyotes', 'Whalers'],
    ['Which Nevada team joined the NHL in 2017?', 'Vegas Golden Knights', 'Utah Grizzlies', 'Reno Raiders', 'Las Vegas Aces'],
    ['What colour is home ice often painted in ads?', 'White ice with logos and lines', 'Green', 'Brown', 'Black'],
    ['What protects players heads?', 'Helmets', 'Caps only', 'Visors only', 'Nothing'],
    ['What do players wear on legs for protection?', 'Shin pads', 'Sandals', 'Sneakers only', 'Knee braces only'],
    ['What is a Zamboni used for?', 'Resurfacing ice between periods', 'Scoring goals', 'Playing music', 'Selling snacks'],
    ['What is the NHL All-Star Game?', 'Midseason showcase of league stars', 'Stanley Cup final', 'Draft lottery', 'Preseason only'],
    ['What is the NHL Draft?', 'Teams select amateur playing rights', 'Trade deadline', 'Salary arbitration', 'Rule book vote'],
    ['What is a captain\'s "C" on a jersey?', 'Team leadership role on ice', 'Coach substitute', 'Rookie marker', 'Sponsor logo'],
    ['What is an alternate captain "A"?', 'Secondary leadership designation', 'Assistant coach', 'Arena staff', 'Amateur tryout'],
    ['What is the trapezoid behind the net about (goalie)?', 'Limits where goalie may play puck with stick', 'Decoration', 'Bench zone', 'TV camera zone'],
    ['What is sudden-death overtime in playoffs?', 'Next goal wins the game', 'Always shootout', 'Tie stands', 'Coin flip'],
    ['What is a shootout (regular season, when used)?', 'Individual skaters vs goalie to break tie', 'Team brawl', 'Coin toss series', 'Replay period'],
  ],
  2: [
    ['How long is a regulation NHL period?', '20 minutes', '12 minutes', '15 minutes', '30 minutes'],
    ['How many teams are in the NHL (approx, 2024–2026 era)?', '32', '30', '28', '36'],
    ['What is the Presidents\' Trophy awarded for?', 'Best regular-season record', 'Stanley Cup winner', 'Most goals by one player', 'Coach of the year'],
    ['What is the Hart Memorial Trophy generally for?', 'League MVP (regular season)', 'Best goalie', 'Best rookie', 'Best defenseman'],
    ['What is the Vezina Trophy for?', 'Top goaltender(s)', 'Top scorer', 'Sportsmanship', 'Comeback player'],
    ['What is the Norris Trophy for?', 'Best defenseman', 'Best forward', 'Best coach', 'Best GM'],
    ['What is the Calder Memorial Trophy for?', 'Rookie of the year', 'Best goalie', 'Best fighter', 'Best captain'],
    ['What is the Lady Byng Memorial Trophy for?', 'Gentlemanly conduct and ability', 'Most penalty minutes', 'Best defenseman', 'Fastest skater'],
    ['What is the Conn Smythe Trophy for?', 'Playoffs MVP', 'Regular-season MVP', 'Best rookie', 'Coach of playoffs'],
    ['What is a two-line pass rule history note?', 'NHL removed the two-line pass offside in 2005–06', 'Still active everywhere', 'Never existed', 'Only in Olympics'],
    ['What is the salary cap?', 'League limit on team player payroll', 'Stadium roof height', 'Ticket price cap', 'Rink length'],
    ['What is LTIR in cap talk (simple)?', 'Long-term injury reserve affecting roster/cap flexibility', 'Long-term interest rate', 'League TV income ratio', 'Line change timing rule'],
    ['What is a no-trade clause?', 'Contract term limiting trades without player approval', 'Ban on fighting', 'Goalie equipment rule', 'TV blackout'],
    ['What is a buyout?', 'Team pays player to terminate contract early per formula', 'Trade', 'Extension', 'Signing bonus only'],
    ['What is a signing bonus?', 'Upfront lump in contract', 'Ticket discount', 'Arena naming fee', 'Merch royalty'],
    ['What is an entry-level contract (ELC)?', 'Standard rookie deal with bonuses/structure limits', 'Coach contract', 'Arena lease', 'TV deal'],
    ['What is waivers?', 'Process exposing player to other teams before AHL assignment', 'Penalty review', 'Equipment check', 'Visa process'],
    ['What is the AHL?', 'American Hockey League — primary NHL farm league', 'Amateur house league', 'Arena hockey league', 'Asian hockey league'],
    ['What is a healthy scratch?', 'Skilled player sits as coach decision', 'Injured reserve', 'Suspension', 'Trade pending'],
    ['What is a back-to-back?', 'Games on consecutive days', 'Two practices', 'Double overtime', 'Two fights'],
    ['What is home-ice advantage in playoffs?', 'Extra home games in a best-of series if it goes long', 'Better hotel', 'More timeouts', 'Larger roster'],
    ['What is a best-of-seven series?', 'First team to four wins advances', 'First to three', 'Single elimination', 'Aggregate goals'],
    ['What is a natural hat trick?', 'Three consecutive goals by same player', 'Three goals any order', 'Three fights', 'Three assists'],
    ['What is a Gordie Howe hat trick?', 'Goal, assist, and fight in same game', 'Three goals', 'Three saves', 'Three penalties'],
    ['What is plus-minus (simple)?', 'On-ice goal differential for player at even strength (limitations apply)', 'Shots on goal', 'Save percentage', 'Face-off %'],
    ['What is Corsi (analytics, simple)?', 'Shot attempts for/against while player on ice (proxy for possession)', 'Save stat', 'Goalie height', 'Ice temperature'],
    ['What is expected goals (xG) in hockey analytics?', 'Model weighting shot quality/locations', 'Actual goals only', 'Plus-minus squared', 'Power-play time'],
    ['What is a short-handed goal?', 'Goal scored while team is killing penalty', 'Goal in first minute', 'Empty-net goal', 'Own goal'],
    ['What is an own goal in hockey?', 'Defending team puts puck in own net', 'Goalie scores', 'Referee goal', 'Video goal'],
    ['What is a bench minor?', 'Two-minute penalty assessed to team/coach, served by a player', 'Major fight', 'Game misconduct', 'Match penalty'],
    ['What is a game misconduct?', 'Ejection from game (often with time penalties context)', 'Minor penalty', 'Coach challenge', 'TV timeout'],
    ['What is goalie interference?', 'Illegal contact impairing goalie ability to play position', 'Goalie leaving crease', 'Icing', 'Offside'],
    ['What is high-sticking penalty often for?', 'Stick contact above shoulders dangerous', 'Lifting stick on face-off', 'Broken stick', 'Tape color'],
    ['What is tripping?', 'Using stick/body to cause opponent to fall', 'Skating fast', 'Diving', 'Line change'],
    ['What is hooking?', 'Impeding with stick on body/hands', 'Legal lift check', 'Face-off win', 'Passing'],
    ['What is slashing?', 'Forceful stick chop on opponent', 'Stick measurement', 'Shot clock', 'Zamboni path'],
    ['What is roughing?', 'Excessive pushing/punching not full fight', 'Clean check', 'Icing', 'Offside'],
    ['What is fighting major?', 'Five-minute penalty for fight (rules vary era)', 'Game always ends', 'Automatic suspension always', 'No penalty'],
    ['What is delayed penalty?', 'Extra attacker until offending team touches puck', 'Video review pause', 'Injury timeout', 'Coach challenge'],
    ['What is an offside challenge (historical note)?', 'Coach challenge on zone entry plays (rules evolved)', 'Challenge fight winner', 'Challenge anthem', 'Challenge salary'],
    ['What is the draft lottery?', 'Weighted chance for early picks among non-playoff teams', 'Stanley Cup draw', 'All-Star vote', 'Trade order'],
    ['What is Seattle Kraken home arena?', 'Climate Pledge Arena', 'KeyArena name only forever', 'T-Mobile Park', 'Lumen Field'],
    ['What is Rogers Arena home to?', 'Vancouver Canucks', 'Toronto Maple Leafs', 'Edmonton Oilers', 'Calgary Flames'],
    ['What is Scotiabank Arena home to?', 'Toronto Maple Leafs', 'Montreal Canadiens', 'Ottawa Senators', 'Buffalo Sabres'],
    ['What is Bell Centre home to?', 'Montreal Canadiens', 'Quebec Nordiques', 'Ottawa Senators', 'Toronto Marlies'],
    ['What is Madison Square Garden NHL team?', 'New York Rangers', 'New York Islanders', 'New Jersey Devils', 'Buffalo Sabres'],
    ['What is a Winter Classic?', 'Outdoor regular-season showcase game', 'All-Star Game', 'Olympics', 'Preseason only'],
    ['What is Stadium Series?', 'Outdoor games in football/baseball stadiums', 'Junior tournament', 'European tour', 'Practice'],
    ['What is 3-on-3 overtime (regular season)?', 'Open ice OT format to reduce shootouts', 'Always 5-on-5', 'Always 4-on-4', 'Goalies fight'],
  ],
  3: [
    ['What is the trapezoid rule\'s nickname among fans?', 'Martin Brodeur rule (goalie puck handling era)', 'Wayne Gretzky rule', 'Sidney Crosby rule', 'Gordie Howe rule'],
    ['Who holds many NHL career scoring records?', 'Wayne Gretzky', 'Mario Lemieux', 'Jaromir Jagr', 'Gordie Howe'],
    ['What number did Wayne Gretzky wear famously?', '99', '66', '87', '4'],
    ['Whose number 99 is retired league-wide?', 'Wayne Gretzky', 'Gordie Howe', 'Jean Beliveau', 'Bobby Orr'],
    ['Who is often called "The Great One"?', 'Wayne Gretzky', 'Mario Lemieux', 'Connor McDavid', 'Sidney Crosby'],
    ['What is the Original Six era?', '1942–1967 with six teams (BOS, CHI, DET, MTL, NYR, TOR)', 'First six expansion teams', 'Six divisions', 'Six referees'],
    ['Which team has the most Stanley Cup championships overall?', 'Montreal Canadiens', 'Toronto Maple Leafs', 'Detroit Red Wings', 'Boston Bruins'],
    ['Which Original Six–era U.S. team won its first Stanley Cup in 1928?', 'New York Rangers', 'Detroit Red Wings', 'Chicago Blackhawks', 'Boston Bruins'],
    ['What is the Presidents\' Trophy "curse" myth?', 'Regular-season best team often does not win Cup (not a rule)', 'Guaranteed Cup', 'Banned from playoffs', 'Extra draft picks'],
    ['What is the trade deadline?', 'Last day for playoff roster trades/acquisitions', 'Draft day', 'Free agency start', 'Camp start'],
    ['What is free agency July 1 tradition?', 'Many NHL contracts expire; signing period opens', 'Trade deadline', 'Draft', 'All-Star break'],
    ['What is an offer sheet?', 'RFA contract offer from another team with compensation rules', 'Practice sheet', 'Salary spreadsheet', 'Ice diagram'],
    ['What is an RFA vs UFA (simple)?', 'Restricted vs unrestricted free agency rights differ', 'Same', 'Only goalies', 'Only rookies'],
    ['What is arbitration?', 'Salary dispute resolution process for some players', 'Trade tribunal', 'Discipline panel', 'Expansion draft'],
    ['What is the expansion draft?', 'New team selects players from existing rosters under rules', 'Entry draft', 'Waiver draft', 'Fantasy draft'],
    ['What is Seattle\'s expansion season?', '2021–22 debut', '2017–18', '1999–2000', '2024–25'],
    ['What is Vegas\' first season?', '2017–18', '2015–16', '2019–20', '2021–22'],
    ['Did Vegas win Cup early?', 'Won Stanley Cup in 2022–23 season', 'Never made playoffs', 'Won in first season', 'No finals appearances'],
    ['What is a "reverse retro" jersey program?', 'League throwback/alternate designs (marketing)', 'Goalie pads rule', 'Ref uniform', 'Practice jerseys only'],
    ['What is Adidas Primegreen era?', 'League supplier period with recycled content jerseys', 'Skate blade brand', 'Arena cooling', 'Puck supplier'],
    ['What is Sportlogiq / tracking data used for?', 'Player and puck tracking analytics', 'Ticket scanning only', 'Zamboni GPS', 'Merch sales'],
    ['What is expected goals models\' weakness?', 'Does not capture pre-shot movement fully; context matters', 'Perfect measure', 'Only counts fights', 'Only power play'],
    ['What is PDO (analytics shorthand)?', 'On-ice shooting% + save% regresses — "luck" signal', 'Player durability index', 'Penalty differential odds', 'Puck distance objective'],
    ['What is WAR/GAR in hockey public models?', 'Overall player value estimates vs replacement', 'Fighting wins', 'Wins above referee', 'Goalie arm rating'],
    ['What is the Masterton Trophy for?', 'Perseverance, sportsmanship, dedication to hockey', 'Leading scorer', 'Best goalie', 'Best rookie'],
    ['What is the Ted Lindsay Award?', 'Outstanding player voted by NHLPA members', 'Coach of year', 'GM of year', 'Rookie trophy'],
    ['What is the Jack Adams Award?', 'Coach of the year', 'GM of year', 'Best rookie', 'Best defenseman'],
    ['What is the Jim Gregory GM of the Year Award?', 'General manager of the year', 'Coach of year', 'MVP', 'Top rookie'],
    ['What is the King Clancy Memorial Trophy for?', 'Leadership on and off ice, humanitarian contribution', 'Most goals', 'Most fights', 'Best goalie'],
    ['What is the Mark Messier Leadership Award?', 'Leadership in community as chosen partly by Messier', 'Scoring title', 'Plus-minus', 'Save%'],
    ['What is the Maurice "Rocket" Richard Trophy for?', 'Most goals in regular season', 'Most assists', 'Most points', 'Fastest skater'],
    ['What is the Art Ross Trophy for?', 'Most regular-season points', 'Most goals', 'Best goalie', 'Playoff MVP'],
    ['What is the William M. Jennings Trophy for?', 'Goaltender(s) on team allowing fewest goals', 'Most shutouts career', 'Best save%', 'Rookie goalie'],
    ['What is the James Norris Memorial Trophy?', 'Best all-around defenseman', 'Best forward', 'Best coach', 'Best GM'],
    ['What is the Frank J. Selke Trophy for?', 'Best defensive forward', 'Best defensive defenseman', 'Best goalie', 'Best rookie'],
    ['What is the Rocket Richard vs Art Ross difference?', 'Goals vs total points leader', 'Same', 'East vs West', 'Playoffs vs regular season'],
    ['What is a "10-and-G" misconduct?', '10-minute misconduct penalty type', '10 goals game', '10 saves', '10 fights'],
    ['What is match penalty?', 'Serious deliberate attempt to injure category', 'Minor stick infraction', 'Bench minor', 'Too many men'],
    ['What is too many men on the ice?', 'Bench minor for extra skater during play', 'Major fight', 'Game misconduct', 'Delay of game'],
    ['What is delay of game penalty examples?', 'Puck shot out of play from defensive zone etc. (rules vary)', 'Slow line change always legal', 'Goalie drink water', 'Celebration'],
    ['What is the "DOPS"?', 'Department of Player Safety — supplemental discipline', 'Data operations', 'Draft operations', 'Digital ops'],
    ['What is a hearing with DOPS for?', 'Reviewing dangerous hits/suspensions', 'Contract signing', 'Trade approval', 'Visa'],
    ['What is the Winter Olympics NHL participation history?', 'Participation varies by CBA/COVID; not every Olympics', 'Always sends NHLers', 'Never sent NHLers', 'Only women'],
    ['What is IIHF?', 'International Ice Hockey Federation', 'Indoor Ice Hockey Foundation', 'International Inline Hockey Federation', 'Inter-league Hockey Finance'],
    ['What is World Juniors?', 'Under-20 national team tournament each winter', 'NHL preseason', 'Senior league', 'Women\'s pro league'],
    ['What is PWHL?', 'Professional Women\'s Hockey League (North America)', 'Public Works Hockey League', 'Pacific Winter Hockey League', 'Practice Women\'s House League'],
    ['What is PHF legacy note?', 'Premier Hockey Federation preceded some women\'s pro structures', 'Still the only league', 'NHL subsidiary', 'Junior league'],
    ['What is CHL in Canadian junior context?', 'Canadian Hockey League umbrella (WHL, OHL, QMJHL)', 'College hockey league', 'Champions Hockey League Europe', 'Casual house league'],
    ['What is Memorial Cup?', 'CHL national championship tournament', 'Stanley Cup minor', 'Olympic cup', 'College trophy'],
    ['What is Hobey Baker Award?', 'Top NCAA men\'s ice hockey player', 'AHL MVP', 'ECHL MVP', 'USHL MVP'],
  ],
  4: [
    ['What was the 2004–05 NHL season outcome?', 'Full season lockout cancelled; no Stanley Cup awarded', 'Normal season', 'Only playoffs', 'World Cup replaced'],
    ['What did the 2005–06 rule changes emphasize?', 'Speed/skill: tighter obstruction crackdown, shootout intro era', 'More fighting', 'Larger nets', 'Four periods'],
    ['What is hybrid icing?', 'Linesman judgment race to face-off dots vs touch icing', 'Always touch', 'Always no-touch', 'Only playoffs'],
    ['What is coach\'s challenge scope (modern)?', 'Offside, goalie interference on goals; limited failed challenge penalty', 'Any whistle', 'Any penalty', 'Salary cap'],
    ['What is hand pass rule in offensive zone?', 'Generally illegal to bat puck in offensive zone with hand toward goal', 'Always legal', 'Only goalie', 'Only captain'],
    ['What is kicked-in goal rule gist?', 'Distinct kicking motion disallowed; deflections nuanced', 'Any skate goal counts', 'Kicks encouraged', 'Only in OT'],
    ['What is high stick goal rule?', 'Batting puck in above crossbar height disallowed', 'Any height ok', 'Only wrist shots', 'Only slap shots'],
    ['What is continuous play on delayed penalty?', 'Until offending team touches puck', 'Immediate whistle always', 'Never stops', 'Coach decides'],
    ['What is intent to blow whistle doctrine?', 'Official may deem play dead slightly before audible whistle', 'Never used', 'Only in fights', 'Only for icing'],
    ['What is standard OT length regular season (typical)?', '5 minutes 3-on-3 then shootout (era-dependent)', '20 minutes', '1 minute', 'No OT'],
    ['What is playoff OT format?', '20-minute sudden-death periods until goal', 'Always shootout', '3-on-3 only', '5-minute only'],
    ['What is longest modern NHL playoff OT game reference?', '116 minutes (6 OT) historical examples exist', 'Single OT max', 'No multi-OT', 'Always shootout'],
    ['What is cap circumvention scandal theme?', 'Front-loaded contracts investigated (late 2000s)', 'Ticket scalping', 'Puck weight', 'Ice temperature'],
    ['What is escrow in player pay (CBA topic)?', 'Withholding portion of pay for HRR true-up', 'Bonus pool', 'Trade kicker', 'Signing bonus tax'],
    ['What is hockey-related revenue (HRR)?', 'Shared revenue definition underpinning salary cap split', 'Merch only', 'TV only', 'Tickets only'],
    ['What is LTIR cap recapture (concept)?', 'Rules around long contracts and retirement/front-loaded deals (evolved)', 'Ticket refunds', 'Arena tax', 'Visa limits'],
    ['What is offer sheet compensation tiers about?', 'Draft picks owed if signing away RFA at certain AAV thresholds', 'Cash to league', 'Player suspensions', 'Coach fines'],
    ['What is Seattle expansion fee ballpark?', '650 million USD order-of-magnitude reported', '$50M', '$2B', '$10M'],
    ['What is Vegas expansion fee ballpark?', '500 million USD reported', '$50M', '$5B', '$100M'],
    ['What is Arizona Coyotes arena saga theme?', 'Franchise stability and temporary venues (ongoing history)', 'Always stable arena', 'Never existed', 'Moved to Houston 1999'],
    ['What is Utah Hockey Club interim naming (2024–25)?', 'Utah placeholder team after Arizona relocation', 'Quebec Nordiques return', 'Hartford Whalers', 'Atlanta Thrashers'],
    ['What is Quebec Nordiques relocation year to Colorado?', '1995 became Avalanche', '1980', '2005', '2010'],
    ['What is Winnipeg Jets 1.0 relocation?', 'Atlanta Thrashers became new Winnipeg Jets (2011)', 'Original Jets never moved', 'Nordiques', 'Whalers'],
    ['What is original Winnipeg Jets destination (1996)?', 'Phoenix Coyotes (now Arizona/Utah lineage)', 'Minnesota', 'Quebec', 'Seattle'],
    ['What is Hartford Whalers relocation?', 'Became Carolina Hurricanes (1997)', 'Boston Bruins', 'New York Rangers', 'Toronto'],
    ['What is Minnesota North Stars relocation?', 'Dallas Stars (1993)', 'Wild', 'Predators', 'Kraken'],
    ['What is Minnesota Wild expansion year?', '2000–01', '1993', '2017', '2021'],
    ['What is Nashville Predators expansion year?', '1998–99', '2000', '1993', '2017'],
    ['What is Columbus Blue Jackets expansion year?', '2000–01', '1998', '1993', '2021'],
    ['What is Atlanta Thrashers history?', '1999–2011 then relocation to Winnipeg', 'Still active', 'Became Kraken', 'Merged with Leafs'],
    ['What is Florida Panthers inaugural year?', '1993–94', '2000', '2017', '1980'],
    ['What is Tampa Bay Lightning inaugural year?', '1992–93', '1998', '2000', '2017'],
    ['What is San Jose Sharks inaugural year?', '1991–92', '1993', '2000', '2017'],
    ['What is Anaheim Ducks inaugural year?', '1993–94 as Mighty Ducks', '2007', '2017', '1980'],
    ['What is Los Angeles Kings expansion year?', '1967', '1970', '1980', '1991'],
    ['What is Philadelphia Flyers expansion year?', '1967', '1970', '1980', '1991'],
    ['What is Pittsburgh Penguins expansion year?', '1967', '1970', '1980', '1991'],
    ['What is St. Louis Blues note?', 'Founded 1967; early finals drought meme until 2019 Cup', 'Won Cup every decade', 'Never made finals', 'Original Six team'],
    ['What is Buffalo Sabres expansion year?', '1970', '1967', '1993', '2017'],
    ['What is Vancouver Canucks NHL entry year?', '1970', '1967', '1980', '1991'],
    ['What is Edmonton Oilers WHA merger year to NHL?', '1979', '1967', '1984', '1991'],
    ['What is Calgary Flames origin?', 'Atlanta Flames relocated to Calgary in 1980', 'Expansion 1967', 'WHA only forever', 'Seattle relocation'],
    ['What is Colorado Avalanche immediate success?', 'Won Cup in first Denver season (1996)', 'Missed playoffs 10 years', 'Never won', 'Won as Nordiques same year'],
    ['What is Detroit Red Wings Russian Five era note?', '1990s international influence on team style', 'No Europeans ever', 'Only goalies Russian', 'Banned imports'],
    ['What is New Jersey Devils trap identity?', '1990s–2000s defensive system reputation', 'Run-and-gun only', 'No defense', 'Goalies never used'],
    ['What is Chicago Blackhawks modern dynasty window?', 'Three Cups 2010, 2013, 2015', '1990s only', 'Never won', '2020s five-peat'],
    ['What is Boston Bruins 2011 Cup captain?', 'Zdeno Chara', 'Patrice Bergeron', 'Brad Marchand', 'Tim Thomas'],
    ['What is Washington Capitals 2018 Cup?', 'Ovechkin first Cup; ended long franchise narrative', 'Never won', '2004', '1998'],
    ['What is St. Louis Blues 2019 Cup?', 'First franchise Cup after long wait', 'Sixth Cup that decade', 'Never made playoffs', 'Won as Thrashers'],
    ['What is Toronto Maple Leafs drought theme?', 'Long Cup drought since 1967 (fan culture)', 'Won annually', 'Never made playoffs', 'Most Cups ever'],
    ['What is Montreal Canadiens bilingual market note?', 'Major French/English fan and media environment', 'English only', 'Spanish market', 'German market'],
    ['What is Battle of Alberta?', 'Flames vs Oilers rivalry', 'Leafs vs Habs', 'Rangers vs Islanders', 'Kraken vs Canucks'],
    ['What is Battle of Ontario?', 'Leafs vs Senators rivalry', 'Oilers vs Flames', 'Habs vs Bruins', 'Wild vs Jets'],
    ['What is Original Six rivalry classic?', 'Habs vs Leafs / Bruins vs Habs etc.', 'Kraken vs Golden Knights historical', 'Utah vs Arizona classic since 1920', 'Seattle vs Portland NHL'],
  ],
  5: [
    ['What is Corsi relative (simple)?', 'Player Corsi vs team when off ice baseline', 'Corsi squared', 'Save relative', 'Goalie height delta'],
    ['What is Fenwick metric?', 'Corsi-like but excludes blocked shots for/against', 'Only blocked shots', 'Only fights', 'Face-off wins'],
    ['What is zone starts (ZS%) used for?', 'Contextualizing deployment (offensive vs defensive zone face-offs)', 'Ticket sales zones', 'Arena seating', 'Salary zones'],
    ['What is quality of competition metrics attempt?', 'Who a player faces on average (limitations)', 'Ticket quality', 'Ice quality', 'Broadcast quality'],
    ['What is RAPM concept?', 'Regularized adjusted plus-minus regression style', 'Random assists per minute', 'Referee assigned penalty minutes', 'Revenue adjusted player money'],
    ['What is xGF% at 5v5?', 'Share of expected goals for team while player on ice', 'Share of fights', 'Share of salary cap', 'Share of shots saved'],
    ['What is PK deployment analytics?', 'Forward pairs used on penalty kill optimization', 'Power play only', 'Goalie stretching', 'Bench door speed'],
    ['What is PP zone entry tactics?', 'Controlled entries vs dumps vs drop passes (coaching)', 'Always dump', 'Always icing', 'Always fight'],
    ['What is neutral zone trap (history)?', 'Defensive clog through neutral zone (1990s Devils era popularized)', 'Offensive strategy', 'Goalie tactic', 'Face-off only'],
    ['What is left wing lock system?', 'Defensive structure variant with LW playing deeper role', 'Line brawl formation', 'Power play umbrella', 'Goalie stance'],
    ['What is 1-3-1 power play formation?', 'Umbrella-like setup with bumper/high slot roles', 'Penalty kill', '4 forwards always', 'Goalie pulled'],
    ['What is overload PP concept?', 'Concentrating players on one side to create seams', 'Spreading evenly always', 'Empty net', 'Icing'],
    ['What is diamond PK?', 'Four-player diamond collapsing around house', 'Four forwards attack', 'Goalie skates', 'Offside trap'],
    ['What is wedge +1 breakout?', 'Support pattern exiting defensive zone', 'Face-off play only', 'Goalie fight', 'Line change'],
    ['What is swing man on regroup?', 'F3 high middle lane role in transition', 'Goalie', 'Referee', 'Zamboni driver'],
    ['What is goalie RVH post integration?', 'Reverse VH technique on post seals (modern technique era)', 'Random vertical height', 'Referee video hub', 'Rear view helmet'],
    ['What is post-integration tracking edge?', 'Goalies using post lean techniques with gear fit', 'Marketing term', 'Skate sharpening', 'Stick flex only'],
    ['What does GSAA commonly measure for goalies?', 'Goals saved above average vs a model baseline', 'Goals scored above average', 'Game starts above average', 'Giveaways per 60'],
    ['What is high-danger chances area roughly?', 'Slot / inner house shot locations (model-dependent)', 'Blue line only', 'Neutral zone', 'Bench'],
    ['What is pre-scout packet in pro hockey?', 'Video and tendencies on opponents', 'Fan giveaway', 'Medical kit', 'Puck shipment'],
    ['What is Catapult / Kinexon wearables?', 'Player load tracking devices (where permitted)', 'Puck chips only', 'Goalie pads sensors banned always', 'Ticket wristbands'],
    ['What is SportVU-like optical tracking in NHL?', 'Second-generation league puck/player tracking rollout', 'Fan cameras only', 'Ref cams only', 'Manual counting'],
    ['What is shift length analytics insight?', 'Long shifts correlate with worse defensive outcomes', 'Long shifts always good', 'Irrelevant', 'Only goalies'],
    ['What is line matching?', 'Coach deploys specific lines vs opponent lines', 'Random lines', 'Only in OT', 'Illegal'],
    ['What is last change home advantage?', 'Home team chooses matchup after away puts line on fly', 'Away chooses always', 'Ref chooses', 'Captain rock-paper-scissors'],
    ['What is salary cap recapture penalty (Kovalchuk-style lesson)?', 'Penalizes front-loaded retirement before contract end (rules evolved)', 'Ticket tax', 'Merch fee', 'Arena rent'],
    ['What is performance bonuses on ELC?', 'Schedule A/B bonuses counting toward performance cushion', 'Illegal', 'Only signing bonus', 'Only coaches'],
    ['What is cap retention trade?', 'Team retains % of salary/cap hit in trade', 'Player pays team', 'League pays', 'No retention allowed'],
    ['What is no-move vs no-trade nuance?', 'NMC blocks certain movement; NTC limits trade destinations', 'Same', 'Only goalies', 'Only rookies'],
    ['What is Seattle Kraken expansion draft strategy theme?', 'Side deals and salary cap weaponization discussions', 'Random picks', 'Only goalies taken', 'No trades allowed'],
    ['What is Vegas Golden Knights expansion draft success factor?', 'Cap flexibility and side agreements (widely analyzed)', 'Luck only', 'Draft lottery', 'No rules'],
    ['What is Arizona Coyotes cap dump history note?', 'Teams used Coyotes cap space trades in some eras', 'Never happened', 'Illegal always', 'NHL banned trades'],
    ['What is LTIR "robbery" discourse (media)?', 'Debate about competitive integrity of LTIR use at deadline', 'Literal theft', 'Tax crime', 'Puck theft'],
    ['What is Patrick Kane / Artemi Panarin era note?', 'High-skill Blackhawks wing chemistry era', 'Goalie tandem', 'Defensive trap', 'Expansion draft'],
    ['What is Sidney Crosby generational skill package?', 'Elite puck protection, vision, two-way center play', 'Enforcer only', 'Goalie', 'Defensive defenseman only'],
    ['What is Alex Ovechkin goal-scoring milestone theme?', 'Chasing Gretzky NHL goal record (ongoing narrative)', 'Retired at 500 goals', 'Never scored power play', 'Defense-first career'],
    ['What is Connor McDavid speed edge measured as?', 'Among fastest end-to-end carriers in modern NHL', 'Slowest forward', 'Goalie speed leader', 'Enforcer'],
    ['What is Auston Matthews shot profile?', 'Elite wrister from slot; goal-scoring forward', 'Defensive specialist', 'Goalie', 'Stay-at-home'],
    ['What is Cale Makar defenseman offense model?', 'High mobility QB from blue line; Norris-level peak', 'Pure enforcer', 'Goalie', 'Face-off specialist only'],
    ['What is Igor Shesterkin peak season note?', 'Elite save results vs expectations (Vezina era)', 'Andrei Vasilevskiy', 'Connor Hellebuyck', 'Carey Price'],
    ['What is Carey Price Montreal era legacy?', 'Vezina/Hart peak; franchise face', 'Never starter', 'Winger', 'Coach'],
    ['What is P.K. Subban brand + skill note?', 'Dynamic offensive D; major media personality', 'Goalie', 'Enforcer only', 'Never Norris candidate'],
    ['What is Jaromir Jagr longevity fact?', 'Played into 40s across leagues', 'Retired at 25', 'Never left Czech league', 'Goalie'],
    ['What is Nicklas Lidstrom two-way defense archetype?', 'Positionally perfect; Norris career', 'Enforcer', 'Goalie', 'Agitator only'],
    ['What is Dominik Hasek style?', 'Unorthodox athletic saves; multiple Hart/Vezina era', 'Stand-up only classic', 'Forward', 'Referee'],
    ['What is Martin Brodeur puck-handling impact?', 'Influenced trapezoid rule; offensive goalie clears', 'Never played puck', 'Winger', 'Coach'],
    ['What is Patrick Roy butterfly revolution note?', 'Popularized drop/butterfly style influence', 'Stand-up only', 'Skater', 'Ref'],
    ['What is Jacques Plante mask innovation?', 'First goalie to regularly wear mask in NHL play era', 'Invented composite stick', 'Shot clock', 'Zamboni'],
    ['What is Gordie Howe Mr. Hockey longevity stat?', 'Played in NHL in multiple decades spanning ages', 'Retired at 20', 'One season', 'Goalie'],
    ['What is Mario Lemieux health + dominance story?', 'Elite scoring despite illness/injury interruptions', 'Never scored', 'Defense-only', 'Goalie career'],
    ['What is Bobby Orr revolution?', 'Offensive defenseman changed position expectations', 'Goalie', 'Enforcer', 'Coach only'],
    ['What is "Sid vs Ovi" narrative era?', '2005–2010s league marketing around Crosby/Ovechkin', '1990s only', '2025 new rivalry only', 'Goalie debate'],
  ],
  6: [
    ['What is Evolving Hockey / Natural Stat Trick public role?', 'Public advanced stats sites for NHL micro + macro metrics', 'Official NHL only source', 'Ticket resale', 'Equipment vendor'],
    ['What is MoneyPuck xG model caveat?', 'Model differences vs official tracking; interpret carefully', 'Identical always', 'Banned by NHL', 'Only for baseball'],
    ['What is Corey Sznajder tracked microstats example?', 'Zone entries/exits manually tracked contributions', 'Goalie height charts', 'Salary database', 'Arena acoustics'],
    ['What is Ryan Stimson passing project influence?', 'Early passing network research in hockey analytics community', 'NHL rulebook author', 'Zamboni patent', 'Ref union'],
    ['What is A3Z analytics firm example space?', 'Hockey consulting/analytics services to teams', 'Puck manufacturer', 'Arena food', 'Jersey laundry'],
    ['What is STAC system some teams use?', 'Internal tracking/video integration platforms (vendor ecosystem)', 'Salary cap spreadsheet', 'Student tickets', 'Stick tape'],
    ['What is Catapult ClearSky / indoor tracking note?', 'Indoor GNSS-like tracking in arenas', 'Outdoor only', 'Fan Wi-Fi speed', 'Puck freezer temp'],
    ['What is biomechanics in skating research?', 'Stride efficiency, knee angle, edge work studies', 'Stick flex marketing', 'Helmet color', 'Ticket pricing'],
    ['What is incremental goals added (ixG) variants space?', 'Different xG models produce different incremental metrics', 'Official NHL single definition always', 'Illegal metric', 'Only AHL'],
    ['What is shooter talent adjustment in models?', 'Some models credit individual finishing above location baseline', 'Never done', 'Only for goalies', 'Only for fights'],
    ['What is RAPM vs xGF share debate?', 'Different approaches to isolating player impact', 'Identical outputs', 'Only counting stats', 'Only +/-'],
    ['What is WAR uncertainty intervals?', 'Bootstrap ranges show estimate confidence', 'Exact truth', 'Random number', 'Salary ranges'],
    ['What is lineup optimizer in DFS context (integrity note)?', 'Daily fantasy analytics; separate from team ops', 'NHL coaching tool banned', 'Ref assignment', 'Drug testing'],
    ['What is betting integrity NHL partnership theme?', 'Official data + integrity monitoring with legal sportsbooks growth', 'Banned all betting', 'No data sold', 'Only horse racing'],
    ['What is integrity monitor suspicious wager flag?', 'Unusual betting patterns trigger review', 'Always criminal', 'Never happens', 'Only soccer'],
    ['What is CBA Article 26 PED program (name level)?', 'Joint NHL/NHLPA anti-doping program framework', 'Salary article', 'Expansion article', 'Helmet article'],
    ['What is World Cup of Hockey 2016 structure note?', 'NHL-run best-on-best tournament with hybrid teams', 'Olympics 2018', 'Never held', 'Only juniors'],
    ['What is NHL Global Series business goal?', 'Regular-season games in Europe/Asia for growth', 'Playoffs abroad', 'Draft abroad', 'Only preseason ever'],
    ['What is digital board ads (DBA) controversy?', 'On-ice LED ads can distort puck motion for some viewers', 'They never drew criticism', 'Illegal in the NHL', 'AHL-only technology'],
    ['What is puck and player tracking official data product?', 'NHL Edge stats for fans/broadcast', 'Secret only', 'Sold to casinos only', 'Discontinued 1990'],
    ['What is Amazon Thursday Night parallel (NHL media)?', 'Streaming rights fragmentation trend includes NHL partners', 'NHL only OTA', 'No streaming', 'Radio only'],
    ['What is ESPN / TNT rights window note?', 'US national rights split influences scheduling', 'Single network forever', 'No US TV', 'Only CBC'],
    ['What is Sportsnet Canadian national rights role?', 'Major NHL partner in Canada', 'US only', 'European only', 'Retired'],
    ['What is TV blackout legacy issue?', 'Local game restrictions historically frustrated fans', 'Never existed', 'Still identical today always', 'Only soccer'],
    ['What is NHL.TV / ESPN+ migration theme?', 'Streaming package changes over time', 'Never changed', 'Banned streams', 'Only cable'],
    ['What is gambling ad patch era?', 'Jersey ads for sportsbooks in some markets', 'Illegal everywhere', 'Only MLB', 'Never allowed'],
    ['What is Diamond Sports bankruptcy Bally impact?', 'Regional sports network distress affected broadcasts', 'Helped NHL only', 'No NHL teams affected', 'NHL owned RSNs'],
    ['What is franchise valuation drivers (MBA-ish)?', 'Media rights, arena, market size, brand, on-ice success', 'Only wins', 'Only population', 'Only jersey sales'],
    ['What is EBITDA sports talk caveat?', 'Team accounting differs; comparisons tricky', 'Perfect profit measure', 'Same as cap space', 'Same as wins'],
    ['What is purchase price allocation in team sale?', 'Goodwill vs tangible assets in acquisition accounting', 'Ticket price', 'Salary cap', 'Draft picks'],
    ['What is arena naming rights revenue?', 'Corporate sponsorship of venue name', 'Player salary', 'Luxury tax', 'Puck cost'],
    ['What is personal seat license (PSL) concept?', 'Upfront rights to buy season tickets in new arenas', 'Player contract', 'Salary bonus', 'Merch license'],
    ['What is suite revenue sharing nuance?', 'Teams/arenas allocate premium seating differently', 'Always equal split', 'Illegal', 'NHL only'],
    ['What is revenue sharing pool NHL?', 'High-revenue teams contribute to support partners', 'Players pay owners', 'Government grant', 'Only playoffs'],
    ['What is escrow true-up math (simple)?', 'Players may owe back if HRR below projections', 'Owners pay players extra always', 'Flat 50/50 daily cash', 'No true-up'],
    ['What is escrow cap on player checks (CBA era detail)?', 'Limits on escrow % in various CBA years', 'Unlimited always', 'Zero always', 'Only rookies'],
    ['What is international tax for players (concept)?', 'Jock tax and multi-jurisdiction filings', 'No tax', 'Flat Canada tax only', 'Only US citizens'],
    ['What is signing bonus tax timing?', 'Often taxed where paid/residency rules apply', 'Never taxed', 'Only in playoffs', 'Only merchandise'],
    ['What is Olympic insurance hurdle for NHL?', 'Who pays injury insurance for stars during Olympics', 'No issue ever', 'Players always pay', 'IOC pays always'],
    ['What is IIHF transfer agreement note?', 'Movement of players between leagues under agreements', 'Banned transfers', 'Only trades', 'Only waivers'],
    ['What is KHL competition for talent (economic)?', 'Tax-free offers and shorter contracts sometimes lure players', 'No competition', 'Higher always than NHL', 'Illegal'],
    ['What is SHL Liiga SM-liiga feeder role?', 'European development paths to NHL', 'No NHL ties', 'Only baseball', 'Only juniors'],
    ['What is NCAA route vs CHL route debate?', 'Different eligibility and development timelines', 'Identical', 'NCAA banned', 'CHL banned'],
    ['What is CHL education packages marketing?', 'Scholarship programs promoted for players', 'No education', 'Only PhD required', 'Only tradeschool'],
    ['What is abuse in hockey investigation era?', 'Hockey Canada / junior scandals increased governance scrutiny', 'Never happened', 'Resolved fully 1990', 'Only NBA issue'],
    ['What is SafeSport US parallel concept?', 'Reporting systems in youth/amateur sport contexts', 'NHL-only program', 'Equipment standard', 'Ice hardness'],
    ['What is diversity and inclusion NHL initiatives theme?', 'Hockey is for Everyone programs; hiring pipelines', 'No initiatives', 'Banned analytics', 'Only marketing'],
    ['What is Kim Davis executive role history note?', 'NHL SVP social impact, growth, legislative matters (titles evolve)', 'Player', 'Referee', 'Zamboni lead'],
    ['What is Steve Mayer events role legacy?', 'NHL events and entertainment leadership (era-dependent)', 'Goalie coach', 'Capologist', 'Linesman'],
    ['What is Bill Daly Gary Bettman tandem?', 'Deputy commissioner and commissioner leadership long tenure', 'Player union', 'PA head', 'Ref chief'],
    ['What is Marty Walsh NHLPA executive director note?', 'Former labor-side mayor became PA leader (era fact)', 'NHL commissioner', 'Referee', 'Owner only'],
    ['What is Donald Fehr NHLPA historical note?', 'Longtime PA leader through lockouts/CBAs', 'NHL commissioner', 'Coach', 'Owner'],
    ['What is escrow vs escrow — CBA negotiation lever?', 'Escrow battles central in multiple lockouts', 'Never discussed', 'Only fighting rules', 'Only helmets'],
    ['What is Seattle climate pledge arena sustainability pitch?', 'Net zero carbon arena branding', 'Coal-powered rink', 'No HVAC', 'Open roof always'],
    ['What is carbon footprint travel schedule analytics?', 'Teams optimize road trips for emissions/cost', 'Never considered', 'Only fans travel', 'Only playoffs'],
    ['What is frozen four?', 'NCAA men\'s hockey semifinals/finals tournament', 'NHL round', 'AHL only', 'KHL final'],
  ],
};
