/** Pop culture grades 4–6: Toronto diaspora, ~65% Western / 35% Desi, ramping difficulty. */
export const grade4: [string, string, string, string, string][] = [
  ['What is the name of the coffee shop where the Friends characters hang out?', 'Central Perk', 'Java Junction', 'Blue Bottle', 'The Beanery'],
  ['In The Office (US), what is the name of the paper company where they work?', 'Dunder Mifflin', 'Staples Plus', 'Wernham Hogg', 'Pied Piper'],
  ['What is Drake\'s full legal first and middle name?', 'Aubrey Drake Graham', 'Drake Aubrey Williams', 'Aubrey Marcus Graham', 'Drake Anthony Graham'],
  ['What is The Weeknd\'s real full name?', 'Abel Makkonen Tesfaye', 'Abel Hassan Tesfaye', 'Abel Michael Tesfaye', 'Abel Daniel Tesfaye'],
  ['In Breaking Bad, what is Walter White\'s middle name?', 'Hartwell', 'Wilson', 'James', 'Edward'],
  ['Which Game of Thrones episode features the Red Wedding?', 'The Rains of Castamere (Season 3, Episode 9)', 'Blackwater', 'The Mountain and the Viper', 'Hardhome'],
  ['In John Wick (2014), what breed is the dog that starts his revenge arc?', 'Beagle', 'Pit bull', 'German Shepherd', 'Labrador'],
  ['Who won the Best Actor Oscar for playing the Joker in Joker (2019)?', 'Joaquin Phoenix', 'Heath Ledger', 'Jared Leto', 'Willem Dafoe'],
  ['What year did Instagram launch?', '2010', '2009', '2011', '2012'],
  ['On TikTok, what does FYP stand for?', 'For You Page', 'Follow Your People', 'Featured Young Posts', 'Fan Your Profile'],
  ['What does "ratio" mean on Twitter/X in common usage?', 'A reply getting more engagement than the original tweet', 'A math comparison', 'A poll result', 'A follower count'],
  ['Who developed Fortnite?', 'Epic Games', 'Activision', 'EA', 'Ubisoft'],
  ['What is the Chinese name for the app known as TikTok internationally?', 'Douyin', 'WeChat', 'Bilibili', 'Kuaishou'],
  ['In The Mandalorian, what is the foundling\'s canonical name?', 'Grogu', 'Yoda Jr.', 'Kanan', 'Ezra'],
  ['What was EA\'s soccer game series rebranded to after losing the FIFA license?', 'EA Sports FC', 'Pro Evo FC', 'Ultimate Soccer', 'World Football'],
  ['Who is credited as the original creator of Minecraft?', 'Markus "Notch" Persson', 'Jens Bergensten', 'Phil Spencer', 'Hideo Kojima'],
  ['Which Stephen King novella was The Shawshank Redemption adapted from?', 'Rita Hayworth and Shawshank Redemption', 'The Body', 'The Mist', 'Apt Pupil'],
  ['In Pulp Fiction, what is famously inside the briefcase?', 'It is never revealed', 'Gold bars', 'Drugs', 'A soul'],
  ['What is the name of the restaurant in The Bear?', 'The Original Beef of Chicagoland', 'Carmy\'s Kitchen', 'Chicago Beef Co.', 'The Beef Stand'],
  ['In Ozark, what lake is central to the Byrdes\' laundering operations?', 'Lake of the Ozarks', 'Lake Michigan', 'Table Rock Lake', 'Bull Shoals Lake'],
  ['Which Pakistani drama stars Ahmed Ali Akbar as the title character who transforms over the series?', 'Parizaad', 'Sang-e-Mah', 'Ehd-e-Wafa', 'Alif'],
  ['Slumdog Millionaire won Oscars including Best Picture; who composed its score?', 'A.R. Rahman', 'Shankar-Ehsaan-Loy', 'Pritam', 'Vishal Bhardwaj'],
  ['Which band originally performed "Aadat" before Atif Aslam\'s solo fame?', 'Jal', 'Strings', 'Noori', 'Call'],
  ['Who are the two core members of the Pakistani band Strings?', 'Bilal Maqsood and Faisal Kapadia', 'Ali Azmat and Salman Ahmad', 'Xulfi and Farhad', 'Junaid and Rohail'],
  ['What is the name of SRK\'s character in DDLJ?', 'Raj Malhotra', 'Rahul Khanna', 'Dev Saran', 'Kabir Khan'],
  ['Which Coke Studio Pakistan season featured "Pasoori" by Ali Sethi and Shae Gill?', 'Season 14', 'Season 12', 'Season 10', 'Season 8'],
  ['In Bollywood, "Chaiyya Chaiyya" appears on a train in which film?', 'Dil Se', 'DDLJ', 'Chennai Express', 'Ra.One'],
  ['What is a "biodata" in desi matchmaking slang?', 'A marriage resume with family details', 'A medical fitness report', 'A visa application', 'A rental agreement'],
  ['Which Vital Signs member later became a televangelist before his death in a plane crash?', 'Junaid Jamshed', 'Rohail Hyatt', 'Shahzad Hasan', 'Nusrat Hussain'],
  ['What does "copium" mean in internet slang?', 'Coping by pretending something false is true', 'A new energy drink meme', 'Copyright infringement joke', 'A Twitch emote only'],
  ['In Succession, what is the name of the family\'s media conglomerate?', 'Waystar Royco', 'Pierce Global', 'ATN Media', 'Roy Holdings'],
  ['What is the name of Joe Goldberg\'s love interest/bookshop employee in You Season 1?', 'Guinevere Beck', 'Love Quinn', 'Marienne', 'Kate'],
  ['In the MCU, which AI voice assists Tony Stark after JARVIS becomes Vision?', 'FRIDAY', 'KAREN', 'EDITH', 'JOCASTA'],
  ['Which Toronto-born rapper\'s album Views features the CN Tower on its cover?', 'Drake', 'The Weeknd', 'Nav', 'PARTYNEXTDOOR'],
  ['In GTA V, the city of Los Santos is mainly modeled on which real US city?', 'Los Angeles', 'Miami', 'New York City', 'Chicago'],
  ['What is the highest-grossing Pakistani film domestically/international reboot sense often cited?', 'The Legend of Maula Jatt', 'Waar', 'Jawani Phir Nahi Ani', 'Punjab Nahi Jaungi'],
  ['In Euphoria, who plays Rue?', 'Zendaya', 'Sydney Sweeney', 'Hunter Schafer', 'Alexa Demie'],
  ['What 2023 Bollywood film starring Ranbir Kapoor as a violent son sparked huge debate?', 'Animal', 'Brahmastra', 'Sanju', 'Tamasha'],
  ['Which Junoon album features "Sayonee"?', 'Azadi', 'Inquilaab', 'Kashmakash', 'Andaz'],
  ['In Black Mirror, which episode shows a social rating app destroying daily life?', 'Nosedive', 'San Junipero', 'USS Callister', 'Metalhead'],
  ['What year did Spotify launch globally (approx)?', '2008', '2004', '2012', '2015'],
  ['In Parasite (2019), the wealthy family\'s home is famously?', 'Built by a famous architect with a hidden bunker below', 'A traditional hanok only', 'A high-rise apartment', 'A boat'],
  ['What streaming service produced Stranger Things?', 'Netflix', 'HBO Max', 'Amazon Prime', 'Apple TV+'],
  ['In The Dark Knight, who plays Harvey Dent before he becomes Two-Face?', 'Aaron Eckhart', 'Cillian Murphy', 'Eric Roberts', 'Tom Hardy'],
  ['What year did the first Avengers film release?', '2012', '2010', '2014', '2008'],
  ['Which Pakistani actress starred in Hindi Medium opposite Irrfan Khan?', 'Saba Qamar', 'Mahira Khan', 'Mawra Hocane', 'Sajal Aly'],
  ['In Better Call Saul, what is Jimmy\'s law degree from (fictional or real alma mater style)?', 'University of American Samoa (diploma mill, in-universe)', 'Harvard Law', 'Yale Law', 'UNM Law'],
  ['What is "rizz" short for in Gen Z slang?', 'Charisma', 'Risk', 'Rhythm', 'Rizzo (name only)'],
  ['In Top Gun: Maverick (2022), what kind of facility do the pilots strike in the climactic mission?', 'A uranium enrichment plant', 'A submarine pen', 'An aircraft carrier only', 'A training base only'],
  ['Which desi wedding event involves henna and often choreographed dances?', 'Mehndi', 'Nikah only', 'Rukhsati only', 'Valima only'],
];

export const grade5: [string, string, string, string, string][] = [
  ['What was Pretty Woman\'s original script title?', '$3,000', 'Hollywood Blvd', 'Vivian', 'Sunset Girl'],
  ['What was Quentin Tarantino\'s debut feature film?', 'Reservoir Dogs', 'Pulp Fiction', 'Jackie Brown', 'True Romance'],
  ['Which MCU film is the highest-grossing worldwide (unadjusted)?', 'Avengers: Endgame', 'Avatar', 'Avengers: Infinity War', 'Spider-Man: No Way Home'],
  ['What is the title of the first video ever uploaded to YouTube?', 'Me at the zoo', 'Hello YouTube', 'First Video', 'Testing 123'],
  ['What year was Reddit founded?', '2005', '2004', '2006', '2007'],
  ['What was Drake\'s debut mixtape (2006)?', 'Room for Improvement', 'Comeback Season', 'So Far Gone', 'Thank Me Later'],
  ['What is the name of The Weeknd\'s 2011 mixtape trilogy\'s first installment?', 'House of Balloons', 'Thursday', 'Echoes of Silence', 'Kiss Land'],
  ['Which album won Kendrick Lamar the Pulitzer Prize for Music?', 'DAMN.', 'To Pimp a Butterfly', 'Mr. Morale & The Big Steppers', 'good kid, m.A.A.d city'],
  ['What is the best-selling video game of all time (single-platform sales often cited)?', 'Minecraft', 'GTA V', 'Tetris', 'Wii Sports'],
  ['GTA V reportedly cost around how much to develop and market (approx)?', 'Around $265 million', '$100 million', '$500 million', '$50 million'],
  ['Who was the scientific consultant on Interstellar for black hole visuals?', 'Kip Thorne', 'Neil deGrasse Tyson', 'Stephen Hawking', 'Brian Greene'],
  ['What year was the first iPhone released?', '2007', '2006', '2008', '2009'],
  ['What pseudonym is used for Bitcoin\'s unknown creator?', 'Satoshi Nakamoto', 'Hal Finney', 'Vitalik Buterin', 'Charlie Lee'],
  ['Netflix\'s first major original series (2013) was?', 'House of Cards', 'Lilyhammer', 'Orange Is the New Black', 'Hemlock Grove'],
  ['In The Matrix, Neo\'s hacker alias before "Neo" is?', 'Thomas A. Anderson', 'John Anderson', 'Samuel Anderson', 'Neo Anderson'],
  ['What does "mid" mean in Gen Z slang?', 'Mediocre or average', 'Middle class', 'Midnight', 'Middle child'],
  ['Who coined the term "metaverse" in the 1992 novel Snow Crash?', 'Neal Stephenson', 'William Gibson', 'Philip K. Dick', 'Isaac Asimov'],
  ['What was Discord originally marketed toward?', 'Gamers', 'Students', 'Musicians only', 'Remote offices only'],
  ['In Breaking Bad, what is the chemical formula Walt writes on his classroom board early on?', 'C10H15N (methamphetamine)', 'NaCl', 'H2SO4', 'CH4'],
  ['What is the name of the fictional law firm Jimmy McGill later operates under?', 'Saul Goodman & Associates', 'Hamlin Hamlin McGill', 'Wexler McGill', 'Davis & Main'],
  ['Which Pakistani film by Shoaib Mansoor tackled extremism and identity post-9/11?', 'Khuda Kay Liye', 'Bol', 'Verna', '7 Din Mohabbat In'],
  ['What was Pakistan\'s first Oscar submission in decades (2013)?', 'Zinda Bhaag', 'Bol', 'Dukhtar', 'Seedlings'],
  ['Which Coke Studio producer era is often called the "golden" early years?', 'Rohail Hyatt (Seasons 1–6)', 'Strings (Season 10)', 'Ali Zafar', 'Zulfiqar Jabbar Khan'],
  ['Which 1977 Urdu romance film starring Waheed Murad and Shabnam is a Lollywood classic?', 'Aaina', 'Armaan', 'Umrao Jaan Ada', 'Dosti'],
  ['What is the traditional communal thaal meal strongly associated with Dawoodi Bohra culture (general knowledge)?', 'Eating from one large platter as a community', 'Only iftar', 'Only Eid breakfast', 'A picnic blanket meal'],
  ['SRK\'s first Bollywood film as lead was?', 'Deewana', 'Raju Ban Gaya Gentleman', 'Dil Aashna Hai', 'Chamatkar'],
  ['Dilip Kumar\'s birth name was?', 'Muhammad Yusuf Khan', 'Dilip Kumar', 'Yusuf Ali', 'Kumar Gopal'],
  ['Which Pakistani cricketer married Indian tennis star Sania Mirza?', 'Shoaib Malik', 'Wasim Akram', 'Shahid Afridi', 'Imran Khan'],
  ['What Hum TV drama featured Fawad Khan and Mahira Khan as Khirad and Ashar?', 'Humsafar', 'Zindagi Gulzar Hai', 'Shehr-e-Zaat', 'Dastaan'],
  ['Which band sang "Duur" and "Anjane"?', 'Strings', 'Junoon', 'Vital Signs', 'Aaroh'],
  ['In the Succession series finale, who becomes CEO of Waystar Royco?', 'Tom Wambsgans', 'Kendall Roy', 'Shiv Roy', 'Roman Roy'],
  ['What is Rotten Tomatoes best known for?', 'Movie and TV review scores with a Tomatometer', 'Video game reviews', 'Music charts', 'Restaurant ratings'],
  ['What PTV music show helped launch Vital Signs in 1989?', 'Music 89', 'Coke Studio', 'Nescafe Basement', 'Indus Music'],
  ['Which Pakistani city hosts the main campus of Aga Khan University?', 'Karachi', 'Lahore', 'Islamabad', 'London'],
  ['What is the Palme d\'Or?', 'The top prize at the Cannes Film Festival', 'An Oscar category', 'A Grammy for soundtracks', 'A BAFTA for TV'],
  ['In Game of Thrones, who kills Tywin Lannister?', 'Tyrion Lannister', 'Jaime Lannister', 'Arya Stark', 'Varys'],
  ['What street name does Walter White use for his blue meth brand identity?', 'Blue Sky', 'Heisenberg Labs', 'Gray Matter', 'Pollos Blue'],
  ['Which Christopher Nolan film is told mostly backwards?', 'Memento', 'Following', 'The Prestige', 'Dunkirk'],
  ['What year did Vine shut down?', '2017', '2016', '2018', '2015'],
  ['In The Social Network, who plays Mark Zuckerberg?', 'Jesse Eisenberg', 'Andrew Garfield', 'Armie Hammer', 'Justin Timberlake'],
  ['What is Letterboxd?', 'A social app for logging and reviewing films', 'A music festival', 'A sports stats site', 'A food delivery app'],
  ['Which Pakistani drama had a finale screened in Pakistani cinemas in 2020?', 'Mere Paas Tum Ho', 'Alif', 'Ehd-e-Wafa', 'Tere Bin'],
  ['What Bollywood director made Lagaan (2001)?', 'Ashutosh Gowariker', 'Farhan Akhtar', 'Karan Johar', 'Rajkumar Hirani'],
  ['In Dangal, who plays Mahavir Singh Phogat?', 'Aamir Khan', 'Salman Khan', 'Shah Rukh Khan', 'Akshay Kumar'],
  ['Who directed the Pakistani film Bol (2011)?', 'Shoaib Mansoor', 'Nabeel Qureshi', 'Mehreen Jabbar', 'Sarmad Khoosat'],
  ['Which streaming service owns The Last of Us TV adaptation?', 'HBO / Max', 'Netflix', 'Amazon', 'Apple'],
  ['In Stranger Things Season 4, which Metallica song does Eddie shred in the Upside Down?', 'Master of Puppets', 'Enter Sandman', 'One', 'Battery'],
  ['What does "plot twist" mean in storytelling?', 'A surprising turn that changes how you see the story', 'The ending credits', 'The first scene', 'The theme song'],
  ['Who directed Get Out (2017)?', 'Jordan Peele', 'Ari Aster', 'Robert Eggers', 'Ryan Coogler'],
  ['In Parasite, the scholar\'s rock is a symbol of?', 'Wealth aspiration / luck', 'Family loyalty', 'Korean nationalism', 'Nothing'],
];

export const grade6: [string, string, string, string, string][] = [
  ['What was the approximate production budget of Iron Man (2008)?', 'Around $140 million', '$80 million', '$200 million', '$40 million'],
  ['Shawshank Redemption famously underperformed in theaters but became a classic via?', 'Home video and TV reruns', 'TikTok', 'Netflix only in 2020', 'Oscars only'],
  ['Which film briefly had the wrong Best Picture winner announced at the 2017 Oscars?', 'La La Land announced; Moonlight won', 'Moonlight announced wrong', 'Parasite', 'Green Book'],
  ['What is Christopher Nolan\'s first feature film (1998)?', 'Following', 'Memento', 'Insomnia', 'The Prestige'],
  ['What was Twitter\'s original character limit?', '140', '280', '120', '200'],
  ['What year was 4chan founded?', '2003', '2005', '2001', '2007'],
  ['What is Drake\'s OVO label often said to stand for (his crew)?', 'October\'s Very Own', 'Only Valid Output', 'Ontario\'s Very Own', 'Ottawa\'s Very Own'],
  ['Who co-produced The Weeknd\'s "Blinding Lights" with Max Martin?', 'Oscar Holter', 'Finneas', 'Jack Antonoff', 'Rick Rubin'],
  ['Kendrick Lamar is from which California city?', 'Compton', 'Long Beach', 'Oakland', 'Inglewood'],
  ['What is the KEKW emote based on?', 'El Risitas / Spanish laughing guy meme', 'A frog', 'A dog', 'A robot'],
  ['The "Gigachad" meme face is based on which model\'s photos?', 'Ernest Khalimov (often cited)', 'Random stock photo', 'Brad Pitt', 'A CGI only'],
  ['What was Minecraft\'s very early internal name?', 'Cave Game', 'Block World', 'Miner 2000', 'Notch World'],
  ['GTA V across all platforms has grossed roughly how much total (often cited)?', 'Over $8 billion', '$1 billion', '$500 million', '$15 billion'],
  ['What was Elon Musk\'s first major startup (Zip2) sold to?', 'Compaq', 'eBay', 'PayPal directly', 'Google'],
  ['What does IMDb stand for?', 'Internet Movie Database', 'International Music Database', 'Integrated Media Data bank', 'Independent Movie Directors bureau'],
  ['What is a "cinematic universe"?', 'Connected franchise of films sharing characters and world (like the MCU)', 'Only IMAX screens', 'Only black-and-white films', 'Only documentaries'],
  ['Which Nusrat Fateh Ali Khan collaboration album with Michael Brook reimagined qawwali for Western charts?', 'Mustt Mustt', 'Night Song', 'Star Rise', 'Dust to Gold'],
  ['What year did Coke Studio Pakistan first air, and who produced season 1?', '2008, Rohail Hyatt', '2005, Strings', '2010, Ali Zafar', '2012, Zulfi'],
  ['Who composed the Humsafar OST lead track "Woh Humsafar Tha" (singer often associated)?', 'Qurat-ul-Ain Balouch (QB) featured prominently', 'Abida Parveen', 'Rahat Fateh Ali Khan', 'Atif Aslam'],
  ['What was the first Indian talkie film (1931)?', 'Alam Ara', 'Raja Harishchandra', 'Kisan Kanya', 'Mother India'],
  ['PTV was founded in which year?', '1964', '1947', '1971', '1980'],
  ['What is Shah Rukh Khan\'s production company name?', 'Red Chillies Entertainment', 'Dharma Productions', 'YRF', 'Excel Entertainment'],
  ['Which Pakistani female director made Dukhtar (2014) about a mother fleeing a tribal marriage?', 'Afia Nathaniel', 'Sharmeen Obaid-Chinoy', 'Mehreen Jabbar', 'Sarmad Khoosat'],
  ['What is "parasocial relationship"?', 'One-sided emotional bond with a celebrity or character', 'A business partnership', 'Co-parenting', 'Therapy'],
  ['In music theory, khayal differs from ghazal mainly how?', 'Khayal is classical raag improvisation; ghazal is poetic song form', 'Same thing', 'Khayal is instrumental only', 'Ghazal is only Punjabi'],
  ['Which raag is extremely common in South Asian qawwali performances?', 'Bhairavi / Kafi (both common)', 'Only C major', 'Blues scale', 'Pentatonic only'],
  ['What does CGI stand for in movies?', 'Computer-Generated Imagery', 'Cinematic Graphic Interface', 'Central Graphics Input', 'Creative General Illustration'],
  ['What was the Nigar Award in Pakistan?', 'Major legacy film awards (1957–2011 era)', 'A music TV show', 'A cricket trophy', 'A literature prize'],
  ['Which Manto short story collection is central to Partition literature?', 'Toba Tek Singh (and many others in same era)', 'Only English novels', 'Science fiction', 'Cookbooks'],
  ['What is the "auteur theory" in film criticism?', 'The idea that a director is the primary creative author of a film', 'Only French films', 'Only animated films', 'Only silent films'],
  ['In Pakistani media, what is PEMRA?', 'Electronic media regulator', 'A film studio', 'A music label', 'A university'],
  ['What is "WhatsApp University" slang for?', 'Forwarded fake news treated as education', 'Oxford online', 'Waterloo group chat', 'A podcast'],
  ['Which Young Stunners track helped define Urdu rap in Karachi?', 'Various — "Afsanay" / scene leaders Talha Anjum & Talha Yunus', 'Only English rap', 'Bella Ciao cover', 'Old Town Road'],
  ['What is "intersectionality" (Kimberlé Crenshaw)?', 'Overlapping systems of discrimination', 'Traffic intersections', 'Math sets', 'Venn diagrams only'],
  ['Which director made Oppenheimer (2023) and released it the same summer as Barbie, sparking "Barbenheimer"?', 'Christopher Nolan', 'Denis Villeneuve', 'Steven Spielberg', 'Damien Chazelle'],
  ['What is the in-universe name of the AI voice assistant in Spike Jonze\'s Her (2013)?', 'Samantha', 'Alexa', 'Cortana', 'Siri'],
  ['Which A24 film follows a Korean immigrant family in 1980s Arkansas?', 'Minari', 'Everything Everywhere All at Once', 'The Farewell', 'Past Lives'],
  ['What streaming service is The Bear originally produced for?', 'FX on Hulu / Hulu (US)', 'Netflix only', 'HBO Max only', 'Prime Video only'],
  ['What is a "box office bomb"?', 'A movie that loses money relative to expectations', 'A hit sequel', 'A short film', 'A documentary'],
  ['What is structural violence (Galtung)?', 'Harm via social structures, not only direct force', 'Only riots', 'Only war', 'Weather'],
  ['Which album is often considered Nusrat\'s purist classical mehfil peak vs Bollywood?', 'Shahen-Shah / traditional sessions (purist debate)', 'Only Hollywood soundtracks', 'Coke Studio only', 'Pop singles only'],
  ['What is a "limited series" on streaming?', 'A show planned for one contained season or arc', 'A pilot only', 'A reality show', 'A news program'],
  ['Which Pakistani web series (Zee5) featured female leads as "Churails"?', 'Churails', 'Sacred Games', 'Ms. Marvel', 'Delhi Crime'],
  ['What is the paradox many diaspora viewers describe: conservative values at home + liberal content consumption?', 'Often called conservative modernity / cultural cognitive dissonance', 'Only Gen Z', 'Impossible', 'Not real'],
  ['What technical approach did Rohail Hyatt emphasize early in Coke Studio?', 'Live ensemble fusion, minimal overdub aesthetic', '100% MIDI', 'Only autotune', 'AI vocals'],
  ['What is the Rekhta tradition historically?', 'Early Urdu mixing Persian-Hindi roots in poetry', 'A food', 'A dance', 'A cricket shot'],
  ['Which philosopher\'s Orientalism is often cited in postcolonial media critique?', 'Edward Said', 'Hannah Arendt', 'John Rawls', 'Karl Popper'],
  ['What is "Occidentalism" in cultural studies (inverse critique)?', 'Stereotyped views of the West', 'Western food only', 'EU law', 'Oxford exams'],
  ['Which 1997 James Cameron film was the first to gross over $1 billion worldwide (unadjusted)?', 'Titanic', 'Terminator 2', 'True Lies', 'Aliens'],
  ['What does "GPT" stand for in ChatGPT-style models?', 'Generative Pre-trained Transformer', 'General Purpose Text', 'Global Processing Tech', 'Graphical Program Tool'],
];
