// Grade 1
export const grade1: [string, string, string, string, string][] = [
  ['What streaming service produced Squid Game?', 'Netflix', 'Amazon Prime', 'Hulu', 'Disney+'],
  ['Who plays Iron Man in the MCU?', 'Robert Downey Jr.', 'Chris Evans', 'Chris Hemsworth', 'Mark Ruffalo'],
  ['Which Toronto rapper is known as Champagne Papi?', 'Drake', 'The Weeknd', 'Nav', 'Tory Lanez'],
  ['Who is commonly known as King Khan in Bollywood?', 'Shah Rukh Khan', 'Aamir Khan', 'Salman Khan', 'Akshay Kumar'],
  ['What company owns Instagram and WhatsApp?', 'Meta', 'Google', 'Amazon', 'Microsoft'],
  ['What show features a chemistry teacher who becomes a drug kingpin?', 'Breaking Bad', 'Ozark', 'Narcos', 'Better Call Saul'],
  ['Who plays Batman in The Dark Knight trilogy?', 'Christian Bale', 'Ben Affleck', 'Robert Pattinson', 'Val Kilmer'],
  ['What Pakistani drama stars Fawad Khan and Mahira Khan as a couple?', 'Humsafar', 'Zindagi Gulzar Hai', 'Mere Paas Tum Ho', 'Daam'],
  ['Which Toronto-born artist sings Blinding Lights?', 'The Weeknd', 'Drake', 'Daniel Caesar', 'Justin Bieber'],
  ['What does GTA stand for in the video game franchise?', 'Grand Theft Auto', 'Greater Toronto Area', 'Global Tactical Assault', 'Grand Tournament Arena'],
  ['What is Coke Studio?', 'A Pakistani music show', 'A Coca-Cola ad campaign', 'A Bollywood soundtrack label', 'A cooking show'],
  ['What Toronto NBA team won its first championship in 2019?', 'Raptors', 'Leafs', 'Blue Jays', 'Toronto FC'],
  ['Who slapped Chris Rock at the 2022 Oscars?', 'Will Smith', 'Denzel Washington', 'Kevin Hart', 'Adam Sandler'],
  ['Which Bollywood actor is nicknamed Bhaijaan?', 'Salman Khan', 'Shah Rukh Khan', 'Aamir Khan', 'Akshay Kumar'],
  ['What app uses a white ghost on a yellow background as its logo?', 'Snapchat', 'TikTok', 'Discord', 'Telegram'],
  ['What reality TV family moved from E! to Hulu for their new show?', 'The Kardashians', 'The Osbournes', 'The Hiltons', 'The Real Housewives'],
  ['In Titanic, who says the line I\'m the king of the world?', 'Jack (Leonardo DiCaprio)', 'Rose (Kate Winslet)', 'Captain Smith', 'Cal (Billy Zane)'],
  ['What do desi parents stereotypically want their kids to become?', 'Doctor or engineer', 'Lawyer or banker', 'Chef or artist', 'Athlete or musician'],
  ['What social media app popularized short-form vertical videos?', 'TikTok', 'Snapchat', 'Instagram', 'YouTube'],
  ['Which Christopher Nolan film is about entering people\'s dreams?', 'Inception', 'Interstellar', 'Tenet', 'The Prestige'],
  ['What does log kya kahenge translate to?', 'What will people say', 'When are we leaving', 'Who invited them', 'Why are you late'],
  ['What HBO series takes place in the fictional land of Westeros?', 'Game of Thrones', 'House of the Dragon', 'The Witcher', 'Lord of the Rings'],
  ['What is Toronto\'s public transit system called?', 'TTC', 'GO Transit', 'MiWay', 'YRT'],
  ['What is a rishta aunty?', 'Someone who arranges marriages', 'A nosy neighbor', 'A cooking teacher', 'A religious scholar'],
  ['What Canadian coffee chain is a national icon?', 'Tim Hortons', 'Second Cup', 'Starbucks', 'Country Style'],
  ['What video game series features an Italian plumber named Mario?', 'Super Mario', 'Sonic the Hedgehog', 'The Legend of Zelda', 'Fortnite'],
  ['Which Bollywood film has the iconic SRK train scene with open arms?', 'DDLJ', 'Kuch Kuch Hota Hai', 'Mohabbatein', 'Kabhi Khushi Kabhie Gham'],
  ['What Netflix show features a girl named Eleven with telekinetic powers?', 'Stranger Things', 'Wednesday', 'Dark', 'The OA'],
  ['Which Avenger wields a vibranium shield?', 'Captain America', 'Iron Man', 'Black Panther', 'Thor'],
  ['What Pakistani singer is famous for Tajdar-e-Haram?', 'Atif Aslam', 'Rahat Fateh Ali Khan', 'Ali Zafar', 'Junaid Jamshed'],
  ['What is Drake\'s famous nickname for Toronto?', 'The 6ix', 'The 4', 'T-Dot', 'The 9'],
  ['What slang term describes natural charm and flirting ability?', 'Rizz', 'Sigma', 'Based', 'Slay'],
  ['What hot beverage is basically a religion in desi households?', 'Chai', 'Coffee', 'Lassi', 'Rooh Afza'],
  ['What video game series features a battle royale mode called Warzone?', 'Call of Duty', 'Battlefield', 'Fortnite', 'Halo'],
  ['Who is the main villain in Avengers: Infinity War?', 'Thanos', 'Loki', 'Ultron', 'Hela'],
  ['What desi word describes acting overly dramatic like a Bollywood movie?', 'Filmy', 'Masala', 'Mirchi', 'Tadka'],
  ['Which actor plays Dominic Toretto in the Fast & Furious franchise?', 'Vin Diesel', 'Dwayne Johnson', 'Paul Walker', 'Jason Statham'],
  ['What Netflix series features a charming stalker named Joe Goldberg?', 'You', 'Dexter', 'Mindhunter', 'Dahmer'],
  ['Who directed both The Dark Knight and Interstellar?', 'Christopher Nolan', 'Steven Spielberg', 'Denis Villeneuve', 'Ridley Scott'],
  ['What is the stereotypical desi mom\'s weapon of choice for discipline?', 'Chappal', 'Wooden spoon', 'Belt', 'Newspaper roll'],
  ['What EA Sports soccer game was rebranded to EA FC in 2023?', 'FIFA', 'PES', 'Football Manager', 'Top Eleven'],
  ['In the MCU, what fictional metal is found in Wakanda?', 'Vibranium', 'Adamantium', 'Beskar', 'Mithril'],
  ['Which Bollywood Khan is known for 3 Idiots and Dangal?', 'Aamir Khan', 'Shah Rukh Khan', 'Salman Khan', 'Saif Ali Khan'],
  ['What James Cameron movie features blue aliens on the planet Pandora?', 'Avatar', 'Aliens', 'The Abyss', 'Terminator'],
  ['What food sparks the fiercest city rivalry debates in Pakistan?', 'Biryani', 'Nihari', 'Haleem', 'Karahi'],
  ['What Netflix show features the Byrde family laundering money?', 'Ozark', 'Breaking Bad', 'Narcos', 'Yellowstone'],
  ['Who plays the Joker in The Dark Knight?', 'Heath Ledger', 'Joaquin Phoenix', 'Jack Nicholson', 'Jared Leto'],
  ['In desi culture, what is a mehndi?', 'A pre-wedding henna ceremony', 'A type of dessert', 'A prayer ritual', 'A farewell party'],
  ['What does ABCD stand for in desi diaspora slang?', 'American-Born Confused Desi', 'Always Be Cool Dude', 'All Brown Canadians Dance', 'Aunties Bring Curry Daily'],
  ['Which Pakistani band sang Dil Dil Pakistan?', 'Vital Signs', 'Junoon', 'Strings', 'EP'],
];

// Grade 2
export const grade2: [string, string, string, string, string][] = [
  ['What was Walter White\'s drug-dealing alias in Breaking Bad?', 'Heisenberg', 'The Chemist', 'Captain Cook', 'The One Who Knocks'],
  ['What is Drake\'s record label called?', 'OVO Sound', 'Young Money', 'XO', 'Republic'],
  ['Which Coke Studio song features Rahat Fateh Ali Khan and Momina Mustehsan?', 'Afreen Afreen', 'Tajdar-e-Haram', 'Ae Dil', 'Tu Jhoom'],
  ['Which Game of Thrones family\'s words are Winter is coming?', 'Stark', 'Lannister', 'Targaryen', 'Baratheon'],
  ['What actor won a 2022 defamation trial against Amber Heard?', 'Johnny Depp', 'Brad Pitt', 'Will Smith', 'Leonardo DiCaprio'],
  ['In Stranger Things, what is the alternate dimension called?', 'The Upside Down', 'The Shadow Realm', 'The Dark Zone', 'The Other Side'],
  ['Who played the lead male role in the Pakistani drama Mere Paas Tum Ho?', 'Humayun Saeed', 'Fawad Khan', 'Ahad Raza Mir', 'Ahmed Ali Akbar'],
  ['What year did the Toronto Raptors win the NBA Finals?', '2019', '2018', '2020', '2017'],
  ['What does Thanos need to collect in the MCU to wipe out half the universe?', 'Infinity Stones', 'Chaos Emeralds', 'Power Rings', 'Cosmic Cubes'],
  ['What Eminem song starts with his palms are sweaty, knees weak, arms are heavy?', 'Lose Yourself', 'Stan', 'Without Me', 'The Real Slim Shady'],
  ['Which Bollywood superstar made a massive comeback with Pathaan in 2023?', 'Shah Rukh Khan', 'Salman Khan', 'Aamir Khan', 'Hrithik Roshan'],
  ['What year was GTA V originally released?', '2013', '2011', '2015', '2010'],
  ['In Interstellar, what is the name of Cooper\'s daughter?', 'Murph', 'Emma', 'Sarah', 'Annie'],
  ['What rapper beefed with Drake and released Not Like Us in 2024?', 'Kendrick Lamar', 'J. Cole', 'Pusha T', 'Kanye West'],
  ['What Pakistani rock band is known for Sayonee and Bulleya?', 'Junoon', 'Vital Signs', 'Strings', 'Noori'],
  ['What Black Mirror episode features a social credit rating system on phones?', 'Nosedive', 'White Christmas', 'Bandersnatch', 'The Entire History of You'],
  ['What Netflix show stars Jenna Ortega as Wednesday Addams?', 'Wednesday', 'The Addams Family', 'Sabrina', 'Yellowjackets'],
  ['Who plays Saul Goodman in both Breaking Bad and Better Call Saul?', 'Bob Odenkirk', 'Bryan Cranston', 'Aaron Paul', 'Jonathan Banks'],
  ['What does jugaad mean in desi culture?', 'A creative hack or workaround', 'A type of food', 'A religious ritual', 'A dance move'],
  ['What Christopher Nolan film deals with time dilation near a black hole?', 'Interstellar', 'Inception', 'Tenet', 'The Prestige'],
  ['What is Kendrick Lamar\'s Pulitzer Prize-winning album?', 'DAMN.', 'To Pimp a Butterfly', 'good kid, m.A.A.d city', 'Mr. Morale & The Big Steppers'],
  ['In Succession, what is the Roy family\'s media empire called?', 'Waystar Royco', 'Pierce Media', 'Sterling Global', 'ATN Holdings'],
  ['What year did Game of Thrones air its final season?', '2019', '2018', '2020', '2021'],
  ['What does "spoiler" mean in TV and movie fan talk?', 'Details that ruin surprises before you watch', 'A type of camera', 'A film award', 'A soundtrack'],
  ['What classic Pakistani military drama from the 90s is still referenced today?', 'Alpha Bravo Charlie', 'Sunehri', 'Dhuwan', 'Dhoop Kinare'],
  ['What Toronto landmark appears on Drake\'s Views album cover?', 'CN Tower', 'Rogers Centre', 'City Hall', 'Distillery District'],
  ['Which Game of Thrones family is known for always paying their debts?', 'Lannister', 'Stark', 'Targaryen', 'Tyrell'],
  ['In Ozark, what state does the Byrde family move to for money laundering?', 'Missouri', 'Arkansas', 'Kentucky', 'Tennessee'],
  ['Which Pakistani singer is known for Channo and Bollywood crossover songs?', 'Ali Zafar', 'Atif Aslam', 'Rahat Fateh Ali Khan', 'Abida Parveen'],
  ['What color was Walter White\'s signature meth in Breaking Bad?', 'Blue', 'White', 'Clear', 'Yellow'],
  ['What Spider-Man movie featured Tobey Maguire, Andrew Garfield, and Tom Holland together?', 'Spider-Man: No Way Home', 'Into the Spider-Verse', 'Far From Home', 'Homecoming'],
  ['What does a desi parent typically say when you score 95% on a test?', 'Where did the other 5% go', 'Congratulations beta', 'You are so smart', 'Let\'s go celebrate'],
  ['What fictional metal is Captain America\'s shield made from?', 'Vibranium', 'Adamantium', 'Uru', 'Carbonadium'],
  ['What streaming service is The Mandalorian on?', 'Disney+', 'Netflix', 'HBO Max', 'Prime Video'],
  ['In Bollywood, what is the signature SRK pose?', 'Arms spread wide', 'Finger on lips', 'Hand on heart', 'Pointing at the audience'],
  ['What Ontario university is stereotypically known for engineering and co-op?', 'University of Waterloo', 'University of Toronto', 'McMaster', 'Western'],
  ['What divisive 2023 Bollywood film stars Ranbir Kapoor as a violent, obsessive son?', 'Animal', 'Brahmastra', 'Tamasha', 'Sanju'],
  ['What show features Zendaya playing a teen dealing with addiction?', 'Euphoria', 'Riverdale', '13 Reasons Why', 'Skins'],
  ['What Toronto neighborhood is The Weeknd (Abel Tesfaye) from?', 'Scarborough', 'North York', 'Etobicoke', 'Brampton'],
  ['Which Pakistani actress starred in both Humsafar and Bollywood\'s Raees?', 'Mahira Khan', 'Saba Qamar', 'Sajal Aly', 'Maya Ali'],
  ['What does "binge-watching" mean?', 'Watching many episodes in one sitting', 'Only watching sports', 'Deleting a show', 'Watching with subtitles only'],
  ['In the MCU, what organization was secretly infiltrated by HYDRA?', 'S.H.I.E.L.D.', 'Stark Industries', 'The Avengers', 'The World Council'],
  ['In desi matchmaking, what is a biodata?', 'A marriage resume', 'A medical report', 'A school transcript', 'A job application'],
  ['What streaming show features a family fighting over a media empire?', 'Succession', 'Billions', 'Industry', 'The Morning Show'],
  ['Which Pakistani drama features Sanam Saeed and Fawad Khan in a story about class differences?', 'Zindagi Gulzar Hai', 'Humsafar', 'Daam', 'Mere Paas Tum Ho'],
  ['What Drake album features the massive hit One Dance?', 'Views', 'Take Care', 'Nothing Was the Same', 'Scorpion'],
  ['What Bollywood movie trilogy features Hrithik Roshan as a superhero?', 'Krrish', 'Ra.One', 'Dhoom', 'Robot'],
  ['What is the most common response when a desi mom calls your name from another room?', 'Yelling COMING while not moving', 'Running immediately', 'Calling back WHAT', 'Pretending you didn\'t hear'],
  ['In desi WhatsApp family groups, what do uncles typically share at 6 AM?', 'Good morning messages with flowers', 'News articles', 'Memes', 'Recipes'],
  ['What does desi literally mean in Hindi/Urdu?', 'From the homeland', 'Cool person', 'Brown-skinned', 'South Asian'],
];

// Grade 3
export const grade3: [string, string, string, string, string][] = [
  ['How many players entered the competition in Squid Game Season 1?', '456', '200', '300', '500'],
  ['What character did Drake play on Degrassi: The Next Generation?', 'Jimmy Brooks', 'James Brooks', 'Jeremy Brooks', 'Jason Brooks'],
  ['Which Pakistani drama features Ahmed Ali Akbar as a transformed common man?', 'Parizaad', 'Ehd-e-Wafa', 'Sang-e-Mah', 'Bashar Momin'],
  ['In Inception, what is Cobb\'s totem that tests if he\'s dreaming?', 'A spinning top', 'A loaded die', 'A poker chip', 'A chess piece'],
  ['What Black Mirror episode is an interactive choose-your-own-adventure film?', 'Bandersnatch', 'White Christmas', 'Nosedive', 'Metalhead'],
  ['In Interstellar, one hour on Miller\'s planet equals how many years on Earth?', '7 years', '5 years', '10 years', '23 years'],
  ['What year did the first Iron Man movie launch the MCU?', '2008', '2006', '2010', '2012'],
  ['What year did Coke Studio Pakistan first launch?', '2008', '2005', '2010', '2012'],
  ['What is the name of Kendrick Lamar\'s 2012 breakthrough album?', 'good kid, m.A.A.d city', 'Section.80', 'To Pimp a Butterfly', 'DAMN.'],
  ['In the Fast & Furious franchise, which actor died in a car crash in 2013?', 'Paul Walker', 'Vin Diesel', 'Tyrese Gibson', 'Ludacris'],
  ['What Bollywood film features the song Chaiyya Chaiyya performed on top of a train?', 'Dil Se', 'DDLJ', 'Devdas', 'Lagaan'],
  ['What is the name of The Weeknd\'s 2020 album?', 'After Hours', 'Starboy', 'Dawn FM', 'Beauty Behind the Madness'],
  ['In Breaking Bad, what is Hank Schrader\'s relation to Walter White?', 'Brother-in-law', 'Brother', 'Best friend', 'Neighbor'],
  ['Is Die Hard a Christmas movie?', 'Yes', 'No', 'Only the first one', 'It\'s a Thanksgiving movie'],
  ['Which Pakistani actress starred in Bollywood\'s Hindi Medium?', 'Saba Qamar', 'Mahira Khan', 'Sajal Aly', 'Maya Ali'],
  ['What Kendrick Lamar diss track became the anthem of the Drake-Kendrick beef?', 'Not Like Us', 'Euphoria', '6:16 in LA', 'Meet the Grahams'],
  ['What is the real first name of The Weeknd?', 'Abel', 'Adam', 'Ahmed', 'Adrian'],
  ['In the Netflix show You, what city does Joe Goldberg move to in Season 2?', 'Los Angeles', 'London', 'Paris', 'San Francisco'],
  ['What Coke Studio Season 14 song by Ali Sethi and Shae Gill went globally viral?', 'Pasoori', 'Tu Jhoom', 'Kana Yaari', 'Phir Milenge'],
  ['What controversial choice did Daenerys make in Game of Thrones Season 8?', 'Burned King\'s Landing and its civilians', 'Married Jon Snow', 'Freed all the dragons', 'Joined Cersei\'s side'],
  ['In Better Call Saul, what is Jimmy McGill\'s brother\'s name?', 'Chuck', 'Charlie', 'Chad', 'Chris'],
  ['What Pakistani singer originally performed Aadat with the band Jal?', 'Atif Aslam', 'Ali Zafar', 'Farhan Saeed', 'Bilal Khan'],
  ['What year did The Weeknd perform at the Super Bowl halftime show?', '2021', '2020', '2022', '2019'],
  ['In the MCU, what AI replaces JARVIS after Age of Ultron?', 'FRIDAY', 'KAREN', 'EDITH', 'JOCASTA'],
  ['What Eminem album features Stan and The Real Slim Shady?', 'The Marshall Mathers LP', 'The Slim Shady LP', 'The Eminem Show', 'Recovery'],
  ['What is the highest-grossing Pakistani film of all time?', 'The Legend of Maula Jatt', 'Jawani Phir Nahi Ani', 'Punjab Nahi Jaungi', 'London Nahi Jaunga'],
  ['What year did Netflix produce its first original series with House of Cards?', '2013', '2011', '2015', '2010'],
  ['In Thor: Ragnarok, who ultimately destroys Asgard?', 'Surtur', 'Hela', 'Thanos', 'Loki'],
  ['In Bollywood\'s three Khans, who is known as Mr. Perfectionist?', 'Aamir Khan', 'Shah Rukh Khan', 'Salman Khan', 'Hrithik Roshan'],
  ['In Succession\'s finale, who ends up as CEO of the merged company?', 'Tom Wambsgans', 'Kendall Roy', 'Shiv Roy', 'Roman Roy'],
  ['What Metallica song does Eddie Munson play in Stranger Things Season 4?', 'Master of Puppets', 'Enter Sandman', 'Nothing Else Matters', 'One'],
  ['What controversial Bollywood franchise stars Salman Khan as cop Chulbul Pandey?', 'Dabangg', 'Singham', 'Rowdy Rathore', 'Wanted'],
  ['What does "spoiler alert" warn you about?', 'Upcoming plot details', 'Loud sound effects', 'Bright lights', 'Ticket prices'],
  ['What year did TikTok launch internationally outside of China?', '2017', '2015', '2019', '2016'],
  ['What Strings song is considered one of the greatest Pakistani rock tracks?', 'Duur', 'Mera Bichra Yaar', 'Najane Kyun', 'Zinda'],
  ['What fictional GTA city is based on Miami?', 'Vice City', 'Liberty City', 'Los Santos', 'San Fierro'],
  ['What does Harvey Dent become in The Dark Knight after his accident?', 'Two-Face', 'Scarecrow', 'The Riddler', 'Bane'],
  ['In what year was the first Avengers movie released?', '2012', '2010', '2014', '2008'],
  ['What 2023 Bollywood film directed by Atlee features SRK in a dual role?', 'Jawan', 'Pathaan', 'Dunki', 'Zero'],
  ['What luxury music festival in the Bahamas became infamous and spawned documentaries?', 'Fyre Festival', 'Coachella', 'Ultra Music Festival', 'Tomorrowland'],
  ['What Ontario university\'s homecoming became so chaotic it was banned for years?', 'Queen\'s', 'Western', 'Laurier', 'Guelph'],
  ['In GTA V, what are the three playable protagonists\' first names?', 'Michael, Trevor, Franklin', 'Tommy, CJ, Niko', 'John, Trevor, Marcus', 'Michael, Carl, Trevor'],
  ['What is the traditional desi response when an elder offers you Eidi money?', 'Refusing three times then accepting', 'Taking it immediately', 'Asking for more', 'Donating it on the spot'],
  ['What does susraal mean in Urdu?', 'In-laws\' house', 'Your own home', 'Wedding venue', 'Workplace'],
  ['What Drake album features God\'s Plan and In My Feelings?', 'Scorpion', 'Views', 'More Life', 'Certified Lover Boy'],
  ['Which Junoon song became an unofficial anthem played at Pakistan cricket matches?', 'Jazba Junoon', 'Sayonee', 'Bulleya', 'Khudi'],
  ['What year did Breaking Bad premiere?', '2008', '2006', '2010', '2009'],
  ['What was unique about the Mere Paas Tum Ho finale in Pakistani TV history?', 'It was screened in cinemas', 'It was broadcast live', 'It had a 3-hour runtime', 'It featured a real nikah'],
  ['What year did the original Dil Dil Pakistan by Vital Signs release?', '1987', '1989', '1985', '1991'],
  ['In Pakistani drama Parizaad, what physical trait makes the protagonist an outcast?', 'His dark complexion', 'His height', 'A facial scar', 'His weight'],
];
