import type { Fact } from './group1';

/** Workplace-friendly statistics and data literacy; pairs with generated arithmetic in questionBank. */
export const workplaceStats: Record<number, Fact[]> = {
  1: [
    ['If 8 out of 10 survey respondents said "yes," what fraction said yes?', '8/10 (four-fifths)', '10/8', '1/10', '2/10'],
    ['What is the "average" in everyday language often called in statistics?', 'The mean', 'The mode only', 'The median only', 'The range'],
    ['Which number appears most often in: 3, 5, 5, 7, 5?', '5', '3', '7', '6'],
    ['What does 50% mean?', 'Half of the whole', 'The whole amount', 'Twice the amount', 'None of the amount'],
    ['If sales went from 100 to 120, the increase is how many units?', '20', '10', '120', '100'],
    ['What is a tally used for?', 'Counting occurrences', 'Measuring weight', 'Showing time', 'Printing labels'],
    ['Which is larger: 0.25 or 0.4?', '0.4', '0.25', 'They are equal', 'Cannot compare'],
    ['What does "total" mean on an expense report?', 'The sum of all items', 'The largest item', 'The first item', 'The average item'],
    ['If 1 in 4 customers churned, what percent churned?', '25%', '4%', '40%', '10%'],
    ['What is a bar chart good for?', 'Comparing categories side by side', 'Showing change over time only', 'Showing parts of one whole only', 'Showing correlations only'],
    ['Round 47 to the nearest ten.', '50', '40', '45', '48'],
    ['What is the middle value of: 2, 4, 9?', '4', '2', '9', '5'],
    ['If a pie chart slice is half the circle, about what share is it?', '50%', '25%', '10%', '100%'],
    ['What does "per capita" roughly mean?', 'Per person', 'Per company', 'Per year only', 'Per dollar'],
    ['Which is a rate: miles per hour or total miles?', 'Miles per hour', 'Total miles', 'Both are only totals', 'Neither'],
    ['If 60% chose option A, what chose not A?', '40%', '60%', '0%', '100%'],
    ['What is a sample in a survey?', 'A subset you measure to learn about a larger group', 'The entire population always', 'A guess', 'A chart type'],
    ['What does CSV often stand for?', 'Comma-separated values (a simple table file)', 'Computer saved video', 'Client service volume', 'Cash sales value'],
    ['If Monday had 12 tickets and Tuesday had 8, the total is?', '20', '18', '14', '96'],
    ['What is a "baseline" metric?', 'A starting reference point for comparison', 'The highest value only', 'The lowest value only', 'A type of chart'],
    ['If data are sorted smallest to largest, the middle value is the?', 'Median', 'Mean', 'Mode', 'Range'],
    ['What does 0% growth from last quarter mean?', 'No change in the measured amount', 'Doubled', 'Halved', 'Unknown'],
    ['If 3 teams tied at 10 points each, the mode of scores is?', '10', '3', '30', 'There is no mode'],
    ['What is a percentage point difference?', 'Difference between two percentages (not relative percent)', 'Same as percent change', 'Always multiplied by 100', 'Always zero'],
    ['If one quarter of the budget is spent, what fraction remains?', 'Three quarters (75%)', 'One quarter', 'Half', 'None'],
    ['What is "noise" in casual data talk?', 'Random variation that hides a clear signal', 'Loud office sounds', 'Missing data only', 'A chart color'],
    ['Which summary is affected most by one very large outlier?', 'Mean', 'Median', 'Mode', 'All equally'],
    ['If response options are Yes / No / Maybe, what type of variable is that?', 'Categorical', 'Continuous numeric', 'Time series', 'Binary only'],
    ['What does "YTD" often mean on a dashboard?', 'Year-to-date (from Jan 1 to now)', 'Yesterday total data', 'Yearly target done', 'Yield to default'],
    ['What is a forecast?', 'An estimate of future values', 'A record of past values only', 'A type of average', 'A database backup'],
    ['If 2 of 20 tests failed, what percent passed?', '90%', '10%', '20%', '2%'],
    ['What is a cohort?', 'A group tracked together over time (e.g. hires of 2024)', 'A single customer', 'A pie chart', 'A spreadsheet tab'],
    ['What does "MoM" often mean in reporting?', 'Month over month', 'Mean of medians', 'Mode on mode', 'Margin of mean'],
    ['If values are 5 and 15, the simple mean is?', '10', '5', '15', '20'],
    ['What is a KPI?', 'Key performance indicator — a tracked metric tied to goals', 'A type of chart file', 'A payroll tax', 'A software bug'],
    ['What is double-counting in metrics?', 'Counting the same item twice', 'Using two charts', 'Doubling the sample', 'Averaging twice'],
    ['If every value in a set is 7, the standard deviation is?', '0', '7', '1', '49'],
    ['What is an axis on a chart?', 'A reference line for values or categories', 'The title', 'The legend', 'The footnote'],
    ['If 40% are in group A and 35% in B, what percent is unaccounted without overlap info?', 'Cannot tell without overlap rules', '75%', '5%', '100%'],
    ['What is rounding 3.78 to one decimal place?', '3.8', '3.7', '4', '3'],
    ['What does "n" often denote in a sample summary?', 'Sample size (number of observations)', 'The average', 'The variance', 'The maximum'],
    ['If inventory dropped from 200 to 150, the change is?', '−50 units', '+50 units', '0', '+350 units'],
    ['What is a frequency table?', 'Counts of how often each category appears', 'A list of salaries', 'A map of offices', 'A timeline'],
    ['What is the range of 4, 9, 2?', '7 (max minus min)', '4', '9', '15'],
    ['If half the respondents picked "Agree," what percent is that?', '50%', '25%', '100%', '2%'],
    ['What is "granularity" of data?', 'Level of detail (daily vs monthly, etc.)', 'How loud the data are', 'File size only', 'Chart color depth'],
    ['What is a data dictionary?', 'Documentation of what each field means', 'A spell checker', 'A password list', 'A chart template'],
    ['What does "QoQ" often mean?', 'Quarter over quarter', 'Quality of quarter', 'Quota on quota', 'Query of queries'],
    ['What is bias in sampling (simple sense)?', 'Systematic skew so results do not represent the whole', 'Random noise', 'Using Excel', 'Having a large sample'],
  ],
  2: [
    ['If revenue grew from $80M to $100M, growth is how many million?', '$20M', '$10M', '$180M', '$0M'],
    ['What is compound growth about?', 'Growth applied on top of prior period\'s total', 'Only adding fixed dollars each period', 'Only one-time change', 'Dividing by zero'],
    ['If 12 of 40 projects finished early, what percent finished early?', '30%', '12%', '40%', '25%'],
    ['What is the median of 1, 2, 100?', '2', '1', '100', '34'],
    ['What is a weighted average?', 'An average where some values count more than others', 'Always the same as median', 'Only for two numbers', 'The largest value'],
    ['If conversion is 2% and traffic doubles with the same rate, what happens to expected conversions?', 'They double', 'They stay the same', 'They halve', 'They become 4%'],
    ['What does CAGR stand for?', 'Compound annual growth rate', 'Current annual gross revenue', 'Cost and gross ratio', 'Credit and risk'],
    ['What is a confidence interval (informal)?', 'A range plausible for an unknown true value, given data', 'A single exact answer', 'Always 100% wide', 'The same as margin of error always'],
    ['If correlation is high between ice cream sales and drownings, what is a common mistake?', 'Assuming causation — a third factor (heat) may drive both', 'Assuming no relationship', 'Assuming negative correlation', 'Assuming data are wrong'],
    ['What is seasonality?', 'Repeating patterns tied to calendar cycles', 'Random noise', 'A one-time spike', 'Data encryption'],
    ['If standard deviation is large, scores are generally?', 'Spread out from the mean', 'All equal to the mean', 'Always negative', 'Always integers'],
    ['What is a percentile?', 'The value below which a given percent of observations fall', 'Always the average', 'Always the max', 'A type of pie chart'],
    ['If A/B test has p-value above a typical 0.05 threshold, what is common interpretation?', 'Not enough evidence to reject "no difference" at that threshold', 'Proof the variants are identical', 'Proof B always wins', 'The test was invalid'],
    ['What is a null hypothesis (simple)?', 'A default "no effect / no difference" statement you test', 'The winning variant', 'The largest number', 'A chart title'],
    ['What is sample bias?', 'When the sample does not represent the population of interest', 'When n is very large', 'When using median', 'When rounding'],
    ['If margin of error is ±3% on a poll, what does that communicate?', 'Uncertainty from sampling — estimates could swing within that band', 'Exactly 3 people answered', 'The poll is wrong', 'The mean is 3'],
    ['What is YoY growth?', 'Year-over-year comparison of the same period', 'Yesterday over yesterday', 'Yield on yield', 'Yearly output of yards'],
    ['What is a histogram?', 'A chart of frequencies in bins along a numeric axis', 'A line chart of stock price', 'A pie chart', 'A table without numbers'],
    ['If two datasets have the same mean but different spreads, what differs?', 'Variance / standard deviation', 'The mean', 'The year', 'The currency'],
    ['What is an outlier?', 'An unusually extreme value versus the rest', 'The median', 'The mode', 'The average always'],
    ['What does "statistically significant" usually mean in business reporting?', 'Result unlikely under a chosen "no effect" model — not necessarily "important"', 'Always large in business terms', 'Always causal', 'Always 100% certain'],
    ['What is normalization of metrics?', 'Putting values on a comparable scale (e.g. per employee)', 'Deleting outliers', 'Doubling all numbers', 'Removing charts'],
    ['If retention improved from 90% to 93%, that is how many percentage points?', '3 percentage points', '3 percent relative', '30 points', '0.3 points'],
    ['What is a rolling average?', 'Average over a sliding window of periods', 'Average of only the first week', 'Maximum of a series', 'Sum of categories'],
    ['What is cohort retention?', 'Tracking what share of a cohort returns in later periods', 'Total revenue', 'Number of employees', 'Server uptime'],
    ['If NPS promoters are 50%, passives 30%, detractors 20%, what is NPS formula style?', 'Promoters% − Detractors% (passives not in score)', 'Sum of all three', 'Promoters only', 'Detractors only'],
    ['What is a funnel metric?', 'Conversion through sequential stages', 'A water bill', 'Inventory on hand', 'Headcount only'],
    ['What is variance (conceptually)?', 'Average squared deviation from the mean', 'The mean itself', 'The max minus min', 'The median gap'],
    ['If you report mean salary but a few executives earn millions, what may mislead?', 'Mean pulled up by outliers — median may be fairer', 'Median always lies', 'Mode is always best', 'Charts cannot help'],
    ['What is a control group in experiments?', 'A baseline not receiving the intervention for comparison', 'The winning group', 'The largest group', 'A duplicate spreadsheet'],
    ['What is statistical power (informal)?', 'Chance a study will detect an effect if it truly exists', 'Always 100%', 'Same as p-value', 'Same as sample size always'],
    ['What is imputation of missing data?', 'Filling missing values with a rule or model', 'Deleting all rows', 'Doubling missing cells', 'Printing blanks'],
    ['If two events are independent, P(A and B) equals?', 'P(A) × P(B) (for independent case)', 'P(A) + P(B) always', '1 always', '0 always'],
    ['What is a moving average in dashboards?', 'Average recomputed as new periods arrive', 'Average never changes', 'Maximum of series', 'Count of rows'],
    ['What does "statistical significance" not tell you alone?', 'Practical importance or business impact', 'Whether the math ran', 'Sample size', 'The mean'],
    ['What is a box plot used to show?', 'Median, quartiles, and spread/outliers', 'Only the mean', 'Only pie slices', 'Only time trends'],
    ['If you stratify results by region, you are?', 'Breaking analysis into subgroups', 'Averaging regions away', 'Deleting small regions', 'Combining all regions blindly'],
    ['What is a base rate?', 'Overall prevalence before conditioning on specifics', 'The highest rate', 'Interest rate only', 'Tax rate only'],
    ['What is Simpson\'s paradox about?', 'A trend can reverse when groups are combined vs split', 'Two charts always agree', 'Pie charts are invalid', 'Means always equal medians'],
    ['What is an index number (e.g. consumer price index idea)?', 'A normalized level versus a base period', 'Always dollars', 'Always a count', 'Always a percent'],
    ['What is "reproducible" analytics?', 'Results can be re-run from documented code and data', 'Results are random', 'Only Excel allowed', 'No documentation'],
    ['If lift is 20% in marketing tests, it often means?', 'Relative improvement vs baseline conversion', 'Always absolute 20 points', 'Revenue doubled', 'Sample doubled'],
    ['What is a placebo effect concern in trials?', 'People respond because they expect benefit, not only treatment', 'Charts are wrong', 'Means equal medians', 'Always bias-free'],
    ['What is a Type I error (concept)?', 'False positive — detecting an effect that is not real', 'False negative', 'Correct rejection', 'Missing data'],
    ['What is a Type II error (concept)?', 'False negative — missing a real effect', 'False positive', 'Always 5%', 'Always 0%'],
    ['What is an odds ratio (very informal)?', 'A way to compare odds between two groups in binary outcomes', 'Always the same as probability', 'Always zero', 'The mean of odds'],
    ['What is "per thousand" reporting (e.g. errors per 1,000 orders)?', 'A rate scaled for easier reading', 'Always larger than percent', 'Illegal in finance', 'Same as percent always'],
    ['What is data lineage?', 'Tracking where data came from and how it transformed', 'A line chart', 'A footnote', 'A password'],
  ],
  3: [
    ['What is the central limit theorem about (informal)?', 'Means of large samples tend toward a normal distribution under broad conditions', 'All data are normal', 'Medians always normal', 'Samples cannot be random'],
    ['What is standard error of the mean?', 'Spread of the sample mean across repeated sampling', 'Same as standard deviation of raw data always', 'Always zero', 'The max error'],
    ['If R² is high in a simple linear regression, what does it suggest?', 'The model explains much of the variance of the outcome', 'Causation is proven', 'Slopes must be positive', 'Outliers do not exist'],
    ['What is multicollinearity?', 'Predictors are highly correlated, destabilizing coefficient estimates', 'Too few rows', 'Too many charts', 'Perfect randomization'],
    ['What is heteroskedasticity?', 'Non-constant variance of errors across levels of X', 'Missing data', 'Perfect linearity', 'Duplicate IDs'],
    ['What is a p-value (careful definition)?', 'Probability of data at least this extreme if the null model were true', 'Probability the hypothesis is true', 'Probability of replication', 'Always the effect size'],
    ['What is Bayesian vs frequentist framing (one line)?', 'Bayesian: probability over hypotheses; Frequentist: long-run error rates of procedures', 'They are identical always', 'Bayesian forbids priors', 'Frequentist uses only medians'],
    ['What is a confidence level of 95% about?', 'The method: intervals from repeated sampling would cover the truth ~95% of the time', '95% chance this interval contains the truth (common misread)', 'Always wider than 90%', 'The p-value'],
    ['What is effect size?', 'Magnitude of a phenomenon — not only whether it exists', 'Same as p-value', 'Always Cohen\'s d', 'Always zero'],
    ['What is statistical vs practical significance?', 'Stats significance does not imply business importance', 'They are always the same', 'Practical implies p<0.05', 'Neither matters'],
    ['What is survivorship bias?', 'Focusing on successes that "survived" while ignoring failures', 'Random sampling', 'Seasonality', 'Using median'],
    ['What is Simpson\'s paradox driven by?', 'Unequal group sizes or lurking variables across splits', 'Bad Excel', 'Too many decimals', 'Pie charts'],
    ['What is a propensity score used for?', 'Balancing observational groups on observed covariates', 'Predicting stock prices perfectly', 'Replacing experiments always', 'Removing outliers'],
    ['What is an intent-to-treat analysis?', 'Analyze by randomized assignment, not only who complied', 'Only completers analyzed', 'Ignore randomization', 'Use only medians'],
    ['What is multiple testing problem?', 'Many tests inflate false positives without correction', 'Running one test', 'Using histograms', 'Using means'],
    ['What is Benjamini–Hochberg about?', 'Controlling false discovery rate across many hypotheses', 'Controlling typing speed', 'A chart palette', 'SQL joins'],
    ['What is a power curve vs sample size?', 'Larger n generally increases power to detect effects', 'Larger n always removes bias', 'Power unrelated to n', 'n should always be 30'],
    ['What is bootstrapping?', 'Resampling with replacement to estimate uncertainty', 'Deleting data', 'Copying one row', 'Using only mean'],
    ['What is cross-validation?', 'Assessing model performance on held-out folds', 'Crossing variables out', 'Validating invoices', 'A/B testing'],
    ['What is overfitting?', 'Model fits noise in training and fails to generalize', 'Too few parameters', 'Using a train set', 'Using median'],
    ['What is regularization?', 'Penalizing complexity to improve generalization', 'Adding random noise always', 'Removing all variables', 'Doubling data'],
    ['What is a ROC curve used for?', 'Tradeoff of true vs false positives in classification', 'Time series seasonality', 'Inventory levels', 'Salary bands'],
    ['What is calibration of predicted probabilities?', 'Predicted risks match observed frequencies', 'Making charts colorful', 'Setting p=0.05', 'Removing variance'],
    ['What is imbalanced classes in classification?', 'Very unequal positive/negative counts', 'Equal classes always', 'Missing labels', 'Too many features'],
    ['What is precision vs recall?', 'Precision: predicted positives that are true; Recall: true positives found', 'They are always equal', 'Same as accuracy always', 'Same as R²'],
    ['What is a lift chart in marketing analytics?', 'Shows incremental gain from ranking by model score', 'Shows revenue only', 'Shows payroll', 'Shows taxes'],
    ['What is cohort analysis in product?', 'Behavior by acquisition cohort over life', 'Only daily totals', 'Only variance', 'Only SQL'],
    ['What is a retention curve?', 'Share still active over days/weeks since start', 'Salary curve', 'Stock price', 'Tax rate'],
    ['What is leading vs lagging indicators?', 'Leading: predictive early signals; Lagging: outcomes after the fact', 'Same thing', 'Only financial', 'Only HR'],
    ['What is stationarity in time series?', 'Statistical properties do not depend on time shift', 'Always upward trend', 'Random walk always', 'Missing values'],
    ['What is autocorrelation?', 'Correlation of a series with its own past values', 'Correlation with another company', 'Always zero', 'Always negative'],
    ['What is MAPE?', 'Mean absolute percent error — forecast accuracy metric', 'Mean absolute payroll error', 'Maximum API errors', 'Median age'],
    ['What is seasonally adjusted data?', 'Removing estimated seasonal component to compare underlying trend', 'Deleting winter rows', 'Doubling summer', 'Adding noise'],
    ['What is an anomaly detection use case?', 'Flagging unusual transactions or metrics', 'Computing payroll taxes', 'Writing OKRs', 'Scheduling meetings'],
    ['What is a funnel drop-off metric?', 'Where users leave a multi-step flow', 'Total headcount', 'Gross margin', 'Cap table size'],
    ['What is unit-root in ARMA talk (informal)?', 'Series needs differencing to be stationary', 'Series always stable', 'Excel error', 'Missing values'],
    ['What is exponential smoothing?', 'Forecast weighting recent observations more', 'Removing exponentials', 'Only linear trends', 'Only medians'],
    ['What is a hazard rate in survival analysis?', 'Instantaneous risk of event given survival so far', 'Total events only', 'Average salary', 'Inventory turns'],
    ['What is censoring in survival data?', 'Event time not observed for some subjects', 'Deleting outliers', 'Winning all bids', 'Duplicate rows'],
    ['What is a propensity-matched study?', 'Pairs treated/control with similar covariates', 'Randomized controlled trial always', 'No covariates used', 'Only Bayesian'],
    ['What is shrinkage in hierarchical models?', 'Group estimates pulled toward overall mean', 'Deleting small groups', 'Increasing variance', 'Removing priors'],
    ['What is a Bonferroni correction?', 'Stricter alpha per test to control family-wise error', 'Increases false positives', 'Only for charts', 'Only SQL'],
    ['What is MDE in experiment design?', 'Minimum detectable effect given power, alpha, and n', 'Maximum data error', 'Mean daily expenses', 'Median delay'],
    ['What is SRM in online experiments?', 'Sample ratio mismatch — assignment imbalance signal', 'Standard revenue model', 'Single retention metric', 'Sales reporting month'],
    ['What is a peeking problem in A/B tests?', 'Stopping early based on interim results inflates false positives', 'Looking at charts', 'Using medians', 'Using weeklies'],
    ['What is CUPED?', 'Variance reduction using pre-experiment covariates', 'A cup design', 'A payroll method', 'A SQL join type'],
    ['What is a quantile-quantile plot for?', 'Checking distributional assumptions vs a reference', 'Comparing means only', 'Pie charts', 'Org charts'],
    ['What is heterogeneity of treatment effects?', 'Effects differ across subgroups', 'Effects always constant', 'No subgroups exist', 'Only marketing'],
    ['What is a DAG in causal inference?', 'Directed acyclic graph of assumptions about causes', 'A database', 'A chart in Excel', 'A legal contract'],
    ['What is instrumental variables idea (one line)?', 'Using an exogenous "instrument" correlated with treatment but not the outcome error', 'Using any correlated variable', 'Always randomization', 'Always OLS'],
  ],
  4: [
    ['What is the law of large numbers (informal)?', 'Averages stabilize with many independent trials', 'Means always increase', 'Variance goes to infinity', 'Samples cannot exceed 30'],
    ['What is Chebyshev\'s inequality used for?', 'Bounding tail probability using variance', 'Finding exact p-values always', 'Plotting pie charts', 'SQL optimization'],
    ['What is Jensen\'s inequality implication for expectations?', 'For convex f, E[f(X)] ≥ f(E[X]) (inequality direction flips for concave)', 'Means always equal', 'Variance is zero', 'Medians irrelevant'],
    ['What is a sufficient statistic?', 'Captures all information in data about a parameter', 'Always the mean', 'Always the max', 'Always the count'],
    ['What is the Fisher information about?', 'Curvature/sensitivity of likelihood — relates to estimator variance', 'Fish counts', 'Bayes priors only', 'Excel functions'],
    ['What is maximum likelihood estimation?', 'Choose parameters maximizing probability of observed data', 'Minimize absolute errors always', 'Use only medians', 'Ignore likelihood'],
    ['What is a likelihood ratio test?', 'Compares nested models via likelihood ratio', 'Compares only charts', 'Tests only means', 'Always Bayesian'],
    ['What is AIC used for?', 'Model comparison trading fit vs complexity', 'Always pick largest', 'Only linear models', 'Only time series'],
    ['What is a generalized linear model?', 'Extends linear regression to other distributions/link functions', 'Only OLS', 'Only deep nets', 'Only trees'],
    ['What is Poisson regression for?', 'Count outcomes with mean-variance linkage', 'Continuous dollars', 'Images', 'Survival with censoring'],
    ['What is logistic regression output?', 'Probability (via logit) of a binary class', 'Always counts', 'Always normal errors', 'Always PCA'],
    ['What is multivariate testing vs A/B?', 'Many factors changed in structured combinations', 'Always worse', 'Illegal', 'Same as multivariate calculus'],
    ['What is sequential testing adjustment?', 'Controls error rates when repeatedly checking results', 'Always increases power', 'Removes randomization', 'Only Bayesian'],
    ['What is a Gelman–Rubin diagnostic about?', 'MCMC chain convergence (R̂ near 1)', 'Linear regression R²', 'SQL explain plans', 'Sample size formula'],
    ['What is hierarchical partial pooling?', 'Group estimates borrow strength from overall data', 'No pooling ever', 'Complete pooling only', 'Delete small groups'],
    ['What is a random effects vs fixed effects distinction (panel)?', 'Random: group-specific intercepts drawn from distribution; Fixed: separate constants', 'Always use random', 'Always same', 'Only cross-section'],
    ['What is difference-in-differences?', 'Compare changes between treated/control around an intervention', 'Double medians', 'Two pie charts', 'Two SQL queries'],
    ['What is regression discontinuity?', 'Compare units just above/below a cutoff receiving treatment', 'Stop regression', 'Discontinue SQL', 'Randomize everything'],
    ['What is an intent-to-treat vs per-protocol tension?', 'ITT preserves randomization; per-protocol can bias', 'Always identical', 'Per-protocol always preferred', 'ITT ignores outcomes'],
    ['What is a placebo test in causal work?', 'Apply method where treatment should not matter — checks artifacts', 'Give sugar pills in HR', 'Remove data', 'Increase alpha'],
    ['What is robust standard errors?', 'Standard errors robust to certain misspecifications (e.g. heteroskedasticity)', 'Always larger than OLS', 'Remove outliers', 'Bayesian only'],
    ['What is clustering of standard errors?', 'Account for correlation within clusters (e.g. firm, region)', 'Always cluster at n=1', 'Remove clusters', 'Only time series'],
    ['What is an instrumental variable exclusion restriction?', 'Instrument affects outcome only through treatment', 'Instrument may directly affect outcome', 'No instruments needed', 'Always weak'],
    ['What is weak instruments problem?', 'IV estimates unstable when instrument barely moves treatment', 'Strong always', 'Only OLS', 'Only RCT'],
    ['What is a propensity score overlap assumption?', 'Common support — comparable treated/control covariate regions', 'Always satisfied', 'Means equal', 'No covariates'],
    ['What is inverse probability weighting?', 'Weights to balance observational groups in estimation', 'Always unbiased', 'Same as matching always', 'Only experimental'],
    ['What is a synthetic control?', 'Weighted combination of donors approximating pre-treatment treated unit', 'A fake dataset', 'A/B test', 'PCA'],
    ['What is Rubin causal model framing?', 'Potential outcomes Y(1), Y(0) and assignment mechanism', 'Only Frequentist', 'Only deep learning', 'Only SQL'],
    ['What is positivity in causal inference?', 'Non-zero probability of treatment levels given covariates', 'Always true', 'Means positive outcomes', 'p-values positive'],
    ['What is unconfoundedness assumption?', 'Treatment independent of potential outcomes given observed covariates', 'Always holds', 'Never needed', 'Only RCT'],
    ['What is SUTVA?', 'No interference between units and single version of treatment', 'Always violated', 'Only maps', 'Only surveys'],
    ['What is a local average treatment effect (LATE)?', 'Effect among compliers identified by IV', 'ATE always', 'ATT always', 'Median effect'],
    ['What is marginal structural model weighting?', 'Handles time-varying confounding affected by past treatment', 'Static only', 'Only means', 'Only SQL'],
    ['What is g-formula / standardization?', 'Estimates potential outcome means by integrating out confounders', 'Only for games', 'Only Bayesian', 'Only Excel'],
    ['What is E-value sensitivity analysis about?', 'How strong unmeasured confounding would need to be to explain away effect', 'Excel values', 'Eigenvalues only', 'E-commerce'],
    ['What is a win ratio in composite endpoints?', 'Prioritized pairwise comparisons beyond first event', 'Win probability in A/B', 'Stock wins', 'HR wins'],
    ['What is frailty in survival models?', 'Random effect capturing unobserved heterogeneity in hazard', 'Weak instruments', 'Missing data', 'SQL fragility'],
    ['What is Aalen additive hazards vs Cox?', 'Additive hazard effects vs proportional hazards assumption', 'Same model', 'Only counts', 'Only Bayesian'],
    ['What is competing risks in survival?', 'Multiple event types that preclude each other', 'Many surveys', 'Many charts', 'Many SQL joins'],
    ['What is Fine–Gray subdistribution hazard?', 'Hazard related to cumulative incidence with competing risks', 'Gray coding', 'Fine dining', 'Gray markets'],
    ['What is a stratified Cox model?', 'Baseline hazard allowed to differ by strata', 'Only one stratum', 'No strata', 'Only OLS'],
    ['What is Schoenfeld residuals test for?', 'Checking proportional hazards assumption', 'Checking normality', 'Checking SQL', 'Checking power'],
    ['What is a likelihood-based confidence interval?', 'Parameter values not rejected by likelihood ratio test at level', 'Always symmetric', 'Always Bayesian', 'Always z-based'],
    ['What is score test vs Wald vs LRT trio?', 'Asymptotic tests in maximum likelihood — different quadratic approximations', 'Always identical finite-sample', 'Only nonparametric', 'Only Excel'],
    ['What is a quasilikelihood model?', 'Uses mean-variance relationship without full distribution', 'Full Bayes always', 'Only normal', 'Only counts'],
    ['What is Tweedie family used for?', 'Semi-continuous data with mass at zero and continuous positive', 'Binary only', 'Images', 'Time zones'],
    ['What is zero-inflated count model?', 'Extra zeros beyond standard count process', 'Removes zeros', 'Only Gaussian', 'Only medians'],
    ['What is a copula (informal)?', 'Joint distribution built from marginals + dependence structure', 'Excel formula', 'Copy/paste', 'GPU shader'],
    ['What is partial correlation?', 'Correlation after adjusting for other variables', 'Half correlation', 'Pie correlation', 'PCA correlation'],
  ],
  5: [
    ['In a revenue dashboard, what does "YoY" compare?', 'This period to the same period last year', 'Yesterday to today', 'Q1 to Q2 only', 'Budget to actual only'],
    ['What is a good practice when reporting survey results?', 'Show sample size and margin of error (when applicable)', 'Hide sample size', 'Report only winners', 'Round all answers to 100%'],
    ['What is "cohort retention" used to measure?', 'How many users from a start group remain active over time', 'Total downloads only', 'Server CPU only', 'Office attendance'],
    ['What is an A/B test designed to compare?', 'Two variants under randomized assignment', 'Two fiscal years', 'Two spreadsheets', 'Two departments\' budgets'],
    ['What does "statistically significant" not guarantee?', 'Business importance or causation', 'Correctness', 'Replication', 'Randomization'],
    ['What is "p-hacking" (selective reporting)?', 'Torturing data until something "significant" appears', 'Using Python', 'Using p-charts', 'Peer review'],
    ['What is a pre-registration plan in experiments?', 'Documenting hypotheses and metrics before data collection', 'Printing spreadsheets', 'Registering domain names', 'Hiring preregistrants'],
    ['What is a holdout group in modeling?', 'Data kept aside to evaluate performance', 'Deleted rows', 'The largest region', 'Senior leadership'],
    ['What is leakage in machine learning features?', 'Using information not available at prediction time', 'Water leaks', 'SQL joins', 'Slow queries'],
    ['What is class imbalance in fraud detection?', 'Very few fraud cases vs many legitimate ones', 'Equal classes', 'Missing labels', 'Too many features'],
    ['What is precision in a fraud model (informal)?', 'Of flagged cases, how many are truly fraud', 'Total fraud caught divided by population', 'Accuracy always', 'Recall always'],
    ['What is recall in a fraud model (informal)?', 'Of true fraud cases, how many the model catches', 'Precision always', 'False positive rate', 'Accuracy always'],
    ['What is ROC AUC summarize (informal)?', 'Overall ability to rank positives above negatives', 'Always accuracy', 'Always precision', 'Always revenue'],
    ['What is calibration for risk scores?', 'Predicted probabilities match observed frequencies', 'Colorful charts', 'Faster scoring', 'Higher AUC always'],
    ['What is uplift modeling used for?', 'Estimating incremental impact of an action (e.g. offer) on individuals', 'Lifting servers', 'HR promotions only', 'Stock price'],
    ['What is survival analysis used for in business?', 'Time-to-event outcomes like churn or default', 'Only marketing copy', 'Only payroll', 'Only tax'],
    ['What is censoring in churn analysis?', 'You stop observing some customers before they churn', 'Deleting churners', 'Winning back all users', 'Duplicate accounts'],
    ['What is a hazard rate (intuitive)?', 'Instantaneous risk of the event given survival so far', 'Total churn count', 'Average tenure only', 'Max tenure'],
    ['What is net present value (NPV) about?', 'Today\'s value of future cash flows with a discount rate', 'Sum of future cash flows without discounting', 'Profit this quarter only', 'Headcount change'],
    ['What is internal rate of return (IRR) (intuitive)?', 'Discount rate that makes NPV of cash flows zero', 'Always the same as interest rate', 'Always negative', 'Same as CAGR always'],
    ['What is working capital?', 'Current assets minus current liabilities', 'Cash only', 'Revenue minus expenses', 'Total assets'],
    ['What is EBITDA often used for?', 'Operating performance before interest, taxes, depreciation, and amortization', 'Net income after tax', 'Cash on hand only', 'Revenue only'],
    ['What is gross margin?', 'Revenue minus cost of goods sold, relative to revenue', 'Net income margin', 'Tax margin', 'Payroll margin'],
    ['What is operating leverage?', 'Fixed costs amplify profit changes as revenue moves', 'Using operating systems', 'Leveraging loans only', 'Stock options'],
    ['What is a cohort LTV analysis?', 'Lifetime value tracked by acquisition cohort', 'LTV of a single invoice', 'Daily active users only', 'Server latency'],
    ['What is payback period?', 'Time to recover an initial investment from cash flows', 'Loan term always', 'ROI always', 'Discount rate'],
    ['What is sensitivity analysis in finance models?', 'How outputs change when assumptions change', 'Deleting assumptions', 'Using only best case', 'Randomizing invoices'],
    ['What is scenario planning?', 'Comparing outcomes under defined alternative futures', 'Only one forecast', 'Only historical averages', 'Only budgets'],
    ['What is a rolling forecast?', 'Forecast updated each period over a fixed horizon', 'Forecast never changes', 'Forecast for one day', 'Forecast only at year-end'],
    ['What is variance analysis in FP&A?', 'Explaining differences between actuals and budget/forecast', 'Statistical variance only', 'HR variance', 'Inventory variance only'],
    ['What is driver-based planning?', 'Model built from operational drivers, not only top-line growth rates', 'Driver\'s license checks', 'Only revenue growth', 'Only headcount'],
    ['What is unit economics?', 'Revenue and costs evaluated per unit (customer, order, seat)', 'Company-wide totals only', 'Macroeconomics', 'Stock splits'],
    ['What is contribution margin?', 'Revenue minus variable costs (toward covering fixed costs)', 'Same as gross margin always', 'Net income', 'EBITDA always'],
    ['What is capacity utilization?', 'How much of available capacity is being used', 'Headcount only', 'Cash utilization', 'CPU brand'],
    ['What is days sales outstanding (DSO)?', 'Average collection time for receivables', 'Sales per day only', 'Discount offered', 'Days payable outstanding'],
    ['What is inventory turnover?', 'How often inventory is sold and replaced in a period', 'Warehouse size', 'SKU count', 'Shrinkage only'],
    ['What is a liquidity ratio used for?', 'Assessing ability to meet short-term obligations', 'Long-term growth', 'Marketing ROI', 'Employee satisfaction'],
    ['What is leverage in corporate finance (simple)?', 'Using debt to finance assets/operations', 'Operating leverage only', 'Team leverage', 'HR leverage'],
    ['What is WACC (intuitive)?', 'Blended cost of equity and debt financing', 'Cash on hand', 'Tax rate only', 'Dividend yield only'],
    ['What is free cash flow (intuitive)?', 'Cash from operations after capital spending', 'Same as revenue', 'Same as net income always', 'Only payroll cash'],
    ['What is enterprise value (EV) (intuitive)?', 'Equity value plus net debt — value to all capital providers', 'Same as market cap always', 'Only debt', 'Only cash'],
    ['What is purchase price allocation?', 'Assigning acquired assets/liabilities for accounting/taxes', 'Shopping receipts', 'Stock buybacks', 'Dividend policy'],
    ['What is goodwill on a balance sheet?', 'Premium paid over identifiable net assets in an acquisition', 'Employee morale', 'Brand color', 'Cash reserves'],
    ['What is deferred revenue?', 'Cash received for services not yet delivered', 'Revenue recognized early', 'Accounts payable', 'Bad debt'],
    ['What is an audit trail important for?', 'Reconstructing who changed what and when in systems', 'Hiking trails', 'Marketing slogans', 'Office layout'],
    ['What is segregation of duties?', 'Splitting responsibilities to reduce fraud/error risk', 'One person does everything', 'Department silos only', 'Remote work policy'],
    ['What is SOX often associated with?', 'US corporate governance and financial reporting controls', 'Socks inventory', 'Software licensing', 'Sales tax'],
    ['What is GDPR primarily about?', 'EU personal data protection and privacy rights', 'US securities law', 'Payment networks', 'Export controls'],
    ['What is PCI DSS about?', 'Security standards for cardholder data', 'Public company insurance', 'Project charters', 'Payroll compliance'],
  ],
  6: [
    ['In risk management, what is "key risk indicator" (KRI)?', 'Metric that signals increasing risk exposure', 'Same as KPI always', 'A compliance checklist item', 'A project milestone'],
    ['What is operational risk (Basel sense, simplified)?', 'Risk of loss from failed processes, people, systems, or external events', 'Only market price risk', 'Only credit risk', 'Only strategic risk'],
    ['What is model risk management about?', 'Controls for errors in models and misuse of model outputs', 'Buying more GPUs', 'Only data entry', 'Only vendor contracts'],
    ['What is an independent model validation group expected to do?', 'Challenge assumptions, inputs, and outputs separately from model developers', 'Write production code', 'Approve all trades', 'Set marketing budgets'],
    ['What is backtesting in trading/risk models?', 'Assessing strategy/model performance on historical data with care for biases', 'Deleting old data', 'Only forward testing', 'Only stress tests'],
    ['What is walk-forward analysis?', 'Out-of-sample testing that rolls training/test windows forward', 'Walking through the office', 'SQL window functions only', 'Random sampling'],
    ['What is survivorship bias in fund performance?', 'Ignoring funds that closed — overstating average returns', 'Counting all funds equally', 'Using medians only', 'Using inflation'],
    ['What is look-ahead bias in backtests?', 'Using information that would not have been available at decision time', 'Looking at charts', 'Using lagged features correctly', 'Using holdouts'],
    ['What is a stress test in banking (simple)?', 'Estimating losses under severe but plausible scenarios', 'Employee stress survey', 'CPU stress test', 'Daily reconciliation'],
    ['What is reverse stress testing?', 'Finding scenarios that would cause failure given a model', 'Testing backups', 'Testing refunds', 'Testing hiring'],
    ['What is credit migration risk?', 'Risk that borrowers\' credit quality moves between rating categories', 'Foreign exchange risk', 'Liquidity risk', 'Operational outages'],
    ['What is concentration risk?', 'Too much exposure to one counterparty, sector, or name', 'Diversification benefit', 'Interest rate risk only', 'Model calibration'],
    ['What is wrong-way risk?', 'Exposure increases when counterparty credit worsens', 'Right-way risk', 'Settlement risk only', 'Legal risk only'],
    ['What is CVA (credit valuation adjustment) about?', 'Pricing counterparty credit risk into derivatives values', 'Customer lifetime value', 'Cash value added', 'Cost variance analysis'],
    ['What is liquidity coverage ratio (LCR) about (high level)?', 'Short-term liquidity buffer vs stressed outflows — banking regulation', 'Long-term lending', 'Loan approval speed', 'Credit score'],
    ['What is net stable funding ratio (NSFR) about (high level)?', 'Stable funding vs illiquid assets — banking regulation', 'Daily revenue', 'Stock buybacks', 'Payroll funding'],
    ['What is AML program designed to combat?', 'Money laundering through financial system', 'Marketing leaks', 'Absenteeism', 'Malware only'],
    ['What is KYC in financial services?', 'Know Your Customer — identity and risk assessment', 'Keep Your Cash', 'Key Yield Curve', 'Know Your Competitor'],
    ['What is beneficial ownership disclosure about?', 'Identifying who ultimately owns or controls a customer', 'Employee stock options', 'Trademark ownership', 'Office leaseholder'],
    ['What is sanctions screening?', 'Checking customers/transactions against restricted lists', 'Screening job applicants', 'Screening emails', 'Screening vendors for price'],
    ['What is a Suspicious Activity Report (SAR) about?', 'Filing to authorities on suspected illicit activity (jurisdiction-specific)', 'Sales activity report', 'Server availability report', 'Security audit report'],
    ['What is open banking (concept)?', 'Consumers/businesses sharing account data via APIs with consent', 'Banks open 24/7', 'Open-source bank software only', 'Public stock tickers'],
    ['What is PSD2 Strong Customer Authentication about?', 'EU requirements for multi-factor customer verification in payments', 'Password length only', 'PCI only', 'SOX only'],
    ['What is tokenization in payments?', 'Replacing sensitive PAN data with non-sensitive surrogate tokens', 'Blockchain tokens only', 'JWT always', 'QR codes'],
    ['What is RTP / instant payments infrastructure about?', 'Near real-time settlement of retail payments (country-specific systems)', 'Batch ACH only', 'Wire transfers only', 'Cryptocurrency only'],
    ['What is a CBDC (central bank digital currency) at a high level?', 'Central bank liability in digital form', 'Same as Bitcoin always', 'Commercial bank deposits', 'Stablecoin always'],
    ['What is a stablecoin (general definition)?', 'Crypto asset designed to track a reference like fiat currency', 'Always central bank issued', 'Always unregulated', 'Always volatile'],
    ['What is DeFi (high-level business risk lens)?', 'Decentralized financial protocols — novel operational, legal, and market risks', 'Department of Finance', 'Defined finance KPIs', 'Deferred financing'],
    ['What is smart contract risk in digital assets?', 'Code flaws or governance issues causing loss', 'Paper contract typos', 'HR contracts', 'SLA penalties'],
    ['What is third-party / vendor risk management?', 'Assessing and monitoring risks from suppliers and partners', 'Buying cheapest vendor', 'Outsourcing everything', 'Internal audit only'],
    ['What is business continuity planning?', 'How the organization continues critical operations during disruption', 'Only IT backups', 'Only insurance', 'Only PR'],
    ['What is RTO vs RPO in disaster recovery?', 'Recovery time objective vs recovery point objective', 'Revenue targets', 'Risk tolerance only', 'Return on projects'],
    ['What is zero trust security model (one line)?', 'Never trust, always verify — least privilege per request', 'No employees on site', 'No internet access', 'No passwords'],
    ['What is SOC 2 report about (common usage)?', 'Service organization controls relevant to security/availability (etc.)', 'Stock compensation', 'Sales operations center', 'Second opinion counsel'],
    ['What is ISO 27001 about?', 'Information security management system standard', 'Manufacturing quality', 'Medical devices', 'Payment interchange'],
    ['What is data minimization principle in privacy?', 'Collect only what you need for stated purposes', 'Collect all data possible', 'Minimize charts', 'Minimize encryption'],
    ['What is purpose limitation in privacy?', 'Use data only for disclosed compatible purposes', 'Unlimited repurposing', 'Sell data freely', 'Ignore consent'],
    ['What is right of access in GDPR-style regimes?', 'Individuals can request copies of personal data held', 'Right to invest', 'Right to audit suppliers', 'Right to delete always only'],
    ['What is algorithmic fairness concern in HR tech?', 'Models may inadvertently discriminate protected groups', 'Faster hiring always', 'Lower cost always', 'Higher accuracy always'],
    ['What is an ethics review board for analytics projects?', 'Panel assessing societal/ethical impacts before deployment', 'IT change board', 'Budget committee', 'Sales kickoff'],
    ['What is lineage for regulatory reporting?', 'Auditable trail from source systems to reported numbers', 'Waiting in line', 'Code linters', 'Family lineage'],
    ['What is materiality in financial reporting?', 'Magnitude/omission that could influence decisions of users', 'Smallest rounding error', 'CEO preference', 'Marketing spend'],
    ['What is a going concern qualification?', 'Auditor doubt the entity can continue operating near term', 'Company is growing fast', 'Minor bookkeeping issue', 'Tax filing delay'],
    ['What is related-party transaction disclosure about?', 'Transparency when company deals with insiders/affiliates', 'Employee birthdays', 'Vendor discounts', 'Customer refunds'],
    ['What is transfer pricing about?', 'Pricing transactions between controlled entities for tax/compliance', 'Retail price tags', 'Stock transfer agents', 'Payroll transfers'],
    ['What is economic substance requirement (general idea)?', 'Jurisdictions demand real activity for tax benefits claimed', 'Substance abuse policy', 'Office snacks', 'Brand substance'],
    ['What is BEPS project about (high level)?', 'OECD work against base erosion and profit shifting', 'Best employee practices', 'Bank encryption standards', 'Budget estimation process'],
    ['What is a whistleblower program intended to encourage?', 'Reporting misconduct through protected channels', 'Competitor intelligence', 'Customer complaints about UI', 'Random audits'],
  ],
};
